Repository googleapis/google-cloud-cpp, pull requests merged in 2018-05, with the labels that each got.

#457 Minimal implementation of InstanceAdmin::CreateInstance
  bigtable/client/instance_admin.cc
  bigtable/client/instance_admin.h
  bigtable/client/instance_admin_client.cc
  bigtable/client/instance_admin_client.h
  bigtable/client/instance_admin_test.cc
  bigtable/client/internal/instance_admin.h
  bigtable/client/testing/mock_instance_admin_client.h
Labels: cla: yes

#468 Fix build breakage.
  bigtable/client/instance_config.h
Labels: cla: yes

#464 Issue#419 Implementation for InstanceAdmin::GetInstance with unit tests for no errors
  bigtable/client/instance_admin.cc
  bigtable/client/instance_admin.h
  bigtable/client/instance_admin_client.cc
  bigtable/client/instance_admin_client.h
  bigtable/client/internal/instance_admin.cc
  bigtable/client/internal/instance_admin.h
  bigtable/client/internal/instance_admin_test.cc
  bigtable/client/testing/mock_instance_admin_client.h
Labels: cla: yes

#472 Implementation of InstanceAdmin::DeleteInstance call
  bigtable/client/instance_admin.cc
  bigtable/client/instance_admin.h
  bigtable/client/instance_admin_client.cc
  bigtable/client/instance_admin_client.h
  bigtable/client/instance_admin_test.cc
  bigtable/client/internal/instance_admin.cc
  bigtable/client/internal/instance_admin.h
  bigtable/client/internal/instance_admin_test.cc
  bigtable/client/testing/mock_instance_admin_client.h
  bigtable/examples/BUILD
  bigtable/examples/CMakeLists.txt
  bigtable/examples/bigtable_samples_instance_admin.cc
  bigtable/tests/instance_admin_integration_test.cc
Labels: cla: yes

#459 Changed expected results against production.
  bigtable/tests/admin_integration_test.cc
Labels: cla: yes

#473 Remove some of the boilerplate for both libraries.
  bigtable/client/CMakeLists.txt
  google/cloud/config-version.cmake.in
  google/cloud/config.pc.in
  storage/CMakeLists.txt
  storage/client/CMakeLists.txt
  storage/client/config-version.cmake.in
  storage/client/config.cmake.in
  storage/client/config.pc.in
Labels: bigtable, cla: yes, storage

#479 Use compiler with full C++11 support for CentOS.
  ci/Dockerfile.centos
  ci/build-linux.sh
Labels: cla: yes

#462 #423:Implement InstanceAdmin::ListClusters
  bigtable/client/instance_admin.cc
  bigtable/client/instance_admin.h
  bigtable/client/instance_admin_client.cc
  bigtable/client/instance_admin_client.h
  bigtable/client/instance_admin_test.cc
  bigtable/client/internal/instance_admin.cc
  bigtable/client/internal/instance_admin.h
  bigtable/client/internal/instance_admin_test.cc
  bigtable/client/testing/mock_instance_admin_client.h
  bigtable/examples/CMakeLists.txt
  bigtable/examples/bigtable_samples_instance_admin.cc
  bigtable/tests/instance_admin_integration_test.cc
Labels: cla: yes

#436 Mark APIs that are "private alpha release" as such.
  bigtable/client/table_admin.h
Labels: cla: yes

#483 Use @par for examples in Doxygen docs.
  bigtable/client/instance_admin.h
  bigtable/client/table.h
  bigtable/client/table_admin.h
Labels: cla: yes

#474 Add Bazel support for the storage/ directory.
  bigtable/client/BUILD
  storage/client/BUILD
  storage/client/CMakeLists.txt
  storage/client/storage_client.bzl
  storage/client/storage_client_unit_tests.bzl
Labels: cla: yes

#478 Refactor random number functions
  bigtable/benchmarks/CMakeLists.txt
  bigtable/benchmarks/apply_read_latency_benchmark.cc
  bigtable/benchmarks/benchmark.cc
  bigtable/benchmarks/benchmark.h
  bigtable/benchmarks/benchmark_test.cc
  bigtable/benchmarks/embedded_server.cc
  bigtable/benchmarks/endurance_benchmark.cc
  bigtable/benchmarks/random_mutation.cc
  bigtable/benchmarks/random_mutation.h
  bigtable/benchmarks/random_mutation_test.cc
  bigtable/benchmarks/scan_throughput_benchmark.cc
  bigtable/benchmarks/setup.cc
  bigtable/client/CMakeLists.txt
  bigtable/client/bigtable_client_testing.bzl
  bigtable/client/bigtable_client_unit_tests.bzl
  bigtable/client/testing/random.cc
  bigtable/client/testing/random.h
  bigtable/client/testing/random_test.cc
Labels: cla: yes

#485 issue #419 GetInstance(), test cases added
  bigtable/client/internal/instance_admin_test.cc
  bigtable/tests/instance_admin_integration_test.cc
Labels: cla: yes

#497 Run test-installs in the build-output subdirectory.
  ci/build-docker.sh
Labels: cla: yes

#493 Add sample snippet for InstanceAdmin::GetInstance()
  bigtable/client/instance_admin.h
  bigtable/examples/bigtable_samples_instance_admin.cc
Labels: cla: yes

#499 Issue template grammar issue
  .github/issue_template.md
Labels: cla: yes

#500 Explain why gcc-4.8 is not good enough.
  storage/CMakeLists.txt
Labels: cla: yes

#502 implementation of InstanceAdmin::DeleteCluster
  bigtable/client/CMakeLists.txt
  bigtable/client/bigtable_client.bzl
  bigtable/client/bigtable_strong_types.h
  bigtable/client/instance_admin.cc
  bigtable/client/instance_admin.h
  bigtable/client/instance_admin_client.cc
  bigtable/client/instance_admin_client.h
  bigtable/client/instance_admin_test.cc
  bigtable/client/internal/instance_admin.cc
  bigtable/client/internal/instance_admin.h
  bigtable/client/internal/instance_admin_test.cc
  bigtable/client/internal/table_admin.h
  bigtable/client/metadata_update_policy.h
  bigtable/client/table_admin.h
  bigtable/client/testing/mock_instance_admin_client.h
  bigtable/examples/bigtable_samples_instance_admin.cc
Labels: cla: yes

#469 Dump the emulator logs in Travis
  .travis.yml
  ci/dump-logs.sh
Labels: cla: yes

#487 Implementation of PollingPolicy
  bigtable/client/CMakeLists.txt
  bigtable/client/bigtable_client.bzl
  bigtable/client/bigtable_client_unit_tests.bzl
  bigtable/client/polling_policy.cc
  bigtable/client/polling_policy.h
  bigtable/client/polling_policy_test.cc
  bigtable/client/rpc_backoff_policy.cc
  bigtable/client/rpc_backoff_policy.h
  bigtable/client/rpc_retry_policy.cc
  bigtable/client/rpc_retry_policy.h
Labels: cla: yes

#504 Add nlohmann json library
  bazel/google_cloud_cpp_deps.bzl
  cmake/DownloadNlohmannJson.cmake
  cmake/IncludeNlohmannJson.cmake
  storage/CMakeLists.txt
  storage/client/BUILD
  storage/client/CMakeLists.txt
  storage/client/internal/nljson.h
  storage/client/internal/nljson_test.cc
  storage/client/storage_client.bzl
  storage/client/storage_client_unit_tests.bzl
Labels: cla: yes, storage

#513 Reset expectations for new Bigtable emulator.
  bigtable/tests/admin_integration_test.cc
  ci/Dockerfile.centos
  ci/Dockerfile.fedora
  ci/Dockerfile.ubuntu
Labels: cla: yes

#431 Firestore Field Path
  CMakeLists.txt
  firestore/CMakeLists.txt
  firestore/README.md
  firestore/client/CMakeLists.txt
  firestore/client/config.cmake.in
  firestore/client/field_path.cc
  firestore/client/field_path.h
  firestore/client/field_path_test.cc
  firestore/client/firestore_client.pc
  firestore/client/version_info.h.in
Labels: cla: yes

#514 Add a build to test Bazel as a dependency.
  .travis.yml
  ci/build-bazel.sh
Labels: cla: yes

#440 AppProfileID in Table:: member functions.
  bigtable/client/CMakeLists.txt
  bigtable/client/bigtable_client.bzl
  bigtable/client/internal/bulk_mutator.cc
  bigtable/client/internal/bulk_mutator.h
  bigtable/client/internal/bulk_mutator_test.cc
  bigtable/client/internal/table.cc
  bigtable/client/internal/table.h
  bigtable/client/internal/table_test.cc
  bigtable/client/row_reader.cc
  bigtable/client/row_reader.h
  bigtable/client/row_reader_test.cc
  bigtable/client/table.h
  bigtable/client/table_strong_types.h
Labels: cla: yes

#498 Create instance integration tests
  bigtable/client/instance_admin.cc
  bigtable/client/instance_admin_test.cc
  bigtable/client/testing/random.h
  bigtable/examples/run_examples_emulator.sh
  bigtable/examples/run_examples_utils.sh
  bigtable/tests/BUILD
  bigtable/tests/CMakeLists.txt
  bigtable/tests/instance_admin_emulator.cc
  bigtable/tests/instance_admin_integration_test.cc
  bigtable/tests/integration_tests_utils.sh
  bigtable/tests/run_integration_tests_emulator.sh
  bigtable/tools/run_emulator_utils.sh
  ci/dump-logs.sh
Labels: bigtable, cla: yes

#521 Remember to push firestore docs too.
  ci/upload-docs.sh
Labels: cla: yes

#517 Basic credentials for Google Cloud Storage
  storage/client/CMakeLists.txt
  storage/client/credentials.cc
  storage/client/credentials.h
  storage/client/internal/curl_request.cc
  storage/client/internal/curl_request.h
  storage/client/internal/service_account_credentials.h
  storage/client/internal/service_account_credentials_test.cc
  storage/client/storage_client.bzl
  storage/client/storage_client_unit_tests.bzl
  storage/tests/curl_request_integration_test.cc
Labels: cla: yes, storage

#527 Default credentials raise if HOME is not set.
  bigtable/client/client_options_test.cc
  google/cloud/CMakeLists.txt
  google/cloud/google_cloud_cpp_common.bzl
  google/cloud/internal/setenv.cc
  google/cloud/internal/setenv.h
  storage/client/CMakeLists.txt
  storage/client/credentials.cc
  storage/client/internal/service_account_credentials.cc
  storage/client/internal/service_account_credentials.h
  storage/client/internal/service_account_credentials_test.cc
  storage/client/storage_client.bzl
Labels: cla: yes

#526 Refactor integration test driver scripts.
  bigtable/ci/run_integration_tests.sh
  ci/build-docker.sh
  storage/ci/run_integration_tests.sh
Labels: cla: yes

#525 Make bigtable examples output prettier.
  bigtable/examples/run_examples_emulator.sh
  bigtable/examples/run_examples_utils.sh
  ci/build-bazel.sh
  ci/build-docker.sh
  ci/colors.sh
Labels: cla: yes

#520 Cleanup the travis yaml file.
  .travis.yml
Labels: cla: yes

#512 #490: Addition of instance_id in ListClusters api
  bigtable/client/instance_admin.cc
  bigtable/client/instance_admin.h
  bigtable/client/instance_admin_test.cc
  bigtable/client/internal/instance_admin.cc
  bigtable/client/internal/instance_admin.h
  bigtable/client/internal/instance_admin_test.cc
  bigtable/examples/bigtable_samples_instance_admin.cc
  bigtable/tests/instance_admin_integration_test.cc
Labels: cla: yes

#532 This time actually print output on test failures.
  ci/build-docker.sh
Labels: cla: yes

#531 Implement a parser for RFC 3339 dates.
  storage/client/CMakeLists.txt
  storage/client/internal/parse_rfc3339.cc
  storage/client/internal/parse_rfc3339.h
  storage/client/internal/parse_rfc3339_test.cc
  storage/client/storage_client.bzl
  storage/client/storage_client_unit_tests.bzl
Labels: cla: yes

#535 Initial class to hold and parse Bucket metadata.
  storage/client/CMakeLists.txt
  storage/client/bucket_metadata.cc
  storage/client/bucket_metadata.h
  storage/client/bucket_metadata_test.cc
  storage/client/storage_client.bzl
  storage/client/storage_client_unit_tests.bzl
Labels: cla: yes, storage

#539 Use GOOGLE_APPLICATION_CREDENTIALS if set.
  storage/client/internal/service_account_credentials.cc
  storage/client/internal/service_account_credentials_test.cc
Labels: cla: yes, storage

#538 Fix integration tests on Jenkins.
  bigtable/tests/integration_tests_utils.sh
Labels: bigtable, cla: yes

#508 Run benchmarks in CI build
  bigtable/benchmarks/benchmark.cc
  bigtable/ci/run_integration_tests.sh
  ci/build-docker.sh
Labels: cla: yes

#541 Capture full http response in storage::internal::CurlRequest
  storage/client/internal/curl_request.cc
  storage/client/internal/curl_request.h
  storage/client/internal/curl_wrappers.cc
  storage/client/internal/curl_wrappers.h
  storage/client/internal/service_account_credentials.h
  storage/client/internal/service_account_credentials_test.cc
  storage/tests/curl_request_integration_test.cc
Labels: cla: yes

#544 Protect client APIs from accidental use.
  bigtable/client/admin_client.h
  bigtable/client/data_client.h
  bigtable/client/instance_admin_client.h
Labels: bigtable, cla: yes, enhancement

#543 Refactor MockHttpRequest.
  storage/client/BUILD
  storage/client/CMakeLists.txt
  storage/client/internal/service_account_credentials_test.cc
  storage/client/storage_client_testing.bzl
  storage/client/testing/mock_http_request.cc
  storage/client/testing/mock_http_request.h
Labels: cla: yes, storage, testing

#529 Correctly cleanup when using the emulator.
  bigtable/examples/run_examples_utils.sh
  bigtable/tools/run_emulator_utils.sh
Labels: bigtable, cla: yes

#524 Improve code coverage for firestore::FieldPath.
  firestore/client/field_path.cc
  firestore/client/field_path.h
  firestore/client/field_path_test.cc
Labels: cla: yes, firestore

#550 Initial storage::Client classes
  storage/client/CMakeLists.txt
  storage/client/client.cc
  storage/client/client.h
  storage/client/internal/default_client.h
  storage/client/internal/default_client_test.cc
  storage/client/status.h
  storage/client/storage_client.bzl
  storage/client/storage_client_unit_tests.bzl
  storage/client/testing/mock_http_request.cc
  storage/client/testing/mock_http_request.h
Labels: cla: yes

#545 InstanceAdmin::UpdateInstance implementation
  bigtable/client/CMakeLists.txt
  bigtable/client/bigtable_client.bzl
  bigtable/client/bigtable_client_unit_tests.bzl
  bigtable/client/instance_admin.cc
  bigtable/client/instance_admin.h
  bigtable/client/instance_admin_client.cc
  bigtable/client/instance_admin_client.h
  bigtable/client/instance_admin_test.cc
  bigtable/client/instance_update_config.cc
  bigtable/client/instance_update_config.h
  bigtable/client/instance_update_config_test.cc
  bigtable/client/testing/mock_instance_admin_client.h
  bigtable/examples/bigtable_samples_instance_admin.cc
  bigtable/tests/instance_admin_emulator.cc
  bigtable/tests/instance_admin_integration_test.cc
Labels: cla: yes

#583 Use random table ids for integration tests.
  bigtable/client/testing/table_integration_test.cc
  bigtable/client/testing/table_integration_test.h
  bigtable/tests/admin_integration_test.cc
  bigtable/tests/data_integration_test.cc
  bigtable/tests/filters_integration_test.cc
  bigtable/tests/integration_tests_utils.sh
  bigtable/tests/mutations_integration_test.cc
Labels: bigtable, cla: yes

#588 Fix the integration tests against production.
  bigtable/tests/instance_admin_emulator.cc
  bigtable/tests/instance_admin_integration_test.cc
Labels: bigtable, cla: yes

#586 Enforce include header guard formatting.
  bigtable/benchmarks/random_mutation.h
  bigtable/benchmarks/setup.h
  bigtable/client/cell.h
  bigtable/client/testing/mock_instance_admin_client.h
  ci/Dockerfile.ubuntu
  ci/check-style.sh
  firestore/client/field_path.h
  google/cloud/internal/build_info.h
  google/cloud/internal/port_platform.h
  google/cloud/internal/setenv.h
  google/cloud/internal/throw_delegate.h
  google/cloud/version.h
  storage/client/credentials.h
  storage/client/internal/parse_rfc3339.h
  storage/client/internal/service_account_credentials.h
Labels: bigtable, cla: yes

#589 Enable one build with gcc-4.9.
  ci/install-bazel.sh
Labels: bigtable, cla: yes, firestore, storage, testing

#591 Turn clang-tidy warnings into errors.
  .clang-tidy
  .travis.yml
  CONTRIBUTING.md
  bigtable/benchmarks/benchmark_test.cc
  bigtable/benchmarks/setup.cc
  bigtable/client/CMakeLists.txt
  bigtable/client/grpc_error.cc
  bigtable/client/internal/endian.cc
  bigtable/client/metadata_update_policy.cc
  bigtable/client/mutations.cc
  bigtable/client/mutations.h
  bigtable/client/row_reader.cc
  bigtable/client/rpc_backoff_policy.cc
  bigtable/client/rpc_retry_policy.cc
  bigtable/client/testing/table_test_fixture.cc
  bigtable/client/testing/table_test_fixture.h
  bigtable/client/version.cc
  cmake/EnableClangTidy.cmake
  cmake/GoogleCloudCppCommon.cmake
  firestore/client/CMakeLists.txt
  google/cloud/CMakeLists.txt
  google/cloud/internal/build_info.cc.in
  google/cloud/internal/build_info.h
  google/cloud/internal/setenv.cc
  storage/client/CMakeLists.txt
  storage/client/internal/curl_request.cc
  storage/client/internal/curl_request.h
  storage/client/internal/curl_wrappers.cc
  storage/client/internal/curl_wrappers.h
  storage/client/internal/parse_rfc3339.cc
  storage/client/version.cc
  storage/tests/curl_request_integration_test.cc
Labels: cla: yes

#595 Make the TableAdmin integration tests easier to follow.
  bigtable/tests/admin_integration_test.cc
Labels: bigtable, cla: yes

#599 Do not check for an empty instance.
  bigtable/tests/filters_integration_test.cc
Labels: bigtable, cla: yes

#597 Format with clang-format-6.0 on ubuntu:18.04.
  .travis.yml
  bigtable/benchmarks/embedded_server_test.cc
  bigtable/client/instance_admin_test.cc
  bigtable/client/internal/bulk_mutator_test.cc
  bigtable/client/internal/instance_admin_test.cc
  bigtable/client/internal/rowreaderiterator.h
  bigtable/client/internal/table_admin_test.cc
  bigtable/client/internal/table_test.cc
  bigtable/client/internal/throw_delegate.cc
  bigtable/client/row_reader_test.cc
  bigtable/client/table_admin_test.cc
  bigtable/client/table_readmodifywriterow_test.cc
  bigtable/tests/data_integration_test.cc
  bigtable/tests/filters_integration_test.cc
  google/cloud/internal/throw_delegate.cc
  google/cloud/internal/throw_delegate_test.cc
  storage/client/bucket_metadata_test.cc
  storage/client/internal/curl_request.cc
  storage/client/internal/curl_wrappers.cc
  storage/tests/curl_request_integration_test.cc
Labels: bigtable, cla: yes, storage

#598 Run Docker builds with the user id.
  .travis.yml
  ci/build-docker.sh
  ci/build-linux.sh
Labels: cla: yes

#602 Fix retry loop to build Docker images.
  ci/install-linux.sh
Labels: cla: yes

#603 Use cache for Bazel builds.
  .travis.yml
Labels: cla: yes

#604 Preserve error messages in grpc::Status.
  bigtable/client/internal/instance_admin_test.cc
  bigtable/client/internal/table_admin_test.cc
  bigtable/client/internal/table_test.cc
  bigtable/client/internal/unary_client_utils.h
Labels: bigtable, cla: yes

#461 Issue#426:Wrap TableAdmin::CheckConsistency in a loop.
  bigtable/client/internal/table_admin.cc
  bigtable/client/internal/table_admin.h
  bigtable/client/internal/table_admin_test.cc
  bigtable/client/table_admin.cc
  bigtable/client/table_admin.h
  bigtable/client/table_admin_test.cc
Labels: bigtable, cla: yes

#605 Refactor macOS install steps to a script.
  .travis.yml
  ci/install-macosx.sh
Labels: cla: yes, testing

#606 Move firestore/ to google/cloud/firestore/
  CMakeLists.txt
  ci/build-bazel.sh
  ci/check-style.sh
  firestore/CMakeLists.txt
  google/cloud/CMakeLists.txt
  google/cloud/firestore/BUILD
  google/cloud/firestore/CMakeLists.txt
  google/cloud/firestore/README.md
  google/cloud/firestore/config.cmake.in
  google/cloud/firestore/field_path.cc
  google/cloud/firestore/field_path.h
  google/cloud/firestore/field_path_test.cc
  google/cloud/firestore/firestore_client.bzl
  google/cloud/firestore/firestore_client.pc
  google/cloud/firestore/firestore_client_unit_tests.bzl
  google/cloud/firestore/version_info.h.in
Labels: cla: yes, firestore
