Repository googleapis/google-cloud-cpp, pull requests merged in 2018-06, with the labels that each got.

#607 Fixed some low hanging fruit to improve code coverage.
  bigtable/client/CMakeLists.txt
  bigtable/client/bigtable_client.bzl
  bigtable/client/client_options_test.cc
  bigtable/client/filters.cc
  bigtable/client/grpc_error_test.cc
  bigtable/client/internal/table_admin.cc
  bigtable/client/internal/table_admin.h
  bigtable/client/read_modify_write_rule.cc
  bigtable/client/rpc_retry_policy.cc
  bigtable/client/table_readmodifywriterow_test.cc
  bigtable/client/table_readrow_test.cc
  ci/build-docker.sh
  storage/client/bucket_metadata_test.cc
Labels: bigtable, cla: yes, storage

#611 Use ccache for Travis builds.
  .travis.yml
  CMakeLists.txt
  ci/Dockerfile.centos
  ci/Dockerfile.fedora
  ci/Dockerfile.ubuntu
  ci/Dockerfile.ubuntu-trusty
  ci/build-docker.sh
  ci/build-linux.sh
Labels: cla: yes, testing

#596 implementation of InstanceAdmin::UpdateCluster
  bigtable/client/cluster_config.h
  bigtable/client/instance_admin.cc
  bigtable/client/instance_admin.h
  bigtable/client/instance_admin_client.cc
  bigtable/client/instance_admin_client.h
  bigtable/client/instance_admin_test.cc
  bigtable/client/testing/mock_instance_admin_client.h
  bigtable/examples/bigtable_samples_instance_admin.cc
  bigtable/tests/instance_admin_emulator.cc
  bigtable/tests/instance_admin_integration_test.cc
Labels: bigtable, cla: yes

#613 Disable ccache on coverage builds.
  .travis.yml
Labels: cla: yes

#626 Print test error messages on failure.
  ci/build-bazel.sh
Labels: cla: yes

#627 Workaround emulator crashes in CI builds.
  bigtable/ci/run_integration_tests.sh
Labels: bigtable, cla: yes, testing

#616 Enable codecov comments for pull requests.
  .codecov.yml
  ci/upload-codecov.sh
Labels: cla: yes

#636 Make Bazel and macOS builds more robust.
  ci/install-bazel.sh
  ci/install-macosx.sh
Labels: cla: yes

#639 Fix `TableAdmin::WaitForConsistencyCheck()`
  bigtable/client/internal/table_admin.cc
  bigtable/client/table_admin_test.cc
Labels: bigtable, cla: yes

#641 Fix retry loop in install scripts.
  ci/install-bazel.sh
  ci/install-linux.sh
  ci/install-macosx.sh
Labels: cla: yes

#633 Move `firestore::` namespace to `google::cloud::`
  google/cloud/firestore/field_path.cc
  google/cloud/firestore/field_path.h
  google/cloud/firestore/field_path_test.cc
Labels: cla: yes, firestore

#614 Take advantage of ccache on builds that install the dependencies
  .travis.yml
  ci/Dockerfile.ubuntu
  ci/Dockerfile.ubuntu-with-dependencies
  ci/build-docker.sh
  ci/build-linux.sh
  cmake/IncludeGrpc.cmake
Labels: cla: yes

#612 Run a local httpbin server for integration tests.
  ci/Dockerfile.centos
  ci/Dockerfile.fedora
  ci/Dockerfile.ubuntu
  ci/Dockerfile.ubuntu-trusty
  ci/kokoro/ubuntu/build.sh
  storage/tests/curl_request_integration_test.cc
  storage/tests/run_integration_tests.sh
Labels: cla: yes

#638 Enable ccache on macOS
  .travis.yml
  ci/build-macosx.sh
  ci/install-macosx.sh
Labels: cla: yes

#634 Include Google Cloud Storage as a component [skip ci].
  .github/issue_template.md
Labels: cla: yes, type: process

#651 Fully qualify grpc::StatusCode values.
  ci/check-style.sh
  google/cloud/bigtable/internal/bulk_mutator.cc
  google/cloud/bigtable/internal/bulk_mutator_test.cc
  google/cloud/bigtable/internal/table_test.cc
  google/cloud/bigtable/row_reader_test.cc
  google/cloud/bigtable/table_bulk_apply_test.cc
Labels: cla: yes

#655 Use EXPECT_THAT to test for substrings.
  google/cloud/bigtable/benchmarks/benchmark_test.cc
  google/cloud/bigtable/grpc_error_test.cc
  google/cloud/bigtable/tests/instance_admin_integration_test.cc
  storage/client/internal/service_account_credentials_test.cc
  storage/tests/curl_request_integration_test.cc
Labels: cla: yes

#601 Introduce basic logging
  google/cloud/CMakeLists.txt
  google/cloud/google_cloud_cpp_common.bzl
  google/cloud/google_cloud_cpp_common_unit_tests.bzl
  google/cloud/log.cc
  google/cloud/log.h
  google/cloud/log_test.cc
Labels: cla: yes

#608 Optimize build matrix for personal forks.
  .travis.yml
Labels: cla: yes

#680 Refactor BucketMetadata code.
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/bucket_metadata.cc
  google/cloud/storage/bucket_metadata.h
  google/cloud/storage/bucket_metadata_test.cc
  google/cloud/storage/internal/common_metadata.cc
  google/cloud/storage/internal/common_metadata.h
  google/cloud/storage/internal/metadata_parser.cc
  google/cloud/storage/internal/metadata_parser.h
  google/cloud/storage/storage_client.bzl
Labels: cla: yes

#684 Improve code coverage after refactoring BucketMetadata.
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/internal/metadata_parser_test.cc
  google/cloud/storage/storage_client_unit_tests.bzl
Labels: cla: yes, storage

#689 Shorten the name of the unit tests.
  google/cloud/CMakeLists.txt
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/benchmarks/CMakeLists.txt
  google/cloud/bigtable/benchmarks/bigtable_benchmark_test.cc
  google/cloud/bigtable/bigtable_client.bzl
  google/cloud/bigtable/bigtable_client_unit_tests.bzl
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/internal/grpc_error_delegate.cc
  google/cloud/bigtable/internal/grpc_error_delegate.h
  google/cloud/bigtable/internal/grpc_error_delegate_test.cc
  google/cloud/bigtable/internal/readrowsparser.cc
  google/cloud/bigtable/internal/unary_client_utils.h
  google/cloud/bigtable/table.cc
  google/cloud/bigtable/table.h
  google/cloud/bigtable/table_admin.cc
  google/cloud/bigtable/table_admin.h
  google/cloud/bigtable/testing/embedded_server_test_fixture.cc
  google/cloud/bigtable/testing/internal_table_test_fixture.cc
  google/cloud/firestore/CMakeLists.txt
  google/cloud/storage/CMakeLists.txt
Labels: bigtable, cla: yes, firestore, storage

#692 Refactor retry loop for install step.
  .travis.yml
  ci/install-bazel.sh
  ci/install-linux.sh
  ci/install-macosx.sh
  ci/install-retry.sh
Labels: cla: yes

#686 Introduce ObjectMetadata class.
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/object_metadata.cc
  google/cloud/storage/object_metadata.h
  google/cloud/storage/object_metadata_test.cc
  google/cloud/storage/storage_client.bzl
  google/cloud/storage/storage_client_unit_tests.bzl
Labels: cla: yes

#685 Support query modifiers in Bucket::GetMetadata.
  google/cloud/CMakeLists.txt
  google/cloud/google_cloud_cpp_common.bzl
  google/cloud/internal/optional.h
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/bucket.cc
  google/cloud/storage/bucket.h
  google/cloud/storage/bucket_test.cc
  google/cloud/storage/client.h
  google/cloud/storage/internal/curl_request.cc
  google/cloud/storage/internal/curl_request.h
  google/cloud/storage/internal/default_client.h
  google/cloud/storage/internal/default_client_test.cc
  google/cloud/storage/storage_client.bzl
  google/cloud/storage/testing/mock_http_request.cc
  google/cloud/storage/testing/mock_http_request.h
  google/cloud/storage/tests/bucket_integration_test.cc
  google/cloud/storage/tests/curl_request_integration_test.cc
  google/cloud/storage/well_known_parameters.h
Labels: cla: yes, storage

#696 implemented integration test of DeleteCluster(#503)
  google/cloud/bigtable/tests/instance_admin_emulator.cc
  google/cloud/bigtable/tests/instance_admin_integration_test.cc
Labels: cla: yes

#698 Include analysis reports in the Travis logs.
  ci/dump-logs.sh
Labels: cla: yes

#695 Run integration tests against a fake.
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/client.cc
  google/cloud/storage/client.h
  google/cloud/storage/client_options.cc
  google/cloud/storage/client_options.h
  google/cloud/storage/credentials.cc
  google/cloud/storage/credentials.h
  google/cloud/storage/internal/default_client.h
  google/cloud/storage/internal/default_client_test.cc
  google/cloud/storage/storage_client.bzl
  google/cloud/storage/tests/bucket_integration_test.cc
  google/cloud/storage/tests/run_integration_tests.sh
  google/cloud/storage/tests/testbench.py
Labels: cla: yes, storage, testing

#703 Use functions to get build-time config.
  google/cloud/bigtable/benchmarks/bigtable_benchmark_test.cc
  google/cloud/bigtable/benchmarks/setup.cc
  google/cloud/bigtable/version.cc
  google/cloud/internal/build_info.cc.in
  google/cloud/internal/build_info.h
  google/cloud/storage/version.cc
Labels: bigtable, cla: yes, firestore, storage

#704 Return "" for auth header of InsecureCredentials.
  google/cloud/storage/credentials.cc
  google/cloud/storage/credentials.h
  google/cloud/storage/internal/authorized_user_credentials.h
  google/cloud/storage/internal/authorized_user_credentials_test.cc
  google/cloud/storage/internal/default_client.h
  google/cloud/storage/internal/default_client_test.cc
Labels: cla: yes

#706 Fix typos in the style guide [skip ci].
  doc/cpp-style-guide.md
Labels: cla: yes

#701 Pass bigtable::Table by value in the samples.
  google/cloud/bigtable/examples/bigtable_samples.cc
Labels: bigtable, cla: yes

#709 Link CURL dependencies only if the library is static.
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/tests/CMakeLists.txt
Labels: cla: yes, storage

#708 Take a new snapshot for the ABI check.
  ci/test-abi/google_cloud_cpp_common.expected.abi.dump
Labels: cla: yes, type: process

#707 Fix implementation of optional<T>.
  google/cloud/CMakeLists.txt
  google/cloud/google_cloud_cpp_common_unit_tests.bzl
  google/cloud/internal/optional.h
  google/cloud/internal/optional_test.cc
Labels: cla: yes, storage

#587 Integration Test for InstanceAdmin::ListCluster
  google/cloud/bigtable/examples/bigtable_samples_instance_admin.cc
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/tests/instance_admin_emulator.cc
  google/cloud/bigtable/tests/instance_admin_integration_test.cc
Labels: bigtable, cla: yes, kokoro:run

#711 Create storage::Object class
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/bucket_test.cc
  google/cloud/storage/internal/curl_request.cc
  google/cloud/storage/object.cc
  google/cloud/storage/object.h
  google/cloud/storage/object_test.cc
  google/cloud/storage/storage_client.bzl
  google/cloud/storage/storage_client_testing.bzl
  google/cloud/storage/storage_client_unit_tests.bzl
  google/cloud/storage/testing/mock_client.h
  google/cloud/storage/well_known_parameters.h
Labels: cla: yes, storage

#715 Propose new ADR [skip ci].
  doc/adr/2018-06-13-storage-always-retries.md
  doc/adr/adr-template.md
Labels: cla: yes, storage

#705 Introduce API to create GCS Objects
  google/cloud/storage/bucket.cc
  google/cloud/storage/bucket.h
  google/cloud/storage/bucket_test.cc
  google/cloud/storage/client.h
  google/cloud/storage/examples/run_examples_production.sh
  google/cloud/storage/examples/storage_bucket_samples.cc
  google/cloud/storage/internal/default_client.h
  google/cloud/storage/testing/mock_client.h
  google/cloud/storage/tests/bucket_integration_test.cc
  google/cloud/storage/tests/testbench.py
Labels: cla: yes, storage

#719 InstanceAdmin::GetCluster Implementation and Unit Tests
  google/cloud/bigtable/examples/bigtable_samples_instance_admin.cc
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/instance_admin_client.cc
  google/cloud/bigtable/instance_admin_client.h
  google/cloud/bigtable/instance_admin_test.cc
  google/cloud/bigtable/internal/instance_admin.cc
  google/cloud/bigtable/internal/instance_admin.h
  google/cloud/bigtable/internal/instance_admin_test.cc
  google/cloud/bigtable/testing/mock_instance_admin_client.h
  google/cloud/bigtable/tests/instance_admin_integration_test.cc
Labels: cla: yes

#700 Pass bigtable::TableAdmin by value in sample snippets.
  google/cloud/bigtable/examples/bigtable_samples.cc
Labels: bigtable, cla: yes

#720 Correctly initialize ClientOptions in test.
  google/cloud/bigtable/benchmarks/embedded_server_test.cc
Labels: cla: yes

#718 Refactor parameter handling for *Request classes.
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/bucket.cc
  google/cloud/storage/bucket.h
  google/cloud/storage/bucket_test.cc
  google/cloud/storage/client.h
  google/cloud/storage/internal/curl_request.cc
  google/cloud/storage/internal/curl_request.h
  google/cloud/storage/internal/default_client.h
  google/cloud/storage/internal/default_client_test.cc
  google/cloud/storage/internal/get_bucket_metadata_request.h
  google/cloud/storage/internal/insert_object_media_request.h
  google/cloud/storage/internal/request_parameters.h
  google/cloud/storage/storage_client.bzl
  google/cloud/storage/testing/mock_client.h
  google/cloud/storage/testing/mock_http_request.cc
  google/cloud/storage/testing/mock_http_request.h
  google/cloud/storage/tests/curl_request_integration_test.cc
  google/cloud/storage/well_known_parameters.h
Labels: cla: yes, storage

#723 Refactor bigtable/testing/random.h to google/cloud.
  google/cloud/CMakeLists.txt
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/benchmarks/apply_read_latency_benchmark.cc
  google/cloud/bigtable/benchmarks/benchmark.cc
  google/cloud/bigtable/benchmarks/benchmark.h
  google/cloud/bigtable/benchmarks/bigtable_benchmark_test.cc
  google/cloud/bigtable/benchmarks/embedded_server.cc
  google/cloud/bigtable/benchmarks/endurance_benchmark.cc
  google/cloud/bigtable/benchmarks/random_mutation.cc
  google/cloud/bigtable/benchmarks/random_mutation.h
  google/cloud/bigtable/benchmarks/random_mutation_test.cc
  google/cloud/bigtable/benchmarks/scan_throughput_benchmark.cc
  google/cloud/bigtable/benchmarks/setup.cc
  google/cloud/bigtable/bigtable_client_testing.bzl
  google/cloud/bigtable/bigtable_client_unit_tests.bzl
  google/cloud/bigtable/testing/table_integration_test.cc
  google/cloud/bigtable/testing/table_integration_test.h
  google/cloud/bigtable/tests/admin_integration_test.cc
  google/cloud/bigtable/tests/instance_admin_integration_test.cc
  google/cloud/google_cloud_cpp_common.bzl
  google/cloud/google_cloud_cpp_common_unit_tests.bzl
  google/cloud/internal/random.cc
  google/cloud/internal/random.h
  google/cloud/internal/random_test.cc
Labels: bigtable, cla: yes, storage

#722 Implement integration tests and samples for InstanceAdmin::CreateCluster
  google/cloud/bigtable/examples/bigtable_samples_instance_admin.cc
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/tests/instance_admin_integration_test.cc
Labels: cla: yes

#731 Polling Policy one failure case handling on server overload
  google/cloud/bigtable/polling_policy_test.cc
  google/cloud/bigtable/rpc_retry_policy_test.cc
Labels: cla: yes

#729 Switch Kokoro configuration to Bazel.
  ci/kokoro/ubuntu/build.sh
  ci/kokoro/ubuntu/continuous.cfg
  ci/kokoro/ubuntu/presubmit.cfg
Labels: cla: yes, type: process

#725 Implement ReadObjectRangeRequest.
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/client.h
  google/cloud/storage/internal/read_object_range_request.h
  google/cloud/storage/internal/read_object_range_request_test.cc
  google/cloud/storage/storage_client.bzl
  google/cloud/storage/storage_client_unit_tests.bzl
Labels: cla: yes, storage

#739 Do not reuse cluster names in the example script.
  google/cloud/bigtable/examples/run_examples_utils.sh
Labels: bigtable, cla: yes, priority: p0

#735 Document treatment of optional parameters [skip ci].
  doc/adr/2018-06-18-storage-request-parameters-are-function-arguments.md
Labels: cla: yes, docs, storage

#736 Initial iostream class to read object media.
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/bucket_test.cc
  google/cloud/storage/client.h
  google/cloud/storage/internal/default_client.h
  google/cloud/storage/object_stream.cc
  google/cloud/storage/object_stream.h
  google/cloud/storage/object_stream_test.cc
  google/cloud/storage/storage_client.bzl
  google/cloud/storage/storage_client_testing.bzl
  google/cloud/storage/storage_client_unit_tests.bzl
  google/cloud/storage/testing/canonical_errors.h
  google/cloud/storage/testing/mock_client.h
Labels: cla: yes, storage

#734 Refactor BackoffPolicy implementation.
  google/cloud/CMakeLists.txt
  google/cloud/bigtable/rpc_backoff_policy.cc
  google/cloud/bigtable/rpc_backoff_policy.h
  google/cloud/google_cloud_cpp_common.bzl
  google/cloud/google_cloud_cpp_common_unit_tests.bzl
  google/cloud/internal/backoff_policy.cc
  google/cloud/internal/backoff_policy.h
  google/cloud/internal/backoff_policy_test.cc
Labels: cla: yes

#749 Fix insert object operation
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_bucket_samples.cc
  google/cloud/storage/internal/default_client.h
  google/cloud/storage/tests/testbench.py
Labels: cla: yes, storage

#748 Document decision regarding input validation.
  doc/adr/2018-06-19-do-not-duplicate-server-side-validation.md
Labels: bigtable, cla: yes, docs, storage

#728 Refactor retry policy to google/cloud/internal.
  google/cloud/CMakeLists.txt
  google/cloud/bigtable/internal/bulk_mutator.cc
  google/cloud/bigtable/polling_policy.h
  google/cloud/bigtable/row_reader_test.cc
  google/cloud/bigtable/rpc_retry_policy.cc
  google/cloud/bigtable/rpc_retry_policy.h
  google/cloud/google_cloud_cpp_common.bzl
  google/cloud/google_cloud_cpp_common_unit_tests.bzl
  google/cloud/internal/retry_policy.h
  google/cloud/internal/retry_policy_test.cc
Labels: bigtable, cla: yes

#747 Implement reading of large objects
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/client.h
  google/cloud/storage/internal/curl_request.h
  google/cloud/storage/internal/default_client.h
  google/cloud/storage/internal/http_response.h
  google/cloud/storage/internal/read_object_range_request.cc
  google/cloud/storage/internal/read_object_range_request.h
  google/cloud/storage/internal/read_object_range_request_test.cc
  google/cloud/storage/object_stream.cc
  google/cloud/storage/object_stream.h
  google/cloud/storage/object_stream_test.cc
  google/cloud/storage/storage_client.bzl
  google/cloud/storage/testing/mock_client.h
Labels: cla: yes, storage

#716 Implement bigtable::OptionalRow using optional<T>.
  google/cloud/bigtable/internal/rowreaderiterator.h
  google/cloud/internal/optional.h
  google/cloud/internal/optional_test.cc
Labels: bigtable, cla: yes

#757 Move test-install build to Ubuntu:18.04.
  .travis.yml
Labels: cla: yes, type: cleanup

#753 Fix include guard and the script to check them.
  ci/check-include-guards.gawk
  ci/check-style.sh
  google/cloud/internal/backoff_policy.h
Labels: cla: yes, storage, type: cleanup

#756 Refactor CheckLimitedTime.
  cmake/CreateBazelConfig.cmake
  google/cloud/BUILD
  google/cloud/CMakeLists.txt
  google/cloud/bigtable/BUILD
  google/cloud/bigtable/polling_policy_test.cc
  google/cloud/bigtable/rpc_retry_policy_test.cc
  google/cloud/cloud_testing/README.md
  google/cloud/cloud_testing/check_predicate_becomes_false.h
  google/cloud/google_cloud_cpp_testing.bzl
  google/cloud/internal/retry_policy_test.cc
  google/cloud/storage/BUILD
Labels: cla: yes

#752 Use retry and backoff policies in all operations.
  ci/kokoro/ubuntu/continuous.cfg
  ci/kokoro/ubuntu/presubmit.cfg
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/client.h
  google/cloud/storage/internal/retry_client.cc
  google/cloud/storage/internal/retry_client.h
  google/cloud/storage/internal/retry_client_test.cc
  google/cloud/storage/retry_policy.h
  google/cloud/storage/retry_policy_test.cc
  google/cloud/storage/storage_client.bzl
  google/cloud/storage/storage_client_unit_tests.bzl
Labels: cla: yes, storage

#764 changed snake_case functions which are not simple accessors
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/internal/table.cc
  google/cloud/bigtable/internal/unary_client_utils.h
  google/cloud/bigtable/metadata_update_policy.cc
  google/cloud/bigtable/metadata_update_policy.h
  google/cloud/bigtable/polling_policy.h
  google/cloud/bigtable/row_reader.cc
  google/cloud/bigtable/row_reader_test.cc
  google/cloud/bigtable/rpc_backoff_policy.cc
  google/cloud/bigtable/rpc_backoff_policy.h
  google/cloud/bigtable/rpc_backoff_policy_test.cc
  google/cloud/bigtable/rpc_retry_policy.cc
  google/cloud/bigtable/rpc_retry_policy.h
  google/cloud/bigtable/rpc_retry_policy_test.cc
Labels: cla: yes

#760 Disable admin integration tests for bigtable.
  google/cloud/bigtable/examples/run_examples_production.sh
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/tests/integration_tests_utils.sh
  google/cloud/bigtable/tests/run_integration_tests_emulator.sh
  google/cloud/bigtable/tests/run_integration_tests_production.sh
  google/cloud/bigtable/tools/run_emulator_utils.sh
Labels: bigtable, cla: yes

#763 storage::Client to storage::internal::RawClient.
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/bucket.h
  google/cloud/storage/internal/default_client.h
  google/cloud/storage/internal/raw_client.cc
  google/cloud/storage/internal/raw_client.h
  google/cloud/storage/internal/retry_client.cc
  google/cloud/storage/internal/retry_client.h
  google/cloud/storage/object.h
  google/cloud/storage/object_stream.h
  google/cloud/storage/storage_client.bzl
  google/cloud/storage/testing/mock_client.h
Labels: cla: yes

#762 Implement classes to read list of objects.
  google/cloud/internal/optional.h
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/internal/default_client.h
  google/cloud/storage/internal/list_objects_request.cc
  google/cloud/storage/internal/list_objects_request.h
  google/cloud/storage/internal/list_objects_request_test.cc
  google/cloud/storage/internal/raw_client.h
  google/cloud/storage/internal/retry_client.cc
  google/cloud/storage/internal/retry_client.h
  google/cloud/storage/list_objects_reader.cc
  google/cloud/storage/list_objects_reader.h
  google/cloud/storage/list_objects_reader_test.cc
  google/cloud/storage/storage_client.bzl
  google/cloud/storage/storage_client_unit_tests.bzl
  google/cloud/storage/testing/mock_client.h
  google/cloud/storage/tests/bucket_integration_test.cc
  google/cloud/storage/tests/testbench.py
  google/cloud/storage/well_known_parameters.h
Labels: cla: yes, storage

#767 Refactor Bucket -> Client.
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/bucket.cc
  google/cloud/storage/bucket.h
  google/cloud/storage/bucket_test.cc
  google/cloud/storage/client.cc
  google/cloud/storage/client.h
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_bucket_samples.cc
  google/cloud/storage/internal/raw_client.cc
  google/cloud/storage/internal/raw_client.h
  google/cloud/storage/object.cc
  google/cloud/storage/object.h
  google/cloud/storage/object_test.cc
  google/cloud/storage/storage_client.bzl
  google/cloud/storage/storage_client_unit_tests.bzl
  google/cloud/storage/tests/bucket_integration_test.cc
  google/cloud/storage/tests/testbench.py
Labels: cla: yes, storage

#766 Add support for basic service account credentials.
  google/cloud/storage/BUILD
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/credentials.cc
  google/cloud/storage/credentials.h
  google/cloud/storage/internal/authorized_user_credentials.h
  google/cloud/storage/internal/authorized_user_credentials_test.cc
  google/cloud/storage/internal/credential_constants.h
  google/cloud/storage/internal/openssl_util.h
  google/cloud/storage/internal/service_account_credentials.h
  google/cloud/storage/internal/service_account_credentials_test.cc
  google/cloud/storage/storage_client.bzl
  google/cloud/storage/storage_client_unit_tests.bzl
Labels: cla: yes

#776 Tweak JWT refresh request so it works against prod
  google/cloud/storage/internal/service_account_credentials.h
  google/cloud/storage/internal/service_account_credentials_test.cc
Labels: cla: yes

#775 CreateCluster now takes only location id instread of full path
  google/cloud/bigtable/examples/bigtable_samples_instance_admin.cc
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/instance_admin_test.cc
  google/cloud/bigtable/tests/instance_admin_integration_test.cc
Labels: cla: yes

#779 Add (optional) logging for each http request / response
  google/cloud/log.cc
  google/cloud/log.h
  google/cloud/log_test.cc
  google/cloud/storage/client_options.cc
  google/cloud/storage/client_options.h
  google/cloud/storage/internal/authorized_user_credentials.h
  google/cloud/storage/internal/authorized_user_credentials_test.cc
  google/cloud/storage/internal/curl_request.cc
  google/cloud/storage/internal/curl_request.h
  google/cloud/storage/internal/default_client.h
  google/cloud/storage/internal/default_client_test.cc
  google/cloud/storage/internal/service_account_credentials.h
  google/cloud/storage/internal/service_account_credentials_test.cc
  google/cloud/storage/testing/mock_http_request.cc
  google/cloud/storage/testing/mock_http_request.h
  google/cloud/storage/tests/curl_request_integration_test.cc
Labels: cla: yes, storage

#778 Enable GCS integration tests in Kokoro.
  ci/kokoro/ubuntu/build.sh
  google/cloud/storage/examples/BUILD
  google/cloud/storage/internal/default_client.h
  google/cloud/storage/tests/BUILD
  google/cloud/storage/tests/CMakeLists.txt
  google/cloud/storage/tests/storage_client_integration_tests.bzl
Labels: cla: yes, storage

#772 Add sample for ListObjects().
  google/cloud/storage/client.h
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_bucket_samples.cc
Labels: cla: yes, storage

#782 ostream operators for requests and responses.
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/internal/binary_data_as_debug_string.cc
  google/cloud/storage/internal/binary_data_as_debug_string.h
  google/cloud/storage/internal/binary_data_as_debug_string_test.cc
  google/cloud/storage/internal/curl_request.cc
  google/cloud/storage/internal/get_bucket_metadata_request.cc
  google/cloud/storage/internal/get_bucket_metadata_request.h
  google/cloud/storage/internal/get_bucket_metadata_request_test.cc
  google/cloud/storage/internal/insert_object_media_request.cc
  google/cloud/storage/internal/insert_object_media_request.h
  google/cloud/storage/internal/insert_object_media_request_test.cc
  google/cloud/storage/internal/list_objects_request.cc
  google/cloud/storage/internal/list_objects_request.h
  google/cloud/storage/internal/list_objects_request_test.cc
  google/cloud/storage/internal/read_object_range_request.cc
  google/cloud/storage/internal/read_object_range_request.h
  google/cloud/storage/internal/read_object_range_request_test.cc
  google/cloud/storage/internal/request_parameters.h
  google/cloud/storage/storage_client.bzl
  google/cloud/storage/storage_client_unit_tests.bzl
Labels: cla: yes, storage

#783 Refactor EnvironmentVariableRestore to testing library.
  google/cloud/CMakeLists.txt
  google/cloud/bigtable/polling_policy_test.cc
  google/cloud/bigtable/rpc_retry_policy_test.cc
  google/cloud/google_cloud_cpp_testing.bzl
  google/cloud/internal/retry_policy_test.cc
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/internal/google_application_default_credentials_file_test.cc
  google/cloud/testing_util/README.md
  google/cloud/testing_util/check_predicate_becomes_false.h
  google/cloud/testing_util/environment_variable_restore.cc
  google/cloud/testing_util/environment_variable_restore.h
Labels: cla: yes, storage

#786 Add support to enable per-call tracing.
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/client_options.cc
  google/cloud/storage/client_options.h
  google/cloud/storage/storage_client_options_test.cc
  google/cloud/storage/storage_client_unit_tests.bzl
Labels: cla: yes, storage

#790 Fix WIN32 macro.
  google/cloud/internal/setenv.cc
  google/cloud/storage/internal/parse_rfc3339.cc
Labels: cla: yes
