Repository googleapis/google-cloud-cpp, pull requests merged in 2019-02, with the labels that each got.

#1917 Link documentation to google/cloud symbols.
  cmake/GoogleCloudCppCommon.cmake
  google/cloud/CMakeLists.txt
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/client.h
Labels: api: storage, cla: yes

#1916 Remove support for StatusOr<void>
  ci/test-install/storage_install_test.cc
  google/cloud/status_or.h
  google/cloud/status_or_test.cc
  google/cloud/storage/benchmarks/storage_latency_benchmark.cc
  google/cloud/storage/benchmarks/storage_throughput_benchmark.cc
  google/cloud/storage/bucket_test.cc
  google/cloud/storage/client.cc
  google/cloud/storage/client.h
  google/cloud/storage/client_bucket_acl_test.cc
  google/cloud/storage/client_default_object_acl_test.cc
  google/cloud/storage/client_notifications_test.cc
  google/cloud/storage/client_object_acl_test.cc
  google/cloud/storage/examples/storage_bucket_acl_samples.cc
  google/cloud/storage/examples/storage_bucket_samples.cc
  google/cloud/storage/examples/storage_default_object_acl_samples.cc
  google/cloud/storage/examples/storage_notification_samples.cc
  google/cloud/storage/examples/storage_object_acl_samples.cc
  google/cloud/storage/examples/storage_object_samples.cc
  google/cloud/storage/object_test.cc
  google/cloud/storage/tests/bucket_integration_test.cc
  google/cloud/storage/tests/curl_resumable_streambuf_integration_test.cc
  google/cloud/storage/tests/object_checksum_integration_test.cc
  google/cloud/storage/tests/object_hash_integration_test.cc
  google/cloud/storage/tests/object_insert_integration_test.cc
  google/cloud/storage/tests/object_integration_test.cc
  google/cloud/storage/tests/object_media_integration_test.cc
  google/cloud/storage/tests/object_resumable_write_integration_test.cc
  google/cloud/storage/tests/object_rewrite_integration_test.cc
  google/cloud/storage/tests/thread_integration_test.cc
Labels: cla: yes

#1908 Changed TableAdmin's CreateTable and ListTables to return StatusOr
  google/cloud/bigtable/examples/bigtable_samples.cc
  google/cloud/bigtable/examples/table_admin_snippets.cc
  google/cloud/bigtable/internal/grpc_error_delegate.cc
  google/cloud/bigtable/internal/grpc_error_delegate.h
  google/cloud/bigtable/internal/grpc_error_delegate_test.cc
  google/cloud/bigtable/table_admin.cc
  google/cloud/bigtable/table_admin.h
  google/cloud/bigtable/table_admin_test.cc
  google/cloud/bigtable/tests/admin_async_future_integration_test.cc
  google/cloud/bigtable/tests/admin_async_integration_test.cc
  google/cloud/bigtable/tests/admin_integration_test.cc
Labels: api: bigtable, cla: yes

#1920 Support scripts for Kokoro+Docker.
  ci/kokoro/docker/asan-presubmit.cfg
  ci/kokoro/docker/asan.cfg
  ci/kokoro/docker/build.sh
  ci/travis/build-docker.sh
  ci/travis/build-linux.sh
  ci/travis/linux-config.sh
Labels: cla: yes, type: process

#1911 Make credential creation not throw exceptions.
  ci/test-install/storage_install_test.cc
  google/cloud/examples/gcs2cbt.cc
  google/cloud/status_or_test.cc
  google/cloud/storage/benchmarks/storage_latency_benchmark.cc
  google/cloud/storage/benchmarks/storage_throughput_benchmark.cc
  google/cloud/storage/bucket_test.cc
  google/cloud/storage/client.cc
  google/cloud/storage/client.h
  google/cloud/storage/client_default_object_acl_test.cc
  google/cloud/storage/client_notifications_test.cc
  google/cloud/storage/client_options.cc
  google/cloud/storage/client_options.h
  google/cloud/storage/client_sign_url_test.cc
  google/cloud/storage/examples/storage_bucket_acl_samples.cc
  google/cloud/storage/examples/storage_bucket_iam_samples.cc
  google/cloud/storage/examples/storage_bucket_samples.cc
  google/cloud/storage/examples/storage_default_object_acl_samples.cc
  google/cloud/storage/examples/storage_notification_samples.cc
  google/cloud/storage/examples/storage_object_acl_samples.cc
  google/cloud/storage/examples/storage_object_samples.cc
  google/cloud/storage/examples/storage_quickstart.cc
  google/cloud/storage/oauth2/authorized_user_credentials.cc
  google/cloud/storage/oauth2/authorized_user_credentials.h
  google/cloud/storage/oauth2/authorized_user_credentials_test.cc
  google/cloud/storage/oauth2/compute_engine_credentials.h
  google/cloud/storage/oauth2/google_credentials.cc
  google/cloud/storage/oauth2/google_credentials.h
  google/cloud/storage/oauth2/google_credentials_test.cc
  google/cloud/storage/oauth2/service_account_credentials.cc
  google/cloud/storage/oauth2/service_account_credentials.h
  google/cloud/storage/oauth2/service_account_credentials_test.cc
  google/cloud/storage/object_test.cc
  google/cloud/storage/storage_client_options_test.cc
  google/cloud/storage/tests/bucket_integration_test.cc
  google/cloud/storage/tests/curl_resumable_streambuf_integration_test.cc
  google/cloud/storage/tests/curl_resumable_upload_session_integration_test.cc
  google/cloud/storage/tests/object_checksum_integration_test.cc
  google/cloud/storage/tests/object_hash_integration_test.cc
  google/cloud/storage/tests/object_insert_integration_test.cc
  google/cloud/storage/tests/object_integration_test.cc
  google/cloud/storage/tests/object_media_integration_test.cc
  google/cloud/storage/tests/object_resumable_write_integration_test.cc
  google/cloud/storage/tests/object_rewrite_integration_test.cc
  google/cloud/storage/tests/service_account_integration_test.cc
  google/cloud/storage/tests/thread_integration_test.cc
Labels: api: storage, cla: yes

#1925 Add an example for multipart uploads.
  google/cloud/storage/client.h
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_object_samples.cc
Labels: api: storage, cla: yes, type: docs

#1927 Remove ASAN build from Travis.
  .travis.yml
Labels: cla: yes, type: process

#1931 Fix Travis CI link [skip ci].
  README.md
Labels: cla: yes, type: process

#1928 Create Kokoro configs for more builds.
  ci/kokoro/docker/centos-7-presubmit.cfg
  ci/kokoro/docker/centos-7.cfg
  ci/kokoro/docker/noex-presubmit.cfg
  ci/kokoro/docker/noex.cfg
  ci/kokoro/docker/ubsan-presubmit.cfg
  ci/kokoro/docker/ubsan.cfg
Labels: cla: yes, type: process

#1934 In examples, do not use StatusOr<T>::value().
  google/cloud/storage/examples/storage_bucket_samples.cc
  google/cloud/storage/examples/storage_object_samples.cc
Labels: api: storage, cla: yes

#1936 Cleanup argc checking in storage/examples.
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_bucket_samples.cc
  google/cloud/storage/examples/storage_object_acl_samples.cc
  google/cloud/storage/examples/storage_object_samples.cc
Labels: cla: yes

#1938 Allow compiling external projects in Debug mode
  cmake/external/c-ares.cmake
  cmake/external/crc32c.cmake
  cmake/external/curl.cmake
  cmake/external/googletest.cmake
  cmake/external/grpc.cmake
  cmake/external/zlib.cmake
Labels: cla: yes

#1933 Improve documentation of Client policies.
  google/cloud/storage/client.h
  google/cloud/storage/doc/storage-main.dox
Labels: api: storage, cla: yes

#1940 Implement example to read a row range.
  google/cloud/storage/client.h
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_object_samples.cc
Labels: api: storage, cla: yes

#1935 Implementation of noex AsyncReadModifyWriteRow
  google/cloud/bigtable/data_client.cc
  google/cloud/bigtable/data_client.h
  google/cloud/bigtable/internal/table.cc
  google/cloud/bigtable/internal/table.h
  google/cloud/bigtable/testing/inprocess_data_client.cc
  google/cloud/bigtable/testing/inprocess_data_client.h
  google/cloud/bigtable/testing/mock_data_client.h
  google/cloud/bigtable/tests/data_async_integration_test.cc
Labels: api: bigtable, cla: yes

#1919 adding Setup member function in PollingPolicy
  google/cloud/bigtable/internal/async_poll_op.h
  google/cloud/bigtable/internal/poll_longrunning_operation.h
  google/cloud/bigtable/internal/table_admin.cc
  google/cloud/bigtable/polling_policy.h
Labels: api: bigtable, cla: yes

#1905 Implementation of AsyncApply function
  google/cloud/bigtable/examples/data_async_snippets.cc
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/table.cc
  google/cloud/bigtable/table.h
  google/cloud/bigtable/tests/data_async_future_integration_test.cc
Labels: cla: yes

#1941 Move some builds from Travis to Kokoro.
  .travis.yml
  README.md
Labels: cla: yes, type: process

#1955 updated release notes [skip ci]
  google/cloud/README.md
  google/cloud/bigtable/README.md
  google/cloud/storage/README.md
Labels: cla: yes

#1957 Change the storage examples to throw a std::runtime_error on failure.
  google/cloud/storage/doc/storage-main.dox
  google/cloud/storage/examples/storage_bucket_acl_samples.cc
  google/cloud/storage/examples/storage_bucket_iam_samples.cc
  google/cloud/storage/examples/storage_bucket_samples.cc
  google/cloud/storage/examples/storage_default_object_acl_samples.cc
  google/cloud/storage/examples/storage_notification_samples.cc
  google/cloud/storage/examples/storage_object_acl_samples.cc
  google/cloud/storage/examples/storage_object_samples.cc
Labels: cla: yes

#1924 List{Instances,Clusters} return failed_locations.
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/bigtable_client.bzl
  google/cloud/bigtable/cluster_list_responses.h
  google/cloud/bigtable/examples/bigtable_samples_instance_admin.cc
  google/cloud/bigtable/examples/bigtable_samples_instance_admin_ext.cc
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/instance_admin_test.cc
  google/cloud/bigtable/instance_list_responses.h
  google/cloud/bigtable/internal/async_list_clusters.h
  google/cloud/bigtable/internal/async_list_instances.h
  google/cloud/bigtable/internal/instance_admin.cc
  google/cloud/bigtable/internal/instance_admin.h
  google/cloud/bigtable/internal/instance_admin_test.cc
  google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
  google/cloud/bigtable/tests/instance_admin_async_integration_test.cc
  google/cloud/bigtable/tests/instance_admin_integration_test.cc
Labels: api: bigtable, cla: yes

#1962 Bumping versions in master to be one creater than the current release
  ci/test-install/CMakeLists.txt
  google/cloud/CMakeLists.txt
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/bigtable_client_version.bzl
  google/cloud/google_cloud_cpp_common_version.bzl
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/storage_client_version.bzl
Labels: cla: yes

#1939 Implementation of RowSet example using discontinuous keys
  google/cloud/bigtable/examples/CMakeLists.txt
  google/cloud/bigtable/examples/bigtable_rowset.cc
  google/cloud/bigtable/examples/run_examples_emulator.sh
  google/cloud/bigtable/examples/run_examples_utils.sh
Labels: cla: yes

#1964 Updated Release instructions
  doc/cutting-a-release.md
Labels: cla: yes

#1972 Package version config work without a version.
  ci/test-install/CMakeLists.txt
  google/cloud/bigtable/config.cmake.in
  google/cloud/config-version.cmake.in
  google/cloud/storage/config.cmake.in
Labels: cla: yes, type: process

#1971 Remove unnecessary code from example.
  google/cloud/storage/examples/storage_object_samples.cc
Labels: api: storage, cla: yes

#1975 README.md: fix typo in command
  CONTRIBUTING.md
Labels: cla: yes

#1976 Pin the Google Cloud SDK version.
  ci/travis/Dockerfile.centos
  ci/travis/Dockerfile.fedora
  ci/travis/Dockerfile.ubuntu
  ci/travis/Dockerfile.ubuntu-install
  ci/travis/Dockerfile.ubuntu-trusty
Labels: cla: yes, type: process

#1979 Simplify Kokoro configs.
  ci/kokoro/docker/asan-presubmit.cfg
  ci/kokoro/docker/asan.cfg
  ci/kokoro/docker/build.sh
  ci/kokoro/docker/centos-7-presubmit.cfg
  ci/kokoro/docker/centos-7.cfg
  ci/kokoro/docker/noex-presubmit.cfg
  ci/kokoro/docker/noex.cfg
  ci/kokoro/docker/ubsan-presubmit.cfg
  ci/kokoro/docker/ubsan.cfg
Labels: cla: yes, type: process

#1984 adds virtual d'tor to some test classes that have virtual functions
  google/cloud/bigtable/internal/async_poll_op_test.cc
  google/cloud/bigtable/internal/async_retry_multi_page_test.cc
  google/cloud/bigtable/internal/async_retry_op_test.cc
Labels: cla: yes

#1942 Initial `make install` instructions.
  INSTALL.md
  README.md
  ci/test-readme/Dockerfile.centos-install
  ci/test-readme/Dockerfile.fedora-install
  ci/test-readme/Dockerfile.ubuntu-install
  cmake/IncludeGrpc.cmake
  cmake/IncludeProtobuf.cmake
  google/cloud/storage/CMakeLists.txt
Labels: cla: yes, type: docs

#1986 removed unneeded virtual functions
  google/cloud/bigtable/internal/async_poll_op_test.cc
  google/cloud/bigtable/internal/async_retry_multi_page_test.cc
  google/cloud/bigtable/internal/async_retry_op_test.cc
Labels: cla: yes

#1988 Implement {ASSERT,EXPECT}_OK.
  google/cloud/CMakeLists.txt
  google/cloud/google_cloud_cpp_common_unit_tests.bzl
  google/cloud/google_cloud_cpp_testing.bzl
  google/cloud/testing_util/assert_ok.cc
  google/cloud/testing_util/assert_ok.h
  google/cloud/testing_util/assert_ok_test.cc
Labels: cla: yes

#1992 Migrate instance admin API to StatusOr<>.
  google/cloud/bigtable/examples/bigtable_samples_instance_admin.cc
  google/cloud/bigtable/examples/bigtable_samples_instance_admin_ext.cc
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/instance_admin_test.cc
  google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
  google/cloud/bigtable/tests/instance_admin_async_integration_test.cc
  google/cloud/bigtable/tests/instance_admin_integration_test.cc
Labels: api: bigtable, cla: yes

#1995 Homogenize failed_locations handling in samples.
  google/cloud/bigtable/examples/bigtable_samples_instance_admin.cc
  google/cloud/bigtable/examples/bigtable_samples_instance_admin_ext.cc
Labels: api: bigtable, cla: yes

#1987 Allow specifying non-default scopes and subject.
  google/cloud/storage/oauth2/credential_constants.h
  google/cloud/storage/oauth2/google_credentials.cc
  google/cloud/storage/oauth2/google_credentials.h
  google/cloud/storage/oauth2/google_credentials_test.cc
  google/cloud/storage/oauth2/service_account_credentials.h
  google/cloud/storage/oauth2/service_account_credentials_test.cc
  google/cloud/storage/tools/make_jwt_assertion_for_test_data.py
Labels: api: storage, cla: yes

#1998 Standardize {EXPECT,ASSERT}_STATUS_OK description.
  google/cloud/testing_util/assert_ok.cc
  google/cloud/testing_util/assert_ok_test.cc
Labels: cla: yes

#1881 Add streaming to (Async)BulkMutator.
  google/cloud/bigtable/internal/async_bulk_apply.h
  google/cloud/bigtable/internal/bulk_mutator.cc
  google/cloud/bigtable/internal/bulk_mutator.h
  google/cloud/bigtable/internal/table.h
  google/cloud/bigtable/internal/table_async_bulk_apply_test.cc
Labels: :rotating_light:, api: bigtable, cla: yes

#2000 Declare GCS client library as Beta.
  README.md
  google/cloud/storage/README.md
Labels: cla: yes

#1879 First version of Apply batching.
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/bigtable_client.bzl
  google/cloud/bigtable/bigtable_client_unit_tests.bzl
  google/cloud/bigtable/client_options.cc
  google/cloud/bigtable/internal/client_options_defaults.h
  google/cloud/bigtable/internal/mutation_batcher.cc
  google/cloud/bigtable/internal/mutation_batcher.h
  google/cloud/bigtable/internal/mutation_batcher_test.cc
  google/cloud/bigtable/mutations.h
  google/cloud/bigtable/mutations_test.cc
Labels: :rotating_light:, api: bigtable, cla: yes

#1996 Use {EXPECT,ASSERT}_STATUS_OK where applicable.
  google/cloud/bigtable/table_admin_test.cc
  google/cloud/bigtable/tests/admin_async_future_integration_test.cc
  google/cloud/bigtable/tests/admin_async_integration_test.cc
  google/cloud/bigtable/tests/admin_integration_test.cc
  google/cloud/status_or_test.cc
  google/cloud/storage/bucket_test.cc
  google/cloud/storage/client_bucket_acl_test.cc
  google/cloud/storage/client_default_object_acl_test.cc
  google/cloud/storage/client_notifications_test.cc
  google/cloud/storage/client_object_acl_test.cc
  google/cloud/storage/client_object_copy_test.cc
  google/cloud/storage/client_service_account_test.cc
  google/cloud/storage/client_sign_url_test.cc
  google/cloud/storage/internal/curl_resumable_upload_session_test.cc
  google/cloud/storage/internal/retry_resumable_upload_session_test.cc
  google/cloud/storage/list_buckets_reader_test.cc
  google/cloud/storage/list_objects_reader_test.cc
  google/cloud/storage/oauth2/anonymous_credentials_test.cc
  google/cloud/storage/oauth2/authorized_user_credentials_test.cc
  google/cloud/storage/oauth2/google_credentials_test.cc
  google/cloud/storage/oauth2/service_account_credentials_test.cc
  google/cloud/storage/object_test.cc
  google/cloud/storage/storage_client_options_test.cc
  google/cloud/storage/tests/bucket_integration_test.cc
  google/cloud/storage/tests/curl_download_request_integration_test.cc
  google/cloud/storage/tests/curl_request_integration_test.cc
  google/cloud/storage/tests/curl_resumable_streambuf_integration_test.cc
  google/cloud/storage/tests/curl_resumable_upload_session_integration_test.cc
  google/cloud/storage/tests/curl_streambuf_integration_test.cc
  google/cloud/storage/tests/curl_upload_request_integration_test.cc
  google/cloud/storage/tests/object_checksum_integration_test.cc
  google/cloud/storage/tests/object_hash_integration_test.cc
  google/cloud/storage/tests/object_insert_integration_test.cc
  google/cloud/storage/tests/object_integration_test.cc
  google/cloud/storage/tests/object_media_integration_test.cc
  google/cloud/storage/tests/object_resumable_write_integration_test.cc
  google/cloud/storage/tests/object_rewrite_integration_test.cc
  google/cloud/storage/tests/service_account_integration_test.cc
  google/cloud/storage/tests/thread_integration_test.cc
Labels: cla: yes

#2002 Declare GCS client library as Beta.
  README.md
  google/cloud/storage/README.md
Labels: cla: yes

#1991 Automate testing of INSTALL.md instructions.
  .dockerignore
  INSTALL.md
  ci/test-install/Makefile
  ci/test-readme/Dockerfile.centos
  ci/test-readme/Dockerfile.centos-install
  ci/test-readme/Dockerfile.debian
  ci/test-readme/Dockerfile.fedora
  ci/test-readme/Dockerfile.fedora-install
  ci/test-readme/Dockerfile.opensuse
  ci/test-readme/Dockerfile.ubuntu
  ci/test-readme/Dockerfile.ubuntu-install
  ci/test-readme/Dockerfile.ubuntu-trusty
  ci/test-readme/dockerfile2markdown.sh
  ci/test-readme/extract-install.sh
  ci/test-readme/extract-readme.sh
  ci/test-readme/generate-install.sh
  ci/travis/build-docker.sh
  cmake/IncludeGrpc.cmake
  google/cloud/storage/benchmarks/run_benchmarks_testbench.sh
  google/cloud/storage/ci/run_integration_tests.sh
Labels: cla: yes, type: process

#1994 Change to StatusOr for Table::SampleRows()
  google/cloud/bigtable/examples/data_snippets.cc
  google/cloud/bigtable/table.h
  google/cloud/bigtable/table_sample_row_keys_test.cc
  google/cloud/bigtable/tests/data_integration_test.cc
Labels: cla: yes

#2011 Remove ciso646 include.
  google/cloud/bigtable/row_set.h
  google/cloud/firestore/field_path.cc
  google/cloud/future_generic_test.cc
  google/cloud/future_void_test.cc
  google/cloud/internal/build_info.cc.in
  google/cloud/internal/make_unique.h
  google/cloud/internal/port_platform.h
  google/cloud/optional.h
  google/cloud/status_or.h
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/internal/curl_wrappers.cc
Labels: cla: yes, type: cleanup

#2013 Stops using grpc's DO_NOT_USE enum
  google/cloud/bigtable/internal/grpc_error_delegate.cc
  google/cloud/status.h
  google/cloud/status_test.cc
Labels: cla: yes

#2010 Use random port for Bigtable emulator.
  google/cloud/bigtable/tests/instance_admin_emulator.cc
  google/cloud/bigtable/tools/run_emulator_utils.sh
Labels: cla: yes, type: process

#2014 Update method doc after the change to StatusOr.
  google/cloud/storage/oauth2/anonymous_credentials.h
  google/cloud/storage/oauth2/credentials.h
Labels: api: storage, cla: yes

#1977 Implementation of ReadRows() example showing how to use Prefix.
  google/cloud/bigtable/examples/CMakeLists.txt
  google/cloud/bigtable/examples/bigtable_rowset.cc
  google/cloud/bigtable/examples/data_snippets.cc
  google/cloud/bigtable/examples/run_examples_emulator.sh
  google/cloud/bigtable/examples/run_examples_utils.sh
Labels: :rotating_light:, cla: yes

#2007 Implement ubuntu:xenial install script.
  INSTALL.md
  ci/test-readme/Dockerfile.ubuntu-xenial
  ci/test-readme/generate-install.sh
Labels: cla: yes

#2012 Run storage testbench on unused port.
  google/cloud/storage/tools/run_testbench_utils.sh
Labels: cla: yes

#2008 Return StatusOr from Table::CheckAndMutateRow()
  google/cloud/bigtable/examples/data_snippets.cc
  google/cloud/bigtable/table.cc
  google/cloud/bigtable/table.h
  google/cloud/bigtable/table_check_and_mutate_row_test.cc
  google/cloud/bigtable/tests/data_integration_test.cc
Labels: cla: yes

#2016 Changes Clear() member to explicitly clear fields rather than rely on move-from
  google/cloud/bigtable/mutations.h
Labels: cla: yes

#2017 Dump detailed logs on build failures.
  ci/kokoro/docker/build.sh
Labels: cla: yes

#2018 Refactor Bazel installation.
  .travis.yml
  ci/install-bazel.sh
  ci/kokoro/macos/build.sh
Labels: cla: yes

#2020 Kokoro build scripts to test install instructions.
  ci/kokoro/install/build.sh
  ci/kokoro/install/centos.cfg
  ci/kokoro/install/debian.cfg
  ci/kokoro/install/fedora.cfg
  ci/kokoro/install/opensuse-leap.cfg
  ci/kokoro/install/opensuse.cfg
  ci/kokoro/install/ubuntu-trusty.cfg
  ci/kokoro/install/ubuntu-xenial.cfg
  ci/kokoro/install/ubuntu.cfg
Labels: cla: yes, type: process

#2023 moved tests into namespace to avoid using directive
  google/cloud/log_test.cc
Labels: cla: yes

#2025 Fix script to enforce formatting.
  CONTRIBUTING.md
  ci/check-style.sh
  google/cloud/bigtable/bigtable_version_test.cc
  google/cloud/bigtable/examples/bigtable_hello_world.cc
  google/cloud/bigtable/examples/bigtable_samples.cc
  google/cloud/bigtable/examples/table_admin_snippets.cc
  google/cloud/bigtable/internal/async_future_from_callback_test.cc
  google/cloud/bigtable/internal/table_async_row_reader_test.cc
  google/cloud/bigtable/rpc_retry_policy.cc
  google/cloud/bigtable/table_admin.cc
  google/cloud/bigtable/table_check_and_mutate_row_test.cc
  google/cloud/firestore/field_path.cc
  google/cloud/future_generic_test.cc
  google/cloud/future_generic_then_test.cc
  google/cloud/future_void_test.cc
  google/cloud/future_void_then_test.cc
  google/cloud/internal/filesystem_test.cc
  google/cloud/internal/future_impl_test.cc
  google/cloud/log_test.cc
  google/cloud/storage/bucket_metadata.cc
  google/cloud/storage/bucket_metadata_test.cc
  google/cloud/storage/examples/storage_object_samples.cc
  google/cloud/storage/hashing_options.cc
  google/cloud/storage/hashing_options_test.cc
  google/cloud/storage/idempotency_policy.cc
  google/cloud/storage/idempotency_policy_test.cc
  google/cloud/storage/internal/access_control_common.cc
  google/cloud/storage/internal/bucket_requests.cc
  google/cloud/storage/internal/bucket_requests_test.cc
  google/cloud/storage/internal/curl_download_request.cc
  google/cloud/storage/internal/curl_handle.cc
  google/cloud/storage/internal/curl_resumable_upload_session.cc
  google/cloud/storage/internal/curl_upload_request.cc
  google/cloud/storage/internal/curl_wrappers_locking_already_present_test.cc
  google/cloud/storage/internal/curl_wrappers_locking_disabled_test.cc
  google/cloud/storage/internal/curl_wrappers_locking_enabled_test.cc
  google/cloud/storage/internal/generate_message_boundary_test.cc
  google/cloud/storage/internal/hash_validator.cc
  google/cloud/storage/internal/http_response_test.cc
  google/cloud/storage/internal/logging_client.cc
  google/cloud/storage/internal/logging_client_test.cc
  google/cloud/storage/internal/logging_resumable_upload_session.cc
  google/cloud/storage/internal/notification_requests_test.cc
  google/cloud/storage/internal/object_requests_test.cc
  google/cloud/storage/internal/retry_client.cc
  google/cloud/storage/internal/retry_client_test.cc
  google/cloud/storage/internal/retry_resumable_upload_session.cc
  google/cloud/storage/internal/signed_url_requests.cc
  google/cloud/storage/list_objects_reader.cc
  google/cloud/storage/oauth2/anonymous_credentials.cc
  google/cloud/storage/object_metadata.cc
  google/cloud/storage/object_metadata_test.cc
  google/cloud/storage/object_rewriter.cc
  google/cloud/storage/service_account_test.cc
  google/cloud/storage/storage_version_test.cc
Labels: cla: yes, type: cleanup

#2027 Make InstanceAdmin emulator thread-safe.
  google/cloud/bigtable/tests/instance_admin_emulator.cc
Labels: api: bigtable, cla: yes

#2030 Fix flake on request-pay examples.
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_bucket_samples.cc
Labels: api: storage, cla: yes

#2031 removed 'move' tests
  google/cloud/bigtable/internal/readrowsparser_test.cc
  google/cloud/bigtable/mutations_test.cc
Labels: cla: yes

#2029 Enable OpenSSL when compiling libcurl as external.
  cmake/external/curl.cmake
Labels: cla: yes

#2026 New scripts to extract README.md instructions.
  INSTALL.md
  README.md
  ci/test-readme/Dockerfile.centos
  ci/test-readme/Dockerfile.ubuntu-trusty
  ci/test-readme/README.md
  ci/test-readme/dockerfile2markdown.sh
  ci/test-readme/extract-install.sh
  ci/test-readme/extract-readme.sh
  ci/test-readme/generate-install.sh
  ci/test-readme/generate-readme.sh
Labels: cla: yes, type: docs

#2033 Support additional build types.
  ci/kokoro/docker/build.sh
Labels: cla: yes

#2034 added needed include for async_stream.h
  google/cloud/bigtable/testing/mock_response_reader.h
Labels: cla: yes

#2035 Only require googletest if it is needed.
  cmake/IncludeGMock.cmake
Labels: cla: yes, type: process

#2037 Return StatusOr for Table::ReadModifyWriteRow()
  google/cloud/bigtable/examples/data_snippets.cc
  google/cloud/bigtable/table.h
  google/cloud/bigtable/table_readmodifywriterow_test.cc
  google/cloud/bigtable/tests/data_integration_test.cc
Labels: api: bigtable, cla: yes

#1958 Change TableAdmin API to use StatusOr<>.
  google/cloud/bigtable/benchmarks/benchmark.cc
  google/cloud/bigtable/examples/bigtable_hello_world.cc
  google/cloud/bigtable/examples/bigtable_samples.cc
  google/cloud/bigtable/examples/opencensus/bigtable_opencensus.cc
  google/cloud/bigtable/examples/table_admin_snippets.cc
  google/cloud/bigtable/internal/table_admin.cc
  google/cloud/bigtable/internal/table_admin.h
  google/cloud/bigtable/internal/table_admin_test.cc
  google/cloud/bigtable/table_admin.cc
  google/cloud/bigtable/table_admin.h
  google/cloud/bigtable/table_admin_test.cc
  google/cloud/bigtable/testing/table_integration_test.cc
  google/cloud/bigtable/testing/table_integration_test.h
  google/cloud/bigtable/tests/admin_async_future_integration_test.cc
  google/cloud/bigtable/tests/admin_async_integration_test.cc
  google/cloud/bigtable/tests/admin_integration_test.cc
  google/cloud/bigtable/tests/data_async_future_integration_test.cc
  google/cloud/bigtable/tests/data_async_integration_test.cc
  google/cloud/bigtable/tests/data_integration_test.cc
  google/cloud/bigtable/tests/filters_integration_test.cc
  google/cloud/bigtable/tests/mutations_integration_test.cc
  google/cloud/bigtable/tests/snapshot_async_integration_test.cc
  google/cloud/bigtable/tests/snapshot_integration_test.cc
Labels: :rotating_light:, api: bigtable, cla: yes

#2039 Search for port number only if the log file has been created.
  google/cloud/storage/tools/run_testbench_utils.sh
Labels: cla: yes

#2040 Create Kokoro configurations for Travis builds.
  ci/kokoro/docker/clang-tidy-presubmit.cfg
  ci/kokoro/docker/clang-tidy.cfg
  ci/kokoro/docker/libcxx-presubmit.cfg
  ci/kokoro/docker/libcxx.cfg
  ci/kokoro/docker/no-tests-presubmit.cfg
  ci/kokoro/docker/no-tests.cfg
  ci/kokoro/docker/shared-presubmit.cfg
  ci/kokoro/docker/shared.cfg
Labels: cla: yes

#2041 Limit all Kokoro builds to 120 minutes.
  ci/kokoro/macos/continuous.cfg
  ci/kokoro/macos/presubmit.cfg
  ci/kokoro/ubuntu/continuous.cfg
  ci/kokoro/ubuntu/presubmit.cfg
Labels: cla: yes

#2043 Update instructions to setup windows workstation. [skip ci]
  doc/setup-development-environment.md
Labels: cla: yes

#2045 Increase timeouts for CompletionQueue tests.
  google/cloud/bigtable/completion_queue_test.cc
Labels: cla: yes

#2047 Increase timeouts in future<> tests.
  google/cloud/future_generic_test.cc
  google/cloud/future_void_test.cc
Labels: cla: yes

#2022 Add Bucket Policy Only samples
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_bucket_samples.cc
Labels: api: storage, cla: yes

#2049 Removes unused import of chrono_literals
  google/cloud/bigtable/internal/async_retry_multi_page_test.cc
Labels: cla: yes

#2050 Update instructions to setup Linux VM [skip ci].
  doc/setup-development-environment.md
Labels: cla: yes

#2052 Remove clang-tidy and libc++ builds.
  .travis.yml
Labels: cla: yes, type: process

#2051 Eliminate BatchFinishedCallback.
  google/cloud/bigtable/internal/mutation_batcher.cc
  google/cloud/bigtable/internal/mutation_batcher.h
Labels: api: bigtable, cla: yes

#2055 Keep Apply callbacks in MutationData.
  google/cloud/bigtable/internal/mutation_batcher.cc
  google/cloud/bigtable/internal/mutation_batcher.h
Labels: api: bigtable, cla: yes

#2044 Return StatusOr for Table::Apply()
  google/cloud/bigtable/benchmarks/apply_read_latency_benchmark.cc
  google/cloud/bigtable/benchmarks/embedded_server_test.cc
  google/cloud/bigtable/benchmarks/endurance_benchmark.cc
  google/cloud/bigtable/examples/bigtable_hello_app_profile.cc
  google/cloud/bigtable/examples/bigtable_hello_world.cc
  google/cloud/bigtable/examples/data_snippets.cc
  google/cloud/bigtable/table.cc
  google/cloud/bigtable/table.h
  google/cloud/bigtable/table_apply_test.cc
  google/cloud/bigtable/tests/data_integration_test.cc
  google/cloud/bigtable/tests/mutations_integration_test.cc
Labels: cla: yes

#2058 More fine-grained outstanding size bookkeeping.
  google/cloud/bigtable/internal/mutation_batcher.cc
  google/cloud/bigtable/internal/mutation_batcher.h
Labels: api: bigtable, cla: yes

#2056 Fix Ubuntu:14.04 install instructions.
  INSTALL.md
  README.md
  ci/test-readme/Dockerfile.ubuntu-trusty
Labels: cla: yes, type: docs

#2053 Add bigtable::Cell constructors without labels argument
  google/cloud/bigtable/cell.h
  google/cloud/bigtable/cell_test.cc
  google/cloud/bigtable/internal/encoder.h
  google/cloud/bigtable/row_test.cc
  google/cloud/bigtable/tests/admin_async_integration_test.cc
  google/cloud/bigtable/tests/admin_integration_test.cc
  google/cloud/bigtable/tests/data_async_future_integration_test.cc
  google/cloud/bigtable/tests/data_async_integration_test.cc
  google/cloud/bigtable/tests/data_integration_test.cc
  google/cloud/bigtable/tests/filters_integration_test.cc
  google/cloud/bigtable/tests/mutations_integration_test.cc
  google/cloud/bigtable/tests/snapshot_async_integration_test.cc
  google/cloud/bigtable/tests/snapshot_integration_test.cc
Labels: cla: yes

#2057 Fix flaky integration test(s) for Bigtable.
  google/cloud/bigtable/ci/run_integration_tests.sh
  google/cloud/bigtable/testing/table_integration_test.cc
  google/cloud/bigtable/testing/table_integration_test.h
  google/cloud/bigtable/tests/admin_async_future_integration_test.cc
  google/cloud/bigtable/tests/admin_async_integration_test.cc
  google/cloud/bigtable/tests/admin_integration_test.cc
  google/cloud/bigtable/tests/data_async_future_integration_test.cc
  google/cloud/bigtable/tests/data_async_integration_test.cc
  google/cloud/bigtable/tests/data_integration_test.cc
  google/cloud/bigtable/tests/filters_integration_test.cc
  google/cloud/bigtable/tests/mutations_integration_test.cc
  google/cloud/bigtable/tests/snapshot_async_integration_test.cc
  google/cloud/bigtable/tests/snapshot_integration_test.cc
Labels: cla: yes

#2063 Add synchronization to MutationBatcher::Batch.
  google/cloud/bigtable/internal/mutation_batcher.cc
  google/cloud/bigtable/internal/mutation_batcher.h
Labels: api: bigtable, cla: yes

#2067 Show badges for the install build too.
  README.md
  ci/test-readme/generate-readme.sh
Labels: cla: yes

#2066 Return StatusOr for Table::ReadRow()
  ci/test-install/bigtable_install_test.cc
  google/cloud/bigtable/benchmarks/apply_read_latency_benchmark.cc
  google/cloud/bigtable/benchmarks/endurance_benchmark.cc
  google/cloud/bigtable/examples/bigtable_hello_app_profile.cc
  google/cloud/bigtable/examples/bigtable_hello_world.cc
  google/cloud/bigtable/examples/bigtable_quickstart.cc
  google/cloud/bigtable/examples/data_snippets.cc
  google/cloud/bigtable/examples/opencensus/bigtable_opencensus.cc
  google/cloud/bigtable/table.cc
  google/cloud/bigtable/table.h
  google/cloud/bigtable/table_readrow_test.cc
  google/cloud/bigtable/tests/data_integration_test.cc
Labels: cla: yes

#2072 Refactor admission into a separate function.
  google/cloud/bigtable/internal/mutation_batcher.cc
  google/cloud/bigtable/internal/mutation_batcher.h
Labels: api: bigtable, cla: yes

#2069 Add the `scaling` parameter to the `ExponentialBackoffPolicy` examples.
  google/cloud/internal/backoff_policy.h
Labels: cla: yes

#2070 Remove MAINTAINER directives in Dockerfiles.
  ci/test-readme/Dockerfile.centos
  ci/test-readme/Dockerfile.debian
  ci/test-readme/Dockerfile.fedora
  ci/test-readme/Dockerfile.opensuse
  ci/test-readme/Dockerfile.opensuse-leap
  ci/test-readme/Dockerfile.ubuntu
  ci/test-readme/Dockerfile.ubuntu-trusty
  ci/test-readme/Dockerfile.ubuntu-xenial
  ci/travis/Dockerfile.centos
  ci/travis/Dockerfile.fedora
  ci/travis/Dockerfile.ubuntu
  ci/travis/Dockerfile.ubuntu-install
  ci/travis/Dockerfile.ubuntu-trusty
Labels: cla: yes

#2071 Remove the Travis + Bazel build.
  .travis.yml
Labels: cla: yes, type: cleanup, type: process

#2075 Replace TEST_CASE with TEST_SUITE for tests.
  ci/kokoro/windows/build-dependencies.ps1
  ci/kokoro/windows/build-project.ps1
  google/cloud/CMakeLists.txt
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/benchmarks/CMakeLists.txt
  google/cloud/bigtable/internal/async_check_consistency_test.cc
  google/cloud/bigtable/internal/async_longrunning_op_test.cc
  google/cloud/bigtable/internal/async_poll_op_test.cc
  google/cloud/bigtable/internal/async_retry_op_test.cc
  google/cloud/bigtable/internal/async_retry_unary_rpc_and_poll_test.cc
  google/cloud/firestore/CMakeLists.txt
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/internal/curl_client_test.cc
Labels: cla: yes

#2077 Remove the Xcode 7.3 build from Travis.
  .travis.yml
  ci/travis/build-macosx.sh
  ci/travis/install-macosx.sh
Labels: cla: yes, type: cleanup

#2068 Simplify all of our endian functions down to two Encode/Decode operations.
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/bigtable_client.bzl
  google/cloud/bigtable/cell.h
  google/cloud/bigtable/cell_test.cc
  google/cloud/bigtable/doc/bigtable-samples-data-client.dox
  google/cloud/bigtable/examples/data_snippets.cc
  google/cloud/bigtable/internal/encoder.h
  google/cloud/bigtable/internal/endian.cc
  google/cloud/bigtable/internal/endian.h
  google/cloud/bigtable/mutations.h
  google/cloud/bigtable/mutations_test.cc
  google/cloud/bigtable/testing/table_integration_test.cc
  google/cloud/bigtable/tests/admin_async_future_integration_test.cc
  google/cloud/bigtable/tests/admin_async_integration_test.cc
  google/cloud/bigtable/tests/data_async_future_integration_test.cc
  google/cloud/bigtable/tests/data_async_integration_test.cc
  google/cloud/bigtable/tests/data_integration_test.cc
  google/cloud/bigtable/tests/mutations_integration_test.cc
  google/cloud/internal/big_endian.h
  google/cloud/internal/big_endian_test.cc
  google/cloud/storage/hashing_options.cc
  google/cloud/storage/internal/hash_validator.cc
Labels: cla: yes

#2073 Refactor MutationBatcher tests.
  google/cloud/bigtable/internal/mutation_batcher_test.cc
Labels: cla: yes

#2078 Collect Windows minidumps.
  ci/kokoro/windows/continuous.cfg
  ci/kokoro/windows/presubmit.cfg
Labels: cla: yes

#2076 Use StatusOr in TableAdmin::SnapshotTable
  google/cloud/bigtable/table_admin.cc
  google/cloud/bigtable/table_admin.h
  google/cloud/bigtable/table_admin_test.cc
  google/cloud/bigtable/tests/snapshot_async_integration_test.cc
  google/cloud/bigtable/tests/snapshot_integration_test.cc
Labels: api: bigtable, cla: yes

#2087 Gives google::cloud::optional value conversion c'tors matching std::optional
  google/cloud/optional.h
  google/cloud/optional_test.cc
  google/cloud/storage/bucket_metadata_test.cc
  google/cloud/storage/oauth2/google_credentials.cc
  google/cloud/storage/oauth2/google_credentials_test.cc
  google/cloud/storage/tests/bucket_integration_test.cc
Labels: cla: yes

#2088 Remove bigtable::internal::ThrowRpcError()
  google/cloud/bigtable/examples/bigtable_samples_instance_admin.cc
  google/cloud/bigtable/examples/table_admin_snippets.cc
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/instance_admin_test.cc
  google/cloud/bigtable/internal/grpc_error_delegate.cc
  google/cloud/bigtable/internal/grpc_error_delegate.h
  google/cloud/bigtable/internal/grpc_error_delegate_test.cc
  google/cloud/bigtable/table_admin.cc
  google/cloud/bigtable/table_admin.h
  google/cloud/bigtable/table_admin_test.cc
  google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
  google/cloud/bigtable/tests/instance_admin_async_integration_test.cc
  google/cloud/bigtable/tests/instance_admin_integration_test.cc
Labels: cla: yes

#2089 Removed unneeded rvalue-reference arguments in bigtable/
  google/cloud/bigtable/instance_config.h
  google/cloud/bigtable/instance_update_config.h
  google/cloud/bigtable/internal/async_bulk_apply.h
  google/cloud/bigtable/internal/async_check_consistency.h
  google/cloud/bigtable/internal/async_future_from_callback.h
  google/cloud/bigtable/internal/async_list_app_profiles.h
  google/cloud/bigtable/internal/async_list_clusters.h
  google/cloud/bigtable/internal/async_list_instances.h
  google/cloud/bigtable/internal/async_longrunning_op.h
  google/cloud/bigtable/internal/async_loop_op.h
  google/cloud/bigtable/internal/async_poll_op.h
  google/cloud/bigtable/internal/async_read_row_operation.h
  google/cloud/bigtable/internal/async_retry_multi_page.h
  google/cloud/bigtable/internal/async_retry_op.h
  google/cloud/bigtable/internal/async_retry_unary_rpc.h
  google/cloud/bigtable/internal/async_row_reader.h
  google/cloud/bigtable/internal/async_sample_row_keys.h
  google/cloud/bigtable/internal/bulk_mutator.cc
  google/cloud/bigtable/internal/bulk_mutator.h
  google/cloud/bigtable/internal/completion_queue_impl.h
  google/cloud/bigtable/internal/instance_admin.h
  google/cloud/bigtable/internal/mutation_batcher.cc
  google/cloud/bigtable/internal/mutation_batcher.h
  google/cloud/bigtable/internal/strong_type.h
  google/cloud/bigtable/internal/table.cc
  google/cloud/bigtable/internal/table.h
  google/cloud/bigtable/mutations.h
  google/cloud/bigtable/table.cc
  google/cloud/bigtable/table.h
Labels: cla: yes

#2091 Add size() for BulkMutation
  google/cloud/bigtable/mutations.h
  google/cloud/bigtable/mutations_test.cc
Labels: cla: yes

#2085 Make use of the streaming batch mutation API.
  google/cloud/bigtable/internal/mutation_batcher.cc
  google/cloud/bigtable/internal/mutation_batcher.h
  google/cloud/bigtable/internal/mutation_batcher_test.cc
  google/cloud/bigtable/internal/table.h
Labels: api: bigtable, cla: yes

#2094 Rename bigtable_samples_instance_admin.cc and bigtable_samples_instance_admin_ext.cc
  google/cloud/bigtable/doc/bigtable-samples-instance-admin.dox
  google/cloud/bigtable/examples/BUILD
  google/cloud/bigtable/examples/CMakeLists.txt
  google/cloud/bigtable/examples/README.md
  google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc
  google/cloud/bigtable/examples/bigtable_samples_instance_admin.cc
  google/cloud/bigtable/examples/bigtable_samples_instance_admin_ext.cc
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/instance_admin.h
Labels: cla: yes

#2101 Rename format_rfc3339.{h,cc}.
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/benchmarks/storage_latency_benchmark.cc
  google/cloud/storage/benchmarks/storage_throughput_benchmark.cc
  google/cloud/storage/bucket_metadata.cc
  google/cloud/storage/bucket_metadata_test.cc
  google/cloud/storage/internal/bucket_requests.cc
  google/cloud/storage/internal/format_time_point.cc
  google/cloud/storage/internal/format_time_point.h
  google/cloud/storage/internal/format_time_point_test.cc
  google/cloud/storage/object_metadata.cc
  google/cloud/storage/storage_client.bzl
  google/cloud/storage/storage_client_unit_tests.bzl
Labels: api: storage, cla: yes

#2102 Fix int overflow in MutationBatcher config.
  google/cloud/bigtable/internal/mutation_batcher.cc
Labels: api: bigtable, cla: yes

#2103 Simplify kokoro windows build
  ci/kokoro/windows/build-dependencies.ps1
  ci/kokoro/windows/build-project.ps1
Labels: cla: yes

#2095 Make MutationBatcher public API.
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/bigtable_client.bzl
  google/cloud/bigtable/bigtable_client_unit_tests.bzl
  google/cloud/bigtable/internal/table.h
  google/cloud/bigtable/mutation_batcher.cc
  google/cloud/bigtable/mutation_batcher.h
  google/cloud/bigtable/mutation_batcher_test.cc
  google/cloud/bigtable/table.h
Labels: cla: yes

#2104 Format timestamps as needed by V4 signed URLs.
  google/cloud/storage/internal/format_time_point.cc
  google/cloud/storage/internal/format_time_point.h
  google/cloud/storage/internal/format_time_point_test.cc
Labels: api: storage, cla: yes

#2105 New functions for SHA256 hashes.
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/internal/sha256_hash.cc
  google/cloud/storage/internal/sha256_hash.h
  google/cloud/storage/internal/sha256_hash_test.cc
  google/cloud/storage/storage_client.bzl
  google/cloud/storage/storage_client_unit_tests.bzl
Labels: api: storage, cla: yes

#2110 Silence MSVC warnings.
  google/cloud/internal/big_endian.h
Labels: cla: yes, type: cleanup

#2111 Properly handle subresources in V2 signed URLs.
  google/cloud/storage/client.h
  google/cloud/storage/internal/signed_url_requests.cc
  google/cloud/storage/internal/signed_url_requests.h
  google/cloud/storage/internal/signed_url_requests_test.cc
  google/cloud/storage/signed_url_options.h
Labels: api: storage, cla: yes

#2109 Add MutationBatcher::AsyncWaitForNoPendingRequests
  google/cloud/bigtable/mutation_batcher.cc
  google/cloud/bigtable/mutation_batcher.h
  google/cloud/bigtable/mutation_batcher_test.cc
Labels: cla: yes

#2114 Cleanup handling of SignedUrlRequest options.
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/internal/signed_url_requests.cc
  google/cloud/storage/internal/signed_url_requests.h
  google/cloud/storage/internal/signed_url_requests_test.cc
  google/cloud/storage/signed_url_options.cc
  google/cloud/storage/signed_url_options.h
  google/cloud/storage/signed_url_options_test.cc
  google/cloud/storage/storage_client.bzl
Labels: cla: yes

#2120 Make ci/kokoro/docker/build.sh executable.
  ci/kokoro/docker/build.sh
Labels: cla: yes

#2115 Enable all cores in Kokoro.
  ci/kokoro/docker/build.sh
  ci/travis/build-docker.sh
Labels: cla: yes

#2119 Makes optional's operator bool explicit.
  google/cloud/optional.h
Labels: cla: yes

#2121 Refactor parts of SignUrlRequest to base class.
  google/cloud/storage/internal/signed_url_requests.cc
  google/cloud/storage/internal/signed_url_requests.h
Labels: api: storage, cla: yes

#2117 Switch gcs2cbt to use MutationBatcher.
  google/cloud/examples/gcs2cbt.cc
Labels: cla: yes
