Repository googleapis/google-cloud-cpp, pull requests merged in 2019-08, with the labels that each got.

#2930 testing: Delete files on windows test failure
  ci/kokoro/windows/build.bat
Labels: cla: yes, testing

#2931 feat: Add Ninja build.
  ci/kokoro/docker/Dockerfile.ubuntu
  ci/kokoro/docker/build-in-docker-cmake.sh
  ci/kokoro/docker/build.sh
  ci/kokoro/docker/ninja-presubmit.cfg
  ci/kokoro/docker/ninja.cfg
Labels: cla: yes

#2932 testing: Fix build on windows 2019
  ci/kokoro/windows/build-dependencies.ps1
  ci/kokoro/windows/build-project.ps1
  ci/kokoro/windows/build.bat
Labels: cla: yes

#2933 doc: update release notes
  google/cloud/README.md
  google/cloud/bigtable/README.md
  google/cloud/storage/README.md
Labels: cla: yes

#2934 Bumping versions after release
  google/cloud/CMakeLists.txt
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/version_info.h
  google/cloud/internal/version_info.h
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/version_info.h
Labels: cla: yes

#2936 testing: cleanup on windows builds
  ci/kokoro/windows/build-dependencies.ps1
  ci/kokoro/windows/continuous.cfg
  ci/kokoro/windows/presubmit.cfg
Labels: cla: yes, testing

#2938 fix: Fix windows include path in curl.BUILD
  bazel/curl.BUILD
Labels: cla: yes

#2937 feat: Use macros for compiler id and version
  ci/test-abi/google_cloud_cpp_common.expected.abi.dump.gz
  google/cloud/BUILD
  google/cloud/CMakeLists.txt
  google/cloud/bigtable/metadata_update_policy.cc
  google/cloud/google_cloud_cpp_common.bzl
  google/cloud/google_cloud_cpp_common_unit_tests.bzl
  google/cloud/internal/build_info.cc.in
  google/cloud/internal/build_info.h
  google/cloud/internal/build_info_test.cc
  google/cloud/internal/compiler_info.cc
  google/cloud/internal/compiler_info.h
  google/cloud/internal/compiler_info_test.cc
  google/cloud/storage/version.cc
Labels: cla: yes

#2939 cleanup: Fix usage of NCPU in Dockerfiles.
  ci/kokoro/docker/Dockerfile.fedora-install
  ci/kokoro/docker/create-docker-image.sh
  ci/kokoro/install/Dockerfile.centos
  ci/kokoro/install/Dockerfile.debian
  ci/kokoro/install/Dockerfile.fedora
  ci/kokoro/install/Dockerfile.opensuse
  ci/kokoro/install/Dockerfile.opensuse-leap
  ci/kokoro/install/Dockerfile.ubuntu
  ci/kokoro/install/Dockerfile.ubuntu-trusty
  ci/kokoro/install/Dockerfile.ubuntu-xenial
  ci/kokoro/install/build.sh
  ci/kokoro/readme/Dockerfile.centos
  ci/kokoro/readme/Dockerfile.debian
  ci/kokoro/readme/Dockerfile.fedora
  ci/kokoro/readme/Dockerfile.opensuse
  ci/kokoro/readme/Dockerfile.opensuse-leap
  ci/kokoro/readme/Dockerfile.ubuntu
  ci/kokoro/readme/Dockerfile.ubuntu-trusty
  ci/kokoro/readme/Dockerfile.ubuntu-xenial
  ci/test-readme/dockerfile2markdown.sh
Labels: cla: yes

#2944 Make GCS throughput benchmark record progress.
  google/cloud/storage/benchmarks/CMakeLists.txt
  google/cloud/storage/benchmarks/benchmark_utils.cc
  google/cloud/storage/benchmarks/benchmark_utils.h
  google/cloud/storage/benchmarks/benchmark_utils_test.cc
  google/cloud/storage/benchmarks/storage_benchmarks_unit_tests.bzl
  google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc
Labels: cla: yes

#2945 Increase download and upload buffers.
  google/cloud/storage/client_options.cc
Labels: cla: yes

#2943 Random CRC and MD5 in storage throughput benchmark
  google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc
Labels: cla: yes

#2946 feat: Increase the threshold for using resumable uploads
  google/cloud/storage/client_options.cc
Labels: cla: yes

#2940 fix: Fix bazel build on windows.
  bazel/curl.BUILD
  ci/kokoro/windows/bazel/build.bat
  ci/kokoro/windows/bazel/common.cfg
  ci/kokoro/windows/bazel/continuous.cfg
  ci/kokoro/windows/bazel/presubmit.cfg
  google/cloud/BUILD
  google/cloud/firestore/BUILD
  google/cloud/storage/BUILD
  google/cloud/storage/benchmarks/BUILD
  google/cloud/storage/tests/BUILD
Labels: cla: yes

#2947 bug: Fix dependencies for googleapis.
  cmake/external/googleapis.cmake
Labels: cla: yes

#2948 feat: Ignore warnings in generated code.
  cmake/CompileProtos.cmake
Labels: cla: yes

#2954 cleanup: Don't include nljson.h from public oauth2 headers.
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/oauth2/authorized_user_credentials.cc
  google/cloud/storage/oauth2/authorized_user_credentials.h
  google/cloud/storage/oauth2/compute_engine_credentials.cc
  google/cloud/storage/oauth2/compute_engine_credentials.h
  google/cloud/storage/oauth2/service_account_credentials.cc
  google/cloud/storage/oauth2/service_account_credentials.h
  google/cloud/storage/storage_client.bzl
Labels: cla: yes

#2957 feat: let clang-tidy build not fail if there are edited files
  ci/check-style.sh
  ci/kokoro/docker/build.sh
Labels: cla: yes

#2958 Tidy cleanup
  .clang-tidy
  google/cloud/internal/backoff_policy.cc
  google/cloud/terminate_handler.cc
Labels: cla: yes

#2962 cleanup: Use vcpkg for all dependencies in Windows build.
  ci/kokoro/windows/build-dependencies.ps1
  ci/kokoro/windows/build-project.ps1
Labels: cla: yes

#2961 feat: Configure C++17 build.
  CMakeLists.txt
  ci/kokoro/docker/build-in-docker-cmake.sh
  ci/kokoro/docker/build.sh
  ci/kokoro/docker/cxx17-presubmit.cfg
  ci/kokoro/docker/cxx17.cfg
  google/cloud/bigtable/internal/google_bytes_traits.h
Labels: cla: yes

#2963 chore: Keep release tags in master branch.
  ci/test-abi/google_cloud_cpp_common.expected.abi.dump.gz
  doc/cutting-a-release.md
  google/cloud/BUILD
  google/cloud/CMakeLists.txt
  google/cloud/bigtable/bigtable_version_test.cc
  google/cloud/bigtable/version.cc
  google/cloud/google_cloud_cpp_common_version.bzl
  google/cloud/grpc_utils/version.cc
  google/cloud/internal/build_info.cc.in
  google/cloud/internal/build_info.h
  google/cloud/storage/storage_version_test.cc
  google/cloud/storage/version.cc
Labels: cla: yes

#2969 cleanup: Use ObjectMetadata in ResumableUploadResponse.
  ci/test-abi/storage_client.expected.abi.dump.gz
  google/cloud/storage/client.cc
  google/cloud/storage/client_write_object_test.cc
  google/cloud/storage/examples/storage_client_mock_samples.cc
  google/cloud/storage/internal/curl_resumable_upload_session_test.cc
  google/cloud/storage/internal/logging_resumable_upload_session_test.cc
  google/cloud/storage/internal/object_streambuf.cc
  google/cloud/storage/internal/object_streambuf.h
  google/cloud/storage/internal/object_streambuf_test.cc
  google/cloud/storage/internal/resumable_upload_session.cc
  google/cloud/storage/internal/resumable_upload_session.h
  google/cloud/storage/internal/resumable_upload_session_test.cc
  google/cloud/storage/internal/retry_resumable_upload_session_test.cc
  google/cloud/storage/object_stream.cc
  google/cloud/storage/tests/curl_resumable_upload_session_integration_test.cc
Labels: cla: yes

#2967 cleanup: Use only find_package to find dependencies.
  .cmake-format.py
  CMakeLists.txt
  INSTALL.md
  README.md
  ci/benchmarks/Dockerfile
  ci/kokoro/docker/Dockerfile.fedora-install
  ci/kokoro/docker/Dockerfile.ubuntu-install
  ci/kokoro/docker/build-in-docker-cmake.sh
  ci/kokoro/docker/build.sh
  ci/kokoro/install/Dockerfile.centos
  ci/kokoro/install/Dockerfile.debian
  ci/kokoro/install/Dockerfile.fedora
  ci/kokoro/install/Dockerfile.opensuse
  ci/kokoro/install/Dockerfile.opensuse-leap
  ci/kokoro/install/Dockerfile.ubuntu
  ci/kokoro/install/Dockerfile.ubuntu-trusty
  ci/kokoro/install/Dockerfile.ubuntu-xenial
  ci/kokoro/refdocs.sh
  ci/kokoro/windows/build-project.ps1
  ci/test-abi/bigtable_client.expected.abi.dump.gz
  ci/test-abi/google_cloud_cpp_grpc_utils.expected.abi.dump.gz
  ci/test-readme/generate-install.sh
  cmake/FindCurlWithTargets.cmake
  cmake/FindGMockWithTargets.cmake
  cmake/FindProtobufTargets.cmake
  cmake/FindProtobufWithTargets.cmake
  cmake/FindgRPC.cmake
  cmake/GoogleCloudCppCommon.cmake
  cmake/IncludeCrc32c.cmake
  cmake/IncludeCurl.cmake
  cmake/IncludeGMock.cmake
  cmake/IncludeGoogleapis.cmake
  cmake/IncludeGrpc.cmake
  cmake/IncludeProtobuf.cmake
  cmake/PkgConfigHelper.cmake
  cmake/external/c-ares.cmake
  cmake/external/crc32c.cmake
  cmake/external/curl.cmake
  cmake/external/googleapis.cmake
  cmake/external/googletest.cmake
  cmake/external/grpc.cmake
  cmake/external/protobuf.cmake
  cmake/external/zlib.cmake
  doc/managing-dependencies-in-cmake.md
  doc/setup-cmake-environment.md
  doc/setup-development-environment.md
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/grpc_utils/CMakeLists.txt
  google/cloud/grpc_utils/config.cmake.in
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/tests/read_object_stall_regression/Dockerfile
  google/cloud/storage/tests/write_deadlock_regression/Dockerfile
  google/cloud/testing_util/CMakeLists.txt
  google/cloud/testing_util/config.cmake.in
  super/CMakeLists.txt
  super/ExternalProjectHelper.cmake
Labels: cla: yes, type: cleanup

#2970 feat: Make integration tests client configurable.
  google/cloud/storage/testing/storage_integration_test.cc
  google/cloud/storage/testing/storage_integration_test.h
  google/cloud/storage/tests/bucket_integration_test.cc
  google/cloud/storage/tests/curl_sign_blob_integration_test.cc
  google/cloud/storage/tests/object_checksum_integration_test.cc
  google/cloud/storage/tests/object_file_integration_test.cc
  google/cloud/storage/tests/object_hash_integration_test.cc
  google/cloud/storage/tests/object_insert_integration_test.cc
  google/cloud/storage/tests/object_integration_test.cc
  google/cloud/storage/tests/object_media_integration_test.cc
  google/cloud/storage/tests/object_resumable_write_integration_test.cc
  google/cloud/storage/tests/object_rewrite_integration_test.cc
  google/cloud/storage/tests/object_write_streambuf_integration_test.cc
  google/cloud/storage/tests/read_object_stall_regression/read_object_stall_test.cc
  google/cloud/storage/tests/service_account_integration_test.cc
  google/cloud/storage/tests/signed_url_integration_test.cc
  google/cloud/storage/tests/slow_reader_integration_test.cc
  google/cloud/storage/tests/thread_integration_test.cc
  google/cloud/storage/tests/write_deadlock_regression/object_write_deadlock_regression_test.cc
Labels: api: storage, cla: yes

#2972 cleanup: Move cmake/external to super/
  super/CMakeLists.txt
  super/external/c-ares.cmake
  super/external/crc32c.cmake
  super/external/curl.cmake
  super/external/googleapis.cmake
  super/external/googletest.cmake
  super/external/grpc.cmake
  super/external/protobuf.cmake
  super/external/ssl.cmake
  super/external/zlib.cmake
Labels: cla: yes

#2973 feat: Cache Docker images for Kokoro builds.
  ci/kokoro/docker/build.sh
  ci/kokoro/docker/common.cfg
  ci/kokoro/docker/create-docker-image.sh
  ci/kokoro/docker/define-docker-variables.sh
Labels: cla: yes

#2975 chore: Use the Docker cache for interactive builds.
  ci/kokoro/install/build.sh
  ci/kokoro/readme/build.sh
Labels: cla: yes

#2976 chore: Update cpp-cmakefiles.
  INSTALL.md
  ci/kokoro/docker/Dockerfile.fedora-install
  ci/kokoro/docker/Dockerfile.ubuntu-install
  ci/kokoro/install/Dockerfile.centos
  ci/kokoro/install/Dockerfile.debian
  ci/kokoro/install/Dockerfile.fedora
  ci/kokoro/install/Dockerfile.opensuse
  ci/kokoro/install/Dockerfile.opensuse-leap
  ci/kokoro/install/Dockerfile.ubuntu
  ci/kokoro/install/Dockerfile.ubuntu-trusty
  ci/kokoro/install/Dockerfile.ubuntu-xenial
  super/external/googleapis.cmake
Labels: cla: yes

#2965 fix: properly handle CURLE_{SEND|RECV}_ERROR.
  google/cloud/storage/internal/curl_handle.cc
  google/cloud/storage/internal/curl_handle_test.cc
  google/cloud/storage/tests/BUILD
  google/cloud/storage/tests/CMakeLists.txt
  google/cloud/storage/tests/error_injection_integration_test.cc
  google/cloud/storage/tests/storage_client_integration_tests.bzl
Labels: cla: yes

#2977 doc: Fix syntax in CMake module documentation.
  cmake/FindProtobufWithTargets.cmake
  cmake/FindgRPC.cmake
Labels: cla: yes

#2982 cleanup: Run CI-specific commands if RUNNING_CI=yes
  ci/kokoro/docker/build.sh
Labels: cla: yes

#2968 fix: use MetadataUpdatePolicy::FromClusterId.
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/row_reader_test.cc
  google/cloud/bigtable/table.h
Labels: cla: yes

#2985 Upgrade grpc to 1.23.0.
  INSTALL.md
  WORKSPACE
  bazel/curl.BUILD
  bazel/google_cloud_cpp_deps.bzl
  ci/test-install/WORKSPACE
  ci/test-readme/generate-install.sh
Labels: cla: yes

#2979 bug: Account for when CreateHashValidator's options are set to false
  google/cloud/storage/internal/hash_validator.cc
  google/cloud/storage/internal/hash_validator.h
  google/cloud/storage/internal/hash_validator_test.cc
Labels: cla: yes

#2986 chore: reduce docker timeout from 120 minutes to 60 minutes
  ci/kokoro/docker/build.sh
Labels: cla: yes

#2987 bug: Fix build for continuous benchmark tests.
  ci/benchmarks/Dockerfile
Labels: cla: yes

#2991 chore: workaround gcc-8.2 build failures.
  google/cloud/storage/internal/object_streambuf_test.cc
  google/cloud/storage/internal/retry_resumable_upload_session_test.cc
Labels: cla: yes

#2989 Improve efficency of ObjectWriteStreambuf by replacing O(n^2) code.
  google/cloud/storage/internal/object_streambuf.cc
  google/cloud/storage/internal/object_streambuf.h
  google/cloud/storage/internal/object_streambuf_test.cc
Labels: cla: yes

#2992 cleanup: use existing function to generate data.
  google/cloud/storage/tests/slow_reader_integration_test.cc
Labels: cla: yes

#2993 feat: allow applications to timeout stalled downloads.
  ci/test-abi/storage_client.expected.abi.dump.gz
  google/cloud/storage/client_options.cc
  google/cloud/storage/client_options.h
  google/cloud/storage/internal/curl_client.cc
  google/cloud/storage/internal/curl_download_request.cc
  google/cloud/storage/internal/curl_download_request.h
  google/cloud/storage/internal/curl_request_builder.cc
  google/cloud/storage/internal/curl_request_builder.h
  google/cloud/storage/storage_client_options_test.cc
  google/cloud/storage/testbench/testbench.py
  google/cloud/storage/tests/curl_request_integration_test.cc
  google/cloud/storage/tests/object_media_integration_test.cc
  google/cloud/storage/tests/read_object_stall_regression/read_object_stall_test.cc
Labels: cla: yes

#2995 Actually enable the error injection test.
  google/cloud/storage/tests/error_injection_integration_test.cc
  google/cloud/storage/tests/run_integration_tests_testbench.sh
Labels: cla: yes

#2996 cleanup: Add missing TODO comment.
  google/cloud/storage/tests/error_injection_integration_test.cc
Labels: cla: yes

#2997 cleanup: Factor out payload creation from ServiceAccountCredentials::…
  google/cloud/storage/oauth2/service_account_credentials.cc
  google/cloud/storage/oauth2/service_account_credentials.h
  google/cloud/storage/oauth2/service_account_credentials_test.cc
Labels: cla: yes

#2988 fix: correct invalid routing headers.
  ci/test-abi/bigtable_client.expected.abi.dump.gz
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/async_list_app_profiles_test.cc
  google/cloud/bigtable/async_list_clusters_test.cc
  google/cloud/bigtable/async_list_instances_test.cc
  google/cloud/bigtable/async_row_reader_test.cc
  google/cloud/bigtable/bigtable_client_testing.bzl
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/instance_admin_test.cc
  google/cloud/bigtable/internal/async_longrunning_op_test.cc
  google/cloud/bigtable/internal/bulk_mutator_test.cc
  google/cloud/bigtable/metadata_update_policy.cc
  google/cloud/bigtable/metadata_update_policy.h
  google/cloud/bigtable/metadata_update_policy_test.cc
  google/cloud/bigtable/mutation_batcher_test.cc
  google/cloud/bigtable/row_reader_test.cc
  google/cloud/bigtable/table.h
  google/cloud/bigtable/table_admin.cc
  google/cloud/bigtable/table_admin_test.cc
  google/cloud/bigtable/table_apply_test.cc
  google/cloud/bigtable/table_bulk_apply_test.cc
  google/cloud/bigtable/table_check_and_mutate_row_test.cc
  google/cloud/bigtable/table_readmodifywriterow_test.cc
  google/cloud/bigtable/table_readrow_test.cc
  google/cloud/bigtable/table_readrows_test.cc
  google/cloud/bigtable/table_sample_row_keys_test.cc
  google/cloud/bigtable/table_test.cc
  google/cloud/bigtable/testing/mock_async_failing_rpc_factory.h
  google/cloud/bigtable/testing/mock_response_reader.h
  google/cloud/bigtable/testing/validate_metadata.cc
  google/cloud/bigtable/testing/validate_metadata.h
Labels: cla: yes

#3000 cleanup: Move FakeClock to its own header
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/oauth2/service_account_credentials_test.cc
  google/cloud/storage/storage_client_testing.bzl
  google/cloud/storage/testing/mock_fake_clock.h
Labels: cla: yes

#3012 chore: Fix builds against vcpkg.
  cmake/FindGMockWithTargets.cmake
Labels: cla: yes

#3008 chore: Sanitizer builds work better with debug info.
  .bazelrc
Labels: cla: yes

#3007 bug: Fix the initial backoff interval.
  google/cloud/storage/internal/retry_client.cc
Labels: cla: yes

#3013 fix: eliminate a race condition from retry loop
  google/cloud/storage/internal/retry_client.cc
Labels: cla: yes

#3011 chore: Configure tsan and msan builds.
  .bazelrc
  ci/kokoro/docker/Dockerfile.fedora-libcxx-msan
  ci/kokoro/docker/build.sh
  ci/kokoro/docker/msan-presubmit.cfg
  ci/kokoro/docker/msan.cfg
  ci/kokoro/docker/tsan-presubmit.cfg
  ci/kokoro/docker/tsan.cfg
  google/cloud/future_generic_test.cc
  google/cloud/future_void_test.cc
  google/cloud/internal/future_impl.h
  google/cloud/storage/internal/curl_wrappers_disable_sigpipe_handler_test.cc
Labels: cla: yes

#3005 fix: return proper error code from upload metadata
  google/cloud/storage/client_write_object_test.cc
  google/cloud/storage/object_stream.cc
Labels: cla: yes

#3023 fix: don't throw on expired retry policies
  google/cloud/storage/internal/retry_client.cc
  google/cloud/storage/internal/retry_client_test.cc
  google/cloud/storage/internal/retry_resumable_upload_session.cc
  google/cloud/storage/internal/retry_resumable_upload_session_test.cc
  google/cloud/storage/tests/error_injection_integration_test.cc
Labels: cla: yes
