Repository googleapis/google-cloud-cpp, pull requests merged in 2019-07, with the labels that each got.

#2840 cleanup!: Remove RawClient::WriteObject().
  ci/test-abi/storage_client.expected.abi.dump.gz
  google/cloud/storage/idempotency_policy.cc
  google/cloud/storage/idempotency_policy.h
  google/cloud/storage/idempotency_policy_test.cc
  google/cloud/storage/internal/curl_client.cc
  google/cloud/storage/internal/curl_client.h
  google/cloud/storage/internal/curl_client_test.cc
  google/cloud/storage/internal/hash_validator.cc
  google/cloud/storage/internal/hash_validator.h
  google/cloud/storage/internal/hash_validator_test.cc
  google/cloud/storage/internal/logging_client.cc
  google/cloud/storage/internal/logging_client.h
  google/cloud/storage/internal/object_requests.cc
  google/cloud/storage/internal/object_requests.h
  google/cloud/storage/internal/object_requests_test.cc
  google/cloud/storage/internal/raw_client.h
  google/cloud/storage/internal/retry_client.cc
  google/cloud/storage/internal/retry_client.h
  google/cloud/storage/testing/mock_client.h
Labels: cla: yes, type: cleanup

#2829 doc: Update release notes.
  README.md
  google/cloud/README.md
  google/cloud/bigtable/README.md
  google/cloud/storage/README.md
Labels: cla: yes, type: docs

#2843 doc: Update Bigtable release numbers.
  ci/test-abi/bigtable_client.expected.abi.dump.gz
  ci/test-abi/google_cloud_cpp_grpc_utils.expected.abi.dump.gz
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/doc/bigtable-hello-instance-admin.dox
  google/cloud/bigtable/doc/bigtable-hello-table-admin.dox
  google/cloud/bigtable/doc/bigtable-hello-world.dox
  google/cloud/bigtable/doc/environment-variables.dox
  google/cloud/bigtable/version_info.h
Labels: cla: yes

#2844 chore: Enable code coverage build on Kokoro.
  ci/kokoro/docker/build.sh
  ci/kokoro/docker/common.cfg
  ci/kokoro/docker/coverage-presubmit.cfg
  ci/kokoro/docker/coverage.cfg
  ci/kokoro/docker/upload-coverage.sh
Labels: cla: yes

#2846 doc: Fix release notes.
  google/cloud/README.md
Labels: cla: yes

#2845 chore: Bump version numbers after cutting release.
  google/cloud/CMakeLists.txt
  google/cloud/README.md
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/README.md
  google/cloud/bigtable/version_info.h
  google/cloud/internal/version_info.h
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/README.md
  google/cloud/storage/version_info.h
Labels: cla: yes

#2847 cleanup: Remove Travis code coverage build.
  .travis.yml
Labels: cla: yes, type: cleanup

#2848 bug: Include 'IncludeGMock.cmake' in testing_util/config.cmake.in
  cmake/IncludeGMock.cmake
  google/cloud/testing_util/CMakeLists.txt
  google/cloud/testing_util/config.cmake.in
Labels: cla: yes

#2849 Fix typo.
  google/cloud/README.md
Labels: cla: yes

#2851 bug: Fix typo in testing_util/config.cmake.in
  google/cloud/testing_util/config.cmake.in
Labels: cla: yes

#2819 Implement NativeIamBinding/Policy and ops.
  cmake/external/googleapis.cmake
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/bigtable_client.bzl
  google/cloud/bigtable/bigtable_client_unit_tests.bzl
  google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc
  google/cloud/bigtable/examples/instance_admin_async_snippets.cc
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/iam_binding.cc
  google/cloud/bigtable/iam_binding.h
  google/cloud/bigtable/iam_binding_test.cc
  google/cloud/bigtable/iam_policy.cc
  google/cloud/bigtable/iam_policy.h
  google/cloud/bigtable/iam_policy_test.cc
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/instance_admin_test.cc
  google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
  google/cloud/bigtable/tests/instance_admin_integration_test.cc
Labels: cla: yes

#2852 chore: Remove last Travis build
  .travis.yml
  CONTRIBUTING.md
  ci/kokoro/docker/build.sh
  ci/kokoro/docker/clang-tidy.cfg
  ci/kokoro/docker/upload-docs.sh
Labels: cla: yes

#2853 cleanup: Simplify Kokoro config files.
  ci/kokoro/docker/asan-presubmit.cfg
  ci/kokoro/docker/asan.cfg
  ci/kokoro/docker/centos-7-presubmit.cfg
  ci/kokoro/docker/centos-7.cfg
  ci/kokoro/docker/check-abi-presubmit.cfg
  ci/kokoro/docker/check-abi.cfg
  ci/kokoro/docker/clang-tidy-presubmit.cfg
  ci/kokoro/docker/clang-tidy.cfg
  ci/kokoro/docker/libcxx-presubmit.cfg
  ci/kokoro/docker/libcxx.cfg
  ci/kokoro/docker/no-tests-presubmit.cfg
  ci/kokoro/docker/no-tests.cfg
  ci/kokoro/docker/noex-presubmit.cfg
  ci/kokoro/docker/noex.cfg
  ci/kokoro/docker/shared-presubmit.cfg
  ci/kokoro/docker/shared.cfg
  ci/kokoro/docker/ubsan-presubmit.cfg
  ci/kokoro/docker/ubsan.cfg
Labels: cla: yes, type: cleanup

#2855 cleanup: Remove Travis support scripts.
  .dockerignore
  ci/build-jenkins.sh
  ci/kokoro/docker/Dockerfile.centos
  ci/kokoro/docker/Dockerfile.fedora
  ci/kokoro/docker/Dockerfile.fedora-install
  ci/kokoro/docker/Dockerfile.ubuntu
  ci/kokoro/docker/Dockerfile.ubuntu-install
  ci/kokoro/docker/Dockerfile.ubuntu-trusty
  ci/kokoro/docker/build-in-docker-bazel.sh
  ci/kokoro/docker/build-in-docker-cmake.sh
  ci/kokoro/docker/build.sh
  ci/kokoro/docker/check-abi.sh
  ci/kokoro/docker/create-docker-image.sh
  ci/kokoro/docker/define-docker-variables.sh
  ci/kokoro/docker/dump-logs.sh
  ci/kokoro/docker/dump-reports.sh
  ci/kokoro/docker/upload-coverage.sh
  ci/kokoro/docker/upload-docs.sh
  ci/kokoro/refdocs_wrapper.sh
  ci/travis/build-bazel.sh
  ci/travis/build-linux.sh
  ci/travis/linux-config.sh
  ci/travis/upload-codecov.sh
  ci/travis/upload-docs.sh
  doc/setup-development-environment.md
Labels: cla: yes, type: cleanup

#2854 Implement support for IAM conditions.
  ci/test-abi/bigtable_client.expected.abi.dump.gz
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/bigtable_client.bzl
  google/cloud/bigtable/bigtable_client_unit_tests.bzl
  google/cloud/bigtable/expr.cc
  google/cloud/bigtable/expr.h
  google/cloud/bigtable/expr_test.cc
  google/cloud/bigtable/iam_binding.cc
  google/cloud/bigtable/iam_binding.h
  google/cloud/bigtable/iam_binding_test.cc
  google/cloud/bigtable/iam_policy_test.cc
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/instance_admin.h
Labels: cla: yes

#2859 bug: Need to set startingDeadlineSeconds to handle failures.
  ci/benchmarks/bigtable/endurance-job.yaml
  ci/benchmarks/bigtable/latency-job.yaml
  ci/benchmarks/bigtable/scan-job.yaml
  ci/benchmarks/bigtable/throughput-job.yaml
  ci/benchmarks/storage/throughput-vs-cpu-job.yaml
Labels: cla: yes

#2858 cleanup: Refactor ObjectWriteStreambuf.
  ci/test-abi/storage_client.expected.abi.dump.gz
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/client.cc
  google/cloud/storage/client_write_object_test.cc
  google/cloud/storage/internal/curl_client.cc
  google/cloud/storage/internal/curl_resumable_streambuf.cc
  google/cloud/storage/internal/curl_resumable_streambuf.h
  google/cloud/storage/internal/curl_resumable_streambuf_test.cc
  google/cloud/storage/internal/object_streambuf.cc
  google/cloud/storage/internal/object_streambuf.h
  google/cloud/storage/internal/object_streambuf_test.cc
  google/cloud/storage/internal/resumable_upload_session.h
  google/cloud/storage/object_stream_test.cc
  google/cloud/storage/storage_client.bzl
  google/cloud/storage/storage_client_unit_tests.bzl
  google/cloud/storage/tests/CMakeLists.txt
  google/cloud/storage/tests/object_write_streambuf_integration_test.cc
  google/cloud/storage/tests/storage_client_integration_tests.bzl
Labels: cla: yes

#2861 cleanup: Refactor file upload/download tests.
  google/cloud/storage/tests/CMakeLists.txt
  google/cloud/storage/tests/object_file_integration_test.cc
  google/cloud/storage/tests/object_media_integration_test.cc
  google/cloud/storage/tests/run_integration_tests_production.sh
  google/cloud/storage/tests/run_integration_tests_testbench.sh
  google/cloud/storage/tests/storage_client_integration_tests.bzl
Labels: cla: yes

#2864 bug: Fix ReadObject() when reading the last chunk.
  google/cloud/storage/internal/curl_download_request.cc
  google/cloud/storage/internal/curl_download_request.h
  google/cloud/storage/internal/object_streambuf.cc
  google/cloud/storage/tests/object_media_integration_test.cc
Labels: api: storage, cla: yes, type: bug

#2866 feat: Support setting 64-bit integers mutations.
  google/cloud/bigtable/mutations.h
  google/cloud/bigtable/mutations_test.cc
Labels: cla: yes, type: feature request

#2876 Use correct field name for MD5 hash.
  google/cloud/storage/internal/curl_client.cc
  google/cloud/storage/tests/object_hash_integration_test.cc
Labels: cla: yes

#2867 cleanup: Move bigtable::CompletionQueue to grpc_utils.
  ci/kokoro/docker/build-in-docker-cmake.sh
  ci/test-abi/bigtable_client.expected.abi.dump.gz
  ci/test-abi/google_cloud_cpp_grpc_utils.expected.abi.dump.gz
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/async_read_stream_test.cc
  google/cloud/bigtable/bigtable_client.bzl
  google/cloud/bigtable/completion_queue.h
  google/cloud/bigtable/data_client.h
  google/cloud/bigtable/internal/async_bulk_apply.h
  google/cloud/bigtable/internal/async_longrunning_op.h
  google/cloud/bigtable/internal/async_retry_multi_page.h
  google/cloud/bigtable/internal/async_retry_unary_rpc.h
  google/cloud/bigtable/internal/async_retry_unary_rpc_and_poll.h
  google/cloud/bigtable/internal/bulk_mutator.h
  google/cloud/bigtable/internal/bulk_mutator_test.cc
  google/cloud/bigtable/testing/mock_completion_queue.h
  google/cloud/grpc_utils/CMakeLists.txt
  google/cloud/grpc_utils/async_operation.h
  google/cloud/grpc_utils/completion_queue.cc
  google/cloud/grpc_utils/completion_queue.h
  google/cloud/grpc_utils/google_cloud_cpp_grpc_utils.bzl
  google/cloud/grpc_utils/internal/async_read_stream_impl.h
  google/cloud/grpc_utils/internal/completion_queue_impl.cc
  google/cloud/grpc_utils/internal/completion_queue_impl.h
Labels: cla: yes, type: cleanup

#2879 doc: Explain why some subdirectories are disabled.
  google/cloud/CMakeLists.txt
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/storage/CMakeLists.txt
Labels: cla: yes

#2887 cleanup: Fix shellcheck warning in upload-docs.sh
  ci/kokoro/docker/upload-docs.sh
Labels: cla: yes

#2889 cleanup: Fix OpenCensus warnings in bigtable example.
  google/cloud/bigtable/examples/opencensus/bigtable_opencensus.cc
Labels: cla: yes

#2892 feat: add conjunction
  google/cloud/CMakeLists.txt
  google/cloud/google_cloud_cpp_common.bzl
  google/cloud/internal/conjunction.h
Labels: cla: yes

#2888 Utilize googleapis repo
  INSTALL.md
  ci/kokoro/docker/Dockerfile.fedora-install
  ci/kokoro/docker/Dockerfile.ubuntu-install
  ci/kokoro/install/Dockerfile.centos
  ci/kokoro/install/Dockerfile.debian
  ci/kokoro/install/Dockerfile.fedora
  ci/kokoro/install/Dockerfile.opensuse
  ci/kokoro/install/Dockerfile.opensuse-leap
  ci/kokoro/install/Dockerfile.ubuntu
  ci/kokoro/install/Dockerfile.ubuntu-trusty
  ci/kokoro/install/Dockerfile.ubuntu-xenial
  ci/kokoro/windows/build-project.ps1
  cmake/IncludeGoogleapis.cmake
  cmake/external/googleapis.cmake
  cmake/external/googleapis/CMakeLists.txt
  cmake/external/googleapis/README.md
  cmake/external/googleapis/config-version.cmake.in
  cmake/external/googleapis/config.cmake.in
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/grpc_utils/CMakeLists.txt
Labels: cla: yes

#2881 Partially change benchmarks to use StatusOr instead of exceptions.
  google/cloud/bigtable/benchmarks/apply_read_latency_benchmark.cc
  google/cloud/bigtable/benchmarks/benchmark.cc
  google/cloud/bigtable/benchmarks/benchmark.h
  google/cloud/bigtable/benchmarks/bigtable_benchmark_test.cc
  google/cloud/bigtable/benchmarks/endurance_benchmark.cc
  google/cloud/bigtable/benchmarks/scan_throughput_benchmark.cc
Labels: cla: yes

#2885 feat: Helpers for PredefinedDefaultObjectAcl.
  google/cloud/storage/tests/bucket_integration_test.cc
  google/cloud/storage/well_known_parameters.h
Labels: cla: yes

#2896 chore: removed attempt to install pkgconfig in opensuse
  ci/kokoro/install/Dockerfile.opensuse
Labels: cla: yes

#2886 Implement native IAM data structures for GCS.
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/iam_policy.cc
  google/cloud/storage/iam_policy.h
  google/cloud/storage/storage_client.bzl
  google/cloud/storage/storage_client_unit_tests.bzl
  google/cloud/storage/storage_iam_policy_test.cc
Labels: cla: yes

#2899 Use print() function in both Python 2 and Python 3
  google/cloud/bigtable/tools/convert_acceptance_tests.py
  google/cloud/bigtable/tools/generate_rpc_policy_parameters.py
Labels: cla: yes

#2897 Convert BenchmarkSetup to use StatusOr.
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/benchmarks/apply_read_latency_benchmark.cc
  google/cloud/bigtable/benchmarks/bigtable_benchmark_test.cc
  google/cloud/bigtable/benchmarks/endurance_benchmark.cc
  google/cloud/bigtable/benchmarks/scan_throughput_benchmark.cc
  google/cloud/bigtable/benchmarks/setup.cc
  google/cloud/bigtable/benchmarks/setup.h
  google/cloud/bigtable/benchmarks/setup_test.cc
Labels: cla: yes

#2898 feat: Add CMake super build.
  ci/kokoro/docker/build-in-docker-cmake.sh
  ci/kokoro/docker/build.sh
  ci/kokoro/docker/cmake-super-presubmit.cfg
  ci/kokoro/docker/cmake-super.cfg
  ci/kokoro/readme/Dockerfile.centos
  ci/kokoro/readme/Dockerfile.debian
  ci/kokoro/readme/Dockerfile.fedora
  ci/kokoro/readme/Dockerfile.opensuse
  ci/kokoro/readme/Dockerfile.opensuse-leap
  ci/kokoro/readme/Dockerfile.ubuntu
  ci/kokoro/readme/Dockerfile.ubuntu-trusty
  ci/kokoro/readme/Dockerfile.ubuntu-xenial
  ci/super/CMakeLists.txt
  cmake/ExternalProjectHelper.cmake
  cmake/external/c-ares.cmake
  cmake/external/crc32c.cmake
  cmake/external/curl.cmake
  cmake/external/googleapis.cmake
  cmake/external/googletest.cmake
  cmake/external/grpc.cmake
  cmake/external/protobuf.cmake
  cmake/external/zlib.cmake
Labels: cla: yes

#2900 Implement native IAM operations for GCS.
  ci/test-abi/storage_client.expected.abi.dump.gz
  google/cloud/storage/client.h
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_bucket_iam_samples.cc
  google/cloud/storage/idempotency_policy.cc
  google/cloud/storage/idempotency_policy.h
  google/cloud/storage/idempotency_policy_test.cc
  google/cloud/storage/internal/bucket_requests.cc
  google/cloud/storage/internal/bucket_requests.h
  google/cloud/storage/internal/bucket_requests_test.cc
  google/cloud/storage/internal/curl_client.cc
  google/cloud/storage/internal/curl_client.h
  google/cloud/storage/internal/curl_client_test.cc
  google/cloud/storage/internal/logging_client.cc
  google/cloud/storage/internal/logging_client.h
  google/cloud/storage/internal/raw_client.h
  google/cloud/storage/internal/retry_client.cc
  google/cloud/storage/internal/retry_client.h
  google/cloud/storage/testing/mock_client.h
  google/cloud/storage/tests/bucket_integration_test.cc
Labels: cla: yes

#2901 Disable ABI compatibility checks.
  ci/kokoro/docker/check-abi-presubmit.cfg
  ci/kokoro/docker/check-abi.cfg
  ci/kokoro/docker/check-abi.sh
  ci/kokoro/docker/dump-reports.sh
Labels: cla: yes

#2903 Remove unused cmake-super cfg files.
  ci/kokoro/docker/cmake-super-presubmit.cfg
  ci/kokoro/docker/cmake-super.cfg
Labels: cla: yes

#2909 docs: add a necessary flag for windows in README
  README.md
  doc/setup-development-environment.md
Labels: cla: yes

#2920 Add tracking region tag to GetBucketMetadata
  google/cloud/storage/examples/storage_bucket_samples.cc
Labels: cla: yes

#2916 feat: Change storage/benchmarks to compile with exceptions disabled.
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/benchmarks/benchmark_parser_test.cc
  google/cloud/storage/benchmarks/benchmark_utils.cc
  google/cloud/storage/benchmarks/benchmark_utils.h
  google/cloud/storage/benchmarks/storage_file_transfer_benchmark.cc
  google/cloud/storage/benchmarks/storage_latency_benchmark.cc
  google/cloud/storage/benchmarks/storage_throughput_benchmark.cc
  google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc
Labels: cla: yes

#2921 testing: Add kokoro build on windows 2019
  ci/kokoro/windows/build-dependencies.ps1
  ci/kokoro/windows/continuous-win-2019.cfg
  ci/kokoro/windows/presubmit-win-2019.cfg
Labels: cla: yes

#2918 cleanup: Use NCPU consistently in all scripts.
  INSTALL.md
  README.md
  ci/kokoro/docker/Dockerfile.fedora-install
  ci/kokoro/docker/Dockerfile.ubuntu-install
  ci/kokoro/docker/build.sh
  ci/kokoro/docker/create-docker-image.sh
  ci/kokoro/docker/define-docker-variables.sh
  ci/kokoro/install/Dockerfile.centos
  ci/kokoro/install/Dockerfile.debian
  ci/kokoro/install/Dockerfile.fedora
  ci/kokoro/install/Dockerfile.opensuse
  ci/kokoro/install/Dockerfile.opensuse-leap
  ci/kokoro/install/Dockerfile.ubuntu
  ci/kokoro/install/Dockerfile.ubuntu-trusty
  ci/kokoro/install/Dockerfile.ubuntu-xenial
  ci/kokoro/install/build.sh
  ci/kokoro/readme/Dockerfile.centos
  ci/kokoro/readme/Dockerfile.debian
  ci/kokoro/readme/Dockerfile.fedora
  ci/kokoro/readme/Dockerfile.opensuse
  ci/kokoro/readme/Dockerfile.opensuse-leap
  ci/kokoro/readme/Dockerfile.ubuntu
  ci/kokoro/readme/Dockerfile.ubuntu-trusty
  ci/kokoro/readme/Dockerfile.ubuntu-xenial
  ci/kokoro/readme/build.sh
  ci/test-readme/README.md
  ci/test-readme/generate-install.sh
Labels: cla: yes

#2922 Updating Macos build instructions for Mojave
  README.md
Labels: cla: yes

#2910 Bigtable write samples
  google/cloud/bigtable/examples/data_snippets.cc
  google/cloud/bigtable/examples/run_examples_utils.sh
Labels: cla: yes

#2919 making partial errors/last_status available to `ObjectWriteStream`
  google/cloud/storage/internal/object_streambuf.cc
  google/cloud/storage/internal/object_streambuf.h
  google/cloud/storage/internal/object_streambuf_test.cc
  google/cloud/storage/object_stream.h
Labels: cla: yes

#2925 cleanup: Move ci/super to super
  ci/kokoro/docker/build.sh
  ci/kokoro/readme/Dockerfile.centos
  ci/kokoro/readme/Dockerfile.debian
  ci/kokoro/readme/Dockerfile.fedora
  ci/kokoro/readme/Dockerfile.opensuse
  ci/kokoro/readme/Dockerfile.opensuse-leap
  ci/kokoro/readme/Dockerfile.ubuntu
  ci/kokoro/readme/Dockerfile.ubuntu-trusty
  ci/kokoro/readme/Dockerfile.ubuntu-xenial
  super/CMakeLists.txt
Labels: cla: yes

#2926 cleanup: Remove unneeded build/Dockerfiles and cleanup build.sh
  ci/kokoro/docker/Dockerfile.centos
  ci/kokoro/docker/Dockerfile.ubuntu-trusty
  ci/kokoro/docker/build.sh
  ci/kokoro/docker/centos-7-presubmit.cfg
  ci/kokoro/docker/centos-7.cfg
Labels: cla: yes

#2923 feat: Minimize contention in Bigtable Client initialization.
  google/cloud/bigtable/internal/common_client.h
Labels: api: bigtable, cla: yes, type: feature request

#2924 Mocking examples of `raw_client` for failed scenarios.
  google/cloud/storage/doc/storage-mocking.dox
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_client_mock_samples.cc
Labels: cla: yes

#2902 Control TCP memory usage in GCS library.
  ci/test-abi/storage_client.expected.abi.dump.gz
  google/cloud/storage/client_options.h
  google/cloud/storage/internal/curl_client.cc
  google/cloud/storage/internal/curl_download_request.cc
  google/cloud/storage/internal/curl_download_request.h
  google/cloud/storage/internal/curl_handle.cc
  google/cloud/storage/internal/curl_handle.h
  google/cloud/storage/internal/curl_request.cc
  google/cloud/storage/internal/curl_request.h
  google/cloud/storage/internal/curl_request_builder.cc
  google/cloud/storage/internal/curl_request_builder.h
  google/cloud/storage/storage_client_options_test.cc
  google/cloud/storage/tests/CMakeLists.txt
  google/cloud/storage/tests/read_object_stall_regression/CMakeLists.txt
  google/cloud/storage/tests/read_object_stall_regression/Dockerfile
  google/cloud/storage/tests/read_object_stall_regression/README.md
  google/cloud/storage/tests/read_object_stall_regression/cloudbuild.yaml
  google/cloud/storage/tests/read_object_stall_regression/create-job.sh
  google/cloud/storage/tests/read_object_stall_regression/read_object_stall_test.cc
Labels: api: storage, cla: yes

#2927 cleanup: Make comment future proof.
  google/cloud/bigtable/internal/common_client.h
Labels: api: bigtable, cla: yes, type: cleanup
