Repository googleapis/google-cloud-cpp, pull requests merged in 2019-04, with the labels that each got.

#2378 Report errors detected in CurlDownloadRequest.
  google/cloud/storage/internal/curl_download_request.cc
  google/cloud/storage/tests/object_media_integration_test.cc
Labels: api: storage, cla: yes

#2381 Fix inconsistently named function in RequestBuilder.
  google/cloud/storage/internal/curl_client.cc
  google/cloud/storage/internal/curl_request_builder.cc
  google/cloud/storage/internal/curl_request_builder.h
  google/cloud/storage/tests/curl_streambuf_integration_test.cc
  google/cloud/storage/tests/curl_upload_request_integration_test.cc
Labels: api: storage, cla: yes

#2380 Use exceptions to report "cannot happen" errors.
  google/cloud/storage/internal/curl_download_request.cc
  google/cloud/storage/internal/curl_download_request.h
  google/cloud/storage/internal/curl_upload_request.cc
  google/cloud/storage/internal/curl_upload_request.h
Labels: api: storage, cla: yes

#2370 Support policy documents
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/client.cc
  google/cloud/storage/client.h
  google/cloud/storage/client_sign_policy_document_test.cc
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_bucket_samples.cc
  google/cloud/storage/internal/policy_document_request.cc
  google/cloud/storage/internal/policy_document_request.h
  google/cloud/storage/policy_document.cc
  google/cloud/storage/policy_document.h
  google/cloud/storage/policy_document_test.cc
  google/cloud/storage/storage_client.bzl
  google/cloud/storage/storage_client_unit_tests.bzl
Labels: cla: yes

#2383 Fix Object*Stream move constructor and assignment.
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/internal/object_streambuf.h
  google/cloud/storage/internal/object_streambuf_test.cc
  google/cloud/storage/object_stream.h
  google/cloud/storage/object_stream_test.cc
  google/cloud/storage/storage_client_unit_tests.bzl
Labels: api: storage, cla: yes

#2382 Implement bigtable::Table::AsyncCheckAndMutateRow
  google/cloud/bigtable/examples/data_async_snippets.cc
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/table.cc
  google/cloud/bigtable/table.h
  google/cloud/bigtable/tests/data_async_future_integration_test.cc
Labels: cla: yes

#2386 Ignore additional build dirs in check-style
  ci/check-style.sh
Labels: cla: yes

#2397 Always use resumable uploads in ObjectWrite() for better error detection and retries.
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/internal/curl_client.cc
  google/cloud/storage/internal/curl_client.h
  google/cloud/storage/internal/curl_handle.h
  google/cloud/storage/internal/curl_request_builder.cc
  google/cloud/storage/internal/curl_request_builder.h
  google/cloud/storage/internal/curl_streambuf.cc
  google/cloud/storage/internal/curl_streambuf.h
  google/cloud/storage/internal/curl_upload_request.cc
  google/cloud/storage/internal/curl_upload_request.h
  google/cloud/storage/storage_client.bzl
  google/cloud/storage/testbench/gcs_bucket.py
  google/cloud/storage/testbench/testbench_utils.py
  google/cloud/storage/tests/CMakeLists.txt
  google/cloud/storage/tests/curl_streambuf_integration_test.cc
  google/cloud/storage/tests/curl_upload_request_integration_test.cc
  google/cloud/storage/tests/object_checksum_integration_test.cc
  google/cloud/storage/tests/object_hash_integration_test.cc
  google/cloud/storage/tests/run_integration_tests_testbench.sh
  google/cloud/storage/tests/storage_client_integration_tests.bzl
Labels: api: storage, cla: yes

#2394 Implementation of TableAdmin::AsyncModifyColumnFamilies
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/examples/table_admin_async_snippets.cc
  google/cloud/bigtable/table_admin.cc
  google/cloud/bigtable/table_admin.h
  google/cloud/bigtable/tests/admin_async_future_integration_test.cc
Labels: cla: yes

#2377 BulkMutator is overusing UNKNOWN error.
  google/cloud/bigtable/internal/bulk_mutator.cc
  google/cloud/bigtable/internal/bulk_mutator.h
  google/cloud/bigtable/internal/bulk_mutator_test.cc
  google/cloud/bigtable/table_bulk_apply_test.cc
Labels: cla: yes

#2389 Fixed small StatusOr::op bool, usage bug
  google/cloud/bigtable/examples/table_admin_snippets.cc
Labels: cla: yes

#2384 Make `StartAsyncPollOp` accept future<Operation>.
  google/cloud/bigtable/internal/async_longrunning_op.h
  google/cloud/bigtable/internal/async_longrunning_op_test.cc
  google/cloud/bigtable/internal/async_poll_op.h
  google/cloud/bigtable/internal/async_poll_op_test.cc
Labels: cla: yes

#2396 Create code snippet for bigtable_read_prefix list
  google/cloud/bigtable/examples/data_snippets.cc
  google/cloud/bigtable/examples/run_examples_utils.sh
Labels: cla: yes

#2401 keep instance_admin_endpoint_ and admin_endpoint_ in sync
  google/cloud/bigtable/client_options.h
  google/cloud/bigtable/client_options_test.cc
Labels: cla: yes

#2400 Do not throw exceptions in WriteObject().
  google/cloud/storage/client.cc
  google/cloud/storage/client.h
  google/cloud/storage/client_write_object_test.cc
  google/cloud/storage/internal/curl_client_test.cc
  google/cloud/storage/tests/object_media_integration_test.cc
  google/cloud/storage/tests/object_resumable_write_integration_test.cc
Labels: api: storage, cla: yes

#2403 release notes
  google/cloud/README.md
  google/cloud/bigtable/README.md
  google/cloud/storage/README.md
Labels: cla: yes

#2393 Implement future-base async multi-page requests.
  google/cloud/bigtable/internal/async_retry_multi_page.h
  google/cloud/bigtable/internal/async_retry_multi_page_test.cc
Labels: cla: yes

#2357 Async start a longrunning op and poll for result.
  google/cloud/bigtable/internal/async_retry_unary_rpc_and_poll.h
  google/cloud/bigtable/internal/async_retry_unary_rpc_and_poll_test.cc
  google/cloud/internal/future_then_impl.h
Labels: :rotating_light:, cla: yes

#2405 bumping version numbers for next release
  google/cloud/CMakeLists.txt
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/bigtable_client_version.bzl
  google/cloud/google_cloud_cpp_common_version.bzl
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/storage_client_version.bzl
Labels: cla: yes

#2402 Implement bigtable::Table::AsyncReadModifyWriteRow
  google/cloud/bigtable/examples/data_async_snippets.cc
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/table.h
  google/cloud/bigtable/tests/data_async_future_integration_test.cc
Labels: cla: yes

#2407 CMake: Use CURL::libcurl instead of CURL::CURL
  cmake/IncludeCurl.cmake
  cmake/external/curl.cmake
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/config.cmake.in
  google/cloud/storage/tests/CMakeLists.txt
Labels: cla: yes, type: cleanup

#2410 Create HMAC Key samples.
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_service_account_samples.cc
Labels: api: storage, cla: yes

#2412 Fix region tags for a couple of storage samples.
  google/cloud/storage/examples/storage_bucket_samples.cc
  google/cloud/storage/examples/storage_object_acl_samples.cc
Labels: api: storage, cla: yes, type: docs

#2418 Make optional's relational operators free functions.
  google/cloud/optional.h
Labels: cla: yes

#2422 Multiple fixes to the HMAC implementation.
  google/cloud/storage/client.h
  google/cloud/storage/client_service_account_test.cc
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_service_account_samples.cc
  google/cloud/storage/internal/curl_client.cc
  google/cloud/storage/internal/curl_client.h
  google/cloud/storage/internal/hmac_key_requests.cc
  google/cloud/storage/internal/hmac_key_requests_test.cc
  google/cloud/storage/internal/logging_client.cc
  google/cloud/storage/internal/logging_client.h
  google/cloud/storage/internal/raw_client.h
  google/cloud/storage/internal/retry_client.cc
  google/cloud/storage/internal/retry_client.h
  google/cloud/storage/testbench/gcs_project.py
  google/cloud/storage/testing/mock_client.h
  google/cloud/storage/tests/service_account_integration_test.cc
  google/cloud/storage/well_known_parameters.h
Labels: api: storage, cla: yes

#2425 Start document to create testing resources.
  google/cloud/storage/doc/setup-test-resources.md
Labels: api: storage, cla: yes, type: docs

#2423 Enable hmac key integration tests
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/tests/service_account_integration_test.cc
Labels: cla: yes

#2424 Implement SignBlobRequest and SignBlobResponse.
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/idempotency_policy.cc
  google/cloud/storage/idempotency_policy.h
  google/cloud/storage/idempotency_policy_test.cc
  google/cloud/storage/internal/sign_blob_requests.cc
  google/cloud/storage/internal/sign_blob_requests.h
  google/cloud/storage/internal/sign_blob_requests_test.cc
  google/cloud/storage/storage_client.bzl
  google/cloud/storage/storage_client_unit_tests.bzl
Labels: api: storage, cla: yes

#2427 Add storage_stream_file_upload region tag.
  google/cloud/storage/examples/storage_object_samples.cc
Labels: api: storage, cla: yes

#2426 Implement get-bucket-class-and-location example.
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_bucket_samples.cc
Labels: api: storage, cla: yes

#2419 Clean up relational operators
  google/cloud/bigtable/internal/rowreaderiterator.h
  google/cloud/bigtable/metadata_update_policy.h
  google/cloud/bigtable/row_range.cc
  google/cloud/bigtable/row_range.h
  google/cloud/firestore/field_path.cc
  google/cloud/firestore/field_path.h
  google/cloud/iam_bindings.h
  google/cloud/storage/internal/access_control_common.h
  google/cloud/storage/internal/common_metadata.h
  google/cloud/storage/internal/range_from_pagination.h
  google/cloud/testing_util/testing_types.h
Labels: cla: yes

#2433 Fix typos in region tags.
  google/cloud/bigtable/examples/bigtable_samples.cc
Labels: api: bigtable, cla: yes

#2432 Remove invalid region tags.
  google/cloud/storage/examples/storage_bucket_acl_samples.cc
  google/cloud/storage/examples/storage_bucket_samples.cc
  google/cloud/storage/examples/storage_default_object_acl_samples.cc
  google/cloud/storage/examples/storage_object_acl_samples.cc
  google/cloud/storage/examples/storage_object_samples.cc
  google/cloud/storage/examples/storage_service_account_samples.cc
Labels: cla: yes

#2399 Standardize documentation on "cmake-out" for cmake's binary output.
  .dockerignore
  .gitignore
  .travis.yml
  CONTRIBUTING.md
  INSTALL.md
  README.md
  ci/build-jenkins.sh
  ci/check-style.sh
  ci/kokoro/docker/check-abi-presubmit.cfg
  ci/kokoro/docker/check-abi.cfg
  ci/kokoro/windows/build-project.ps1
  ci/test-readme/Dockerfile.centos
  ci/test-readme/Dockerfile.debian
  ci/test-readme/Dockerfile.fedora
  ci/test-readme/Dockerfile.opensuse
  ci/test-readme/Dockerfile.opensuse-leap
  ci/test-readme/Dockerfile.ubuntu
  ci/test-readme/Dockerfile.ubuntu-trusty
  ci/test-readme/Dockerfile.ubuntu-xenial
  ci/test-readme/generate-install.sh
  ci/travis/Dockerfile.ubuntu-install
  ci/travis/build-docker.sh
  ci/travis/dump-logs.sh
  ci/travis/dump-reports.sh
  ci/travis/linux-config.sh
  ci/travis/upload-codecov.sh
  cmake/GoogleCloudCppCommon.cmake
  doc/cutting-a-release.md
  doc/setup-development-environment.md
  google/cloud/storage/doc/storage-main.dox
Labels: cla: yes

#2428 Prepare Credentials class to support SignBlob API.
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/client.cc
  google/cloud/storage/client.h
  google/cloud/storage/client_sign_policy_document_test.cc
  google/cloud/storage/client_sign_url_test.cc
  google/cloud/storage/oauth2/credentials.cc
  google/cloud/storage/oauth2/credentials.h
  google/cloud/storage/oauth2/service_account_credentials.h
  google/cloud/storage/oauth2/service_account_credentials_test.cc
  google/cloud/storage/signed_url_options.h
  google/cloud/storage/storage_client.bzl
Labels: api: storage, cla: yes

#2436 Fix flaky HMAC key integration tests.
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/tests/service_account_integration_test.cc
Labels: api: storage, cla: yes

#2437 Fix region tags for bigtable_hello_world.
  google/cloud/bigtable/examples/bigtable_hello_world.cc
Labels: api: storage, cla: yes

#2439 Implement "Make Bucket public using IAM" sample.
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_bucket_iam_samples.cc
Labels: api: storage, cla: yes

#2431 Implement internal::*Client::SignBlob().
  google/cloud/storage/client_options.cc
  google/cloud/storage/client_options.h
  google/cloud/storage/idempotency_policy.h
  google/cloud/storage/internal/curl_client.cc
  google/cloud/storage/internal/curl_client.h
  google/cloud/storage/internal/curl_client_test.cc
  google/cloud/storage/internal/logging_client.cc
  google/cloud/storage/internal/logging_client.h
  google/cloud/storage/internal/raw_client.h
  google/cloud/storage/internal/retry_client.cc
  google/cloud/storage/internal/retry_client.h
  google/cloud/storage/storage_client_options_test.cc
  google/cloud/storage/testbench/gcs_iam.py
  google/cloud/storage/testbench/testbench.py
  google/cloud/storage/testing/mock_client.h
  google/cloud/storage/tests/CMakeLists.txt
  google/cloud/storage/tests/curl_sign_blob_integration_test.cc
  google/cloud/storage/tests/run_integration_tests_production.sh
  google/cloud/storage/tests/run_integration_tests_testbench.sh
  google/cloud/storage/tests/storage_client_integration_tests.bzl
Labels: api: storage, cla: yes

#2429 Fix inconsistencies in SignBlob{Request,Response} tests.
  google/cloud/storage/internal/sign_blob_requests_test.cc
Labels: api: storage, cla: yes, type: cleanup

#2438 Output content-length-range parameters as numbers, not strings.
  google/cloud/storage/client_sign_policy_document_test.cc
  google/cloud/storage/internal/policy_document_request.cc
Labels: cla: yes

#2416 Create code snippet for bigtable_row_exists
  google/cloud/bigtable/examples/data_snippets.cc
  google/cloud/bigtable/examples/run_examples_utils.sh
Labels: cla: yes

#2445 Fix cut&paste mistakes in HMAC key examples.
  google/cloud/storage/examples/storage_service_account_samples.cc
Labels: api: storage, cla: yes

#2444 Add a number of missing examples to CI build.
  google/cloud/storage/examples/run_examples_utils.sh
Labels: api: storage, cla: yes

#2446 Refactor UsingTestbench() function.
  google/cloud/storage/testing/storage_integration_test.cc
  google/cloud/storage/testing/storage_integration_test.h
  google/cloud/storage/tests/object_checksum_integration_test.cc
  google/cloud/storage/tests/object_hash_integration_test.cc
  google/cloud/storage/tests/object_media_integration_test.cc
  google/cloud/storage/tests/object_resumable_write_integration_test.cc
Labels: api: storage, cla: yes

#2409 Remove noex::Table::ReadModifyWriteRow() and SampleRows()
  google/cloud/bigtable/table.cc
  google/cloud/bigtable/table.h
Labels: cla: yes

#2443 Moved Status operator== and operator!= from member to free functions
  google/cloud/status.h
Labels: cla: yes

#2447 Add SigningAccount options to Sign*Request.
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/internal/policy_document_request.cc
  google/cloud/storage/internal/policy_document_request.h
  google/cloud/storage/internal/policy_document_request_test.cc
  google/cloud/storage/internal/signed_url_requests.h
  google/cloud/storage/internal/signed_url_requests_test.cc
  google/cloud/storage/storage_client_unit_tests.bzl
Labels: api: storage, cla: yes

#2448 Cleanup implementation oauth2::*Credentials.
  google/cloud/storage/oauth2/authorized_user_credentials.h
  google/cloud/storage/oauth2/compute_engine_credentials.h
  google/cloud/storage/oauth2/refreshing_credentials_wrapper.cc
  google/cloud/storage/oauth2/refreshing_credentials_wrapper.h
  google/cloud/storage/oauth2/service_account_credentials.h
Labels: api: storage, cla: yes, type: cleanup

#2450 Fix HMAC key leak in integration test.
  google/cloud/storage/tests/service_account_integration_test.cc
Labels: api: storage, cla: yes

#2449 Use SignBlob API if needed.
  google/cloud/storage/client.cc
  google/cloud/storage/client.h
  google/cloud/storage/client_sign_policy_document_test.cc
  google/cloud/storage/client_sign_url_test.cc
Labels: api: storage, cla: yes

#2452 Refactor V4 signed URL conformance test.
  google/cloud/storage/tests/CMakeLists.txt
  google/cloud/storage/tests/run_integration_tests_production.sh
  google/cloud/storage/tests/run_integration_tests_testbench.sh
  google/cloud/storage/tests/signed_url_conformance_test.cc
  google/cloud/storage/tests/storage_client_integration_tests.bzl
Labels: api: storage, cla: yes, type: cleanup

#2453 Restore accidentally removed comment.
  google/cloud/storage/client.h
Labels: api: storage, cla: yes

#2454 Fix test names.
  google/cloud/storage/client_sign_policy_document_test.cc
Labels: cla: yes

#2460 Avoid std::make_exception_ptr() in future_shared_state_base::abandon()
  google/cloud/internal/future_impl.h
Labels: cla: yes, type: cleanup

#2455 Use CMAKE_BINARY_DIR to make google-cloud-cpp work as a submodule.
  cmake/ExternalProjectHelper.cmake
  cmake/external/grpc.cmake
Labels: cla: yes

#2456 New integration tests for SignUrl.
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/tests/CMakeLists.txt
  google/cloud/storage/tests/run_integration_tests_production.sh
  google/cloud/storage/tests/run_integration_tests_testbench.sh
  google/cloud/storage/tests/signed_url_integration_test.cc
  google/cloud/storage/tests/storage_client_integration_tests.bzl
Labels: api: storage, cla: yes

#2461 Use SFINAE to constrain applicability of the BulkMutation(M&&...) ctor
  google/cloud/bigtable/mutations.h
Labels: api: bigtable, cla: yes, type: cleanup

#2457 Include what you use: std::function, std::string, std::vector.
  google/cloud/storage/internal/range_from_pagination.h
Labels: api: storage, cla: yes, type: cleanup

#2458 Include what you use: google/cloud/storage/version.h
  google/cloud/storage/bucket_access_control.h
  google/cloud/storage/bucket_metadata.h
  google/cloud/storage/client.h
  google/cloud/storage/client_options.h
  google/cloud/storage/download_options.h
  google/cloud/storage/hashing_options.h
  google/cloud/storage/idempotency_policy.h
  google/cloud/storage/internal/access_control_common.h
  google/cloud/storage/internal/bucket_acl_requests.h
  google/cloud/storage/internal/bucket_requests.h
  google/cloud/storage/internal/common_metadata.h
  google/cloud/storage/internal/curl_client.h
  google/cloud/storage/internal/curl_download_request.h
  google/cloud/storage/internal/curl_handle.h
  google/cloud/storage/internal/curl_handle_factory.h
  google/cloud/storage/internal/curl_request.h
  google/cloud/storage/internal/curl_request_builder.h
  google/cloud/storage/internal/curl_resumable_streambuf.h
  google/cloud/storage/internal/curl_resumable_upload_session.h
  google/cloud/storage/internal/curl_streambuf.h
  google/cloud/storage/internal/default_object_acl_requests.h
  google/cloud/storage/internal/generic_object_request.h
  google/cloud/storage/internal/generic_request.h
  google/cloud/storage/internal/hmac_key_requests.h
  google/cloud/storage/internal/logging_client.h
  google/cloud/storage/internal/logging_resumable_upload_session.h
  google/cloud/storage/internal/metadata_parser.h
  google/cloud/storage/internal/notification_requests.h
  google/cloud/storage/internal/object_acl_requests.h
  google/cloud/storage/internal/object_requests.h
  google/cloud/storage/internal/object_streambuf.h
  google/cloud/storage/internal/patch_builder.h
  google/cloud/storage/internal/policy_document_request.h
  google/cloud/storage/internal/raw_client.h
  google/cloud/storage/internal/raw_client_wrapper_utils.h
  google/cloud/storage/internal/resumable_upload_session.h
  google/cloud/storage/internal/retry_client.h
  google/cloud/storage/internal/retry_resumable_upload_session.h
  google/cloud/storage/internal/service_account_requests.h
  google/cloud/storage/internal/signed_url_requests.h
  google/cloud/storage/lifecycle_rule.h
  google/cloud/storage/list_buckets_reader.h
  google/cloud/storage/list_objects_reader.h
  google/cloud/storage/notification_metadata.h
  google/cloud/storage/oauth2/anonymous_credentials.h
  google/cloud/storage/oauth2/authorized_user_credentials.h
  google/cloud/storage/oauth2/compute_engine_credentials.h
  google/cloud/storage/oauth2/google_credentials.h
  google/cloud/storage/oauth2/service_account_credentials.h
  google/cloud/storage/object_access_control.h
  google/cloud/storage/object_metadata.h
  google/cloud/storage/object_rewriter.h
  google/cloud/storage/object_stream.h
  google/cloud/storage/override_default_project.h
  google/cloud/storage/retry_policy.h
  google/cloud/storage/service_account.h
  google/cloud/storage/signed_url_options.h
  google/cloud/storage/upload_options.h
Labels: api: storage, cla: yes, type: cleanup

#2462 Add test for using google-cloud-cpp as a submodule.
  README.md
  ci/test-install/submodule/CMakeLists.txt
  ci/test-readme/Dockerfile.centos
  ci/test-readme/Dockerfile.debian
  ci/test-readme/Dockerfile.fedora
  ci/test-readme/Dockerfile.opensuse
  ci/test-readme/Dockerfile.opensuse-leap
  ci/test-readme/Dockerfile.ubuntu
  ci/test-readme/Dockerfile.ubuntu-trusty
  ci/test-readme/Dockerfile.ubuntu-xenial
  ci/travis/build-docker.sh
Labels: cla: yes

#2459 Include what you use: google/cloud/bigtable/version.h
  google/cloud/bigtable/admin_client.h
  google/cloud/bigtable/app_profile_config.h
  google/cloud/bigtable/bigtable_strong_types.h
  google/cloud/bigtable/completion_queue.h
  google/cloud/bigtable/data_client.h
  google/cloud/bigtable/filters.h
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/instance_admin_client.h
  google/cloud/bigtable/instance_config.h
  google/cloud/bigtable/instance_update_config.h
  google/cloud/bigtable/internal/async_bulk_apply.h
  google/cloud/bigtable/internal/async_check_consistency.h
  google/cloud/bigtable/internal/async_future_from_callback.h
  google/cloud/bigtable/internal/async_list_app_profiles.h
  google/cloud/bigtable/internal/async_list_clusters.h
  google/cloud/bigtable/internal/async_list_instances.h
  google/cloud/bigtable/internal/async_longrunning_op.h
  google/cloud/bigtable/internal/async_loop_op.h
  google/cloud/bigtable/internal/async_poll_op.h
  google/cloud/bigtable/internal/async_read_row_operation.h
  google/cloud/bigtable/internal/async_retry_multi_page.h
  google/cloud/bigtable/internal/async_retry_op.h
  google/cloud/bigtable/internal/async_retry_unary_rpc.h
  google/cloud/bigtable/internal/async_retry_unary_rpc_and_poll.h
  google/cloud/bigtable/internal/async_row_reader.h
  google/cloud/bigtable/internal/async_sample_row_keys.h
  google/cloud/bigtable/internal/bulk_mutator.h
  google/cloud/bigtable/internal/common_client.h
  google/cloud/bigtable/internal/completion_queue_impl.h
  google/cloud/bigtable/internal/instance_admin.h
  google/cloud/bigtable/internal/poll_longrunning_operation.h
  google/cloud/bigtable/internal/readrowsparser.h
  google/cloud/bigtable/internal/rowreaderiterator.h
  google/cloud/bigtable/internal/table_admin.h
  google/cloud/bigtable/internal/unary_client_utils.h
  google/cloud/bigtable/mutations.h
  google/cloud/bigtable/row.h
  google/cloud/bigtable/row_range.h
  google/cloud/bigtable/row_reader.h
  google/cloud/bigtable/row_set.h
  google/cloud/bigtable/table.h
  google/cloud/bigtable/table_admin.h
  google/cloud/bigtable/table_config.h
  google/cloud/bigtable/table_strong_types.h
Labels: api: bigtable, cla: yes, type: cleanup

#2467 Use the unparsed args in export_variables_to_bazel
  cmake/CreateBazelConfig.cmake
Labels: cla: yes

#2470 Fix typos in these READMEs: support->supports
  google/cloud/bigtable/README.md
  google/cloud/storage/README.md
Labels: cla: yes

#2466 Stub spanner_client library.
  ci/travis/build-docker.sh
  google/cloud/CMakeLists.txt
  google/cloud/spanner/BUILD
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/README.md
  google/cloud/spanner/config.cmake.in
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_unit_tests.bzl
  google/cloud/spanner/spanner_client_version.bzl
  google/cloud/spanner/spanner_version_test.cc
  google/cloud/spanner/version.cc
  google/cloud/spanner/version.h
  google/cloud/spanner/version_info.h.in
Labels: cla: yes

#2471 Bump version numbers for release v0.8.1
  google/cloud/CMakeLists.txt
  google/cloud/README.md
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/README.md
  google/cloud/bigtable/bigtable_client_version.bzl
  google/cloud/google_cloud_cpp_common_version.bzl
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/storage_client_version.bzl
Labels: cla: yes

#2464 Implementation of `TableAdmin::AsyncDropRowsByPrefix`
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/examples/table_admin_async_snippets.cc
  google/cloud/bigtable/table_admin.cc
  google/cloud/bigtable/table_admin.h
  google/cloud/bigtable/tests/admin_async_future_integration_test.cc
Labels: cla: yes

#2473 Enclose instances of $0 in quotes
  ci/check-abi.sh
  ci/check-style.sh
  ci/define-example-runner.sh
  ci/install-retry.sh
  ci/kokoro/bazel-dependency/linux/build.sh
  ci/kokoro/docker/build.sh
  ci/kokoro/install/build.sh
  ci/kokoro/macos/build.sh
  ci/kokoro/ubuntu/build.sh
  ci/test-readme/dockerfile2markdown.sh
  ci/test-readme/extract-install.sh
  ci/test-readme/extract-readme.sh
  ci/test-readme/generate-install.sh
  ci/test-readme/generate-readme.sh
  ci/travis/build-bazel.sh
  ci/travis/build-linux.sh
  ci/travis/dump-logs.sh
  ci/travis/dump-reports.sh
  ci/travis/install-linux.sh
  ci/travis/upload-codecov.sh
  ci/travis/upload-docs.sh
  google/cloud/bigtable/ci/run_integration_tests.sh
  google/cloud/bigtable/examples/run_examples_emulator.sh
  google/cloud/bigtable/examples/run_examples_production.sh
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/tests/run_integration_tests_emulator.sh
  google/cloud/ci/run_integration_tests.sh
  google/cloud/examples/run_gcs2cbt_emulator.sh
  google/cloud/storage/benchmarks/run_benchmarks_testbench.sh
  google/cloud/storage/ci/run_integration_tests.sh
  google/cloud/storage/examples/run_examples_production.sh
  google/cloud/storage/examples/run_examples_testbench.sh
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/tests/run_integration_tests_production.sh
  google/cloud/storage/tests/run_integration_tests_testbench.sh
  google/cloud/storage/tools/run_testbench_utils.sh
Labels: cla: yes

#2472 Enable ShellCheck in check-style.sh
  ci/check-style.sh
  ci/travis/Dockerfile.ubuntu
  ci/travis/Dockerfile.ubuntu-install
Labels: cla: yes

#2479 Purge some newly-introduced trailing whitespace
  README.md
  doc/managing-dependencies-in-cmake.md
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/storage/examples/run_examples_utils.sh
Labels: cla: yes

#2478 Add v0.8.1 release notes
  google/cloud/README.md
  google/cloud/bigtable/README.md
Labels: cla: yes

#2481 Implement GC rule examples.
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/examples/table_admin_snippets.cc
Labels: cla: yes

#2465 Fix a race condition in MutationBatcher.
  google/cloud/bigtable/mutation_batcher.cc
Labels: cla: yes

#2477 Adds spanner_tool for easy experimenting
  bazel/googleapis.BUILD
  google/cloud/spanner/BUILD
  google/cloud/spanner/spanner_tool.cc
Labels: cla: yes

#2430 Improve README for storage client.
  README.md
  google/cloud/storage/README.md
Labels: api: storage, cla: yes, type: docs

#2474 Fix portability/logical errors in shell scripts.
  ci/check-style.sh
  ci/coverity-scan.sh
  ci/install-retry.sh
  ci/test-readme/dockerfile2markdown.sh
  ci/travis/build-docker.sh
  ci/travis/dump-reports.sh
  google/cloud/bigtable/ci/run_integration_tests.sh
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/tools/run_testbench_utils.sh
Labels: cla: yes

#2480 Support P12 key files.
  ci/kokoro/ubuntu/build.sh
  ci/kokoro/ubuntu/continuous.cfg
  ci/kokoro/ubuntu/presubmit.cfg
  google/cloud/storage/doc/setup-test-resources.md
  google/cloud/storage/oauth2/google_credentials.cc
  google/cloud/storage/oauth2/google_credentials.h
  google/cloud/storage/oauth2/service_account_credentials.cc
  google/cloud/storage/oauth2/service_account_credentials.h
  google/cloud/storage/oauth2/service_account_credentials_test.cc
  google/cloud/storage/tests/CMakeLists.txt
  google/cloud/storage/tests/key_file_integration_test.cc
  google/cloud/storage/tests/run_integration_tests_production.sh
  google/cloud/storage/tests/storage_client_integration_tests.bzl
Labels: api: storage, cla: yes

#2482 Reimplement AsyncListInstances via futures.
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/async_list_instances_test.cc
  google/cloud/bigtable/bigtable_client_unit_tests.bzl
  google/cloud/bigtable/instance_admin.cc
Labels: cla: yes

#2475 Declare and assign local variables separately.
  ci/define-example-runner.sh
  ci/kokoro/docker/build.sh
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/storage/examples/run_examples_utils.sh
Labels: cla: yes

#2484 Implementation of `TableAdmin::AsyncDropAllRows`
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/examples/table_admin_async_snippets.cc
  google/cloud/bigtable/table_admin.cc
  google/cloud/bigtable/table_admin.h
  google/cloud/bigtable/tests/admin_async_future_integration_test.cc
Labels: cla: yes

#2487 Support P12 files in GoogleDefaultCredentials().
  google/cloud/storage/oauth2/google_credentials.cc
  google/cloud/storage/oauth2/google_credentials_test.cc
  google/cloud/storage/tests/run_integration_tests_production.sh
Labels: api: storage, cla: yes

#2490 Bypass creating real alarms in MockCompletionQueue
  google/cloud/bigtable/completion_queue.cc
Labels: cla: yes

#2488 The Google Cloud Storage C++ client library is GA.
  README.md
  ci/check-abi.sh
  ci/test-abi/google_cloud_cpp_common.expected.abi.dump.gz
  ci/test-abi/storage_client.expected.abi.dump.gz
  ci/travis/build-docker.sh
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/README.md
  google/cloud/storage/doc/storage-main.dox
  google/cloud/storage/storage_client_version.bzl
Labels: api: storage, cla: yes

#2483 Reimplement AsyncListClusters with futures.
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/async_list_clusters_test.cc
  google/cloud/bigtable/bigtable_client_unit_tests.bzl
  google/cloud/bigtable/instance_admin.cc
Labels: cla: yes

#2485 Update the README for Cloud Bigtable.
  google/cloud/bigtable/README.md
Labels: api: bigtable, cla: yes, type: docs

#2491 Implement InstanceAdmin::AsyncListAppProfiles.
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/async_list_app_profiles_test.cc
  google/cloud/bigtable/bigtable_client_unit_tests.bzl
  google/cloud/bigtable/examples/instance_admin_async_snippets.cc
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
Labels: cla: yes

#2486 Support compiling spanner_tool with CMake.
  cmake/external/googleapis.cmake
  cmake/external/googleapis/CMakeLists.txt
  cmake/external/googleapis/config.cmake.in
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/spanner_tool.cc
Labels: cla: yes

#2492 Implement bigtable_get_family_metadata example.
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/examples/table_admin_snippets.cc
Labels: api: bigtable, cla: yes

#2493 Moves enablers to LHS of assignment to prevent callers specifying.
  google/cloud/bigtable/mutations.h
  google/cloud/internal/invoke_result.h
Labels: cla: yes

#2494 Implement InstanceAdmin::AsyncCreateInstance.
  google/cloud/bigtable/examples/instance_admin_async_snippets.cc
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/instance_admin_client.h
  google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
Labels: cla: yes

#2476 Put quotes around variables where necessary.
  ci/build-jenkins.sh
  ci/check-style.sh
  ci/coverity-scan.sh
  ci/define-example-runner.sh
  ci/kokoro/install/build.sh
  ci/kokoro/ubuntu/build.sh
  ci/travis/build-docker.sh
  ci/travis/install-linux.sh
  ci/travis/upload-codecov.sh
  ci/travis/upload-docs.sh
  google/cloud/bigtable/examples/run_examples_emulator.sh
  google/cloud/bigtable/examples/run_examples_production.sh
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/examples/table_admin_snippets.cc
  google/cloud/bigtable/tests/run_integration_tests_emulator.sh
  google/cloud/bigtable/tools/run_emulator_utils.sh
  google/cloud/ci/run_integration_tests.sh
  google/cloud/storage/benchmarks/run_benchmarks_testbench.sh
  google/cloud/storage/examples/run_examples_utils.sh
Labels: cla: yes

#2495 Implement InstanceAdmin::AsyncCreateCluster.
  google/cloud/bigtable/examples/instance_admin_async_snippets.cc
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
Labels: cla: yes

#2512 Implement InstanceAdmin::AsyncUpdateInstance.
  google/cloud/bigtable/examples/instance_admin_async_snippets.cc
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
Labels: cla: yes

#2515 Fix new ShellCheck warnings.
  ci/check-abi.sh
Labels: cla: yes, type: cleanup

#2518 Refactor Table::*ReadModifyWriteRow().
  google/cloud/bigtable/examples/data_async_snippets.cc
  google/cloud/bigtable/table.cc
  google/cloud/bigtable/table.h
  google/cloud/bigtable/tests/data_async_future_integration_test.cc
Labels: api: bigtable, cla: yes

#2517 Add links to best practices for bucket policy only.
  google/cloud/storage/bucket_metadata.h
  google/cloud/storage/client.h
Labels: api: storage, cla: yes

#2514 Implement remaining column family examples.
  ci/define-example-runner.sh
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/examples/table_admin_snippets.cc
Labels: api: bigtable, cla: yes

#2519 Coalesce the separated #include blocks
  google/cloud/bigtable/column_family.h
Labels: cla: yes

#2521 Fix chocolately link. [skip ci]
  README.md
Labels: cla: yes

#2523 Implement remaining bigtable_read_* samples.
  google/cloud/bigtable/examples/data_snippets.cc
  google/cloud/bigtable/examples/run_examples_utils.sh
Labels: api: bigtable, cla: yes

#2522 Check for (and fix) whitespace formatting in non-C++ files
  ci/check-style.sh
  ci/travis/build-docker.sh
  google/cloud/bigtable/README.md
  google/cloud/storage/README.md
Labels: cla: yes

#2526 Restore code coverage uploads.
  ci/travis/upload-codecov.sh
Labels: cla: yes

#2516 Implement InstanceAdmin::AsyncUpdateAppProfile.
  google/cloud/bigtable/examples/instance_admin_async_snippets.cc
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
Labels: cla: yes

#2527 implementation of `TableAdmin::AsyncListTables`
  google/cloud/bigtable/admin_client.cc
  google/cloud/bigtable/admin_client.h
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/examples/table_admin_async_snippets.cc
  google/cloud/bigtable/table_admin.cc
  google/cloud/bigtable/table_admin.h
  google/cloud/bigtable/testing/inprocess_admin_client.cc
  google/cloud/bigtable/testing/inprocess_admin_client.h
  google/cloud/bigtable/testing/mock_admin_client.h
  google/cloud/bigtable/tests/admin_async_future_integration_test.cc
Labels: cla: yes

#2528 Fix typos and comments in the CompletionQueue test.
  google/cloud/bigtable/completion_queue_test.cc
Labels: api: bigtable, cla: yes, type: cleanup

#2529 Support move-only callables in future<T>.
  google/cloud/future_generic_then_test.cc
  google/cloud/future_void_then_test.cc
  google/cloud/internal/future_then_impl.h
Labels: cla: yes

#2531 Remove AsyncFutureFromCallback.
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/bigtable_client.bzl
  google/cloud/bigtable/bigtable_client_unit_tests.bzl
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/internal/async_future_from_callback.cc
  google/cloud/bigtable/internal/async_future_from_callback.h
  google/cloud/bigtable/internal/async_future_from_callback_test.cc
  google/cloud/bigtable/table.cc
  google/cloud/bigtable/table_admin.cc
Labels: cla: yes

#2530 Adding `AsyncGenerateConsistencyToken` and `AsyncCheckConsistency` to `TableAdmin`.
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/examples/table_admin_async_snippets.cc
  google/cloud/bigtable/table_admin.cc
  google/cloud/bigtable/table_admin.h
  google/cloud/bigtable/testing/table_integration_test.cc
  google/cloud/bigtable/tests/admin_async_future_integration_test.cc
  google/cloud/bigtable/tests/run_integration_tests_emulator.sh
Labels: cla: yes

#2532 Add the "IncludeBlocks: Merge" clang-format option
  .clang-format
  google/cloud/bigtable/cell.h
  google/cloud/bigtable/cell_test.cc
  google/cloud/bigtable/data_client_test.cc
  google/cloud/bigtable/row_set_test.cc
  google/cloud/storage/client_sign_policy_document_test.cc
  google/cloud/storage/examples/storage_bucket_samples.cc
  google/cloud/storage/oauth2/google_credentials.cc
  google/cloud/storage/oauth2/refreshing_credentials_wrapper.cc
  google/cloud/storage/oauth2/service_account_credentials.cc
  google/cloud/storage/tests/key_file_integration_test.cc
Labels: cla: yes

#2535 Move to clang-format-7
  CONTRIBUTING.md
  ci/travis/Dockerfile.ubuntu
  ci/travis/Dockerfile.ubuntu-install
  doc/setup-development-environment.md
  google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc
  google/cloud/bigtable/examples/bigtable_samples_instance_admin.cc
  google/cloud/bigtable/examples/data_snippets.cc
  google/cloud/bigtable/examples/table_admin_snippets.cc
  google/cloud/storage/examples/storage_bucket_acl_samples.cc
  google/cloud/storage/examples/storage_bucket_iam_samples.cc
  google/cloud/storage/examples/storage_bucket_samples.cc
  google/cloud/storage/examples/storage_default_object_acl_samples.cc
  google/cloud/storage/examples/storage_notification_samples.cc
  google/cloud/storage/examples/storage_object_acl_samples.cc
  google/cloud/storage/examples/storage_object_samples.cc
  google/cloud/storage/examples/storage_service_account_samples.cc
Labels: cla: yes

#2533 Wrap streaming read RPC loop.
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/async_read_stream_test.cc
  google/cloud/bigtable/bigtable_client.bzl
  google/cloud/bigtable/bigtable_client_unit_tests.bzl
  google/cloud/bigtable/completion_queue.h
  google/cloud/bigtable/internal/async_read_stream_impl.h
Labels: api: bigtable, cla: yes

#2536 Rename AsyncBulkApply support classes.
  google/cloud/bigtable/data_client.h
  google/cloud/bigtable/internal/async_bulk_apply.h
  google/cloud/bigtable/internal/bulk_mutator.h
  google/cloud/bigtable/internal/bulk_mutator_test.cc
  google/cloud/bigtable/internal/table.h
Labels: api: bigtable, cla: yes

#2539 Fix noex build and improve build logs.
  ci/install-retry.sh
  ci/travis/Dockerfile.ubuntu
Labels: cla: yes

#2542 Fix Ubuntu build by disabling the HMAC Key tests in production.
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/tests/run_integration_tests_production.sh
Labels: api: storage, cla: yes

#2534 Remove Snapshot-related functions, tests, examples, etc.
  google/cloud/bigtable/admin_client.cc
  google/cloud/bigtable/admin_client.h
  google/cloud/bigtable/bigtable_strong_types.h
  google/cloud/bigtable/examples/table_admin_snippets.cc
  google/cloud/bigtable/internal/table_admin.cc
  google/cloud/bigtable/internal/table_admin.h
  google/cloud/bigtable/internal/table_admin_test.cc
  google/cloud/bigtable/metadata_update_policy.cc
  google/cloud/bigtable/metadata_update_policy.h
  google/cloud/bigtable/metadata_update_policy_test.cc
  google/cloud/bigtable/table.h
  google/cloud/bigtable/table_admin.cc
  google/cloud/bigtable/table_admin.h
  google/cloud/bigtable/table_admin_test.cc
  google/cloud/bigtable/testing/embedded_server_test_fixture.h
  google/cloud/bigtable/testing/inprocess_admin_client.cc
  google/cloud/bigtable/testing/inprocess_admin_client.h
  google/cloud/bigtable/testing/mock_admin_client.h
  google/cloud/bigtable/tests/CMakeLists.txt
  google/cloud/bigtable/tests/bigtable_client_integration_tests.bzl
  google/cloud/bigtable/tests/run_integration_tests_emulator.sh
  google/cloud/bigtable/tests/snapshot_async_integration_test.cc
  google/cloud/bigtable/tests/snapshot_integration_test.cc
Labels: cla: yes

#2538 Refactor BulkMutator state to a separate class.
  google/cloud/bigtable/internal/bulk_mutator.cc
  google/cloud/bigtable/internal/bulk_mutator.h
  google/cloud/bigtable/internal/bulk_mutator_test.cc
  google/cloud/bigtable/internal/table.cc
  google/cloud/bigtable/table.cc
Labels: api: bigtable, cla: yes

#2544 New implementation of Table::BulkApply().
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/bigtable_client.bzl
  google/cloud/bigtable/data_client.cc
  google/cloud/bigtable/data_client.h
  google/cloud/bigtable/internal/async_bulk_apply.cc
  google/cloud/bigtable/internal/async_bulk_apply.h
  google/cloud/bigtable/table.cc
  google/cloud/bigtable/testing/inprocess_data_client.cc
  google/cloud/bigtable/testing/inprocess_data_client.h
  google/cloud/bigtable/testing/mock_data_client.h
Labels: cla: yes

#2548 Fix race condition in async_read_stream_test.
  google/cloud/bigtable/async_read_stream_test.cc
Labels: api: bigtable, cla: yes

#2547 Implement examples for Apply() and BulkApply().
  google/cloud/bigtable/examples/data_snippets.cc
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/table.h
Labels: api: bigtable, cla: yes

#2549 Fix exit status in examples runner.
  ci/define-example-runner.sh
  google/cloud/bigtable/examples/run_examples_emulator.sh
  google/cloud/bigtable/examples/run_examples_production.sh
  google/cloud/storage/examples/run_examples_production.sh
  google/cloud/storage/examples/run_examples_testbench.sh
Labels: cla: yes

#2546 Implement AsyncTestIamPermissions.
  google/cloud/bigtable/examples/instance_admin_async_snippets.cc
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/instance_admin_client.cc
  google/cloud/bigtable/instance_admin_client.h
  google/cloud/bigtable/instance_admin_test.cc
  google/cloud/bigtable/testing/mock_instance_admin_client.h
  google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
Labels: cla: yes

#2550 Reimplement AsyncDeleteCluster.
  google/cloud/bigtable/examples/instance_admin_async_snippets.cc
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/instance_admin_test.cc
  google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
Labels: cla: yes

#2566 Cleanup the InstanceAdmin snippets.
  google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc
Labels: api: bigtable, cla: yes, type: cleanup

#2555 Implement InstanceAdmin::AsyncGetIamPolicy.
  google/cloud/bigtable/examples/instance_admin_async_snippets.cc
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/instance_admin_test.cc
  google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
Labels: cla: yes

#2551 Implement InstanceAdmin::AsyncCreateAppProfile.
  google/cloud/bigtable/examples/instance_admin_async_snippets.cc
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
Labels: cla: yes

#2552 Implement InstanceAdmin::AsyncGetAppProfile.
  google/cloud/bigtable/examples/instance_admin_async_snippets.cc
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
Labels: cla: yes

#2568 Preserve timestamps for unchanged files.
  ci/check-style.sh
Labels: cla: yes

#2570 Remove invalid region tags.
  google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc
  google/cloud/bigtable/examples/bigtable_samples.cc
  google/cloud/bigtable/examples/bigtable_samples_instance_admin.cc
  google/cloud/bigtable/examples/data_snippets.cc
  google/cloud/bigtable/examples/table_admin_snippets.cc
Labels: api: bigtable, cla: yes, type: cleanup

#2553 Implement InstanceAdmin::AsyncDeleteAppProfile.
  google/cloud/bigtable/examples/instance_admin_async_snippets.cc
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
Labels: cla: yes

#2575 Consistently use namespace aliases in examples.
  google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc
  google/cloud/bigtable/examples/data_async_snippets.cc
  google/cloud/bigtable/examples/data_snippets.cc
  google/cloud/bigtable/examples/instance_admin_async_snippets.cc
  google/cloud/bigtable/examples/table_admin_async_snippets.cc
  google/cloud/bigtable/examples/table_admin_snippets.cc
Labels: cla: yes

#2574 Return google::cloud::future from InstanceAdmin functions.
  google/cloud/bigtable/examples/bigtable_samples_instance_admin.cc
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/instance_admin_test.cc
Labels: api: bigtable, cla: yes

#2576 Add bigtable_delete_rows region tag.
  google/cloud/bigtable/examples/table_admin_snippets.cc
Labels: api: bigtable, cla: yes

#2577 Use the bigtable_get_table_metadata region tag.
  google/cloud/bigtable/examples/table_admin_snippets.cc
Labels: api: bigtable, cla: yes

#2571 Implement InstanceAdmin::AsyncSetIamPolicy.
  google/cloud/bigtable/examples/instance_admin_async_snippets.cc
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/instance_admin_client.cc
  google/cloud/bigtable/instance_admin_client.h
  google/cloud/bigtable/instance_admin_test.cc
  google/cloud/bigtable/testing/mock_instance_admin_client.h
  google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
Labels: cla: yes

#2582 Implement bigtable_get_or_create_family example.
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/examples/table_admin_snippets.cc
Labels: api: bigtable, cla: yes

#2580 Implement bigtable_list_column_families sample.
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/examples/table_admin_snippets.cc
Labels: api: bigtable, cla: yes

#2569 Spanner experiments
  google/cloud/spanner/BUILD
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/spanner_tool.cc
Labels: api: spanner, cla: yes

#2578 Prevent transient problems from breaking production test.
  google/cloud/bigtable/tests/data_integration_test.cc
Labels: api: bigtable, cla: yes
