Repository googleapis/google-cloud-cpp, pull requests merged in 2019-03, with the labels that each got.

#2125 Fix name of openSUSE Tumbleweed image.
  ci/test-readme/Dockerfile.opensuse
Labels: cla: yes

#2118 Use StatusOr<> in `ReadRows`
  google/cloud/bigtable/examples/bigtable_hello_app_profile.cc
  google/cloud/bigtable/examples/bigtable_hello_world.cc
  google/cloud/bigtable/examples/data_snippets.cc
  google/cloud/bigtable/examples/opencensus/bigtable_opencensus.cc
  google/cloud/bigtable/internal/rowreaderiterator.cc
  google/cloud/bigtable/internal/rowreaderiterator.h
  google/cloud/bigtable/internal/table.cc
  google/cloud/bigtable/internal/table.h
  google/cloud/bigtable/internal/table_test.cc
  google/cloud/bigtable/row_reader.cc
  google/cloud/bigtable/row_reader.h
  google/cloud/bigtable/row_reader_test.cc
  google/cloud/bigtable/table.cc
  google/cloud/bigtable/table_readrows_test.cc
  google/cloud/bigtable/testing/table_integration_test.cc
  google/cloud/bigtable/tests/data_integration_test.cc
Labels: cla: yes

#2122 Remove Travis build for shared libs.
  .travis.yml
Labels: cla: yes

#2123 A build for google-cloud-cpp as dependency.
  ci/kokoro/bazel-dependency/linux/build.sh
  ci/kokoro/bazel-dependency/linux/continuous.cfg
  ci/kokoro/bazel-dependency/linux/presubmit.cfg
Labels: cla: yes

#2124 Rename SignUrlRequest to V2SignUrlRequest.
  google/cloud/storage/client.cc
  google/cloud/storage/client.h
  google/cloud/storage/internal/signed_url_requests.cc
  google/cloud/storage/internal/signed_url_requests.h
  google/cloud/storage/internal/signed_url_requests_test.cc
Labels: api: storage, cla: yes

#2126 Fix Kokoro build for integration tests.
  ci/kokoro/bazel-dependency/linux/build.sh
  ci/kokoro/macos/build.sh
  ci/kokoro/ubuntu/build.sh
Labels: cla: yes

#2127 Use new location for openSUSE:Leap Docker images.
  INSTALL.md
  README.md
  ci/test-readme/Dockerfile.opensuse-leap
Labels: cla: yes

#2129 Support different RSA-SHA256 signature formats.
  google/cloud/storage/internal/openssl_util.cc
  google/cloud/storage/internal/openssl_util.h
  google/cloud/storage/oauth2/service_account_credentials.h
Labels: api: storage, cla: yes

#2108 Change bigtable::FailedMutation to work with google::cloud::Status
  google/cloud/bigtable/internal/bulk_mutator.cc
  google/cloud/bigtable/internal/bulk_mutator_test.cc
  google/cloud/bigtable/mutation_batcher.cc
  google/cloud/bigtable/mutations.cc
  google/cloud/bigtable/mutations.h
  google/cloud/bigtable/mutations_test.cc
  google/cloud/bigtable/table.cc
Labels: api: bigtable, cla: yes

#2128 Implement V4SignedUrlRequest.
  google/cloud/storage/internal/signed_url_requests.cc
  google/cloud/storage/internal/signed_url_requests.h
  google/cloud/storage/internal/signed_url_requests_test.cc
  google/cloud/storage/signed_url_options.h
Labels: api: storage, cla: yes

#2134 Fix linter warnings.
  google/cloud/storage/internal/curl_wrappers.cc
Labels: cla: yes

#2137 Remove as-bazel-dependency build.
  .travis.yml
Labels: cla: yes

#2136 Retry the docker setup in the Kokoro builds.
  ci/kokoro/docker/build.sh
Labels: cla: yes

#2138 Use gcloud SDK to get cbt tool.
  ci/kokoro/ubuntu/build.sh
Labels: cla: yes

#2132 Implement make_ready_future().
  google/cloud/future_generic.h
  google/cloud/future_generic_then_test.cc
  google/cloud/future_void.h
  google/cloud/future_void_then_test.cc
  google/cloud/internal/future_then_meta.h
Labels: cla: yes

#2141 Remove OpenSslUtils struct.
  google/cloud/storage/hashing_options.cc
  google/cloud/storage/internal/hash_validator.cc
  google/cloud/storage/internal/openssl_util.cc
  google/cloud/storage/internal/openssl_util.h
  google/cloud/storage/oauth2/service_account_credentials.h
  google/cloud/storage/well_known_headers.cc
Labels: cla: yes, type: cleanup

#2143 Refactor Base64Encode() implementation.
  google/cloud/storage/internal/openssl_util.cc
Labels: api: storage, cla: yes, type: cleanup

#2142 Update release notes.
  google/cloud/README.md
  google/cloud/bigtable/README.md
  google/cloud/storage/README.md
Labels: cla: yes

#2139 Add estimated_size_in_bytes() accessor to BulkMutation
  google/cloud/bigtable/mutations.h
Labels: api: bigtable, cla: yes

#2147 Remove unnecessary casts.
  google/cloud/storage/internal/openssl_util.cc
Labels: api: storage, cla: yes

#2149 Bump versions in master to be one greater than the current release
  google/cloud/CMakeLists.txt
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/bigtable_client_version.bzl
  google/cloud/google_cloud_cpp_common_version.bzl
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/storage_client_version.bzl
Labels: cla: yes

#2150 Implement class to represent HMAC key resources.
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/hmac_key_metadata.cc
  google/cloud/storage/hmac_key_metadata.h
  google/cloud/storage/hmac_key_metadata_test.cc
  google/cloud/storage/internal/hmac_key_requests.cc
  google/cloud/storage/internal/hmac_key_requests.h
  google/cloud/storage/internal/hmac_key_requests_test.cc
  google/cloud/storage/storage_client.bzl
  google/cloud/storage/storage_client_unit_tests.bzl
Labels: api: storage, cla: yes

#2151 Refactor function to create Base64 BIO chains.
  google/cloud/storage/internal/openssl_util.cc
Labels: api: storage, cla: yes

#2152 Refactor GCS project components in the testbench.
  google/cloud/storage/testbench/gcs_bucket.py
  google/cloud/storage/testbench/gcs_object.py
  google/cloud/storage/testbench/gcs_project.py
  google/cloud/storage/testbench/testbench.py
Labels: api: storage, cla: yes

#2153 Simplify Base64Encode() implementation.
  google/cloud/storage/internal/openssl_util.cc
Labels: api: storage, cla: yes, type: cleanup

#2130 Implement V4 signed URLs.
  google/cloud/storage/client.cc
  google/cloud/storage/client.h
  google/cloud/storage/client_sign_url_test.cc
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_object_samples.cc
Labels: api: storage, cla: yes

#2156 Implement `HmacKeys: insert` in testbench.
  google/cloud/storage/testbench/gcs_project.py
Labels: api: storage, cla: yes

#2154 Better return type for Base64Decode.
  google/cloud/storage/internal/openssl_util.cc
  google/cloud/storage/internal/openssl_util.h
  google/cloud/storage/internal/sha256_hash.cc
  google/cloud/storage/internal/sha256_hash.h
  google/cloud/storage/well_known_headers.cc
Labels: api: storage, cla: yes, type: cleanup

#2155 Update check-abi script.
  ci/check-abi.sh
Labels: cla: yes, type: process

#2165 Save some space in the Travis log.
  .travis.yml
  ci/travis/dump-logs.sh
  ci/travis/dump-reports.sh
Labels: cla: yes, type: cleanup, type: process

#2164 Refactor service account examples.
  google/cloud/storage/client.h
  google/cloud/storage/examples/BUILD
  google/cloud/storage/examples/CMakeLists.txt
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_bucket_samples.cc
  google/cloud/storage/examples/storage_service_account_samples.cc
Labels: api: storage, cla: yes

#2157 Implement CreateHmacKey{Request,Response}.
  google/cloud/storage/internal/hmac_key_requests.cc
  google/cloud/storage/internal/hmac_key_requests.h
  google/cloud/storage/internal/hmac_key_requests_test.cc
Labels: api: storage, cla: yes

#2135 Return vector<FailedMutation> for Table::BulkApply()
  google/cloud/bigtable/benchmarks/benchmark.cc
  google/cloud/bigtable/benchmarks/embedded_server_test.cc
  google/cloud/bigtable/examples/data_snippets.cc
  google/cloud/bigtable/table.cc
  google/cloud/bigtable/table.h
  google/cloud/bigtable/table_bulk_apply_test.cc
  google/cloud/bigtable/testing/table_integration_test.cc
  google/cloud/bigtable/tests/data_async_integration_test.cc
  google/cloud/bigtable/tests/data_integration_test.cc
  google/cloud/bigtable/tests/filters_integration_test.cc
  google/cloud/bigtable/tests/mutations_integration_test.cc
Labels: api: bigtable, cla: yes

#2170 Implement Requests for `HmacKeys: list`.
  google/cloud/storage/internal/hmac_key_requests.cc
  google/cloud/storage/internal/hmac_key_requests.h
  google/cloud/storage/internal/hmac_key_requests_test.cc
  google/cloud/storage/well_known_parameters.h
Labels: api: storage, cla: yes

#2172 Statusor for readrowparser test
  google/cloud/bigtable/internal/readrowsparser_acceptance_tests.inc
  google/cloud/bigtable/internal/readrowsparser_test.cc
  google/cloud/bigtable/tools/convert_acceptance_tests.py
Labels: cla: yes

#2167 Implement Client::CreateHmacKey.
  google/cloud/storage/client.h
  google/cloud/storage/client_service_account_test.cc
  google/cloud/storage/idempotency_policy.cc
  google/cloud/storage/idempotency_policy.h
  google/cloud/storage/idempotency_policy_test.cc
  google/cloud/storage/internal/curl_client.cc
  google/cloud/storage/internal/curl_client.h
  google/cloud/storage/internal/curl_client_test.cc
  google/cloud/storage/internal/logging_client.cc
  google/cloud/storage/internal/logging_client.h
  google/cloud/storage/internal/raw_client.h
  google/cloud/storage/internal/retry_client.cc
  google/cloud/storage/internal/retry_client.h
  google/cloud/storage/testing/mock_client.h
  google/cloud/storage/tests/run_integration_tests_production.sh
  google/cloud/storage/tests/run_integration_tests_testbench.sh
  google/cloud/storage/tests/service_account_integration_test.cc
Labels: api: storage, cla: yes

#2180 Fix region tag for one example.
  google/cloud/storage/examples/storage_bucket_samples.cc
Labels: api: storage, cla: yes

#2169 Remove Mutation body from FailedMutation
  google/cloud/bigtable/internal/bulk_mutator.cc
  google/cloud/bigtable/internal/bulk_mutator_test.cc
  google/cloud/bigtable/internal/table.cc
  google/cloud/bigtable/internal/table_async_bulk_apply_test.cc
  google/cloud/bigtable/internal/table_test.cc
  google/cloud/bigtable/mutations.h
  google/cloud/bigtable/mutations_test.cc
  google/cloud/bigtable/table_bulk_apply_test.cc
Labels: cla: yes

#2179 Properly handle files with spaces.
  ci/travis/dump-reports.sh
Labels: cla: yes

#2168 Do not throw exceptions from ClientOptions.
  google/cloud/bigtable/client_options.cc
  google/cloud/bigtable/client_options.h
  google/cloud/bigtable/client_options_test.cc
  google/cloud/storage/client_options.h
Labels: cla: yes

#2171 Refactor List{Object,Bucket}Reader classes.
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/client.h
  google/cloud/storage/internal/range_from_pagination.h
  google/cloud/storage/list_buckets_reader.cc
  google/cloud/storage/list_buckets_reader.h
  google/cloud/storage/list_buckets_reader_test.cc
  google/cloud/storage/list_objects_reader.cc
  google/cloud/storage/list_objects_reader.h
  google/cloud/storage/list_objects_reader_test.cc
  google/cloud/storage/storage_client.bzl
Labels: api: storage, cla: yes

#2184 Eliminate TABs from source files
  google/cloud/bigtable/table_admin_test.cc
  google/cloud/bigtable/table_readmodifywriterow_test.cc
Labels: cla: yes

#2187 Remove trailing whitespace
  CONTRIBUTING.md
  README.md
  doc/adr/2018-06-18-storage-request-parameters-are-function-arguments.md
  doc/adr/2018-10-30-storage-metadata-fields-and-optional.md
  doc/managing-dependencies-in-cmake.md
  doc/setup-development-environment.md
  google/cloud/README.md
  google/cloud/bigtable/README.md
  google/cloud/bigtable/doc/bigtable-main.dox
  google/cloud/bigtable/doc/bigtable-samples-data-client.dox
  google/cloud/bigtable/doc/bigtable-samples-instance-admin.dox
  google/cloud/bigtable/examples/README.md
  google/cloud/bigtable/examples/opencensus/README.md
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/table_admin_test.cc
  google/cloud/bigtable/tests/run_integration_tests_emulator.sh
  google/cloud/bigtable/tools/generate_rpc_policy_parameters.py
  google/cloud/firestore/README.md
  google/cloud/firestore/firestore_client.pc
Labels: cla: yes

#2189 Handle object names with slashes.
  google/cloud/storage/testbench/testbench.py
Labels: api: storage, cla: yes

#2193 Improve error messages in {Upload,Download}File.
  google/cloud/storage/client.cc
Labels: cla: yes

#2195 Kokoro support to run ABI checks.
  ci/check-abi.sh
  ci/kokoro/docker/build.sh
  ci/kokoro/docker/check-abi-presubmit.cfg
  ci/kokoro/docker/check-abi.cfg
  ci/travis/build-docker.sh
Labels: cla: yes, type: process

#2190 Implement ListHmacKeysReader and friends.
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/idempotency_policy.cc
  google/cloud/storage/idempotency_policy.h
  google/cloud/storage/idempotency_policy_test.cc
  google/cloud/storage/internal/curl_client.cc
  google/cloud/storage/internal/curl_client.h
  google/cloud/storage/internal/curl_client_test.cc
  google/cloud/storage/internal/hmac_key_requests.cc
  google/cloud/storage/internal/hmac_key_requests_test.cc
  google/cloud/storage/internal/logging_client.cc
  google/cloud/storage/internal/logging_client.h
  google/cloud/storage/internal/raw_client.h
  google/cloud/storage/internal/retry_client.cc
  google/cloud/storage/internal/retry_client.h
  google/cloud/storage/list_hmac_keys_reader.cc
  google/cloud/storage/list_hmac_keys_reader.h
  google/cloud/storage/list_hmac_keys_reader_test.cc
  google/cloud/storage/storage_client.bzl
  google/cloud/storage/storage_client_unit_tests.bzl
  google/cloud/storage/testing/mock_client.h
Labels: api: storage, cla: yes

#2197 Fix trivial typo.
  google/cloud/storage/internal/bucket_requests_test.cc
Labels: cla: yes

#2185 Add Client::CreateHmacKey examples.
  google/cloud/storage/client.h
  google/cloud/storage/examples/run_examples_testbench.sh
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_service_account_samples.cc
Labels: api: storage, cla: yes

#2198 Add `HmacKeys: list` API to the testbench.
  google/cloud/storage/testbench/gcs_project.py
Labels: api: storage, cla: yes

#2199 Refactor HmacKey requests.
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/client.h
  google/cloud/storage/client_service_account_test.cc
  google/cloud/storage/examples/storage_service_account_samples.cc
  google/cloud/storage/internal/hmac_key_requests.cc
  google/cloud/storage/internal/hmac_key_requests.h
  google/cloud/storage/internal/hmac_key_requests_test.cc
  google/cloud/storage/override_default_project.h
  google/cloud/storage/storage_client.bzl
  google/cloud/storage/tests/service_account_integration_test.cc
Labels: api: storage, cla: yes, type: cleanup

#2191 Moving noex::TableAdmin::CreateTable to TableAdmin::CreateTable
  google/cloud/bigtable/table_admin.cc
Labels: api: bigtable, cla: yes

#2202 Mention pushing the release to Microsoft vcpkg
  doc/cutting-a-release.md
Labels: cla: yes

#2201 Examples and integration test for ListHmacKeys().
  google/cloud/storage/client.h
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_service_account_samples.cc
  google/cloud/storage/tests/service_account_integration_test.cc
Labels: cla: yes

#2183 Create an example listing objects with a prefix.
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_object_samples.cc
Labels: cla: yes

#2204 Fix comparison functions
  google/cloud/storage/internal/access_control_common.h
  google/cloud/storage/lifecycle_rule.h
  google/cloud/storage/object_metadata.h
Labels: cla: yes

#2205 moving GetTable, ListTables and DeleteTable from noex::TableAdmin to TableAdmin
  google/cloud/bigtable/table_admin.cc
  google/cloud/bigtable/table_admin.h
Labels: api: bigtable, cla: yes

#2196 Remove noex::Table::ReadRow()
  google/cloud/bigtable/table.cc
  google/cloud/bigtable/table.h
Labels: cla: yes

#2206 Implement asynchronous timers with futures.
  google/cloud/bigtable/completion_queue.cc
  google/cloud/bigtable/completion_queue.h
  google/cloud/bigtable/completion_queue_test.cc
Labels: api: bigtable, cla: yes

#2207 Implement Client::DeleteHmacKey
  google/cloud/storage/client.h
  google/cloud/storage/client_service_account_test.cc
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_service_account_samples.cc
  google/cloud/storage/idempotency_policy.cc
  google/cloud/storage/idempotency_policy.h
  google/cloud/storage/idempotency_policy_test.cc
  google/cloud/storage/internal/curl_client.cc
  google/cloud/storage/internal/curl_client.h
  google/cloud/storage/internal/hmac_key_requests.cc
  google/cloud/storage/internal/hmac_key_requests.h
  google/cloud/storage/internal/hmac_key_requests_test.cc
  google/cloud/storage/internal/logging_client.cc
  google/cloud/storage/internal/logging_client.h
  google/cloud/storage/internal/raw_client.h
  google/cloud/storage/internal/retry_client.cc
  google/cloud/storage/internal/retry_client.h
  google/cloud/storage/testbench/gcs_project.py
  google/cloud/storage/testing/mock_client.h
  google/cloud/storage/tests/service_account_integration_test.cc
Labels: api: storage, cla: yes

#2194 Create storage examples for object versioning.
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_bucket_samples.cc
  google/cloud/storage/examples/storage_object_samples.cc
Labels: cla: yes

#2213 Fix version integration test
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/tests/object_integration_test.cc
Labels: cla: yes

#2211 Upgrade grpc to v1.19.1
  bazel/google_cloud_cpp_deps.bzl
  cmake/external/grpc.cmake
Labels: cla: yes

#2210 Remove check-abi build from Travis.
  .travis.yml
Labels: cla: yes, type: cleanup

#2215 Implement Client::GetHmacKey.
  google/cloud/storage/client.h
  google/cloud/storage/client_service_account_test.cc
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_service_account_samples.cc
  google/cloud/storage/idempotency_policy.cc
  google/cloud/storage/idempotency_policy.h
  google/cloud/storage/idempotency_policy_test.cc
  google/cloud/storage/internal/curl_client.cc
  google/cloud/storage/internal/curl_client.h
  google/cloud/storage/internal/hmac_key_requests.cc
  google/cloud/storage/internal/hmac_key_requests.h
  google/cloud/storage/internal/hmac_key_requests_test.cc
  google/cloud/storage/internal/logging_client.cc
  google/cloud/storage/internal/logging_client.h
  google/cloud/storage/internal/raw_client.h
  google/cloud/storage/internal/retry_client.cc
  google/cloud/storage/internal/retry_client.h
  google/cloud/storage/testbench/gcs_project.py
  google/cloud/storage/testing/mock_client.h
  google/cloud/storage/tests/service_account_integration_test.cc
Labels: api: storage, cla: yes

#2222 Fix Kokoro + Windows build.
  ci/kokoro/windows/build-project.ps1
  ci/kokoro/windows/install-dependencies.ps1
Labels: cla: yes

#2217 Fix a couple of issues in README.md under the Windows section
  README.md
Labels: cla: yes

#2218 Implement UpdateHmacKey().
  google/cloud/storage/client.h
  google/cloud/storage/client_service_account_test.cc
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_service_account_samples.cc
  google/cloud/storage/hmac_key_metadata.h
  google/cloud/storage/hmac_key_metadata_test.cc
  google/cloud/storage/idempotency_policy.cc
  google/cloud/storage/idempotency_policy.h
  google/cloud/storage/idempotency_policy_test.cc
  google/cloud/storage/internal/curl_client.cc
  google/cloud/storage/internal/curl_client.h
  google/cloud/storage/internal/hmac_key_requests.cc
  google/cloud/storage/internal/hmac_key_requests.h
  google/cloud/storage/internal/hmac_key_requests_test.cc
  google/cloud/storage/internal/logging_client.cc
  google/cloud/storage/internal/logging_client.h
  google/cloud/storage/internal/raw_client.h
  google/cloud/storage/internal/retry_client.cc
  google/cloud/storage/internal/retry_client.h
  google/cloud/storage/testbench/gcs_project.py
  google/cloud/storage/testing/mock_client.h
  google/cloud/storage/tests/service_account_integration_test.cc
Labels: api: storage, cla: yes

#2227 Fix hmac key snippets
  google/cloud/storage/client.h
  google/cloud/storage/examples/storage_service_account_samples.cc
Labels: api: storage, cla: yes

#2228 Implement examples of lifecycle management.
  google/cloud/storage/examples/storage_bucket_samples.cc
Labels: cla: yes

#2223 Changed to use the latest version of bazel
  ci/install-bazel.sh
  ci/kokoro/bazel-dependency/linux/build.sh
  ci/kokoro/macos/build.sh
  ci/kokoro/ubuntu/build.sh
Labels: cla: yes

#2229 Fix object revision tracking
  google/cloud/storage/testbench/gcs_object.py
Labels: cla: yes

#2230 Initial draft of "flags" for integration tests.
  google/cloud/storage/tests/bucket_integration_test.cc
Labels: cla: yes, type: cleanup

#2233 Explicitly include grpcpp/resource_quota.h
  google/cloud/bigtable/client_options.h
Labels: cla: yes, type: cleanup

#2220 Modify the scripts to update the ABI snapshot.
  ci/check-abi.sh
  ci/kokoro/docker/build.sh
  ci/test-abi/bigtable_client.expected.abi.dump.gz
  ci/test-abi/google_cloud_cpp_common.expected.abi.dump.gz
  ci/test-abi/storage_client.expected.abi.dump.gz
  ci/travis/build-docker.sh
  ci/travis/build-linux.sh
Labels: cla: yes

#2224 Implement simple asynchronous RPCs with futures.
  google/cloud/bigtable/completion_queue.h
  google/cloud/bigtable/completion_queue_test.cc
  google/cloud/bigtable/internal/completion_queue_impl.h
Labels: api: bigtable, cla: yes

#2235 Do not initialize statics in constructors.
  google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
  google/cloud/bigtable/tests/instance_admin_async_integration_test.cc
  google/cloud/bigtable/tests/instance_admin_integration_test.cc
  google/cloud/storage/tests/bucket_integration_test.cc
  google/cloud/storage/tests/curl_resumable_streambuf_integration_test.cc
  google/cloud/storage/tests/curl_resumable_upload_session_integration_test.cc
  google/cloud/storage/tests/object_checksum_integration_test.cc
  google/cloud/storage/tests/object_hash_integration_test.cc
  google/cloud/storage/tests/object_insert_integration_test.cc
  google/cloud/storage/tests/object_integration_test.cc
  google/cloud/storage/tests/object_media_integration_test.cc
  google/cloud/storage/tests/object_resumable_write_integration_test.cc
  google/cloud/storage/tests/object_rewrite_integration_test.cc
  google/cloud/storage/tests/service_account_integration_test.cc
  google/cloud/storage/tests/thread_integration_test.cc
Labels: cla: yes, type: cleanup

#2221 Remove noexTable::CheckAndMutateRow() and ReadRows()
  google/cloud/bigtable/internal/table.h
  google/cloud/bigtable/table.cc
Labels: cla: yes

#2232 Moving more non-Async functions from `noex::TableAdmin` to `TableAdmin`
  google/cloud/bigtable/table_admin.cc
Labels: api: bigtable, cla: yes

#2237 Support g::c::Status in retry and backoff policies.
  google/cloud/bigtable/internal/async_retry_multi_page_test.cc
  google/cloud/bigtable/row_reader_test.cc
  google/cloud/bigtable/rpc_backoff_policy.cc
  google/cloud/bigtable/rpc_backoff_policy.h
  google/cloud/bigtable/rpc_retry_policy.cc
  google/cloud/bigtable/rpc_retry_policy.h
Labels: api: bigtable, cla: yes

#2247 Remove noex::Table::Apply() and BulkApply()
  google/cloud/bigtable/table.cc
Labels: cla: yes

#2240 Moving non Async functions from `noex::TableAdmin` to `TableAdmin`.
  google/cloud/bigtable/table_admin.cc
  google/cloud/bigtable/table_admin.h
Labels: api: bigtable, cla: yes

#2244 Create an example changing object encryption from CSEK to CMEK.
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_object_samples.cc
Labels: cla: yes

#2238 Update gRPC in Dockerfiles and install instructions
  INSTALL.md
  README.md
  ci/test-readme/Dockerfile.centos
  ci/test-readme/Dockerfile.debian
  ci/test-readme/Dockerfile.opensuse-leap
  ci/test-readme/Dockerfile.ubuntu
  ci/test-readme/Dockerfile.ubuntu-trusty
  ci/test-readme/Dockerfile.ubuntu-xenial
  ci/test-readme/generate-install.sh
  ci/travis/Dockerfile.ubuntu-install
Labels: cla: yes

#2248 Disable signals in libcurl.
  google/cloud/storage/internal/curl_download_request.cc
  google/cloud/storage/internal/curl_request.cc
  google/cloud/storage/internal/curl_upload_request.cc
Labels: api: storage, cla: yes

#2241 Moving `noex::InstanceAdmin` functions to `InstanceAdmin`
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/instance_admin.h
Labels: api: bigtable, cla: yes

#2243 Create an example to print the CMEK key in an object.
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_object_samples.cc
Labels: cla: yes

#2251 Moving functions from noex::InstanceAdmin to InstanceAdmin
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/instance_admin.h
Labels: cla: yes

#2252 Implement asynchronous retry loop for simple RPCs.
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/bigtable_client_unit_tests.bzl
  google/cloud/bigtable/internal/async_retry_unary_rpc.h
  google/cloud/bigtable/internal/async_retry_unary_rpc_test.cc
  google/cloud/bigtable/table_admin.cc
  google/cloud/bigtable/table_admin.h
Labels: api: storage, cla: yes

#2257 Fix several region tags.
  google/cloud/storage/examples/storage_bucket_samples.cc
  google/cloud/storage/examples/storage_object_samples.cc
Labels: cla: yes

#2258 Implement TableAdmin::AsyncDeleteTable().
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/examples/table_admin_async_snippets.cc
  google/cloud/bigtable/internal/async_retry_unary_rpc_test.cc
  google/cloud/bigtable/table_admin.cc
  google/cloud/bigtable/table_admin.h
  google/cloud/bigtable/tests/admin_async_future_integration_test.cc
Labels: api: bigtable, cla: yes

#2259 Do not construct an OK grpc::Status with an error message
  google/cloud/bigtable/completion_queue_test.cc
  google/cloud/bigtable/internal/async_check_consistency_test.cc
  google/cloud/bigtable/internal/async_longrunning_op_test.cc
  google/cloud/bigtable/internal/async_retry_unary_rpc_and_poll_test.cc
  google/cloud/bigtable/internal/bulk_mutator_test.cc
  google/cloud/bigtable/internal/table_async_apply_test.cc
  google/cloud/bigtable/internal/table_async_bulk_apply_test.cc
  google/cloud/bigtable/internal/table_async_check_and_mutate_row_test.cc
  google/cloud/bigtable/internal/table_async_row_reader_test.cc
  google/cloud/bigtable/internal/table_async_sample_row_keys_test.cc
  google/cloud/bigtable/internal/table_test.cc
  google/cloud/bigtable/mutation_batcher_test.cc
  google/cloud/bigtable/rpc_retry_policy_test.cc
Labels: cla: yes, type: cleanup

#2261 Break from stream loop early if we encounter an error
  google/cloud/examples/gcs2cbt.cc
  google/cloud/storage/benchmarks/storage_latency_benchmark.cc
  google/cloud/storage/benchmarks/storage_throughput_benchmark.cc
  google/cloud/storage/client_options.cc
  google/cloud/storage/tests/thread_integration_test.cc
  google/cloud/testing_util/capture_log_lines_backend.cc
Labels: cla: yes

#2263 Create examples for bucket static website configuration.
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_bucket_samples.cc
Labels: cla: yes

#2268 Refactor MSVC runtime configuration.
  cmake/GoogleCloudCppCommon.cmake
  cmake/IncludeGrpc.cmake
  cmake/SelectMSVCRuntime.cmake
Labels: cla: yes, type: cleanup

#2270 Use standard name for grpc_cpp_plugin target.
  cmake/CompileProtos.cmake
  cmake/IncludeGrpc.cmake
  cmake/external/grpc.cmake
Labels: cla: yes, type: cleanup

#2269 Write a custom module for find protobuf.
  cmake/FindProtobufTargets.cmake
  cmake/IncludeProtobuf.cmake
Labels: cla: yes, type: cleanup

#2276 Add a FindgRPC module.
  cmake/FindgRPC.cmake
  cmake/IncludeGrpc.cmake
Labels: cla: yes, type: cleanup

#2267 Adding region tag in BigTable C++ client samples for better documentation.
  google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc
  google/cloud/bigtable/examples/bigtable_samples_instance_admin.cc
  google/cloud/bigtable/examples/table_admin_snippets.cc
Labels: cla: yes

#2282 Add some missing dependencies to storage's config.cmake.in
  google/cloud/storage/config.cmake.in
Labels: cla: yes

#2273 Pass NCPU to external projects.
  cmake/ExternalProjectHelper.cmake
  cmake/external/c-ares.cmake
  cmake/external/crc32c.cmake
  cmake/external/curl.cmake
  cmake/external/googletest.cmake
  cmake/external/grpc.cmake
  cmake/external/protobuf.cmake
  cmake/external/zlib.cmake
Labels: cla: yes

#2285 Map curl_easy_perform() errors to StatusCode.
  google/cloud/storage/internal/curl_client_test.cc
  google/cloud/storage/internal/curl_handle.cc
Labels: api: storage, cla: yes

#2280 Create sample for adding CORS configuration to a bucket.
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_bucket_samples.cc
Labels: cla: yes

#2279 Pass CMake flags if we disable testing
  .travis.yml
  ci/kokoro/docker/build.sh
  ci/travis/build-docker.sh
  ci/travis/build-linux.sh
Labels: cla: yes

#2294 Enable presubmit for "test-install" builds.
  ci/kokoro/install/centos-presubmit.cfg
  ci/kokoro/install/debian-presubmit.cfg
  ci/kokoro/install/fedora-presubmit.cfg
  ci/kokoro/install/opensuse-leap-presubmit.cfg
  ci/kokoro/install/opensuse-presubmit.cfg
  ci/kokoro/install/ubuntu-presubmit.cfg
  ci/kokoro/install/ubuntu-trusty-presubmit.cfg
  ci/kokoro/install/ubuntu-xenial-presubmit.cfg
Labels: cla: yes

#2291 Replaced (date +%s) with {RANDOM}
  google/cloud/bigtable/examples/run_examples_emulator.sh
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/tests/run_integration_tests_emulator.sh
  google/cloud/examples/run_gcs2cbt_emulator.sh
  google/cloud/storage/benchmarks/run_benchmarks_testbench.sh
  google/cloud/storage/examples/run_examples_testbench.sh
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/tests/run_integration_tests_testbench.sh
Labels: cla: yes

#2306 Fix openSUSE build.
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/internal/curl_client_test.cc
  google/cloud/storage/internal/curl_handle.h
  google/cloud/storage/internal/curl_handle_test.cc
  google/cloud/storage/storage_client_unit_tests.bzl
Labels: api: storage, cla: yes

#2295 Implement add bucket owner sample.
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_bucket_acl_samples.cc
Labels: cla: yes

#2311 Workaround build problems on openSUSE:Leap.
  ci/test-readme/Dockerfile.opensuse
  ci/test-readme/Dockerfile.opensuse-leap
Labels: cla: yes

#2307 Adding region tag in Bigtable C++ client samples
  google/cloud/bigtable/examples/data_snippets.cc
  google/cloud/bigtable/examples/table_admin_snippets.cc
Labels: api: bigtable, cla: yes

#2316 Moving `noex::InstanceAdmin` async functions to `InstanceAdmin`
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/instance_admin.h
Labels: api: bigtable, cla: yes

#2292 Do not depend on noex::Table::AsyncApply().
  google/cloud/bigtable/examples/data_async_snippets.cc
  google/cloud/bigtable/table.cc
  google/cloud/bigtable/table.h
  google/cloud/bigtable/tests/data_async_future_integration_test.cc
Labels: cla: yes

#2318 Implement remove/add object owner samples.
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_object_acl_samples.cc
Labels: cla: yes

#2289 Set CMAKE_SKIP_INSTALL_RPATH for bigtable_protos
  cmake/external/googleapis.cmake
Labels: cla: yes

#2317 Moving `noex::TableAdmin` async functions to `TableAdmin`
  google/cloud/bigtable/table_admin.cc
Labels: cla: yes

#2321 Implement storage create bucket with storage class/location sample.
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_bucket_samples.cc
Labels: cla: yes

#2324 Support including nlohmann::json before our headers.
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/internal/nljson.h
  google/cloud/storage/internal/nljson_use_after_third_party_test.cc
  google/cloud/storage/internal/nljson_use_third_party_test.cc
  google/cloud/storage/storage_client_unit_tests.bzl
Labels: api: storage, cla: yes

#2323 Change CMake-config files to work without `pkg-config` dependency.
  ci/test-readme/Dockerfile.centos
  ci/test-readme/Dockerfile.debian
  ci/test-readme/Dockerfile.fedora
  ci/test-readme/Dockerfile.opensuse
  ci/test-readme/Dockerfile.opensuse-leap
  ci/test-readme/Dockerfile.ubuntu
  ci/test-readme/Dockerfile.ubuntu-trusty
  ci/test-readme/Dockerfile.ubuntu-xenial
  cmake/FindProtobufTargets.cmake
  cmake/FindgRPC.cmake
  cmake/external/googleapis/CMakeLists.txt
  cmake/external/googleapis/config.cmake.in
  google/cloud/bigtable/config.cmake.in
Labels: cla: yes

#2325 Make multiple attempts to download json.hpp.
  cmake/DownloadNlohmannJson.cmake
Labels: cla: yes

#2328 Update HMAC functions to catchup with protocol.
  google/cloud/storage/client.h
  google/cloud/storage/client_service_account_test.cc
  google/cloud/storage/hmac_key_metadata.cc
  google/cloud/storage/hmac_key_metadata.h
  google/cloud/storage/hmac_key_metadata_test.cc
  google/cloud/storage/internal/hmac_key_requests.cc
  google/cloud/storage/internal/hmac_key_requests.h
  google/cloud/storage/internal/hmac_key_requests_test.cc
  google/cloud/storage/testbench/gcs_project.py
Labels: api: storage, cla: yes

#2327 Remove pkg config references from the documentation.
  CMakeLists.txt
  INSTALL.md
  cmake/IncludeCrc32c.cmake
  cmake/IncludeCurl.cmake
  cmake/IncludeGMock.cmake
  cmake/IncludeGrpc.cmake
  cmake/IncludeProtobuf.cmake
  doc/managing-dependencies-in-cmake.md
Labels: cla: yes, type: docs

#2329 Added binary-distributions adr [skip ci]
  doc/adr/2019-03-26-binary-distributions.md
Labels: cla: yes

#2326 Create code snippet for bigtable_get_family
  google/cloud/bigtable/examples/data_snippets.cc
  google/cloud/bigtable/examples/run_examples_utils.sh
Labels: cla: yes

#2332 Fix ADR status [skip ci].
  doc/adr/2019-03-26-binary-distributions.md
Labels: cla: yes

#2330 Refactor ObjectMetadata to JSON conversion functions.
  google/cloud/storage/internal/curl_client.cc
  google/cloud/storage/internal/object_requests.cc
  google/cloud/storage/internal/object_requests.h
  google/cloud/storage/object_metadata_test.cc
Labels: api: storage, cla: yes

#2333 Simplify Makefile configuration.
  ci/test-install/Makefile
  cmake/external/googleapis/CMakeLists.txt
  google/cloud/storage/CMakeLists.txt
Labels: cla: yes

#2336 Update reference ABI after latest changes.
  ci/test-abi/storage_client.expected.abi.dump.gz
Labels: cla: yes

#2338 Fix missing `using` declaration.
  google/cloud/bigtable/internal/table_test.cc
Labels: cla: yes, type: cleanup

#2337 Disable some MSVC warnings because Protobuf.
  google/cloud/bigtable/CMakeLists.txt
Labels: cla: yes, type: cleanup

#2334 Implement ObjectMetadata::set_storage_class().
  google/cloud/storage/object_metadata.h
  google/cloud/storage/object_metadata_test.cc
  google/cloud/storage/testbench/gcs_object.py
Labels: api: storage, cla: yes

#2335 Add instructions on how to use the installed libraries.
  INSTALL.md
  ci/test-readme/generate-install.sh
  google/cloud/bigtable/doc/bigtable-main.dox
  google/cloud/storage/doc/storage-main.dox
Labels: cla: yes, type: docs

#2340 Fix misspelling and warnings.
  google/cloud/bigtable/mutation_batcher.cc
  google/cloud/bigtable/mutation_batcher.h
  google/cloud/bigtable/mutation_batcher_test.cc
Labels: cla: yes

#2343 Update README shields.
  README.md
Labels: cla: yes

#2341 Fix std::size_t to int warnings.
  google/cloud/bigtable/benchmarks/endurance_benchmark.cc
  google/cloud/bigtable/testing/table_integration_test.cc
  google/cloud/storage/tests/object_media_integration_test.cc
Labels: cla: yes, type: cleanup

#2342 Add change object storage class sample.
  google/cloud/storage/examples/run_examples_utils.sh
  google/cloud/storage/examples/storage_object_samples.cc
Labels: cla: yes

#2339 Reimplement AsyncPollOp via futures.
  google/cloud/bigtable/internal/async_poll_op.h
  google/cloud/bigtable/internal/async_poll_op_test.cc
  google/cloud/bigtable/polling_policy.h
  google/cloud/bigtable/polling_policy_test.cc
Labels: cla: yes

#2345 Cleanup some FromHttpResponse fn's to take std::string
  google/cloud/storage/client_object_copy_test.cc
  google/cloud/storage/client_service_account_test.cc
  google/cloud/storage/internal/bucket_acl_requests.cc
  google/cloud/storage/internal/bucket_acl_requests.h
  google/cloud/storage/internal/bucket_acl_requests_test.cc
  google/cloud/storage/internal/bucket_requests.cc
  google/cloud/storage/internal/bucket_requests.h
  google/cloud/storage/internal/bucket_requests_test.cc
  google/cloud/storage/internal/curl_client.cc
  google/cloud/storage/internal/default_object_acl_requests.cc
  google/cloud/storage/internal/default_object_acl_requests.h
  google/cloud/storage/internal/default_object_acl_requests_test.cc
  google/cloud/storage/internal/hmac_key_requests.cc
  google/cloud/storage/internal/hmac_key_requests.h
  google/cloud/storage/internal/hmac_key_requests_test.cc
  google/cloud/storage/internal/notification_requests.cc
  google/cloud/storage/internal/notification_requests.h
  google/cloud/storage/internal/notification_requests_test.cc
  google/cloud/storage/internal/object_acl_requests.cc
  google/cloud/storage/internal/object_acl_requests.h
  google/cloud/storage/internal/object_acl_requests_test.cc
  google/cloud/storage/internal/object_requests.cc
  google/cloud/storage/internal/object_requests.h
  google/cloud/storage/internal/object_requests_test.cc
Labels: cla: yes

#2348 Consistently warn about async-APIs status.
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/table.h
  google/cloud/bigtable/table_admin.h
Labels: cla: yes

#2349 Disable debug output for googleapis_project.
  cmake/FindProtobufTargets.cmake
  cmake/external/googleapis.cmake
Labels: cla: yes, type: cleanup

#2346 Fix some region tags for storage samples.
  google/cloud/storage/client.h
  google/cloud/storage/examples/storage_default_object_acl_samples.cc
  google/cloud/storage/examples/storage_object_acl_samples.cc
Labels: cla: yes

#2351 Removed redundant enablers
  google/cloud/bigtable/internal/unary_client_utils.h
Labels: cla: yes

#2352 Removed unneeded enablers in storage/
  google/cloud/storage/internal/logging_client.cc
  google/cloud/storage/internal/raw_client_wrapper_utils.h
  google/cloud/storage/internal/retry_client.cc
Labels: cla: yes

#2347 Implement longrunning ops via StartAsyncPollOp.
  google/cloud/bigtable/admin_client.h
  google/cloud/bigtable/internal/async_longrunning_op.h
  google/cloud/bigtable/internal/async_longrunning_op_test.cc
Labels: cla: yes

#2354 storage: add region tags for PUT signed URL sample
  google/cloud/storage/examples/storage_object_samples.cc
Labels: cla: yes

#2355 Fix flakiness caused by drop all rows quota
  google/cloud/bigtable/testing/table_integration_test.cc
  google/cloud/bigtable/testing/table_integration_test.h
  google/cloud/bigtable/tests/data_integration_test.cc
  google/cloud/bigtable/tests/filters_integration_test.cc
  google/cloud/bigtable/tests/mutations_integration_test.cc
  google/cloud/bigtable/tests/run_integration_tests_emulator.sh
Labels: cla: yes

#2250 Create signed URL V4 conformance tests
  google/cloud/storage/tests/CMakeLists.txt
  google/cloud/storage/tests/UrlSignerV4TestAccount.json
  google/cloud/storage/tests/UrlSignerV4TestData.json
  google/cloud/storage/tests/client_sign_url_integration_test.cc
  google/cloud/storage/tests/run_integration_tests_testbench.sh
  google/cloud/storage/tests/storage_client_integration_tests.bzl
Labels: :rotating_light:, cla: yes

#2353 Create code snippet for bigtable_delete_all_cells
  google/cloud/bigtable/examples/data_snippets.cc
  google/cloud/bigtable/examples/run_examples_utils.sh
Labels: cla: yes

#2360 Updates bazel used in CI
  ci/install-bazel.sh
Labels: cla: yes

#2358 Add required dependencies so genrule can access CC and CC_FLAGS.
  google/cloud/BUILD
Labels: cla: yes

#2362 Implement bigtable::InstanceAdmin::AsyncDeleteInstance
  google/cloud/bigtable/examples/instance_admin_async_snippets.cc
  google/cloud/bigtable/examples/run_examples_utils.sh
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
Labels: cla: yes
