Repository googleapis/google-cloud-cpp, pull requests merged in 2020-10, with the labels that each got.

#5172 doc: update CHANGELOG for v1.19.0 releases
  CHANGELOG.md
Labels: cla: yes

#5175 chore: bump version numbers post v1.19.0 release
  CMakeLists.txt
  ci/generate-markdown/generate-packaging.sh
  doc/packaging.md
  generator/integration_tests/golden/golden_connection_options_test.cc
  google/cloud/bigquery/version_info.h
  google/cloud/bigtable/quickstart/WORKSPACE
  google/cloud/bigtable/version_info.h
  google/cloud/internal/version_info.h
  google/cloud/pubsub/quickstart/WORKSPACE
  google/cloud/pubsub/version_info.h
  google/cloud/spanner/quickstart/WORKSPACE
  google/cloud/spanner/version_info.h
  google/cloud/storage/quickstart/WORKSPACE
  google/cloud/storage/version_info.h
Labels: cla: yes

#5176 fix: race condition canceling CompletionQueue timers
  google/cloud/completion_queue_test.cc
  google/cloud/internal/default_completion_queue_impl.cc
Labels: cla: yes

#5178 doc(pubsub): use codition variables in sample code
  google/cloud/pubsub/samples/samples.cc
Labels: cla: yes

#5179 feat(common): serialize output through std::clog
  google/cloud/log.cc
  google/cloud/log_test.cc
Labels: cla: yes

#5177 doc: improve verbiage in packaging.md
  ci/generate-markdown/generate-packaging.sh
  doc/packaging.md
Labels: cla: yes

#5182 cleanup(common): simplify promise::set_value()
  google/cloud/future_generic.h
  google/cloud/future_generic_test.cc
  google/cloud/internal/future_impl.h
Labels: cla: yes

#5185 refactor: relocate polling_loop.h from spanner to common
  google/cloud/CMakeLists.txt
  google/cloud/google_cloud_cpp_grpc_utils.bzl
  google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl
  google/cloud/internal/polling_loop.h
  google/cloud/internal/polling_loop_test.cc
  google/cloud/polling_policy.h
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/database_admin_connection.cc
  google/cloud/spanner/instance_admin_connection.cc
  google/cloud/spanner/polling_policy.h
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_unit_tests.bzl
Labels: cla: yes

#5183 feat(common): wrapper for bi-dir async streaming RPCs
  google/cloud/CMakeLists.txt
  google/cloud/completion_queue.h
  google/cloud/google_cloud_cpp_grpc_utils.bzl
  google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl
  google/cloud/internal/async_read_write_stream_impl.h
  google/cloud/internal/async_read_write_stream_impl_test.cc
Labels: cla: yes

#5187 feat(pubsub): only empty order keys for non-ordered publishers
  google/cloud/pubsub/CMakeLists.txt
  google/cloud/pubsub/internal/rejects_with_ordering_key.cc
  google/cloud/pubsub/internal/rejects_with_ordering_key.h
  google/cloud/pubsub/internal/rejects_with_ordering_key_test.cc
  google/cloud/pubsub/publisher_connection.cc
  google/cloud/pubsub/publisher_connection_test.cc
  google/cloud/pubsub/pubsub_client.bzl
  google/cloud/pubsub/pubsub_client_unit_tests.bzl
Labels: api: pubsub, cla: yes

#5188 feat(pubsub): add streaming pull function to stub
  google/cloud/pubsub/integration_tests/CMakeLists.txt
  google/cloud/pubsub/integration_tests/pubsub_client_integration_tests.bzl
  google/cloud/pubsub/integration_tests/subscriber_integration_test.cc
  google/cloud/pubsub/internal/subscriber_logging.cc
  google/cloud/pubsub/internal/subscriber_logging.h
  google/cloud/pubsub/internal/subscriber_logging_test.cc
  google/cloud/pubsub/internal/subscriber_metadata.cc
  google/cloud/pubsub/internal/subscriber_metadata.h
  google/cloud/pubsub/internal/subscriber_metadata_test.cc
  google/cloud/pubsub/internal/subscriber_stub.cc
  google/cloud/pubsub/internal/subscriber_stub.h
  google/cloud/pubsub/testing/mock_subscriber_stub.h
Labels: api: pubsub, cla: yes

#5190 feat(pubsub): the streaming pull state machine
  google/cloud/pubsub/CMakeLists.txt
  google/cloud/pubsub/integration_tests/subscriber_integration_test.cc
  google/cloud/pubsub/internal/streaming_subscription_batch_source.cc
  google/cloud/pubsub/internal/streaming_subscription_batch_source.h
  google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc
  google/cloud/pubsub/internal/subscription_batch_source.h
  google/cloud/pubsub/pubsub_client.bzl
  google/cloud/pubsub/pubsub_client_unit_tests.bzl
Labels: api: pubsub, cla: yes

#5209 test: replace EXPECT_EQ(kOk) with EXPECT_STATUS_OK
  google/cloud/storage/internal/http_response_test.cc
  google/cloud/storage/oauth2/authorized_user_credentials_test.cc
  google/cloud/storage/oauth2/compute_engine_credentials_test.cc
  google/cloud/storage/oauth2/service_account_credentials_test.cc
Labels: cla: yes

#5207 test: remove unused files
  google/cloud/storage/benchmarks/throughput_download_task.cc
  google/cloud/storage/benchmarks/throughput_download_task.h
Labels: cla: yes

#5203 test(storage): store the full Status in ThroughputResult
  google/cloud/storage/benchmarks/storage_benchmarks.bzl
  google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc
  google/cloud/storage/benchmarks/throughput_experiment.cc
  google/cloud/storage/benchmarks/throughput_experiment_test.cc
  google/cloud/storage/benchmarks/throughput_result.cc
  google/cloud/storage/benchmarks/throughput_result.h
  google/cloud/storage/benchmarks/throughput_result_test.cc
Labels: cla: yes

#5197 fix(spanner): use `ExecuteStreamingSql`for PDML operations
  google/cloud/spanner/internal/connection_impl.cc
  google/cloud/spanner/internal/connection_impl_test.cc
Labels: api: spanner, cla: yes

#5210 fix(pubsub): streaming pull race conditions
  google/cloud/pubsub/internal/streaming_subscription_batch_source.cc
  google/cloud/pubsub/internal/streaming_subscription_batch_source.h
  google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc
Labels: api: pubsub, cla: yes

#5211 test: use `StatusIs` matcher in spanner tests
  google/cloud/spanner/benchmarks/benchmarks_config_test.cc
  google/cloud/spanner/bytes_test.cc
  google/cloud/spanner/client_test.cc
  google/cloud/spanner/database_admin_client_test.cc
  google/cloud/spanner/database_admin_connection_test.cc
  google/cloud/spanner/instance_admin_client_test.cc
  google/cloud/spanner/instance_admin_connection_test.cc
  google/cloud/spanner/internal/merge_chunk_test.cc
  google/cloud/spanner/internal/partial_result_set_resume_test.cc
  google/cloud/spanner/internal/partial_result_set_source_test.cc
  google/cloud/spanner/internal/session_pool_test.cc
  google/cloud/spanner/internal/spanner_stub_test.cc
  google/cloud/spanner/numeric_test.cc
  google/cloud/spanner/results_test.cc
  google/cloud/spanner/row_test.cc
  google/cloud/spanner/sql_statement_test.cc
  google/cloud/spanner/testing/cleanup_stale_databases_test.cc
  google/cloud/spanner/timestamp_test.cc
  google/cloud/spanner/value_test.cc
Labels: cla: yes

#5212 fix: MSVC+x86 build
  google/cloud/storage/benchmarks/throughput_result.cc
Labels: cla: yes

#5213 fix: remove test from library sources list
  google/cloud/storage/benchmarks/CMakeLists.txt
Labels: cla: yes

#5215 ci: fix build script for Bazel
  ci/kokoro/docker/build-in-docker-bazel.sh
Labels: cla: yes

#5214 doc: prefer UBLA references over bucket-policy-only
  google/cloud/storage/bucket_metadata.h
  google/cloud/storage/client.h
Labels: cla: yes

#5216 doc: improve top-level README links
  README.md
  ci/generate-markdown/generate-readme.sh
Labels: cla: yes

#5217 doc(pubsub): Link subscriber doc to the quickstart
  google/cloud/pubsub/subscriber.h
Labels: cla: yes

#5219 ci: check for diffs post-build
  ci/kokoro/docker/build-in-docker-cmake.sh
Labels: cla: yes

#5198 feat(pubsub): faster subscription shutdowns
  google/cloud/pubsub/BUILD
  google/cloud/pubsub/CMakeLists.txt
  google/cloud/pubsub/internal/default_subscription_batch_source.cc
  google/cloud/pubsub/internal/default_subscription_batch_source.h
  google/cloud/pubsub/internal/default_subscription_batch_source_test.cc
  google/cloud/pubsub/internal/session_shutdown_manager.h
  google/cloud/pubsub/internal/streaming_subscription_batch_source.cc
  google/cloud/pubsub/internal/streaming_subscription_batch_source.h
  google/cloud/pubsub/internal/subscription_batch_source.h
  google/cloud/pubsub/internal/subscription_flow_control.cc
  google/cloud/pubsub/internal/subscription_flow_control.h
  google/cloud/pubsub/internal/subscription_flow_control_test.cc
  google/cloud/pubsub/internal/subscription_lease_management.cc
  google/cloud/pubsub/internal/subscription_lease_management.h
  google/cloud/pubsub/internal/subscription_lease_management_test.cc
  google/cloud/pubsub/internal/subscription_message_queue.cc
  google/cloud/pubsub/internal/subscription_message_queue.h
  google/cloud/pubsub/internal/subscription_message_queue_test.cc
  google/cloud/pubsub/internal/subscription_message_source.h
  google/cloud/pubsub/internal/subscription_session.cc
  google/cloud/pubsub/internal/subscription_session.h
  google/cloud/pubsub/internal/subscription_session_test.cc
  google/cloud/pubsub/pubsub_client.bzl
  google/cloud/pubsub/pubsub_client_testing.bzl
  google/cloud/pubsub/pubsub_client_unit_tests.bzl
  google/cloud/pubsub/subscriber_connection.cc
  google/cloud/pubsub/subscriber_connection_test.cc
  google/cloud/pubsub/testing/fake_streaming_pull.cc
  google/cloud/pubsub/testing/fake_streaming_pull.h
  google/cloud/pubsub/testing/mock_subscription_batch_source.h
Labels: cla: yes

#5221 ci: automatically fix problematic Abseil includes
  ci/check-style.sh
Labels: cla: yes

#5222 cleanup(pubsub): remove AsyncPull() and friends
  google/cloud/pubsub/internal/subscriber_logging.cc
  google/cloud/pubsub/internal/subscriber_logging.h
  google/cloud/pubsub/internal/subscriber_logging_test.cc
  google/cloud/pubsub/internal/subscriber_metadata.cc
  google/cloud/pubsub/internal/subscriber_metadata.h
  google/cloud/pubsub/internal/subscriber_metadata_test.cc
  google/cloud/pubsub/internal/subscriber_stub.cc
  google/cloud/pubsub/internal/subscriber_stub.h
  google/cloud/pubsub/testing/mock_subscriber_stub.h
Labels: cla: yes

#5223 test(storage): finish bucket and filter response
  google/cloud/storage/emulator/gcs/bucket.py
  google/cloud/storage/emulator/tests/test_gcs.py
  google/cloud/storage/emulator/tests/test_utils.py
  google/cloud/storage/emulator/utils/common.py
Labels: cla: yes

#5224 cleanup(pubsub): remove SubscriptionFlowControl stage
  google/cloud/pubsub/CMakeLists.txt
  google/cloud/pubsub/internal/subscription_flow_control.cc
  google/cloud/pubsub/internal/subscription_flow_control.h
  google/cloud/pubsub/internal/subscription_flow_control_test.cc
  google/cloud/pubsub/internal/subscription_message_queue.cc
  google/cloud/pubsub/internal/subscription_message_queue.h
  google/cloud/pubsub/internal/subscription_message_queue_test.cc
  google/cloud/pubsub/internal/subscription_session.cc
  google/cloud/pubsub/internal/subscription_session.h
  google/cloud/pubsub/pubsub_client.bzl
  google/cloud/pubsub/pubsub_client_unit_tests.bzl
Labels: api: pubsub, cla: yes

#5226 cleanup(pubsub)!: simplify flow control config
  CHANGELOG.md
  google/cloud/pubsub/internal/streaming_subscription_batch_source.h
  google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc
  google/cloud/pubsub/internal/subscription_session_test.cc
  google/cloud/pubsub/samples/samples.cc
  google/cloud/pubsub/subscription_options.cc
  google/cloud/pubsub/subscription_options.h
  google/cloud/pubsub/subscription_options_test.cc
Labels: cla: yes

#5232 feat(bigtable): convert protos to filters
  google/cloud/bigtable/filters.h
  google/cloud/bigtable/filters_test.cc
Labels: cla: yes

#5229 cleanup(pubsub): simplify `SubscriptionBatchSource`
  google/cloud/pubsub/integration_tests/subscriber_integration_test.cc
  google/cloud/pubsub/internal/streaming_subscription_batch_source.cc
  google/cloud/pubsub/internal/streaming_subscription_batch_source.h
  google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc
  google/cloud/pubsub/internal/subscription_batch_source.h
  google/cloud/pubsub/internal/subscription_lease_management.cc
  google/cloud/pubsub/internal/subscription_lease_management.h
  google/cloud/pubsub/internal/subscription_lease_management_test.cc
  google/cloud/pubsub/internal/subscription_message_queue.cc
  google/cloud/pubsub/internal/subscription_message_queue_test.cc
  google/cloud/pubsub/testing/mock_subscription_batch_source.h
Labels: cla: yes

#5230 fix(storage): Make private_key_id optional for JSON credentials
  google/cloud/storage/oauth2/service_account_credentials.cc
  google/cloud/storage/oauth2/service_account_credentials_test.cc
Labels: cla: yes

#5231 fix(pubsub): handle start completion after shutdown
  google/cloud/pubsub/internal/streaming_subscription_batch_source.cc
  google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc
Labels: cla: yes

#5234 test(storage): use StatusIs in google/cloud/storage tests
  google/cloud/storage/client_write_object_test.cc
  google/cloud/storage/internal/bucket_requests_test.cc
  google/cloud/storage/internal/grpc_client_failures_test.cc
  google/cloud/storage/internal/grpc_client_object_request_test.cc
  google/cloud/storage/internal/grpc_object_read_source_test.cc
  google/cloud/storage/internal/grpc_resumable_upload_session_test.cc
  google/cloud/storage/internal/http_response_test.cc
  google/cloud/storage/internal/logging_resumable_upload_session_test.cc
  google/cloud/storage/internal/object_streambuf_test.cc
  google/cloud/storage/internal/policy_document_request_test.cc
  google/cloud/storage/internal/retry_client_test.cc
  google/cloud/storage/internal/retry_resumable_upload_session_test.cc
  google/cloud/storage/internal/signed_url_requests_test.cc
  google/cloud/storage/oauth2/authorized_user_credentials_test.cc
  google/cloud/storage/oauth2/compute_engine_credentials_test.cc
  google/cloud/storage/oauth2/google_credentials_test.cc
  google/cloud/storage/oauth2/service_account_credentials_test.cc
  google/cloud/storage/object_stream_test.cc
  google/cloud/storage/parallel_uploads_test.cc
  google/cloud/storage/testing/remove_stale_buckets_test.cc
  google/cloud/storage/tests/error_injection_integration_test.cc
  google/cloud/storage/tests/object_checksum_integration_test.cc
Labels: cla: yes

#5240 test: clang-tidy fixes
  google/cloud/storage/internal/grpc_client_failures_test.cc
Labels: cla: yes

#5239 feat(storage): Create an example for Client::DeleteResumableUpload()
  google/cloud/storage/examples/storage_object_resumable_write_samples.cc
Labels: cla: yes

#5225 feat(pubsub): an endurance benchmark
  google/cloud/pubsub/CMakeLists.txt
  google/cloud/pubsub/benchmarks/BUILD
  google/cloud/pubsub/benchmarks/CMakeLists.txt
  google/cloud/pubsub/benchmarks/README.md
  google/cloud/pubsub/benchmarks/endurance.cc
  google/cloud/pubsub/benchmarks/pubsub_client_benchmark_programs.bzl
Labels: cla: yes

#5242 cleanup(pubsub)!: inconsistent names in PublisherOptions
  CHANGELOG.md
  google/cloud/pubsub/internal/batching_publisher_connection.cc
  google/cloud/pubsub/internal/batching_publisher_connection_test.cc
  google/cloud/pubsub/publisher_option_test.cc
  google/cloud/pubsub/publisher_options.h
  google/cloud/pubsub/samples/samples.cc
Labels: cla: yes

#5243 test(pubsub): enable DetachSubscription test
  google/cloud/pubsub/integration_tests/subscription_admin_integration_test.cc
Labels: cla: yes

#5244 cleanup(pubsub)!: remove redundant publisher option
  CHANGELOG.md
  google/cloud/pubsub/internal/batching_publisher_connection.cc
  google/cloud/pubsub/publisher.h
  google/cloud/pubsub/publisher_connection_test.cc
  google/cloud/pubsub/publisher_option_test.cc
  google/cloud/pubsub/publisher_options.h
  google/cloud/pubsub/samples/samples.cc
Labels: cla: yes

#5245 cleanup(pubsub): return types for ack/nack functions
  google/cloud/pubsub/integration_tests/subscriber_integration_test.cc
  google/cloud/pubsub/internal/streaming_subscription_batch_source.cc
  google/cloud/pubsub/internal/streaming_subscription_batch_source.h
  google/cloud/pubsub/internal/subscription_batch_source.h
  google/cloud/pubsub/internal/subscription_lease_management.cc
  google/cloud/pubsub/internal/subscription_lease_management.h
  google/cloud/pubsub/internal/subscription_lease_management_test.cc
  google/cloud/pubsub/internal/subscription_message_queue.cc
  google/cloud/pubsub/testing/mock_subscription_batch_source.h
Labels: cla: yes

#5250 docs: update code of conduct to version 1.4.0
  CODE_OF_CONDUCT.md
Labels: cla: yes

#5247 cleanup(pubsub)!: make Subscriber more consistent
  CHANGELOG.md
  google/cloud/pubsub/benchmarks/endurance.cc
  google/cloud/pubsub/integration_tests/message_integration_test.cc
  google/cloud/pubsub/integration_tests/subscription_lifecycle_test.cc
  google/cloud/pubsub/internal/subscription_session.cc
  google/cloud/pubsub/internal/subscription_session.h
  google/cloud/pubsub/internal/subscription_session_test.cc
  google/cloud/pubsub/samples/mock_subscriber.cc
  google/cloud/pubsub/samples/pubsub_samples_common.cc
  google/cloud/pubsub/samples/pubsub_samples_common.h
  google/cloud/pubsub/samples/pubsub_samples_common_test.cc
  google/cloud/pubsub/samples/samples.cc
  google/cloud/pubsub/subscriber.h
  google/cloud/pubsub/subscriber_connection.cc
  google/cloud/pubsub/subscriber_connection.h
  google/cloud/pubsub/subscriber_connection_test.cc
  google/cloud/pubsub/subscriber_test.cc
Labels: cla: yes

#5248 test: enable all clang-tidy presubmit warnings for source files
  ci/kokoro/docker/build-in-docker-cmake.sh
Labels: cla: yes

#5251 cleanup(pubsub)!: rename SubcriptionOptions
  CHANGELOG.md
  google/cloud/pubsub/CMakeLists.txt
  google/cloud/pubsub/integration_tests/subscriber_integration_test.cc
  google/cloud/pubsub/internal/streaming_subscription_batch_source.h
  google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc
  google/cloud/pubsub/internal/subscription_session.cc
  google/cloud/pubsub/internal/subscription_session.h
  google/cloud/pubsub/internal/subscription_session_test.cc
  google/cloud/pubsub/pubsub_client.bzl
  google/cloud/pubsub/pubsub_client_unit_tests.bzl
  google/cloud/pubsub/samples/samples.cc
  google/cloud/pubsub/subscriber_connection.cc
  google/cloud/pubsub/subscriber_connection.h
  google/cloud/pubsub/subscriber_connection_test.cc
  google/cloud/pubsub/subscriber_options.cc
  google/cloud/pubsub/subscriber_options.h
  google/cloud/pubsub/subscriber_options_test.cc
Labels: cla: yes

#5252 refactor(pubsub): consolidate integration tests
  google/cloud/pubsub/integration_tests/CMakeLists.txt
  google/cloud/pubsub/integration_tests/message_integration_test.cc
  google/cloud/pubsub/integration_tests/pubsub_client_integration_tests.bzl
  google/cloud/pubsub/integration_tests/subscriber_integration_test.cc
  google/cloud/pubsub/integration_tests/subscription_lifecycle_test.cc
Labels: api: pubsub, cla: yes

#5255 cleanup: use absl::StrSplit where appropriate
  google/cloud/bigquery/internal/connection_impl.cc
  google/cloud/bigtable/client_options.cc
  google/cloud/bigtable/examples/data_snippets.cc
  google/cloud/connection_options.cc
  google/cloud/examples/gcs2cbt.cc
  google/cloud/storage/client_options.cc
  google/cloud/storage/internal/signed_url_requests.cc
  google/cloud/storage/oauth2/service_account_credentials_test.cc
  google/cloud/storage/tests/thread_integration_test.cc
  google/cloud/testing_util/capture_log_lines_backend.cc
Labels: cla: yes

#5253 feat(pubsub): support subscription filters
  google/cloud/pubsub/samples/samples.cc
  google/cloud/pubsub/subscription_builder.h
  google/cloud/pubsub/subscription_builder_test.cc
Labels: api: pubsub, cla: yes

#5264 cleanup(pubsub)!: rename SnapshotMutationBuilder
  CHANGELOG.md
  google/cloud/pubsub/CMakeLists.txt
  google/cloud/pubsub/integration_tests/subscription_admin_integration_test.cc
  google/cloud/pubsub/pubsub_client.bzl
  google/cloud/pubsub/pubsub_client_unit_tests.bzl
  google/cloud/pubsub/samples/samples.cc
  google/cloud/pubsub/snapshot_builder.cc
  google/cloud/pubsub/snapshot_builder.h
  google/cloud/pubsub/snapshot_builder_test.cc
  google/cloud/pubsub/subscription_admin_client.h
  google/cloud/pubsub/subscription_admin_client_test.cc
  google/cloud/pubsub/subscription_admin_connection_test.cc
Labels: cla: yes

#5268 cleanup(pubsub): Use top-level target in Pub/Sub quickstart guide
  google/cloud/pubsub/quickstart/BUILD
  google/cloud/pubsub/quickstart/WORKSPACE
Labels: cla: yes

#5269 cleanup(storage): Update HmacKey documentation with link
  google/cloud/storage/hmac_key_metadata.h
Labels: cla: yes

#5273 test(storage): add rest for bucket and gcs object
  google/cloud/storage/emulator/database.py
  google/cloud/storage/emulator/gcs/bucket.py
  google/cloud/storage/emulator/gcs/object.py
  google/cloud/storage/emulator/requirements.txt
  google/cloud/storage/emulator/rest_server.py
  google/cloud/storage/emulator/tests/test_utils.py
  google/cloud/storage/emulator/utils/common.py
Labels: api: storage, cla: yes

#5276 test(bigtable): update ReadsRowParser acceptance tests
  google/cloud/bigtable/tools/convert_acceptance_tests.py
Labels: cla: yes

#5278 fix: breakage caused by tumbleweed update
  ci/kokoro/install/Dockerfile.opensuse-tumbleweed
  doc/packaging.md
Labels: cla: yes

#5281 cleanup(common): Fix link in Doxygen TAGFILES
  cmake/GoogleCloudCppCommon.cmake
Labels: cla: yes

#5282 test(pubsub): more control over streaming start
  google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc
Labels: cla: yes

#5285 feat(pubsub)!: share connections for subscribers
  google/cloud/pubsub/benchmarks/endurance.cc
  google/cloud/pubsub/integration_tests/subscriber_integration_test.cc
  google/cloud/pubsub/internal/subscription_session.cc
  google/cloud/pubsub/internal/subscription_session.h
  google/cloud/pubsub/internal/subscription_session_test.cc
  google/cloud/pubsub/samples/mock_subscriber.cc
  google/cloud/pubsub/samples/pubsub_samples_common.cc
  google/cloud/pubsub/samples/samples.cc
  google/cloud/pubsub/subscriber.h
  google/cloud/pubsub/subscriber_connection.cc
  google/cloud/pubsub/subscriber_connection.h
  google/cloud/pubsub/subscriber_connection_test.cc
  google/cloud/pubsub/subscriber_test.cc
Labels: cla: yes

#5189 fix: handling of session URLs in gRPC
  CMakeLists.txt
  cmake/CompileProtos.cmake
  external/googleapis/CMakeLists.txt
  google/cloud/CMakeLists.txt
  google/cloud/storage/BUILD
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/internal/grpc_client.cc
  google/cloud/storage/internal/grpc_client.h
  google/cloud/storage/internal/grpc_resumable_upload_session.cc
  google/cloud/storage/internal/grpc_resumable_upload_session.h
  google/cloud/storage/internal/grpc_resumable_upload_session_test.cc
  google/cloud/storage/internal/grpc_resumable_upload_session_url.cc
  google/cloud/storage/internal/grpc_resumable_upload_session_url.h
  google/cloud/storage/internal/grpc_resumable_upload_session_url.proto
  google/cloud/storage/internal/grpc_resumable_upload_session_url_test.cc
  google/cloud/storage/internal/hybrid_client.cc
  google/cloud/storage/storage_client_grpc.bzl
  google/cloud/storage/storage_client_grpc_unit_tests.bzl
Labels: cla: yes

#5291 fix(pubsub): crashes for fire & forget sessions
  google/cloud/pubsub/internal/session_shutdown_manager.cc
  google/cloud/pubsub/internal/session_shutdown_manager.h
  google/cloud/pubsub/internal/streaming_subscription_batch_source.cc
Labels: cla: yes

#5292 fix(pubsub): handle errors on first Read()
  google/cloud/pubsub/integration_tests/subscriber_integration_test.cc
  google/cloud/pubsub/internal/streaming_subscription_batch_source.cc
  google/cloud/pubsub/internal/streaming_subscription_batch_source.h
  google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc
Labels: cla: yes

#5288 test(bigtable): unit test for AsyncRetryBulkApply
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/bigtable_client_unit_tests.bzl
  google/cloud/bigtable/internal/async_bulk_apply_test.cc
Labels: api: bigtable, cla: yes

#5283 refactor(storage): Remove storage-{download,upload}.googleapis.com endpoints
  google/cloud/storage/client_options.cc
  google/cloud/storage/client_options.h
  google/cloud/storage/client_options_test.cc
  google/cloud/storage/internal/curl_client.cc
  google/cloud/storage/internal/curl_client.h
Labels: cla: yes

#5298 bug: Fix building instructions w.r.t. testing
  ci/generate-markdown/generate-packaging.sh
  doc/packaging.md
  doc/setup-development-environment.md
Labels: cla: yes

#5280 feature(generator): generate header only retry policy
  generator/CMakeLists.txt
  generator/generator_test.cc
  generator/google_cloud_cpp_generator.bzl
  generator/integration_tests/generator_integration_test.cc
  generator/integration_tests/golden/BUILD
  generator/integration_tests/golden/CMakeLists.txt
  generator/integration_tests/golden/google_cloud_cpp_generator_golden_files.bzl
  generator/integration_tests/golden/retry_policy.gcpcxx.pb.h
  generator/integration_tests/golden/retry_traits.h
  generator/internal/descriptor_utils.cc
  generator/internal/descriptor_utils_test.cc
  generator/internal/printer.h
  generator/internal/retry_policy_generator.cc
  generator/internal/retry_policy_generator.h
  generator/internal/service_code_generator.cc
  generator/internal/service_code_generator.h
Labels: cla: yes

#5294 test: use protobufs, not json in conformance tests
  ci/kokoro/windows/build-bazel.ps1
  google/cloud/storage/internal/policy_document_request.cc
  google/cloud/storage/tests/BUILD
  google/cloud/storage/tests/CMakeLists.txt
  google/cloud/storage/tests/conformance_tests.proto
  google/cloud/storage/tests/signed_url_conformance_test.cc
  google/cloud/storage/tests/storage_client_integration_tests.bzl
Labels: cla: yes

#5301 test(spanner): correct guard on UpdateDatabaseDdlMetadata expectation
  google/cloud/spanner/integration_tests/database_admin_integration_test.cc
Labels: cla: yes

#5302 revert(pubsub): revert changes to share connections
  CHANGELOG.md
  ci/kokoro/docker/build-in-docker-quickstart-bazel.sh
  ci/kokoro/docker/build-in-docker-quickstart-cmake.sh
  ci/kokoro/macos/build-quickstart-bazel.sh
  ci/kokoro/macos/build-quickstart-cmake.sh
  ci/kokoro/windows/build-quickstart-bazel.ps1
  ci/kokoro/windows/build-quickstart-cmake.ps1
  google/cloud/pubsub/CMakeLists.txt
  google/cloud/pubsub/README.md
  google/cloud/pubsub/benchmarks/endurance.cc
  google/cloud/pubsub/integration_tests/subscriber_integration_test.cc
  google/cloud/pubsub/internal/batching_publisher_connection.cc
  google/cloud/pubsub/internal/batching_publisher_connection.h
  google/cloud/pubsub/internal/batching_publisher_connection_test.cc
  google/cloud/pubsub/internal/message_batcher.h
  google/cloud/pubsub/internal/ordering_key_publisher_connection.cc
  google/cloud/pubsub/internal/ordering_key_publisher_connection.h
  google/cloud/pubsub/internal/ordering_key_publisher_connection_test.cc
  google/cloud/pubsub/internal/rejects_with_ordering_key.cc
  google/cloud/pubsub/internal/rejects_with_ordering_key.h
  google/cloud/pubsub/internal/rejects_with_ordering_key_test.cc
  google/cloud/pubsub/internal/subscription_session.cc
  google/cloud/pubsub/internal/subscription_session.h
  google/cloud/pubsub/internal/subscription_session_test.cc
  google/cloud/pubsub/mocks/mock_publisher_connection.h
  google/cloud/pubsub/publisher.cc
  google/cloud/pubsub/publisher.h
  google/cloud/pubsub/publisher_connection.cc
  google/cloud/pubsub/publisher_connection.h
  google/cloud/pubsub/publisher_connection_test.cc
  google/cloud/pubsub/publisher_test.cc
  google/cloud/pubsub/pubsub_client.bzl
  google/cloud/pubsub/pubsub_client_testing.bzl
  google/cloud/pubsub/quickstart/quickstart.cc
  google/cloud/pubsub/samples/mock_publisher.cc
  google/cloud/pubsub/samples/mock_subscriber.cc
  google/cloud/pubsub/samples/pubsub_samples_common.cc
  google/cloud/pubsub/samples/samples.cc
  google/cloud/pubsub/subscriber.h
  google/cloud/pubsub/subscriber_connection.cc
  google/cloud/pubsub/subscriber_connection.h
  google/cloud/pubsub/subscriber_connection_test.cc
  google/cloud/pubsub/subscriber_test.cc
  google/cloud/pubsub/testing/mock_message_batcher.h
Labels: cla: yes

#5303 refactor(spanner): some simple CreateDatabase() refactoring
  google/cloud/spanner/samples/samples.cc
  google/cloud/spanner/testing/database_integration_test.cc
Labels: cla: yes

#5274 add error handling example from client->ReadObject() in README.md
  README.md
  google/cloud/storage/README.md
  google/cloud/storage/quickstart/quickstart.cc
Labels: cla: yes

#5305 feat(storage): Move nlohmann/json.hpp includes to cc file
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/client_notifications_test.cc
  google/cloud/storage/client_service_account_test.cc
  google/cloud/storage/hmac_key_metadata_test.cc
  google/cloud/storage/iam_policy.cc
  google/cloud/storage/iam_policy.h
  google/cloud/storage/internal/access_control_common.h
  google/cloud/storage/internal/access_control_common_parser.cc
  google/cloud/storage/internal/access_control_common_parser.h
  google/cloud/storage/internal/access_control_common_parser_test.cc
  google/cloud/storage/internal/bucket_acl_requests.cc
  google/cloud/storage/internal/bucket_requests.cc
  google/cloud/storage/internal/common_metadata.h
  google/cloud/storage/internal/common_metadata_parser.h
  google/cloud/storage/internal/curl_client.cc
  google/cloud/storage/internal/hmac_key_metadata_parser.cc
  google/cloud/storage/internal/hmac_key_metadata_parser.h
  google/cloud/storage/internal/hmac_key_requests.cc
  google/cloud/storage/internal/hmac_key_requests.h
  google/cloud/storage/internal/hmac_key_requests_test.cc
  google/cloud/storage/internal/notification_metadata_parser.cc
  google/cloud/storage/internal/notification_metadata_parser.h
  google/cloud/storage/internal/notification_requests.cc
  google/cloud/storage/internal/notification_requests.h
  google/cloud/storage/internal/notification_requests_test.cc
  google/cloud/storage/internal/object_acl_requests.cc
  google/cloud/storage/internal/object_requests.cc
  google/cloud/storage/list_hmac_keys_reader_test.cc
  google/cloud/storage/notification_metadata.cc
  google/cloud/storage/notification_metadata_test.cc
  google/cloud/storage/storage_client.bzl
  google/cloud/storage/storage_client_unit_tests.bzl
  google/cloud/storage/storage_iam_policy_test.cc
Labels: cla: yes

#5304 feat(pubsub): sequence batches with ordering keys
  google/cloud/pubsub/integration_tests/subscriber_integration_test.cc
  google/cloud/pubsub/internal/batching_publisher_connection.cc
  google/cloud/pubsub/internal/batching_publisher_connection.h
  google/cloud/pubsub/internal/batching_publisher_connection_test.cc
  google/cloud/pubsub/internal/ordering_key_publisher_connection.cc
  google/cloud/pubsub/internal/ordering_key_publisher_connection.h
  google/cloud/pubsub/internal/ordering_key_publisher_connection_test.cc
  google/cloud/pubsub/internal/rejects_with_ordering_key.cc
  google/cloud/pubsub/internal/rejects_with_ordering_key.h
  google/cloud/pubsub/internal/rejects_with_ordering_key_test.cc
  google/cloud/pubsub/mocks/mock_publisher_connection.h
  google/cloud/pubsub/publisher.h
  google/cloud/pubsub/publisher_connection.cc
  google/cloud/pubsub/publisher_connection.h
  google/cloud/pubsub/publisher_options.h
  google/cloud/pubsub/samples/samples.cc
Labels: api: pubsub, cla: yes

#5307 ci: update vcpkg revision
  ci/kokoro/docker/build-in-docker-quickstart-cmake.sh
  ci/kokoro/macos/build-quickstart-cmake.sh
  ci/kokoro/windows/build-cmake-dependencies.ps1
Labels: cla: yes

#5306 ci: add pubsub quickstart to Windows builds
  ci/kokoro/windows/build-quickstart-bazel.ps1
  ci/kokoro/windows/build-quickstart-cmake.ps1
Labels: cla: yes

#5289 test(storage): add rest handle for object
  google/cloud/storage/emulator/database.py
  google/cloud/storage/emulator/gcs/__init__.py
  google/cloud/storage/emulator/gcs/bucket.py
  google/cloud/storage/emulator/gcs/object.py
  google/cloud/storage/emulator/rest_server.py
  google/cloud/storage/emulator/tests/test_gcs.py
  google/cloud/storage/emulator/utils/__init__.py
  google/cloud/storage/emulator/utils/common.py
  google/cloud/storage/emulator/utils/csek.py
Labels: api: storage, cla: yes

#5312 fix: retry unexpected curl errors
  google/cloud/storage/internal/curl_handle.cc
  google/cloud/storage/internal/curl_handle_test.cc
Labels: cla: yes

#5309 feature(generator): generate idempotency policy
  generator/CMakeLists.txt
  generator/generator_test.cc
  generator/google_cloud_cpp_generator.bzl
  generator/integration_tests/generator_integration_test.cc
  generator/integration_tests/golden/CMakeLists.txt
  generator/integration_tests/golden/connection_options.cc
  generator/integration_tests/golden/connection_options.h
  generator/integration_tests/golden/database_admin_connection_idempotency_policy.gcpcxx.pb.cc
  generator/integration_tests/golden/database_admin_connection_idempotency_policy.gcpcxx.pb.h
  generator/integration_tests/golden/golden_idempotency_policy_test.cc
  generator/integration_tests/golden/google_cloud_cpp_generator_golden_files.bzl
  generator/integration_tests/golden/google_cloud_cpp_generator_golden_tests.bzl
  generator/internal/descriptor_utils.cc
  generator/internal/descriptor_utils_test.cc
  generator/internal/idempotency_policy_generator.cc
  generator/internal/idempotency_policy_generator.h
Labels: cla: yes

#5313 fix: include nlohmann with angle brackets
  google/cloud/storage/internal/access_control_common_parser.h
Labels: cla: yes

#5310 cleanup(pubsub): enable ordering examples in production
  google/cloud/pubsub/samples/samples.cc
Labels: cla: yes

#5316 fix: avoid error_code, which doesn't exist internally
  google/cloud/storage/tests/signed_url_conformance_test.cc
Labels: cla: yes

#5317 fix: add string cast to work when bytes is a Cord
  google/cloud/pubsub/internal/batching_publisher_connection_test.cc
Labels: cla: yes

#5319 cleanup(bigtable): Remove leftover conjunction.h file
  google/cloud/bigtable/internal/conjunction.h
Labels: cla: yes

#5271 cleanup(spanner): Use absl::FixedArray instead of vector
  google/cloud/spanner/BUILD
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/internal/session_pool.cc
  google/cloud/spanner/internal/session_pool.h
Labels: api: spanner, cla: yes

#5321 cleanup(bigtable): pylint warnings
  google/cloud/bigtable/tools/convert_acceptance_tests.py
Labels: cla: yes

#5322 cleanup(storage): always list all tests
  google/cloud/storage/tests/CMakeLists.txt
  google/cloud/storage/tests/signed_url_conformance_test.cc
  google/cloud/storage/tests/storage_client_integration_tests.bzl
Labels: cla: yes

#5323 cleanup(pubsub): use bigger counters in benchmark
  google/cloud/pubsub/benchmarks/endurance.cc
Labels: cla: yes

#5324 fix(common): crashes on background thread shutdown
  google/cloud/internal/background_threads_impl.cc
  google/cloud/internal/background_threads_impl_test.cc
Labels: cla: yes

#5328 ci(pubsub): enable api checks
  ci/kokoro/docker/build-in-docker-cmake.sh
  ci/test-abi/pubsub_client.expected.abi.dump.gz
Labels: cla: yes

#5330 cleanup(pubsub): disable trace logs
  google/cloud/pubsub/internal/session_shutdown_manager.cc
  google/cloud/pubsub/internal/streaming_subscription_batch_source.cc
  google/cloud/pubsub/internal/subscription_session.cc
Labels: cla: yes

#5332 test(bigtable): unit tests for async_poll_op
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/bigtable_client_unit_tests.bzl
  google/cloud/bigtable/internal/async_poll_op_test.cc
Labels: api: bigtable, cla: yes

#5333 refactor: helpers to parse benchmark arguments
  ci/kokoro/docker/build-in-docker-cmake.sh
  google/cloud/pubsub/benchmarks/endurance.cc
  google/cloud/storage/benchmarks/BUILD
  google/cloud/storage/benchmarks/CMakeLists.txt
  google/cloud/storage/benchmarks/benchmark_parser_test.cc
  google/cloud/storage/benchmarks/benchmark_utils.cc
  google/cloud/storage/benchmarks/benchmark_utils.h
  google/cloud/storage/benchmarks/benchmark_utils_test.cc
  google/cloud/storage/benchmarks/storage_benchmarks_unit_tests.bzl
  google/cloud/storage/benchmarks/storage_file_transfer_benchmark.cc
  google/cloud/storage/benchmarks/storage_parallel_uploads_benchmark.cc
  google/cloud/storage/benchmarks/storage_shard_throughput_benchmark.cc
  google/cloud/storage/benchmarks/throughput_options.cc
  google/cloud/testing_util/CMakeLists.txt
  google/cloud/testing_util/command_line_parsing.cc
  google/cloud/testing_util/command_line_parsing.h
  google/cloud/testing_util/command_line_parsing_test.cc
  google/cloud/testing_util/google_cloud_cpp_testing.bzl
  google/cloud/testing_util/google_cloud_cpp_testing_unit_tests.bzl
Labels: cla: yes

#5331 fix(generator): convert predicate logic operators from classes to functions
  generator/internal/idempotency_policy_generator.cc
  generator/internal/predicate_utils.h
Labels: cla: yes

#5329 cleanup(pubsub): no pure virtuals in `*Connection`
  google/cloud/internal/pagination_range.h
  google/cloud/internal/pagination_range_test.cc
  google/cloud/pubsub/ack_handler.h
  google/cloud/pubsub/publisher_connection.cc
  google/cloud/pubsub/publisher_connection.h
  google/cloud/pubsub/subscriber_connection.cc
  google/cloud/pubsub/subscriber_connection.h
  google/cloud/pubsub/subscription_admin_connection.cc
  google/cloud/pubsub/subscription_admin_connection.h
  google/cloud/pubsub/topic_admin_connection.cc
  google/cloud/pubsub/topic_admin_connection.h
Labels: api: pubsub, cla: yes

#5335 chore: update API baselines
  ci/test-abi/bigtable_client.expected.abi.dump.gz
  ci/test-abi/google_cloud_cpp_common.expected.abi.dump.gz
  ci/test-abi/google_cloud_cpp_grpc_utils.expected.abi.dump.gz
  ci/test-abi/pubsub_client.expected.abi.dump.gz
  ci/test-abi/spanner_client.expected.abi.dump.gz
  ci/test-abi/storage_client.expected.abi.dump.gz
Labels: cla: yes

#5334 refactor: getrusage wrapper to common
  google/cloud/spanner/benchmarks/CMakeLists.txt
  google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
  google/cloud/storage/benchmarks/CMakeLists.txt
  google/cloud/storage/benchmarks/benchmark_utils.cc
  google/cloud/storage/benchmarks/benchmark_utils.h
  google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc
  google/cloud/storage/benchmarks/throughput_experiment.cc
  google/cloud/storage/benchmarks/throughput_options.cc
  google/cloud/testing_util/BUILD
  google/cloud/testing_util/CMakeLists.txt
  google/cloud/testing_util/google_cloud_cpp_testing.bzl
  google/cloud/testing_util/timer.cc
  google/cloud/testing_util/timer.h
Labels: cla: yes

#5327 feat(pubsub): preserve order for messages with ordering keys
  google/cloud/pubsub/BUILD
  google/cloud/pubsub/CMakeLists.txt
  google/cloud/pubsub/internal/subscription_message_queue.cc
  google/cloud/pubsub/internal/subscription_message_queue.h
  google/cloud/pubsub/internal/subscription_message_queue_test.cc
Labels: api: pubsub, cla: yes

#5340 fix(pubsub): MSVC+x86 errors
  google/cloud/pubsub/internal/subscription_message_queue.h
Labels: cla: yes

#5341 fix: pop the diagnostic stack to restore defaults
  google/cloud/internal/absl_str_cat_quiet.h
  google/cloud/internal/absl_str_join_quiet.h
  google/cloud/internal/absl_str_replace_quiet.h
Labels: cla: yes

#5325 doc: update notes for the storage library
  CHANGELOG.md
Labels: cla: yes

#5320 cleanup(bigquery): Fix absl related TODOs
  google/cloud/bigquery/CMakeLists.txt
  google/cloud/bigquery/internal/storage_stub.cc
Labels: api: bigquery, cla: yes

#5345 fix: MSVC+x86 build fixes
  google/cloud/bigquery/internal/storage_stub.cc
Labels: cla: yes

#5348 test: fix unnecessary name attribute from submit
  google/cloud/storage/examples/storage_policy_doc_samples.cc
Labels: cla: yes

#5346 ci: fetch more dependencies for Bazel builds
  ci/kokoro/docker/build-in-docker-bazel.sh
  ci/kokoro/docker/build-in-docker-quickstart-bazel.sh
  ci/kokoro/macos/build-bazel.sh
  ci/kokoro/macos/build-quickstart-bazel.sh
  ci/kokoro/windows/build-bazel.ps1
  ci/kokoro/windows/build-quickstart-bazel.ps1
Labels: cla: yes

#5347 chore: update GCS V4 signed URLs conformance tests
  google/cloud/storage/internal/policy_document_request.cc
  google/cloud/storage/internal/policy_document_request_test.cc
  google/cloud/storage/tests/signed_url_conformance_test.cc
  google/cloud/storage/tests/v4_signatures.json
Labels: cla: yes

#5349 ci: update builds for Fedora:33
  ci/etc/install-config.sh
  ci/generate-markdown/generate-packaging.sh
  ci/kokoro/docker/Dockerfile.fedora
  ci/kokoro/docker/Dockerfile.fedora-install
  ci/kokoro/docker/Dockerfile.fedora-libcxx-msan
  ci/kokoro/docker/build.sh
  ci/kokoro/install/Dockerfile.fedora
  ci/test-abi/bigtable_client.expected.abi.dump.gz
  ci/test-abi/google_cloud_cpp_common.expected.abi.dump.gz
  ci/test-abi/google_cloud_cpp_grpc_utils.expected.abi.dump.gz
  ci/test-abi/pubsub_client.expected.abi.dump.gz
  ci/test-abi/spanner_client.expected.abi.dump.gz
  ci/test-abi/storage_client.expected.abi.dump.gz
  doc/packaging.md
  generator/internal/predicate_utils_test.cc
Labels: cla: yes

#5354 chore: update vcpkg-based to get newest gRPC
  ci/kokoro/docker/build-in-docker-quickstart-cmake.sh
  ci/kokoro/macos/build-quickstart-cmake.sh
  ci/kokoro/windows/build-cmake-dependencies.ps1
Labels: cla: yes

#5343 doc: update the API baseline as part of releasing
  release/README.md
Labels: cla: yes

#5357 feature(generator): generate connection class
  generator/CMakeLists.txt
  generator/generator_test.cc
  generator/google_cloud_cpp_generator.bzl
  generator/integration_tests/generator_integration_test.cc
  generator/integration_tests/golden/CMakeLists.txt
  generator/integration_tests/golden/database_admin_connection.gcpcxx.pb.cc
  generator/integration_tests/golden/database_admin_connection.gcpcxx.pb.h
  generator/integration_tests/golden/golden_connection_test.cc
  generator/integration_tests/golden/google_cloud_cpp_generator_golden_files.bzl
  generator/integration_tests/golden/google_cloud_cpp_generator_golden_tests.bzl
  generator/internal/connection_generator.cc
  generator/internal/connection_generator.h
  generator/internal/descriptor_utils.cc
  generator/internal/descriptor_utils_test.cc
  generator/internal/predicate_utils.cc
  generator/internal/predicate_utils.h
  generator/internal/predicate_utils_test.cc
Labels: cla: yes

#5359 refactor(spanner): Use testing_utils for command-line parsing
  google/cloud/spanner/integration_tests/client_stress_test.cc
Labels: cla: yes

#5366 ci: restore ccache to fedora builds
  ci/kokoro/docker/Dockerfile.fedora
  ci/kokoro/docker/Dockerfile.fedora-install
  ci/kokoro/docker/Dockerfile.fedora-libcxx-msan
Labels: cla: yes

#5364 cleanup(pubsub): remove obsolete TODOs
  google/cloud/pubsub/publisher.cc
Labels: cla: yes

#5361 refactor(generator): use new proto_grpc_path var everywhere
  generator/internal/logging_decorator_generator.cc
  generator/internal/metadata_decorator_generator.cc
  generator/internal/stub_generator.cc
Labels: cla: yes

#5363 cleanup: Replace ad-hoc Join with Abseil StrJoin
  google/cloud/bigtable/testing/table_integration_test.cc
  google/cloud/bigtable/tests/data_integration_test.cc
  google/cloud/iam_bindings.cc
  google/cloud/pubsub/internal/session_shutdown_manager.cc
  google/cloud/storage/bucket_metadata.cc
  google/cloud/storage/internal/bucket_acl_requests.cc
  google/cloud/storage/internal/default_object_acl_requests.cc
  google/cloud/storage/internal/notification_requests.cc
  google/cloud/storage/internal/object_acl_requests.cc
  google/cloud/storage/internal/sign_blob_requests.cc
  google/cloud/storage/internal/signed_url_requests.cc
  google/cloud/storage/lifecycle_rule.cc
  google/cloud/storage/object_metadata.cc
  google/cloud/storage/policy_document.cc
  google/cloud/storage/tests/curl_download_request_integration_test.cc
Labels: cla: yes

#5365 feat(pubsub): more efficient message builder
  google/cloud/pubsub/message.h
  google/cloud/pubsub/message_test.cc
  google/cloud/pubsub/samples/samples.cc
Labels: cla: yes

#5367 feat(pubsub): more efficient batching
  google/cloud/pubsub/internal/batching_publisher_connection.cc
  google/cloud/pubsub/internal/batching_publisher_connection.h
Labels: cla: yes

#5371 fix(generator): allow for flaky mock leak
  generator/integration_tests/golden/golden_connection_test.cc
Labels: cla: yes

#5370 ci: move tsan build to Ubunt:18.04
  ci/kokoro/docker/Dockerfile.ubuntu
  ci/kokoro/docker/build.sh
Labels: cla: yes

#5373 fix(generator): use weak_ptr and deadline in cancel
  generator/integration_tests/golden/database_admin_connection.gcpcxx.pb.cc
  generator/integration_tests/golden/golden_connection_test.cc
  generator/internal/connection_generator.cc
Labels: cla: yes

#5368 feat(pubsub): implement a throughput benchmark
  google/cloud/pubsub/benchmarks/BUILD
  google/cloud/pubsub/benchmarks/CMakeLists.txt
  google/cloud/pubsub/benchmarks/README.md
  google/cloud/pubsub/benchmarks/pubsub_client_benchmark_programs.bzl
  google/cloud/pubsub/benchmarks/throughput.cc
Labels: api: pubsub, cla: yes

#5376 cleanup(pubsub): remove redundant code
  google/cloud/pubsub/internal/publisher_stub.cc
  google/cloud/pubsub/internal/subscriber_stub.cc
Labels: cla: yes

#5375 fix: build problems with MSVC+x86
  google/cloud/pubsub/benchmarks/throughput.cc
Labels: cla: yes

#5378 feat(pubsub): do not delay acks and nacks
  google/cloud/pubsub/internal/streaming_subscription_batch_source.cc
  google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc
Labels: cla: yes

#5381 doc(storage): announce removal of bucket_policy_only
  CHANGELOG.md
  google/cloud/storage/bucket_metadata.h
Labels: cla: yes

#5382 doc(pubsub): fix rendering for paragraphs
  google/cloud/pubsub/doc/pubsub-main.dox
  google/cloud/pubsub/subscriber.h
  google/cloud/pubsub/subscriber_options.h
  google/cloud/pubsub/subscription_admin_client.h
  google/cloud/pubsub/topic_admin_client.h
Labels: cla: yes

#5374 bug: Use write_basic_package_version_file to generate cmake configs
  external/googleapis/CMakeLists.txt
  google/cloud/CMakeLists.txt
  google/cloud/bigquery/CMakeLists.txt
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/config-version.cmake.in
  google/cloud/firestore/CMakeLists.txt
  google/cloud/pubsub/CMakeLists.txt
  google/cloud/spanner/CMakeLists.txt
  google/cloud/storage/CMakeLists.txt
  google/cloud/testing_util/CMakeLists.txt
Labels: cla: yes, kokoro:run
