Repository googleapis/google-cloud-cpp, pull requests merged in 2020-12, with the labels that each got.

#5562 feat(spanner): Point-In-Time Recovery (lite) throttled DB update
  bazel/google_cloud_cpp_deps.bzl
  external/googleapis/CMakeLists.txt
  google/cloud/spanner/integration_tests/database_admin_integration_test.cc
Labels: api: spanner, cla: yes

#5565 fix(bigtable): missing functions to change policies
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/instance_admin_test.cc
Labels: api: bigtable, cla: yes

#5566 chore: december release notes and ABI update
  CHANGELOG.md
  ci/test-abi/bigtable_client.expected.abi.dump.gz
  ci/test-abi/google_cloud_cpp_common.expected.abi.dump.gz
  ci/test-abi/google_cloud_cpp_grpc_utils.expected.abi.dump.gz
  ci/test-abi/pubsub_client.expected.abi.dump.gz
  ci/test-abi/spanner_client.expected.abi.dump.gz
  ci/test-abi/storage_client.expected.abi.dump.gz
Labels: cla: yes

#5567 refactor(generator): remove generation of ConnectionOptions Client constructor
  generator/integration_tests/golden/database_admin_client.gcpcxx.pb.cc
  generator/integration_tests/golden/database_admin_client.gcpcxx.pb.h
  generator/internal/client_generator.cc
Labels: cla: yes

#5568 chore: bump version numbers after v1.21 release
  CMakeLists.txt
  google/cloud/bigquery/version_info.h
  google/cloud/bigtable/quickstart/WORKSPACE
  google/cloud/bigtable/version_info.h
  google/cloud/internal/version_info.h
  google/cloud/pubsub/quickstart/WORKSPACE
  google/cloud/pubsub/version_info.h
  google/cloud/spanner/quickstart/WORKSPACE
  google/cloud/spanner/version_info.h
  google/cloud/storage/quickstart/WORKSPACE
  google/cloud/storage/version_info.h
Labels: cla: yes

#5569 feat: asynchronous waiting for connections
  google/cloud/CMakeLists.txt
  google/cloud/completion_queue.h
  google/cloud/google_cloud_cpp_grpc_utils.bzl
  google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl
  google/cloud/internal/async_connection_ready.cc
  google/cloud/internal/async_connection_ready.h
  google/cloud/internal/async_connection_ready_test.cc
Labels: cla: yes

#5572 chore: fix test name to match file
  google/cloud/spanner/database_admin_connection_test.cc
Labels: cla: yes

#5564 doc(api-support): document API support guarantees
  README.md
  ci/generate-markdown/generate-readme.sh
Labels: cla: yes

#5574 fix: get the code to compile with MSVC 2017
  google/cloud/spanner/numeric.cc
  google/cloud/testing_util/command_line_parsing.cc
Labels: cla: yes

#5576 cleanup(spanner): fix cmek_and_pitr_lite branch rebase issues
  ci/test-abi/spanner_client.expected.abi.dump.gz
  external/googleapis/CMakeLists.txt
Labels: api: spanner, cla: yes

#5578 fix(storage): allow endings without \r\n in emulator multipart
  google/cloud/storage/emulator/tests/test_utils.py
  google/cloud/storage/emulator/utils/common.py
Labels: api: storage, cla: yes

#5570 feature(generator): add doxygen permalinks for proto message types
  generator/generator_test.cc
  generator/integration_tests/generator_integration_test.cc
  generator/integration_tests/golden/database_admin_client.gcpcxx.pb.h
  generator/internal/client_generator.cc
  generator/internal/descriptor_utils.cc
  generator/internal/descriptor_utils.h
  generator/internal/descriptor_utils_test.cc
Labels: cla: yes

#5589 test: deflake completion queue test
  google/cloud/completion_queue_test.cc
Labels: cla: yes

#5585 feat: Implement backup level IAM policy
  bazel/google_cloud_cpp_deps.bzl
  external/googleapis/CMakeLists.txt
  google/cloud/bigtable/table_admin.cc
  google/cloud/bigtable/table_admin.h
  google/cloud/bigtable/table_admin_test.cc
  google/cloud/testing_util/validate_metadata.cc
  google/cloud/testing_util/validate_metadata.h
Labels: cla: yes

#5594 fix: only build gRPC testing utilities if needed
  CMakeLists.txt
  google/cloud/storage/benchmarks/CMakeLists.txt
  google/cloud/testing_util/CMakeLists.txt
Labels: cla: yes

#5550 feat: implement Bigtable connection refresh
  google/cloud/bigtable/client_options.cc
  google/cloud/bigtable/client_options.h
  google/cloud/bigtable/internal/common_client.cc
  google/cloud/bigtable/internal/common_client.h
  google/cloud/bigtable/tests/data_integration_test.cc
Labels: cla: yes

#5596 feat(spanner): use spanner_request_options protos
  bazel/google_cloud_cpp_deps.bzl
  external/googleapis/CMakeLists.txt
  google/cloud/spanner/integration_tests/database_admin_integration_test.cc
Labels: api: spanner, cla: yes

#5597 feat(spanner): use spanner_rpc_priority protos
  bazel/google_cloud_cpp_deps.bzl
  external/googleapis/CMakeLists.txt
  google/cloud/spanner/integration_tests/database_admin_integration_test.cc
Labels: api: spanner, cla: yes

#5599 chore: change libressl -> openssl on macos
  CMakeLists.txt
  ci/kokoro/macos/build-cmake.sh
Labels: cla: yes

#5602 feat(spanner): patch CommitOptions support
  ci/test-abi/spanner_client.expected.abi.dump.gz
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/client.cc
  google/cloud/spanner/client.h
  google/cloud/spanner/client_test.cc
  google/cloud/spanner/commit_options.h
  google/cloud/spanner/commit_options_test.cc
  google/cloud/spanner/commit_result.h
  google/cloud/spanner/connection.h
  google/cloud/spanner/internal/connection_impl_test.cc
  google/cloud/spanner/samples/samples.cc
  google/cloud/spanner/spanner_client.bzl
  google/cloud/spanner/spanner_client_unit_tests.bzl
Labels: api: spanner, cla: yes

#5603 refactor: use absl::ParseTime rather than custom impl
  google/cloud/internal/parse_rfc3339.cc
  google/cloud/internal/parse_rfc3339.h
  google/cloud/internal/parse_rfc3339_test.cc
Labels: cla: yes

#5604 feature(generator): add utility functions to handle non LRO services
  generator/internal/codegen_utils.cc
  generator/internal/codegen_utils_test.cc
  generator/internal/predicate_utils.cc
  generator/internal/predicate_utils.h
  generator/internal/predicate_utils_test.cc
  generator/internal/service_code_generator.cc
  generator/internal/service_code_generator.h
Labels: cla: yes

#5608 feat(pubsub): add equality to Publisher
  google/cloud/pubsub/publisher.h
  google/cloud/pubsub/publisher_test.cc
Labels: api: pubsub, cla: yes

#5610 cleanup: include proto header w/ brackets
  google/cloud/bigtable/cluster_list_responses.h
  google/cloud/bigtable/instance_list_responses.h
Labels: cla: yes

#5615 chore: disable output buffering on shell printf
  ci/check-style.sh
Labels: cla: yes

#5616 chore: explicitly avoid printf builtin
  ci/check-style.sh
Labels: cla: yes

#5611 feat(spanner): add QueryOptions to Execute{Batch,Partitioned}Dml()
  ci/test-abi/spanner_client.expected.abi.dump.gz
  google/cloud/spanner/client.cc
  google/cloud/spanner/client.h
  google/cloud/spanner/connection.h
  google/cloud/spanner/internal/connection_impl.cc
Labels: api: spanner, cla: yes

#5618 ci: move cspell words to dictionary
  ci/cspell.json
  ci/custom-words.txt
Labels: cla: yes

#5617 feature(generator): conditionally generate longrunning includes and helpers
  generator/integration_tests/golden/internal/database_admin_logging_decorator.gcpcxx.pb.cc
  generator/integration_tests/golden/internal/database_admin_logging_decorator.gcpcxx.pb.h
  generator/integration_tests/golden/internal/database_admin_metadata_decorator.gcpcxx.pb.cc
  generator/integration_tests/golden/internal/database_admin_metadata_decorator.gcpcxx.pb.h
  generator/internal/logging_decorator_generator.cc
  generator/internal/metadata_decorator_generator.cc
  generator/internal/stub_factory_generator.cc
  generator/internal/stub_generator.cc
Labels: cla: yes

#5626 test: enable RPC tracing for integration tests
  ci/kokoro/docker/build-in-docker-bazel.sh
  ci/kokoro/docker/build-in-docker-cmake.sh
Labels: cla: yes

#5623 refactor(generator): product wide retry and connection option types to service specific
  generator/generator_test.cc
  generator/integration_tests/generator_integration_test.cc
  generator/integration_tests/golden/CMakeLists.txt
  generator/integration_tests/golden/connection_options.gcpcxx.pb.cc
  generator/integration_tests/golden/connection_options.gcpcxx.pb.h
  generator/integration_tests/golden/database_admin_connection.gcpcxx.pb.cc
  generator/integration_tests/golden/database_admin_connection.gcpcxx.pb.h
  generator/integration_tests/golden/golden_connection_options_test.cc
  generator/integration_tests/golden/golden_connection_test.cc
  generator/integration_tests/golden/golden_stub_factory_test.cc
  generator/integration_tests/golden/google_cloud_cpp_generator_golden_files.bzl
  generator/integration_tests/golden/google_cloud_cpp_generator_golden_tests.bzl
  generator/integration_tests/golden/internal/database_admin_stub_factory.gcpcxx.pb.cc
  generator/integration_tests/golden/internal/database_admin_stub_factory.gcpcxx.pb.h
  generator/integration_tests/golden/retry_policy.gcpcxx.pb.h
  generator/integration_tests/golden/retry_traits.h
  generator/internal/connection_generator.cc
  generator/internal/descriptor_utils.cc
  generator/internal/descriptor_utils_test.cc
  generator/internal/stub_factory_generator.cc
Labels: cla: yes

#5627 test(storage): enable service tracing for integration tests
  ci/kokoro/docker/build-in-docker-bazel.sh
  ci/kokoro/docker/build-in-docker-cmake.sh
Labels: api: storage, cla: yes

#5629 feature(generator): conditional generation of lro support in Client and Connection
  generator/internal/client_generator.cc
  generator/internal/connection_generator.cc
Labels: cla: yes

#5630 feature(generator): generate multiple services from proto file
  ci/custom-words.txt
  generator/integration_tests/generator_integration_test.cc
  generator/integration_tests/golden/CMakeLists.txt
  generator/integration_tests/golden/database_admin_client.gcpcxx.pb.h
  generator/integration_tests/golden/google_cloud_cpp_generator_golden_files.bzl
  generator/integration_tests/golden/google_cloud_cpp_generator_golden_tests.bzl
  generator/integration_tests/golden/iam_credentials_client.gcpcxx.pb.cc
  generator/integration_tests/golden/iam_credentials_client.gcpcxx.pb.h
  generator/integration_tests/golden/iam_credentials_client_test.cc
  generator/integration_tests/golden/iam_credentials_connection.gcpcxx.pb.cc
  generator/integration_tests/golden/iam_credentials_connection.gcpcxx.pb.h
  generator/integration_tests/golden/iam_credentials_connection_idempotency_policy.gcpcxx.pb.cc
  generator/integration_tests/golden/iam_credentials_connection_idempotency_policy.gcpcxx.pb.h
  generator/integration_tests/golden/iam_credentials_connection_test.cc
  generator/integration_tests/golden/iam_credentials_idempotency_policy_test.cc
  generator/integration_tests/golden/iam_credentials_logging_decorator_test.cc
  generator/integration_tests/golden/iam_credentials_metadata_decorator_test.cc
  generator/integration_tests/golden/iam_credentials_stub_factory_test.cc
  generator/integration_tests/golden/iam_credentials_stub_test.cc
  generator/integration_tests/golden/internal/iam_credentials_logging_decorator.gcpcxx.pb.cc
  generator/integration_tests/golden/internal/iam_credentials_logging_decorator.gcpcxx.pb.h
  generator/integration_tests/golden/internal/iam_credentials_metadata_decorator.gcpcxx.pb.cc
  generator/integration_tests/golden/internal/iam_credentials_metadata_decorator.gcpcxx.pb.h
  generator/integration_tests/golden/internal/iam_credentials_stub.gcpcxx.pb.cc
  generator/integration_tests/golden/internal/iam_credentials_stub.gcpcxx.pb.h
  generator/integration_tests/golden/internal/iam_credentials_stub_factory.gcpcxx.pb.cc
  generator/integration_tests/golden/internal/iam_credentials_stub_factory.gcpcxx.pb.h
  generator/integration_tests/golden/mocks/mock_iam_credentials_connection.gcpcxx.pb.h
  generator/integration_tests/golden/retry_traits.h
  generator/integration_tests/test.proto
Labels: cla: yes

#5633 fix(generator): unnecessary lro include in idempotency policy
  generator/integration_tests/golden/database_admin_connection_idempotency_policy.gcpcxx.pb.h
  generator/integration_tests/golden/iam_credentials_connection_idempotency_policy.gcpcxx.pb.h
  generator/internal/idempotency_policy_generator.cc
Labels: cla: yes

#5631 feat(spanner): remove CommitStats::overload_delay
  ci/test-abi/spanner_client.expected.abi.dump.gz
  google/cloud/spanner/client_test.cc
  google/cloud/spanner/commit_result.h
  google/cloud/spanner/internal/connection_impl.cc
  google/cloud/spanner/internal/connection_impl_test.cc
  google/cloud/spanner/samples/samples.cc
Labels: api: spanner, cla: yes

#5635 refactor(generator): change namespace containing mocks to align with existing products
  generator/integration_tests/golden/golden_client_test.cc
  generator/integration_tests/golden/iam_credentials_client_test.cc
  generator/integration_tests/golden/mocks/mock_database_admin_connection.gcpcxx.pb.h
  generator/integration_tests/golden/mocks/mock_iam_credentials_connection.gcpcxx.pb.h
  generator/internal/codegen_utils.cc
  generator/internal/codegen_utils.h
  generator/internal/mock_connection_generator.cc
Labels: cla: yes

#5632 feat(storage): propagate custom header with resumable upload PUT requests
  google/cloud/storage/emulator/emulator.py
  google/cloud/storage/internal/curl_client.cc
  google/cloud/storage/internal/curl_resumable_upload_session.cc
  google/cloud/storage/internal/curl_resumable_upload_session.h
  google/cloud/storage/tests/object_file_integration_test.cc
Labels: api: storage, cla: yes

#5636 test: revert service tracing for integration tests
  ci/kokoro/docker/build-in-docker-bazel.sh
  ci/kokoro/docker/build-in-docker-cmake.sh
Labels: cla: yes

#5637 docs: homogenize region tags
  google/cloud/spanner/samples/samples.cc
Labels: cla: yes

#5638 feature(generator): only include polling_loop if lro present
  generator/integration_tests/golden/iam_credentials_connection.gcpcxx.pb.cc
  generator/internal/connection_generator.cc
Labels: cla: yes

#5556 feat(bigtable): create logging layer for Cloud Bigtable
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/admin_client.cc
  google/cloud/bigtable/admin_client.h
  google/cloud/bigtable/bigtable_client.bzl
  google/cloud/bigtable/bigtable_client_unit_tests.bzl
  google/cloud/bigtable/internal/logging_admin_client.cc
  google/cloud/bigtable/internal/logging_admin_client.h
  google/cloud/bigtable/internal/logging_admin_client_test.cc
  google/cloud/bigtable/tests/admin_integration_test.cc
Labels: api: bigtable, cla: yes

#5639 feature(generator): accept commit hash from command line arg
  generator/internal/codegen_utils.cc
  generator/internal/codegen_utils_test.cc
Labels: cla: yes

#5641 refactor(generator): remove generation of default destructor in mocks
  generator/integration_tests/golden/mocks/mock_database_admin_connection.gcpcxx.pb.h
  generator/integration_tests/golden/mocks/mock_iam_credentials_connection.gcpcxx.pb.h
  generator/internal/mock_connection_generator.cc
Labels: cla: yes

#5644 fix(generator): emitting unnecessary includes and code with no lro or pagination
  generator/integration_tests/golden/database_admin_connection_idempotency_policy.gcpcxx.pb.cc
  generator/integration_tests/golden/iam_credentials_connection.gcpcxx.pb.cc
  generator/integration_tests/golden/iam_credentials_connection.gcpcxx.pb.h
  generator/integration_tests/golden/iam_credentials_connection_idempotency_policy.gcpcxx.pb.cc
  generator/integration_tests/golden/iam_credentials_connection_idempotency_policy.gcpcxx.pb.h
  generator/integration_tests/golden/iam_credentials_connection_test.cc
  generator/integration_tests/golden/internal/database_admin_logging_decorator.gcpcxx.pb.cc
  generator/integration_tests/golden/internal/database_admin_metadata_decorator.gcpcxx.pb.cc
  generator/integration_tests/golden/internal/database_admin_metadata_decorator.gcpcxx.pb.h
  generator/integration_tests/golden/internal/iam_credentials_logging_decorator.gcpcxx.pb.cc
  generator/integration_tests/golden/internal/iam_credentials_metadata_decorator.gcpcxx.pb.cc
  generator/integration_tests/golden/internal/iam_credentials_metadata_decorator.gcpcxx.pb.h
  generator/internal/connection_generator.cc
  generator/internal/idempotency_policy_generator.cc
  generator/internal/logging_decorator_generator.cc
  generator/internal/metadata_decorator_generator.cc
  generator/internal/predicate_utils.cc
  generator/internal/predicate_utils.h
  generator/internal/predicate_utils_test.cc
  generator/internal/service_code_generator.cc
  generator/internal/service_code_generator.h
Labels: cla: yes

#5645 feat(spanner): set protobuf request_options.priority fields
  google/cloud/spanner/internal/connection_impl.cc
  google/cloud/spanner/internal/connection_impl_test.cc
Labels: api: spanner, cla: yes

#5643 feature(iam): add IAMCredentials service library
  CMakeLists.txt
  ci/etc/integration-tests-config.ps1
  ci/etc/integration-tests-config.sh
  ci/kokoro/docker/build-in-docker-bazel.sh
  ci/kokoro/docker/build-in-docker-cmake.sh
  ci/kokoro/macos/build-bazel.sh
  ci/kokoro/windows/build-bazel.ps1
  external/googleapis/CMakeLists.txt
  google/cloud/CMakeLists.txt
  google/cloud/iam/BUILD
  google/cloud/iam/CMakeLists.txt
  google/cloud/iam/config.cmake.in
  google/cloud/iam/config.pc.in
  google/cloud/iam/iam_client.bzl
  google/cloud/iam/iam_client_mocks.bzl
  google/cloud/iam/iam_credentials_client.gcpcxx.pb.cc
  google/cloud/iam/iam_credentials_client.gcpcxx.pb.h
  google/cloud/iam/iam_credentials_connection.gcpcxx.pb.cc
  google/cloud/iam/iam_credentials_connection.gcpcxx.pb.h
  google/cloud/iam/iam_credentials_connection_idempotency_policy.gcpcxx.pb.cc
  google/cloud/iam/iam_credentials_connection_idempotency_policy.gcpcxx.pb.h
  google/cloud/iam/integration_tests/BUILD
  google/cloud/iam/integration_tests/CMakeLists.txt
  google/cloud/iam/integration_tests/iam_client_integration_tests.bzl
  google/cloud/iam/integration_tests/iam_credentials_integration_test.cc
  google/cloud/iam/internal/iam_credentials_logging_decorator.gcpcxx.pb.cc
  google/cloud/iam/internal/iam_credentials_logging_decorator.gcpcxx.pb.h
  google/cloud/iam/internal/iam_credentials_metadata_decorator.gcpcxx.pb.cc
  google/cloud/iam/internal/iam_credentials_metadata_decorator.gcpcxx.pb.h
  google/cloud/iam/internal/iam_credentials_stub.gcpcxx.pb.cc
  google/cloud/iam/internal/iam_credentials_stub.gcpcxx.pb.h
  google/cloud/iam/internal/iam_credentials_stub_factory.gcpcxx.pb.cc
  google/cloud/iam/internal/iam_credentials_stub_factory.gcpcxx.pb.h
  google/cloud/iam/mocks/mock_iam_credentials_connection.gcpcxx.pb.h
  google/cloud/iam/retry_traits.h
Labels: api: iam, cla: yes

#5651 fix(storage): incorrect CURL handle manipulation
  google/cloud/storage/internal/curl_handle_factory.cc
Labels: api: storage, cla: yes

#5652 feat(storage): add `UpdateBucket` for gRPC
  google/cloud/storage/emulator/grpc_server.py
  google/cloud/storage/internal/grpc_client.cc
  google/cloud/storage/internal/grpc_client.h
  google/cloud/storage/internal/grpc_client_bucket_request_test.cc
  google/cloud/storage/tests/grpc_integration_test.cc
Labels: api: storage, cla: yes

#5654 feat(bigtable): create logging layer for Cloud Bigtable DataClient
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/bigtable_client.bzl
  google/cloud/bigtable/bigtable_client_unit_tests.bzl
  google/cloud/bigtable/data_client.cc
  google/cloud/bigtable/data_client.h
  google/cloud/bigtable/internal/logging_data_client.cc
  google/cloud/bigtable/internal/logging_data_client.h
  google/cloud/bigtable/internal/logging_data_client_test.cc
Labels: api: bigtable, cla: yes

#5658 feat: add frequently mentioned proto libraries
  ci/kokoro/docker/build-in-docker-cmake.sh
  external/googleapis/CMakeLists.txt
  external/googleapis/config.cmake.in
Labels: cla: yes

#5659 fix(generator): handle package local and non-imported deduced lro response types
  generator/internal/descriptor_utils.cc
  generator/internal/descriptor_utils_test.cc
Labels: cla: yes

#5663 docs: cleanup unnecessary tagging
  google/cloud/spanner/samples/samples.cc
Labels: cla: yes

#5666 feat: allow cq actions in StartOperation
  google/cloud/completion_queue_test.cc
  google/cloud/internal/default_completion_queue_impl.cc
  google/cloud/internal/default_completion_queue_impl.h
Labels: cla: yes
