Repository googleapis/google-cloud-cpp, pull requests merged in 2021-06, with the labels that each got.

#6651 cleanup(storage): simplify gRPC plugin initialization
  google/cloud/storage/benchmarks/throughput_experiment.cc
  google/cloud/storage/examples/storage_grpc_samples.cc
  google/cloud/storage/grpc_plugin.cc
  google/cloud/storage/grpc_plugin.h
  google/cloud/storage/quickstart/grpc/quickstart.cc
  google/cloud/storage/tests/unified_credentials_integration_test.cc
Labels: api: storage, cla: yes

#6662 fix(pubsub): save refresh timer for cancellation
  google/cloud/pubsub/internal/subscription_lease_management.cc
Labels: api: pubsub, cla: yes

#6661 ci: split checkers build to its own Dockerfile
  ci/cloudbuild/dockerfiles/checkers.Dockerfile
  ci/cloudbuild/triggers/checkers-ci.yaml
  ci/cloudbuild/triggers/checkers-pr.yaml
Labels: cla: yes

#6659 feat(spanner): use multiple channels instead of multiple client for the multiple rows cpu benchmark
  google/cloud/spanner/benchmarks/README.md
  google/cloud/spanner/benchmarks/benchmarks_config.cc
  google/cloud/spanner/benchmarks/benchmarks_config.h
  google/cloud/spanner/benchmarks/benchmarks_config_test.cc
  google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
  google/cloud/spanner/benchmarks/single_row_throughput_benchmark.cc
Labels: cla: yes

#6663 ci: remove deps that are no longer needed
  ci/cloudbuild/dockerfiles/fedora-34.Dockerfile
Labels: cla: yes

#6660 ci: run sed checkers in parallel
  ci/cloudbuild/builds/checkers.sh
Labels: cla: yes

#6669 ci: fix test condition per devbww
  ci/cloudbuild/builds/checkers.sh
Labels: cla: yes

#6668 ci: move slow checkers last
  ci/cloudbuild/builds/checkers.sh
Labels: cla: yes

#6665 refactor(spanner): simplify multiple rows benchmark experiments
  google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
Labels: api: spanner, cla: yes

#6664 chore(deps): upgrade abseil to 20210324.2
  bazel/google_cloud_cpp_deps.bzl
  ci/abi-dumps/google_cloud_cpp_bigtable.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_common.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_grpc_utils.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_pubsub.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_spanner.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_storage.expected.abi.dump.gz
  ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile
  ci/cloudbuild/dockerfiles/demo-centos-8.Dockerfile
  ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile
  ci/cloudbuild/dockerfiles/demo-debian-stretch.Dockerfile
  ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile
  ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile
  ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile
  ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile
  ci/cloudbuild/dockerfiles/demo-ubuntu-xenial.Dockerfile
  ci/cloudbuild/dockerfiles/fedora-33.Dockerfile
  ci/cloudbuild/dockerfiles/fedora-34.Dockerfile
  ci/generate-markdown/generate-packaging.sh
  cmake/GoogleCloudCppCommon.cmake
  doc/packaging.md
  google/cloud/CMakeLists.txt
  google/cloud/bigquery/CMakeLists.txt
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/iam/CMakeLists.txt
  google/cloud/logging/CMakeLists.txt
  google/cloud/pubsub/CMakeLists.txt
  google/cloud/spanner/CMakeLists.txt
  google/cloud/storage/CMakeLists.txt
  super/external/abseil.cmake
Labels: cla: yes

#6667 chore: update CHANGELOG and abi dumps in preparation for release
  CHANGELOG.md
  ci/abi-dumps/google_cloud_cpp_bigtable.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_common.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_grpc_utils.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_pubsub.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_spanner.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_storage.expected.abi.dump.gz
Labels: cla: yes

#6666 feat(pubsub): direct Ack/Nack through SubscriberStub
  google/cloud/pubsub/internal/subscriber_logging.cc
  google/cloud/pubsub/internal/subscriber_logging.h
  google/cloud/pubsub/internal/subscriber_logging_test.cc
  google/cloud/pubsub/internal/subscriber_metadata.cc
  google/cloud/pubsub/internal/subscriber_metadata.h
  google/cloud/pubsub/internal/subscriber_metadata_test.cc
  google/cloud/pubsub/internal/subscriber_round_robin.cc
  google/cloud/pubsub/internal/subscriber_round_robin.h
  google/cloud/pubsub/internal/subscriber_round_robin_test.cc
  google/cloud/pubsub/internal/subscriber_stub.cc
  google/cloud/pubsub/internal/subscriber_stub.h
  google/cloud/pubsub/testing/mock_subscriber_stub.h
Labels: api: pubsub, cla: yes

#6673 chore: version bump
  CMakeLists.txt
  google/cloud/bigquery/quickstart/WORKSPACE
  google/cloud/bigtable/quickstart/WORKSPACE
  google/cloud/internal/version_info.h
  google/cloud/pubsub/quickstart/WORKSPACE
  google/cloud/spanner/quickstart/WORKSPACE
  google/cloud/storage/quickstart/WORKSPACE
  google/cloud/storage/quickstart/grpc/WORKSPACE
Labels: cla: yes

#6672 chore(deps): renovate-bot also updates packaging.md
  .github/renovate.json
Labels: cla: yes

#6674 feat(pubsub): use unary RPCs for Ack/Nack
  google/cloud/pubsub/internal/streaming_subscription_batch_source.cc
  google/cloud/pubsub/internal/streaming_subscription_batch_source.h
  google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc
  google/cloud/pubsub/internal/subscription_session_test.cc
  google/cloud/pubsub/subscriber_connection_test.cc
Labels: api: pubsub, cla: yes

#6679 ci: move coverage build to Fedora:34
  bazel/google_cloud_cpp_deps.bzl
  ci/cloudbuild/triggers/coverage-ci.yaml
  ci/cloudbuild/triggers/coverage-pr.yaml
Labels: cla: yes

#6681 ci(macos): homebrew tweaks to work on intel and ARM macs
  ci/kokoro/macos/build-cmake.sh
  ci/kokoro/macos/build.sh
Labels: cla: yes

#6684 ci(macos): use brew --prefix
  ci/kokoro/macos/build-cmake.sh
Labels: cla: yes

#6686 test(pubsub): reduce system entropy used by test
  google/cloud/pubsub/internal/subscription_message_queue_test.cc
Labels: api: pubsub, cla: yes

#6678 feat(pubsub): flow control for Publisher
  google/cloud/pubsub/CMakeLists.txt
  google/cloud/pubsub/google_cloud_cpp_pubsub.bzl
  google/cloud/pubsub/internal/flow_controlled_publisher_connection.cc
  google/cloud/pubsub/internal/flow_controlled_publisher_connection.h
  google/cloud/pubsub/internal/flow_controlled_publisher_connection_test.cc
  google/cloud/pubsub/publisher_connection.cc
  google/cloud/pubsub/publisher_connection_test.cc
  google/cloud/pubsub/publisher_option_test.cc
  google/cloud/pubsub/publisher_options.h
  google/cloud/pubsub/pubsub_client_unit_tests.bzl
Labels: api: pubsub, cla: yes

#6689 refactor(pubsub): match test filename to tested code
  google/cloud/pubsub/CMakeLists.txt
  google/cloud/pubsub/publisher_options_test.cc
  google/cloud/pubsub/pubsub_client_unit_tests.bzl
Labels: api: pubsub, cla: yes

#6688 ci: upgrade to vcpkg 2021.05.12 which understands Apple M1
  ci/cloudbuild/builds/quickstart-cmake.sh
  ci/kokoro/macos/build-quickstart-cmake.sh
  ci/kokoro/windows/build-cmake-dependencies.ps1
Labels: cla: yes

#6690 ci(macos): stop syncing macos clocks
  ci/kokoro/macos/build.sh
Labels: cla: yes

#6693 ci: log timestamp with io::log_h{1,2}
  ci/lib/io.sh
Labels: cla: yes

#6691 fix(spanner): pick up tracing-option defaults in SetBasicDefaults()
  google/cloud/spanner/client.h
  google/cloud/spanner/internal/defaults.cc
  google/cloud/spanner/internal/defaults_test.cc
Labels: api: spanner, cla: yes

#6694 ci(macos): cleanup logging output
  ci/cloudbuild/build.sh
  ci/kokoro/lib/cache.sh
  ci/kokoro/lib/gcloud.sh
  ci/kokoro/macos/build-bazel.sh
  ci/kokoro/macos/build-cmake.sh
  ci/kokoro/macos/build-quickstart-bazel.sh
  ci/kokoro/macos/build-quickstart-cmake.sh
  ci/kokoro/macos/build.sh
  ci/kokoro/macos/download-cache.sh
  ci/kokoro/macos/upload-cache.sh
Labels: cla: yes

#6695 test(common): also log streaming RPCs after test/sample failure
  ci/cloudbuild/builds/lib/integration.sh
  ci/kokoro/macos/build-bazel.sh
  ci/kokoro/macos/build-cmake.sh
  ci/kokoro/windows/build-bazel.ps1
  google/cloud/bigtable/ci/run_integration_tests_emulator_bazel.sh
  google/cloud/bigtable/ci/run_integration_tests_emulator_cmake.sh
  google/cloud/pubsub/ci/run_integration_tests_emulator_bazel.sh
  google/cloud/pubsub/ci/run_integration_tests_emulator_cmake.sh
  google/cloud/spanner/ci/run_integration_tests_emulator_cmake.sh
  google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh
  google/cloud/storage/ci/run_integration_tests_emulator_cmake.sh
Labels: cla: yes, samples

#6698 ci(macos): install ccache when needed
  ci/kokoro/macos/build-cmake.sh
  ci/kokoro/macos/build-quickstart-cmake.sh
Labels: cla: yes

#6701 ci(vcpkg): create lib/vcpkg.sh used by several builds
  ci/cloudbuild/builds/cmake-oldest-deps.sh
  ci/cloudbuild/builds/lib/vcpkg.sh
  ci/cloudbuild/builds/quickstart-cmake.sh
Labels: cla: yes

#6702 ci(cache): log cache file sizes
  ci/cloudbuild/cache.sh
Labels: cla: yes

#6708 ci: update builds to Fedora:34
  ci/cloudbuild/triggers/bazel-targets-ci.yaml
  ci/cloudbuild/triggers/bazel-targets-pr.yaml
  ci/cloudbuild/triggers/gcs-grpc-ci.yaml
  ci/cloudbuild/triggers/gcs-grpc-pr.yaml
  ci/cloudbuild/triggers/generate-libraries-ci.yaml
  ci/cloudbuild/triggers/generate-libraries-pr.yaml
  ci/cloudbuild/triggers/libcxx-ci.yaml
  ci/cloudbuild/triggers/libcxx-pr.yaml
Labels: cla: yes

#6710 cleanup(doc): remove doc/landing/...
  doc/landing/README.md
  doc/landing/index.html
  doc/landing/version-redirect.html
Labels: cla: yes

#6709 ci: update check-api build to Fedora:34
  ci/abi-dumps/google_cloud_cpp_bigtable.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_common.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_grpc_utils.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_pubsub.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_spanner.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_storage.expected.abi.dump.gz
  ci/cloudbuild/triggers/check-api-ci.yaml
  ci/cloudbuild/triggers/check-api-pr.yaml
Labels: cla: yes

#6696 feature(iam): add iam admin samples
  ci/cloudbuild/builds/integration-daily.sh
  ci/cloudbuild/builds/lib/integration.sh
  google/cloud/iam/CMakeLists.txt
  google/cloud/iam/samples/BUILD
  google/cloud/iam/samples/CMakeLists.txt
  google/cloud/iam/samples/iam_client_samples.bzl
  google/cloud/iam/samples/iam_samples.cc
Labels: api: iam, cla: yes, samples

#6712 ci(macos): simplify the brew install commands
  ci/kokoro/macos/build-cmake.sh
  ci/kokoro/macos/build-quickstart-cmake.sh
  ci/kokoro/macos/build.sh
Labels: cla: yes

#6714 chore: move doxygen config from doc/ -> ci/etc/doxygen
  ci/etc/doxygen/DoxygenLayout.xml
  cmake/GoogleCloudCppCommon.cmake
Labels: cla: yes

#6715 cleanup(bigtable): remove unused forward class declarations
  google/cloud/bigtable/admin_client.h
  google/cloud/bigtable/data_client.h
  google/cloud/bigtable/instance_admin_client.h
Labels: api: bigtable, cla: yes

#6716 ci: add a seconds delta to the "io" timestamps
  ci/cloudbuild/build.sh
  ci/lib/io.sh
Labels: cla: yes

#6725 cleanup(storage): reduce noise in debug log
  google/cloud/storage/internal/curl_handle.cc
  google/cloud/storage/internal/curl_handle.h
Labels: api: storage, cla: yes

#6722 cleanup(ci): use bash colon builtin to set vars with defaults
  ci/cloudbuild/build.sh
Labels: cla: yes

#6711 cleanup(bigtable)!: remove admin async integration tests
  CHANGELOG.md
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/async_list_app_profiles_test.cc
  google/cloud/bigtable/async_list_clusters_test.cc
  google/cloud/bigtable/async_list_instances_test.cc
  google/cloud/bigtable/bigtable_client_unit_tests.bzl
  google/cloud/bigtable/ci/run_integration_tests_emulator_bazel.sh
  google/cloud/bigtable/examples/table_admin_iam_policy_snippets.cc
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/instance_admin_test.cc
  google/cloud/bigtable/table_admin.cc
  google/cloud/bigtable/table_admin.h
  google/cloud/bigtable/table_admin_test.cc
  google/cloud/bigtable/tests/CMakeLists.txt
  google/cloud/bigtable/tests/admin_async_future_integration_test.cc
  google/cloud/bigtable/tests/admin_backup_async_future_integration_test.cc
  google/cloud/bigtable/tests/admin_iam_policy_integration_test.cc
  google/cloud/bigtable/tests/bigtable_client_integration_tests.bzl
  google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
  google/cloud/bigtable/tests/instance_admin_integration_test.cc
  google/cloud/bigtable/version.h
Labels: api: bigtable, cla: yes

#6723 cleanup: move Make*Connection overload to internal
  generator/integration_tests/golden/golden_kitchen_sink_connection.cc
  generator/integration_tests/golden/golden_kitchen_sink_connection.h
  generator/integration_tests/golden/golden_thing_admin_connection.cc
  generator/integration_tests/golden/golden_thing_admin_connection.h
  generator/integration_tests/golden/tests/golden_kitchen_sink_connection_test.cc
  generator/integration_tests/golden/tests/golden_thing_admin_connection_test.cc
  generator/internal/connection_generator.cc
  google/cloud/bigquery/bigquery_read_connection.cc
  google/cloud/bigquery/bigquery_read_connection.h
  google/cloud/iam/iam_connection.cc
  google/cloud/iam/iam_connection.h
  google/cloud/iam/iam_credentials_connection.cc
  google/cloud/iam/iam_credentials_connection.h
  google/cloud/logging/logging_service_v2_connection.cc
  google/cloud/logging/logging_service_v2_connection.h
Labels: cla: yes

#6728 feat: support background threads in generated libraries
  generator/integration_tests/golden/golden_kitchen_sink_connection.cc
  generator/integration_tests/golden/golden_thing_admin_connection.cc
  generator/internal/connection_generator.cc
  google/cloud/bigquery/bigquery_read_connection.cc
  google/cloud/iam/iam_connection.cc
  google/cloud/iam/iam_credentials_connection.cc
  google/cloud/logging/logging_service_v2_connection.cc
Labels: cla: yes

#6727 feature(spanner): add optimizer_statistics_package to QueryOptions
  google/cloud/spanner/client.cc
  google/cloud/spanner/client.h
  google/cloud/spanner/client_test.cc
  google/cloud/spanner/integration_tests/client_integration_test.cc
  google/cloud/spanner/internal/connection_impl.cc
  google/cloud/spanner/internal/connection_impl_test.cc
  google/cloud/spanner/query_options.h
  google/cloud/spanner/query_options_test.cc
  google/cloud/spanner/samples/samples.cc
Labels: api: spanner, cla: yes

#6736 ci(macos): print elapsed time in Ninja builds
  ci/kokoro/macos/build-cmake.sh
  ci/kokoro/macos/build-quickstart-cmake.sh
Labels: cla: yes

#6737 cleanup(storage): restore GCS+gRPC production integration tests
  ci/cloudbuild/builds/gcs-grpc.sh
  ci/cloudbuild/builds/install-gcs-grpc.sh
  ci/kokoro/macos/build-bazel.sh
  ci/kokoro/windows/build-bazel.ps1
  google/cloud/storage/benchmarks/throughput_experiment_test.cc
  google/cloud/storage/client_test.cc
  google/cloud/storage/internal/grpc_client.cc
Labels: api: storage, cla: yes

#6734 ci: use bazelisk to run the desired version of bazel
  ci/.dockerignore
  ci/cloudbuild/build.sh
  ci/cloudbuild/builds/lib/bazel.sh
  ci/cloudbuild/builds/lib/cmake.sh
  ci/cloudbuild/cloudbuild.yaml
  ci/cloudbuild/dockerfiles/fedora-34.Dockerfile
  ci/cloudbuild/dockerfiles/fedora-msan.Dockerfile
  ci/cloudbuild/dockerfiles/ubuntu-bionic.Dockerfile
  ci/cloudbuild/dockerfiles/ubuntu-focal.Dockerfile
  ci/etc/install-config.sh
  ci/install-bazel.sh
  ci/install-cloud-sdk.sh
  ci/kokoro/macos/build-bazel.sh
  ci/kokoro/macos/build-cmake.sh
  ci/kokoro/macos/build-quickstart-bazel.sh
  ci/kokoro/macos/build-quickstart-cmake.sh
  ci/kokoro/macos/build.sh
  ci/kokoro/macos/upload-cache.sh
Labels: cla: yes

#6738 chore: teach renovate how to update bazelisk
  .github/renovate.json
Labels: cla: yes

#6741 fix(ci): avoid centos-8 bug w/ dnf update
  ci/cloudbuild/dockerfiles/demo-centos-8.Dockerfile
  doc/packaging.md
Labels: cla: yes

#6739 ci: pass USE_BAZEL_VERSION to docker
  ci/cloudbuild/build.sh
Labels: cla: yes

#6745 refactor: move mock for GrpcAuthenticationStrategy
  google/cloud/storage/internal/storage_auth_test.cc
  google/cloud/testing_util/CMakeLists.txt
  google/cloud/testing_util/google_cloud_cpp_testing_grpc.bzl
  google/cloud/testing_util/mock_grpc_authentication_strategy.h
Labels: cla: yes

#6744 feat(generator): generators for auth decorator
  generator/CMakeLists.txt
  generator/generator_test.cc
  generator/google_cloud_cpp_generator.bzl
  generator/internal/auth_decorator_generator.cc
  generator/internal/auth_decorator_generator.h
  generator/internal/descriptor_utils.cc
Labels: cla: yes

#6747 ci(windows): use bazelisk
  ci/kokoro/windows/build-32.bat
  ci/kokoro/windows/build-bazel.ps1
  ci/kokoro/windows/build-quickstart-bazel.ps1
  ci/kokoro/windows/build.bat
Labels: cla: yes

#6748 ci(mac): refactor build scripts to look more like GCB scripts
  ci/kokoro/lib/cache.sh
  ci/kokoro/macos/build.sh
  ci/kokoro/macos/builds/bazel.sh
  ci/kokoro/macos/builds/cmake-super.sh
  ci/kokoro/macos/builds/quickstart-bazel.sh
  ci/kokoro/macos/builds/quickstart-cmake.sh
  ci/kokoro/macos/download-cache.sh
  ci/kokoro/macos/upload-cache.sh
Labels: cla: yes

#6751 ci: include link to all kokoro logs
  ci/cloudbuild/builds/log-linker.sh
Labels: cla: yes

#6750 feat: `*Auth` decorators for generated libraries
  google/cloud/bigquery/internal/bigquery_read_auth_decorator.cc
  google/cloud/bigquery/internal/bigquery_read_auth_decorator.h
  google/cloud/iam/internal/iam_auth_decorator.cc
  google/cloud/iam/internal/iam_auth_decorator.h
  google/cloud/iam/internal/iam_credentials_auth_decorator.cc
  google/cloud/iam/internal/iam_credentials_auth_decorator.h
  google/cloud/logging/internal/logging_service_v2_auth_decorator.cc
  google/cloud/logging/internal/logging_service_v2_auth_decorator.h
Labels: cla: yes

#6754 test(storage): more tests for backwards compability
  google/cloud/storage/tests/CMakeLists.txt
  google/cloud/storage/tests/create_client_integration_test.cc
  google/cloud/storage/tests/storage_client_integration_tests.bzl
Labels: api: storage, cla: yes

#6756 test(spanner): relax emulator SPANNER_STATISTICS expectation
  google/cloud/spanner/integration_tests/client_integration_test.cc
Labels: api: spanner, cla: yes

#6749 feat(generator): golden files for Auth decorators
  generator/integration_tests/golden/CMakeLists.txt
  generator/integration_tests/golden/google_cloud_cpp_generator_golden_tests.bzl
  generator/integration_tests/golden/internal/golden_kitchen_sink_auth_decorator.cc
  generator/integration_tests/golden/internal/golden_kitchen_sink_auth_decorator.h
  generator/integration_tests/golden/internal/golden_thing_admin_auth_decorator.cc
  generator/integration_tests/golden/internal/golden_thing_admin_auth_decorator.h
  generator/integration_tests/golden/tests/golden_kitchen_sink_auth_decorator_test.cc
  generator/integration_tests/golden/tests/golden_thing_admin_auth_decorator_test.cc
Labels: cla: yes

#6758 refactor: use helper to join testing::TempDir()
  generator/integration_tests/generator_integration_test.cc
  google/cloud/internal/filesystem.cc
  google/cloud/internal/filesystem.h
  google/cloud/internal/filesystem_test.cc
  google/cloud/internal/unified_grpc_credentials_test.cc
  google/cloud/storage/client_options_test.cc
  google/cloud/storage/internal/unified_rest_credentials_test.cc
  google/cloud/storage/oauth2/google_credentials_test.cc
  google/cloud/storage/oauth2/service_account_credentials_test.cc
  google/cloud/storage/testing/temp_file.cc
  google/cloud/storage/tests/object_file_integration_test.cc
Labels: cla: yes

#6766 chore: tweak renovate configuration
  .github/renovate.json
Labels: cla: yes

#6768 test(iam): disable flaky integration tests
  google/cloud/iam/integration_tests/iam_credentials_integration_test.cc
Labels: api: iam, cla: yes

#6759 chore: update googletest to 1.11.0
  bazel/google_cloud_cpp_deps.bzl
  ci/cloudbuild/dockerfiles/fedora-34.Dockerfile
  google/cloud/storage/benchmarks/throughput_result_test.cc
  google/cloud/testing_util/expect_exception.h
  super/external/googletest.cmake
Labels: cla: yes

#6773 ci: disable test result cache on CI builds
  ci/cloudbuild/builds/lib/bazel.sh
Labels: cla: yes

#6771 ci: run integration tests for generated libraries
  ci/cloudbuild/builds/lib/integration.sh
Labels: cla: yes

#6774 test(iam): disable more integration tests
  google/cloud/iam/integration_tests/iam_credentials_integration_test.cc
Labels: api: iam, cla: yes

#6775 ci: disable iam integration until its deflaked
  ci/cloudbuild/builds/lib/integration.sh
Labels: cla: yes

#6776 test(bigquery): enable integration tests in GCB builds
  ci/cloudbuild/builds/lib/integration.sh
Labels: api: bigquery, cla: yes

#6778 fix(iam): missing service account for credentials tests
  ci/cloudbuild/builds/lib/integration.sh
  ci/etc/integration-tests-config.ps1
  ci/etc/integration-tests-config.sh
  ci/kokoro/macos/builds/bazel.sh
  ci/kokoro/windows/build-bazel.ps1
  google/cloud/iam/integration_tests/iam_credentials_integration_test.cc
  google/cloud/iam/samples/iam_samples.cc
Labels: api: iam, cla: yes

#6777 cleanup(storage): handle cases in emulator where metadata is optional
  google/cloud/storage/emulator/emulator.py
Labels: api: storage, cla: yes

#6780 refactor: easier to change integration tests
  google/cloud/iam/integration_tests/iam_credentials_integration_test.cc
  google/cloud/iam/integration_tests/iam_integration_test.cc
  google/cloud/logging/integration_tests/logging_integration_test.cc
Labels: cla: yes

#6786 chore: update googleapis version
  bazel/google_cloud_cpp_deps.bzl
  external/googleapis/CMakeLists.txt
  google/cloud/bigquery/bigquery_read_client.h
  google/cloud/iam/iam_client.h
  google/cloud/iam/iam_credentials_client.h
  google/cloud/logging/logging_service_v2_client.h
Labels: cla: yes

#6784 doc(pubsub): an example for publisher flow control
  google/cloud/pubsub/samples/samples.cc
Labels: api: pubsub, cla: yes

#6782 ci: use Fedora:34 for msan build
  ci/cloudbuild/builds/lib/integration.sh
  ci/cloudbuild/builds/msan.sh
  ci/cloudbuild/dockerfiles/fedora-msan.Dockerfile
  generator/integration_tests/BUILD
  google/cloud/internal/filesystem.cc
Labels: cla: yes

#6765 feat(generator): support unified credentials
  generator/generator_test.cc
  generator/integration_tests/golden/golden_kitchen_sink_connection.cc
  generator/integration_tests/golden/golden_thing_admin_connection.cc
  generator/integration_tests/golden/internal/golden_kitchen_sink_stub_factory.cc
  generator/integration_tests/golden/internal/golden_kitchen_sink_stub_factory.h
  generator/integration_tests/golden/internal/golden_thing_admin_stub_factory.cc
  generator/integration_tests/golden/internal/golden_thing_admin_stub_factory.h
  generator/integration_tests/golden/tests/golden_kitchen_sink_stub_factory_test.cc
  generator/integration_tests/golden/tests/golden_thing_admin_stub_factory_test.cc
  generator/internal/connection_generator.cc
  generator/internal/descriptor_utils.cc
  generator/internal/stub_factory_generator.cc
  google/cloud/bigquery/CMakeLists.txt
  google/cloud/bigquery/bigquery_read_connection.cc
  google/cloud/bigquery/google_cloud_cpp_bigquery.bzl
  google/cloud/bigquery/integration_tests/bigquery_read_integration_test.cc
  google/cloud/bigquery/internal/bigquery_read_stub_factory.cc
  google/cloud/bigquery/internal/bigquery_read_stub_factory.h
  google/cloud/iam/CMakeLists.txt
  google/cloud/iam/google_cloud_cpp_iam.bzl
  google/cloud/iam/iam_connection.cc
  google/cloud/iam/iam_credentials_connection.cc
  google/cloud/iam/integration_tests/iam_credentials_integration_test.cc
  google/cloud/iam/integration_tests/iam_integration_test.cc
  google/cloud/iam/internal/iam_credentials_stub_factory.cc
  google/cloud/iam/internal/iam_credentials_stub_factory.h
  google/cloud/iam/internal/iam_stub_factory.cc
  google/cloud/iam/internal/iam_stub_factory.h
  google/cloud/logging/CMakeLists.txt
  google/cloud/logging/google_cloud_cpp_logging.bzl
  google/cloud/logging/integration_tests/logging_integration_test.cc
  google/cloud/logging/internal/logging_service_v2_stub_factory.cc
  google/cloud/logging/internal/logging_service_v2_stub_factory.h
  google/cloud/logging/logging_service_v2_connection.cc
Labels: cla: yes

#6788 cleanup(storage): revise error message in emulator handle_retry_test_instruction
  google/cloud/storage/emulator/utils/common.py
Labels: api: storage, cla: yes

#6789 cleanup(storage): remove nextPageToken field in emulator list operations
  google/cloud/storage/emulator/emulator.py
Labels: api: storage, cla: yes

#6791 test(pubsub): deflake BatchingPublisherConnection test
  google/cloud/pubsub/internal/batching_publisher_connection_test.cc
Labels: api: pubsub, cla: yes

#6790 test(storage): resumable uploads abort on errors
  google/cloud/storage/client_write_object_test.cc
Labels: api: storage, cla: yes

#6792 test(storage): deflake integration tests
  ci/cloudbuild/builds/lib/integration.sh
  google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh
  google/cloud/storage/emulator/ci/run_integration_tests_bazel.sh
  google/cloud/storage/tools/run_emulator_utils.sh
Labels: api: storage, cla: yes

#6795 ci: increase the GCB timeout
  ci/cloudbuild/cloudbuild.yaml
Labels: cla: yes

#6805 test(storage): deflake thread_integration_test
  google/cloud/storage/tests/thread_integration_test.cc
Labels: api: storage, cla: yes

#6806 ci(gcb): disable test caching on daily builds too
  ci/cloudbuild/builds/lib/bazel.sh
Labels: cla: yes

#6808 doc: contact us using Discussions or Issues
  .github/ISSUE_TEMPLATE/question.md
  README.md
  ci/generate-markdown/generate-readme.sh
Labels: cla: yes

#6804 feat(common): a generic long-running operation
  google/cloud/BUILD
  google/cloud/CMakeLists.txt
  google/cloud/google_cloud_cpp_grpc_utils.bzl
  google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl
  google/cloud/internal/async_long_running_operation.cc
  google/cloud/internal/async_long_running_operation.h
  google/cloud/internal/async_long_running_operation_test.cc
  google/cloud/internal/async_polling_loop.cc
  google/cloud/internal/async_polling_loop.h
  google/cloud/internal/async_polling_loop_test.cc
Labels: cla: yes

#6812 ci: use emulator for Spanner and Bazel
  ci/cloudbuild/builds/lib/integration.sh
  google/cloud/spanner/ci/lib/spanner_emulator.sh
  google/cloud/spanner/ci/run_integration_tests_emulator_bazel.sh
Labels: cla: yes

#6813 fix(common): remove blocking call in MinimalIamCredentials
  google/cloud/internal/minimal_iam_credentials_stub.cc
Labels: cla: yes

#6815 test(generator): fix crashes on test failure
  generator/integration_tests/generator_integration_test.cc
Labels: cla: yes

#6814 refactor(generator): de-duplicate mock stubs
  generator/integration_tests/golden/tests/golden_kitchen_sink_connection_test.cc
  generator/integration_tests/golden/tests/golden_kitchen_sink_metadata_decorator_test.cc
  generator/integration_tests/golden/tests/golden_thing_admin_connection_test.cc
  generator/integration_tests/golden/tests/golden_thing_admin_metadata_decorator_test.cc
Labels: cla: yes

#6816 fix(common): lifetime management in AsyncPollingLoop
  google/cloud/internal/async_polling_loop.cc
  google/cloud/internal/async_polling_loop_test.cc
Labels: cla: yes

#6820 refactor(common): move longrunning to value functions
  google/cloud/CMakeLists.txt
  google/cloud/google_cloud_cpp_grpc_utils.bzl
  google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl
  google/cloud/internal/async_long_running_operation.h
  google/cloud/internal/async_long_running_operation_test.cc
  google/cloud/internal/extract_long_running_result.cc
  google/cloud/internal/extract_long_running_result.h
  google/cloud/internal/extract_long_running_result_test.cc
Labels: cla: yes

#6822 feat(common): support response in long-running operations
  google/cloud/internal/async_long_running_operation.h
  google/cloud/internal/async_long_running_operation_test.cc
  google/cloud/internal/extract_long_running_result.cc
  google/cloud/internal/extract_long_running_result.h
  google/cloud/internal/extract_long_running_result_test.cc
Labels: cla: yes

#6825 cleanup(doc): master -> main
  ci/cloudbuild/builds/lib/bazel.sh
  ci/kokoro/macos/builds/bazel.sh
  ci/kokoro/macos/builds/quickstart-bazel.sh
  ci/kokoro/windows/build-bazel.ps1
  ci/kokoro/windows/build-quickstart-bazel.ps1
  google/cloud/bigquery/quickstart/README.md
  google/cloud/bigtable/doc/bigtable-hello-instance-admin.dox
  google/cloud/bigtable/doc/bigtable-hello-table-admin.dox
  google/cloud/bigtable/doc/bigtable-hello-world.dox
  google/cloud/bigtable/doc/bigtable-main.dox
  google/cloud/bigtable/doc/bigtable-samples-data-client.dox
  google/cloud/bigtable/doc/bigtable-samples-grpc-credentials.dox
  google/cloud/bigtable/quickstart/README.md
  google/cloud/pubsub/doc/pubsub-main.dox
  google/cloud/pubsub/quickstart/README.md
  google/cloud/spanner/doc/spanner-main.dox
  google/cloud/spanner/quickstart/README.md
  google/cloud/spanner/samples/README.md
  google/cloud/storage/doc/storage-main.dox
  google/cloud/storage/quickstart/README.md
Labels: cla: yes

#6823 refactor(common): re-use value extractors in synchronous polling loop
  google/cloud/internal/polling_loop.h
Labels: cla: yes

#6824 feat(common): long-running operations cancel support
  google/cloud/internal/async_long_running_operation.h
  google/cloud/internal/async_long_running_operation_test.cc
  google/cloud/internal/async_polling_loop.cc
  google/cloud/internal/async_polling_loop.h
  google/cloud/internal/async_polling_loop_test.cc
Labels: cla: yes

#6828 test(pubsub): deflake batching_publisher_connection_test
  google/cloud/pubsub/internal/batching_publisher_connection_test.cc
Labels: api: pubsub, cla: yes

#6829 chore: retrieve repo via vcpkg by commit hash
  ci/cloudbuild/builds/lib/vcpkg.sh
  ci/kokoro/macos/builds/quickstart-cmake.sh
  ci/kokoro/windows/build-cmake-dependencies.ps1
Labels: cla: yes

#6831 feat(common): cancel long-running operations
  google/cloud/internal/async_long_running_operation.h
  google/cloud/internal/async_long_running_operation_test.cc
  google/cloud/internal/async_polling_loop_test.cc
Labels: cla: yes

#6830 feat(generator): use async for long-running operations
  generator/integration_tests/golden/golden_thing_admin_connection.cc
  generator/integration_tests/golden/internal/golden_kitchen_sink_auth_decorator.h
  generator/integration_tests/golden/internal/golden_thing_admin_auth_decorator.cc
  generator/integration_tests/golden/internal/golden_thing_admin_auth_decorator.h
  generator/integration_tests/golden/internal/golden_thing_admin_logging_decorator.cc
  generator/integration_tests/golden/internal/golden_thing_admin_logging_decorator.h
  generator/integration_tests/golden/internal/golden_thing_admin_metadata_decorator.cc
  generator/integration_tests/golden/internal/golden_thing_admin_metadata_decorator.h
  generator/integration_tests/golden/internal/golden_thing_admin_stub.cc
  generator/integration_tests/golden/internal/golden_thing_admin_stub.h
  generator/integration_tests/golden/mocks/mock_golden_thing_admin_stub.h
  generator/integration_tests/golden/tests/golden_thing_admin_auth_decorator_test.cc
  generator/integration_tests/golden/tests/golden_thing_admin_connection_test.cc
  generator/integration_tests/golden/tests/golden_thing_admin_logging_decorator_test.cc
  generator/integration_tests/golden/tests/golden_thing_admin_metadata_decorator_test.cc
  generator/integration_tests/golden/tests/golden_thing_admin_stub_factory_test.cc
  generator/integration_tests/golden/tests/golden_thing_admin_stub_test.cc
  generator/internal/auth_decorator_generator.cc
  generator/internal/connection_generator.cc
  generator/internal/logging_decorator_generator.cc
  generator/internal/metadata_decorator_generator.cc
  generator/internal/stub_generator.cc
Labels: cla: yes

#6838 doc(bigtable): add IAM examples to Bigtable gRPC doc, fix typos/hyperlinks
  google/cloud/bigtable/doc/bigtable-main.dox
  google/cloud/bigtable/doc/bigtable-samples-grpc-credentials.dox
Labels: cla: yes

#6840 Revert "chore(deps): update dependency grpc/grpc to v1.38.1"
  ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile
  ci/cloudbuild/dockerfiles/demo-centos-8.Dockerfile
  ci/cloudbuild/dockerfiles/demo-debian-stretch.Dockerfile
  ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile
  ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile
  ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile
  ci/cloudbuild/dockerfiles/demo-ubuntu-xenial.Dockerfile
  doc/packaging.md
Labels: cla: yes

#6841 Revert "chore(deps): update dependency com_github_grpc_grpc to v1.38.1"
  bazel/google_cloud_cpp_deps.bzl
Labels: cla: yes

#6834 docs: fix connection pool size for samples
  google/cloud/bigtable/examples/data_snippets.cc
Labels: api: bigtable, cla: yes, samples

#6833 test(storage): tune bucket creation
  google/cloud/storage/tests/bucket_integration_test.cc
  google/cloud/storage/tests/grpc_integration_test.cc
  google/cloud/storage/tests/object_list_objects_versions_integration_test.cc
Labels: api: storage, cla: yes

#6837 ci: move CentOS 8 builds to Rocky Linux 8
  ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile
  ci/cloudbuild/triggers/demo-rockylinux-8-ci.yaml
  ci/cloudbuild/triggers/demo-rockylinux-8-pr.yaml
Labels: cla: yes

#6835 refactor(spanner): Use background threads for instance-admin LROs
  google/cloud/spanner/instance_admin_connection.cc
  google/cloud/spanner/instance_admin_connection_test.cc
  google/cloud/spanner/internal/instance_admin_logging.cc
  google/cloud/spanner/internal/instance_admin_logging.h
  google/cloud/spanner/internal/instance_admin_logging_test.cc
  google/cloud/spanner/internal/instance_admin_metadata.cc
  google/cloud/spanner/internal/instance_admin_metadata.h
  google/cloud/spanner/internal/instance_admin_metadata_test.cc
  google/cloud/spanner/internal/instance_admin_stub.cc
  google/cloud/spanner/internal/instance_admin_stub.h
  google/cloud/spanner/testing/mock_instance_admin_stub.h
Labels: api: spanner, cla: yes

#6839 doc(bigtable): revamp examples README
  google/cloud/bigtable/examples/README.md
  google/cloud/bigtable/quickstart/README.md
Labels: api: bigtable, cla: yes

#6846 chore(deps): upgrade pkg-config on CentOS-7 to avoid bug
  ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile
  doc/packaging.md
Labels: cla: yes

#6850 fix: cast to std::string which works with string and Cord
  google/cloud/pubsub/internal/batching_publisher_connection_test.cc
Labels: cla: yes

#6849 fix: include which breaks during our import
  google/cloud/internal/extract_long_running_result.h
Labels: cla: yes

#6851 cleanup(ci): dedupe integration envvars
  ci/cloudbuild/builds/lib/integration.sh
  ci/etc/integration-tests-config.ps1
  ci/etc/integration-tests-config.sh
  google/cloud/bigtable/ci/run_integration_tests_emulator_bazel.sh
  google/cloud/bigtable/ci/run_integration_tests_emulator_cmake.sh
  google/cloud/pubsub/ci/run_integration_tests_emulator_bazel.sh
  google/cloud/pubsub/ci/run_integration_tests_emulator_cmake.sh
  google/cloud/spanner/ci/run_integration_tests_emulator_bazel.sh
  google/cloud/spanner/ci/run_integration_tests_emulator_cmake.sh
  google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh
  google/cloud/storage/ci/run_integration_tests_emulator_cmake.sh
  google/cloud/storage/emulator/ci/run_integration_tests_bazel.sh
Labels: cla: yes

#6842 ci: remove CentOS 8 support files
  ci/cloudbuild/dockerfiles/demo-centos-8.Dockerfile
  ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile
  ci/cloudbuild/triggers/demo-centos-8-ci.yaml
  ci/cloudbuild/triggers/demo-centos-8-pr.yaml
  ci/generate-markdown/generate-packaging.sh
  doc/packaging.md
Labels: cla: yes

#6853 refactor(spanner): Use background threads for database-admin LROs
  google/cloud/spanner/database_admin_connection.cc
  google/cloud/spanner/database_admin_connection_test.cc
  google/cloud/spanner/internal/database_admin_logging.cc
  google/cloud/spanner/internal/database_admin_logging.h
  google/cloud/spanner/internal/database_admin_logging_test.cc
  google/cloud/spanner/internal/database_admin_metadata.cc
  google/cloud/spanner/internal/database_admin_metadata.h
  google/cloud/spanner/internal/database_admin_metadata_test.cc
  google/cloud/spanner/internal/database_admin_stub.cc
  google/cloud/spanner/internal/database_admin_stub.h
  google/cloud/spanner/testing/mock_database_admin_stub.h
Labels: api: spanner, cla: yes

#6847 feat(bigtable): add Backup IAM Policy snippets
  google/cloud/bigtable/examples/bigtable_table_admin_backup_snippets.cc
  google/cloud/bigtable/table_admin.h
Labels: api: bigtable, cla: yes

#6852 cleanup(storage): remove resourceId from emulator Bucket.set_iam_policy
  google/cloud/storage/emulator/gcs/bucket.py
Labels: api: storage, cla: yes

#6857 ci(cmake): ctest will print output from failed tests
  ci/cloudbuild/builds/lib/cmake.sh
Labels: cla: yes

#6859 cleanup: bigtable emulator scripts
  ci/cloudbuild/builds/lib/integration.sh
  google/cloud/bigtable/ci/run_integration_tests_emulator_cmake.sh
  google/cloud/bigtable/tools/run_emulator_utils.sh
Labels: cla: yes

#6858 test(pubsub): deflake batching_publisher_connection
  google/cloud/pubsub/internal/batching_publisher_connection_test.cc
Labels: api: pubsub, cla: yes

#6855 fix(common): synchronize cancel for long-running operations
  google/cloud/internal/async_polling_loop.cc
  google/cloud/spanner/database_admin_connection_test.cc
Labels: cla: yes

#6863 cleanup(doc): fix some links
  doc/contributor/howto-guide-setup-development-workstation.md
  google/cloud/examples/README.md
Labels: cla: yes

#6862 cleanup(bigtable): miscellaneous example cleaning
  google/cloud/bigtable/doc/bigtable-hello-instance-admin.dox
  google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc
  google/cloud/bigtable/examples/bigtable_table_admin_backup_snippets.cc
  google/cloud/bigtable/examples/data_async_snippets.cc
  google/cloud/bigtable/examples/data_snippets.cc
  google/cloud/bigtable/examples/table_admin_iam_policy_snippets.cc
Labels: api: bigtable, cla: yes

#6865 chore: update googleapis version
  bazel/google_cloud_cpp_deps.bzl
  external/googleapis/CMakeLists.txt
  google/cloud/bigquery/bigquery_read_client.h
  google/cloud/iam/iam_client.h
  google/cloud/iam/iam_credentials_client.h
  google/cloud/logging/logging_service_v2_client.h
Labels: cla: yes

#6867 cleanup(bigtable): fix AsyncReadRowsWithLimit example
  google/cloud/bigtable/examples/data_async_snippets.cc
  google/cloud/bigtable/examples/read_snippets.cc
Labels: api: bigtable, cla: yes

#6866 cleanup(spanner): Prefer absl::make_unique<T>() over std::unique_ptr<T>(new T)
  google/cloud/spanner/internal/database_admin_logging_test.cc
  google/cloud/spanner/internal/database_admin_metadata_test.cc
  google/cloud/spanner/internal/instance_admin_logging_test.cc
  google/cloud/spanner/internal/instance_admin_metadata_test.cc
  google/cloud/spanner/internal/partial_result_set_source_test.cc
  google/cloud/spanner/samples/mock_execute_query.cc
Labels: api: spanner, cla: yes

#6845 test: improve output for troubleshooting
  google/cloud/examples/grpc_credential_types.cc
Labels: cla: yes

#6869 cleanup(bigtable): delete extraneous example tests
  google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc
  google/cloud/bigtable/examples/data_snippets.cc
Labels: api: bigtable, cla: yes

#6871 cleanup(storage): run benchmarks with fewer privileges
  google/cloud/storage/benchmarks/storage_file_transfer_benchmark.cc
  google/cloud/storage/benchmarks/storage_parallel_uploads_benchmark.cc
  google/cloud/storage/benchmarks/storage_shard_throughput_benchmark.cc
  google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc
Labels: api: storage, cla: yes

#6870 fix(storage): crashes with tracing enabled
  google/cloud/storage/internal/curl_handle.cc
  google/cloud/storage/internal/curl_handle.h
  google/cloud/storage/tests/CMakeLists.txt
  google/cloud/storage/tests/storage_client_integration_tests.bzl
  google/cloud/storage/tests/tracing_integration_test.cc
Labels: api: storage, cla: yes

#6864 fix(storage): alternative endpoints and Host header
  ci/cloudbuild/builds/lib/integration.sh
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh
  google/cloud/storage/internal/curl_client.cc
  google/cloud/storage/internal/curl_client.h
  google/cloud/storage/internal/curl_client_test.cc
  google/cloud/storage/internal/curl_wrappers.cc
  google/cloud/storage/internal/curl_wrappers.h
  google/cloud/storage/internal/curl_wrappers_test.cc
  google/cloud/storage/storage_client_unit_tests.bzl
  google/cloud/storage/tests/CMakeLists.txt
  google/cloud/storage/tests/alternative_endpoint_integration_test.cc
  google/cloud/storage/tests/storage_client_integration_tests.bzl
Labels: api: storage, cla: yes

#6874 feat(storage): make auto-finalization optional
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/auto_finalize.cc
  google/cloud/storage/auto_finalize.h
  google/cloud/storage/auto_finalize_test.cc
  google/cloud/storage/client.cc
  google/cloud/storage/client.h
  google/cloud/storage/examples/storage_object_resumable_write_samples.cc
  google/cloud/storage/google_cloud_cpp_storage.bzl
  google/cloud/storage/internal/object_requests.h
  google/cloud/storage/internal/object_streambuf.cc
  google/cloud/storage/internal/object_streambuf.h
  google/cloud/storage/internal/object_streambuf_test.cc
  google/cloud/storage/object_stream.cc
  google/cloud/storage/object_stream.h
  google/cloud/storage/object_stream_test.cc
  google/cloud/storage/parallel_upload.cc
  google/cloud/storage/storage_client_unit_tests.bzl
  google/cloud/storage/tests/CMakeLists.txt
  google/cloud/storage/tests/auto_finalize_integration_test.cc
  google/cloud/storage/tests/object_write_streambuf_integration_test.cc
  google/cloud/storage/tests/storage_client_integration_tests.bzl
Labels: api: storage, cla: yes

#6877 cleanup(storage): remove obsolete TODO entry
  google/cloud/storage/internal/grpc_client_test.cc
Labels: api: storage, cla: yes

#6876 cleanup(common): avoid spurious warnings
  google/cloud/internal/streaming_read_rpc.h
Labels: cla: yes

#6879 ci: use cache_test_results=auto for non-ci/daily bazel builds
  ci/cloudbuild/builds/lib/bazel.sh
Labels: cla: yes

#6882 feat(storage): share client in throughput benchmark
  google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc
  google/cloud/storage/benchmarks/throughput_experiment.cc
  google/cloud/storage/benchmarks/throughput_experiment.h
  google/cloud/storage/benchmarks/throughput_experiment_test.cc
  google/cloud/storage/benchmarks/throughput_options.cc
  google/cloud/storage/benchmarks/throughput_options.h
  google/cloud/storage/benchmarks/throughput_options_test.cc
Labels: api: storage, cla: yes

#6881 fix(GCS+gRPC): resumable uploads can resume
  google/cloud/storage/emulator/grpc_server.py
  google/cloud/storage/internal/grpc_resumable_upload_session.cc
  google/cloud/storage/internal/grpc_resumable_upload_session.h
  google/cloud/storage/internal/grpc_resumable_upload_session_test.cc
  google/cloud/storage/tests/auto_finalize_integration_test.cc
  google/cloud/storage/tests/grpc_integration_test.cc
Labels: cla: yes

#6886 cleanup(storage): enable more integration tests with gRPC
  google/cloud/storage/tests/object_media_integration_test.cc
  google/cloud/storage/tests/object_resumable_write_integration_test.cc
Labels: api: storage, cla: yes

#6755 feat(storage): implement "public access prevention"
  google/cloud/storage/bucket_metadata.cc
  google/cloud/storage/bucket_metadata.h
  google/cloud/storage/bucket_metadata_test.cc
  google/cloud/storage/emulator/gcs/bucket.py
  google/cloud/storage/examples/storage_bucket_samples.cc
  google/cloud/storage/internal/bucket_metadata_parser.cc
  google/cloud/storage/internal/grpc_client_bucket_metadata_test.cc
  google/cloud/storage/tests/bucket_integration_test.cc
Labels: api: storage, cla: yes

#6887 feat(storage): create datasets for benchmarks
  google/cloud/storage/benchmarks/CMakeLists.txt
  google/cloud/storage/benchmarks/benchmark_utils.cc
  google/cloud/storage/benchmarks/benchmark_utils.h
  google/cloud/storage/benchmarks/create_dataset.cc
  google/cloud/storage/benchmarks/create_dataset_options.cc
  google/cloud/storage/benchmarks/create_dataset_options.h
  google/cloud/storage/benchmarks/create_dataset_options_test.cc
  google/cloud/storage/benchmarks/storage_benchmark_programs.bzl
  google/cloud/storage/benchmarks/storage_benchmarks.bzl
  google/cloud/storage/benchmarks/storage_benchmarks_unit_tests.bzl
Labels: api: storage, cla: yes

#6889 cleanup(storage): reduce tracing noise
  google/cloud/storage/internal/object_streambuf.cc
Labels: api: storage, cla: yes

#6890 cleanup(generator): remove additional mock dups
  generator/integration_tests/golden/mocks/mock_golden_kitchen_sink_stub.h
  generator/integration_tests/golden/tests/golden_kitchen_sink_connection_test.cc
  generator/integration_tests/golden/tests/golden_kitchen_sink_logging_decorator_test.cc
  generator/integration_tests/golden/tests/golden_kitchen_sink_metadata_decorator_test.cc
Labels: cla: yes

#6891 fix(GCS+gRPC): avoid duplicate headers in downloads
  google/cloud/storage/internal/grpc_object_read_source.cc
  google/cloud/storage/internal/grpc_object_read_source.h
  google/cloud/storage/internal/grpc_object_read_source_test.cc
Labels: cla: yes

#6892 feat(storage): micro-optimization for downloads
  google/cloud/storage/internal/object_streambuf.cc
Labels: api: storage, cla: yes

#6897 fix(storage): treat 304 errors as kFailedPrecondition
  google/cloud/storage/examples/CMakeLists.txt
  google/cloud/storage/examples/storage_examples.bzl
  google/cloud/storage/examples/storage_object_preconditions_samples.cc
  google/cloud/storage/internal/http_response.cc
  google/cloud/storage/internal/http_response.h
  google/cloud/storage/internal/http_response_test.cc
  google/cloud/storage/tests/CMakeLists.txt
  google/cloud/storage/tests/object_read_preconditions_integration_test.cc
  google/cloud/storage/tests/storage_client_integration_tests.bzl
Labels: api: storage, cla: yes

#6899 fix(ci): fix iam account flag when deleting keys
  ci/cloudbuild/builds/rotate-keys.sh
Labels: cla: yes

#6901 cleanup(spanner): remove empty options.cc
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/google_cloud_cpp_spanner.bzl
  google/cloud/spanner/options.cc
Labels: api: spanner, cla: yes

#6900 fix(storage): use JSON for reads with pre-conditions
  google/cloud/storage/internal/curl_client.cc
  google/cloud/storage/tests/object_read_preconditions_integration_test.cc
Labels: api: storage, cla: yes

#6898 test(storage): deflake benchmark integration test
  google/cloud/storage/benchmarks/throughput_experiment_test.cc
Labels: api: storage, cla: yes

#6888 ci(spanner): run spanner integration tests against prod
  ci/cloudbuild/builds/integration-daily.sh
  ci/cloudbuild/builds/lib/integration.sh
  google/cloud/spanner/testing/policies.h
Labels: api: spanner, cla: yes

#6895 feature(spanner): low-cost instances
  google/cloud/spanner/create_instance_request_builder.h
  google/cloud/spanner/create_instance_request_builder_test.cc
  google/cloud/spanner/samples/samples.cc
  google/cloud/spanner/update_instance_request_builder.h
  google/cloud/spanner/update_instance_request_builder_test.cc
Labels: api: spanner, cla: yes

#6904 test(storage): verify writes with pre-conditions work
  google/cloud/storage/tests/CMakeLists.txt
  google/cloud/storage/tests/object_write_preconditions_integration_test.cc
  google/cloud/storage/tests/storage_client_integration_tests.bzl
Labels: api: storage, cla: yes
