Repository googleapis/google-cloud-cpp, pull requests merged in 2021-02, with the labels that each got.

#5780 doc: better define the public interface
  README.md
  ci/generate-markdown/generate-readme.sh
Labels: cla: yes

#5787 feat(spanner): rollback CommitStats prior to Feb release
  ci/test-abi/google_cloud_cpp_spanner.expected.abi.dump.gz
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/client.cc
  google/cloud/spanner/client.h
  google/cloud/spanner/client_test.cc
  google/cloud/spanner/commit_options.h
  google/cloud/spanner/commit_options_test.cc
  google/cloud/spanner/commit_result.h
  google/cloud/spanner/connection.h
  google/cloud/spanner/google_cloud_cpp_spanner.bzl
  google/cloud/spanner/internal/connection_impl.cc
  google/cloud/spanner/internal/connection_impl_test.cc
  google/cloud/spanner/samples/samples.cc
  google/cloud/spanner/spanner_client_unit_tests.bzl
Labels: api: spanner, cla: yes

#5786 chore: update CHANGELOG and ABI dumps
  CHANGELOG.md
  ci/test-abi/google_cloud_cpp_bigtable.expected.abi.dump.gz
  ci/test-abi/google_cloud_cpp_common.expected.abi.dump.gz
  ci/test-abi/google_cloud_cpp_grpc_utils.expected.abi.dump.gz
  ci/test-abi/google_cloud_cpp_pubsub.expected.abi.dump.gz
  ci/test-abi/google_cloud_cpp_spanner.expected.abi.dump.gz
  ci/test-abi/google_cloud_cpp_storage.expected.abi.dump.gz
Labels: cla: yes

#5789 chore: bump version numbers post v1.24.0 release
  CMakeLists.txt
  google/cloud/bigtable/quickstart/WORKSPACE
  google/cloud/internal/version_info.h
  google/cloud/pubsub/quickstart/WORKSPACE
  google/cloud/spanner/quickstart/WORKSPACE
  google/cloud/storage/quickstart/WORKSPACE
Labels: cla: yes

#5792 cleanup: use new top-level targets for quickstart
  google/cloud/bigtable/quickstart/BUILD
  google/cloud/bigtable/quickstart/WORKSPACE
  google/cloud/pubsub/quickstart/BUILD
  google/cloud/pubsub/quickstart/WORKSPACE
  google/cloud/spanner/quickstart/BUILD
  google/cloud/spanner/quickstart/WORKSPACE
  google/cloud/storage/quickstart/BUILD
  google/cloud/storage/quickstart/WORKSPACE
Labels: cla: yes

#5795 ci: temporary disable flask debug
  google/cloud/storage/emulator/emulator.py
  google/cloud/storage/emulator/gcs/iam.py
  google/cloud/storage/emulator/gcs/project.py
Labels: cla: yes

#5794 ci: install llvm-9 package
  ci/kokoro/docker/Dockerfile.ubuntu
Labels: cla: yes

#5798 fix(storage): remove unneeded dependency
  google/cloud/storage/legacy.cmake.in
Labels: api: storage, cla: yes

#5799 cleanup: use case insensitive absl::ParseTime
  google/cloud/internal/parse_rfc3339.cc
Labels: cla: yes

#5801 fix(common): streaming RPC permanent error handling
  google/cloud/internal/resumable_streaming_read_rpc.h
  google/cloud/internal/resumable_streaming_read_rpc_test.cc
Labels: cla: yes

#5800 doc: add Abseil as a packaging dep
  ci/generate-markdown/generate-packaging.sh
  doc/packaging.md
Labels: cla: yes

#5802 ci: update vcpkg version
  ci/kokoro/docker/build-in-docker-quickstart-cmake.sh
  ci/kokoro/macos/build-quickstart-cmake.sh
  ci/kokoro/windows/build-cmake-dependencies.ps1
Labels: cla: yes

#5804 cleanup: quickstarts use google-cloud-cpp:: targets
  ci/generate-markdown/generate-packaging.sh
  ci/kokoro/docker/build-in-docker-quickstart-cmake.sh
  ci/kokoro/macos/build-quickstart-cmake.sh
  ci/kokoro/windows/build-cmake-dependencies.ps1
  doc/packaging.md
  google/cloud/bigtable/quickstart/CMakeLists.txt
  google/cloud/pubsub/quickstart/CMakeLists.txt
  google/cloud/spanner/quickstart/CMakeLists.txt
  google/cloud/storage/quickstart/CMakeLists.txt
Labels: cla: yes

#5806 clean: remove outdated comments about throwing exceptions
  google/cloud/bigtable/internal/readrowsparser.h
  google/cloud/bigtable/row_reader.h
  google/cloud/bigtable/table_admin.h
Labels: cla: yes

#5807 feat(storage): use correct load balancer for direct path
  google/cloud/storage/internal/grpc_client.cc
Labels: api: storage, cla: yes

#5808 test: detect OS using standard Bazel configs
  google/cloud/testing_util/BUILD
Labels: cla: yes

#5805 feature(generator): add utils for streaming read generation
  generator/internal/descriptor_utils.cc
  generator/internal/descriptor_utils_test.cc
  generator/internal/predicate_utils.cc
  generator/internal/predicate_utils.h
  generator/internal/predicate_utils_test.cc
  generator/internal/service_code_generator.cc
  generator/internal/service_code_generator.h
Labels: cla: yes

#5811 feat: make StreamRange<T> public
  google/cloud/CMakeLists.txt
  google/cloud/google_cloud_cpp_common.bzl
  google/cloud/google_cloud_cpp_common_unit_tests.bzl
  google/cloud/internal/pagination_range.h
  google/cloud/stream_range.h
  google/cloud/stream_range_test.cc
Labels: cla: yes

#5812 ci: remove redundant vcpkg-quickstart-cache
  ci/kokoro/docker/Dockerfile.ubuntu
  ci/kokoro/docker/build-in-docker-quickstart-cmake.sh
  ci/kokoro/docker/upload-cache.sh
  ci/kokoro/macos/build-quickstart-cmake.sh
Labels: cla: yes

#5815 test(spanner): run slow integration tests in nightly build
  ci/kokoro/docker/build.sh
Labels: api: spanner, cla: yes

#5748 feature(generator): add support for streaming read rpcs
  generator/integration_tests/BUILD
  generator/integration_tests/golden/BUILD
  generator/integration_tests/golden/CMakeLists.txt
  generator/integration_tests/golden/database_admin_client.gcpcxx.pb.h
  generator/integration_tests/golden/golden_logging_decorator_test.cc
  generator/integration_tests/golden/google_cloud_cpp_generator_golden_files.bzl
  generator/integration_tests/golden/iam_credentials_client.gcpcxx.pb.cc
  generator/integration_tests/golden/iam_credentials_client.gcpcxx.pb.h
  generator/integration_tests/golden/iam_credentials_client_test.cc
  generator/integration_tests/golden/iam_credentials_connection.gcpcxx.pb.cc
  generator/integration_tests/golden/iam_credentials_connection.gcpcxx.pb.h
  generator/integration_tests/golden/iam_credentials_connection_test.cc
  generator/integration_tests/golden/iam_credentials_logging_decorator_test.cc
  generator/integration_tests/golden/iam_credentials_metadata_decorator_test.cc
  generator/integration_tests/golden/iam_credentials_stub_test.cc
  generator/integration_tests/golden/internal/database_admin_logging_decorator.gcpcxx.pb.cc
  generator/integration_tests/golden/internal/database_admin_logging_decorator.gcpcxx.pb.h
  generator/integration_tests/golden/internal/database_admin_stub_factory.gcpcxx.pb.cc
  generator/integration_tests/golden/internal/iam_credentials_logging_decorator.gcpcxx.pb.cc
  generator/integration_tests/golden/internal/iam_credentials_logging_decorator.gcpcxx.pb.h
  generator/integration_tests/golden/internal/iam_credentials_metadata_decorator.gcpcxx.pb.cc
  generator/integration_tests/golden/internal/iam_credentials_metadata_decorator.gcpcxx.pb.h
  generator/integration_tests/golden/internal/iam_credentials_stub.gcpcxx.pb.cc
  generator/integration_tests/golden/internal/iam_credentials_stub.gcpcxx.pb.h
  generator/integration_tests/golden/internal/iam_credentials_stub_factory.gcpcxx.pb.cc
  generator/integration_tests/golden/mocks/mock_iam_credentials_connection.gcpcxx.pb.h
  generator/integration_tests/golden/streaming.cc
  generator/integration_tests/test.proto
  generator/internal/client_generator.cc
  generator/internal/connection_generator.cc
  generator/internal/logging_decorator_generator.cc
  generator/internal/metadata_decorator_generator.cc
  generator/internal/mock_connection_generator.cc
  generator/internal/stub_factory_generator.cc
  generator/internal/stub_generator.cc
  google/cloud/connection_options.h
Labels: cla: yes

#5817 doc(spanner): document CleanupStaleInstances()
  google/cloud/spanner/testing/cleanup_stale_instances.cc
  google/cloud/spanner/testing/cleanup_stale_instances.h
Labels: api: spanner, cla: yes

#5816 ci: cache vcpkg binary
  ci/kokoro/docker/build-in-docker-quickstart-cmake.sh
  ci/kokoro/macos/build-quickstart-cmake.sh
  ci/kokoro/macos/upload-cache.sh
Labels: cla: yes

#5822 ci: only cache certain .cache/ dirs
  ci/kokoro/docker/upload-cache.sh
  ci/kokoro/macos/upload-cache.sh
Labels: cla: yes

#5826 ci: deflake downloads for roots.pem
  ci/kokoro/macos/build-quickstart-bazel.sh
  ci/kokoro/macos/build-quickstart-cmake.sh
  ci/kokoro/macos/build.sh
  ci/kokoro/windows/build-bazel.ps1
  ci/kokoro/windows/build-cmake.ps1
  ci/kokoro/windows/build-quickstart-bazel.ps1
  ci/kokoro/windows/build-quickstart-cmake.ps1
Labels: cla: yes

#5830 cleanup(common): use bug number for TODO
  google/cloud/future_generic_test.cc
Labels: cla: yes

#5829 cleanup(storage): error streams cannot validate data
  google/cloud/storage/internal/object_streambuf.cc
Labels: api: storage, cla: yes

#5820 refactor(generator): remove range type aliases
  generator/integration_tests/golden/database_admin_client.gcpcxx.pb.cc
  generator/integration_tests/golden/database_admin_client.gcpcxx.pb.h
  generator/integration_tests/golden/database_admin_connection.gcpcxx.pb.cc
  generator/integration_tests/golden/database_admin_connection.gcpcxx.pb.h
  generator/integration_tests/golden/golden_client_test.cc
  generator/integration_tests/golden/iam_credentials_client.gcpcxx.pb.cc
  generator/integration_tests/golden/iam_credentials_client.gcpcxx.pb.h
  generator/integration_tests/golden/iam_credentials_client_test.cc
  generator/integration_tests/golden/iam_credentials_connection.gcpcxx.pb.cc
  generator/integration_tests/golden/iam_credentials_connection.gcpcxx.pb.h
  generator/integration_tests/golden/mocks/mock_database_admin_connection.gcpcxx.pb.h
  generator/integration_tests/golden/mocks/mock_iam_credentials_connection.gcpcxx.pb.h
  generator/internal/client_generator.cc
  generator/internal/connection_generator.cc
  generator/internal/mock_connection_generator.cc
Labels: cla: yes

#5823 chore(generator): relocate golden unit tests to enable clang-formatting
  ci/check-style.sh
  generator/integration_tests/golden/.clang-format
  generator/integration_tests/golden/CMakeLists.txt
  generator/integration_tests/golden/google_cloud_cpp_generator_golden_tests.bzl
  generator/integration_tests/golden/tests/.clang-format
  generator/integration_tests/golden/tests/golden_client_test.cc
  generator/integration_tests/golden/tests/golden_connection_test.cc
  generator/integration_tests/golden/tests/golden_idempotency_policy_test.cc
  generator/integration_tests/golden/tests/golden_logging_decorator_test.cc
  generator/integration_tests/golden/tests/golden_metadata_decorator_test.cc
  generator/integration_tests/golden/tests/golden_stub_factory_test.cc
  generator/integration_tests/golden/tests/golden_stub_test.cc
  generator/integration_tests/golden/tests/iam_credentials_client_test.cc
  generator/integration_tests/golden/tests/iam_credentials_connection_test.cc
  generator/integration_tests/golden/tests/iam_credentials_idempotency_policy_test.cc
  generator/integration_tests/golden/tests/iam_credentials_logging_decorator_test.cc
  generator/integration_tests/golden/tests/iam_credentials_metadata_decorator_test.cc
  generator/integration_tests/golden/tests/iam_credentials_stub_factory_test.cc
  generator/integration_tests/golden/tests/iam_credentials_stub_test.cc
Labels: cla: yes

#5831 chore: upgrade googleapis to current head
  bazel/google_cloud_cpp_deps.bzl
  ci/etc/generator-googleapis-commit-hash.sh
  external/googleapis/CMakeLists.txt
  google/cloud/iam/iam_credentials_client.gcpcxx.pb.h
  google/cloud/iam/internal/iam_credentials_logging_decorator.gcpcxx.pb.cc
  google/cloud/iam/internal/iam_credentials_logging_decorator.gcpcxx.pb.h
  google/cloud/iam/internal/iam_credentials_stub_factory.gcpcxx.pb.cc
  google/cloud/logging/internal/logging_service_v2_logging_decorator.gcpcxx.pb.cc
  google/cloud/logging/internal/logging_service_v2_logging_decorator.gcpcxx.pb.h
  google/cloud/logging/internal/logging_service_v2_stub_factory.gcpcxx.pb.cc
  google/cloud/logging/logging_service_v2_client.gcpcxx.pb.cc
  google/cloud/logging/logging_service_v2_client.gcpcxx.pb.h
  google/cloud/logging/logging_service_v2_connection.gcpcxx.pb.cc
  google/cloud/logging/logging_service_v2_connection.gcpcxx.pb.h
  google/cloud/logging/mocks/mock_logging_service_v2_connection.gcpcxx.pb.h
Labels: cla: yes

#5827 doc: cross-reference building guides
  README.md
  ci/generate-markdown/generate-bigtable-readme.sh
  ci/generate-markdown/generate-packaging.sh
  ci/generate-markdown/generate-pubsub-readme.sh
  ci/generate-markdown/generate-readme.sh
  ci/generate-markdown/generate-spanner-readme.sh
  ci/generate-markdown/generate-storage-readme.sh
  ci/kokoro/macos/build-cmake.sh
  doc/packaging.md
  doc/setup-development-environment.md
  google/cloud/bigtable/README.md
  google/cloud/bigtable/quickstart/README.md
  google/cloud/pubsub/README.md
  google/cloud/pubsub/quickstart/README.md
  google/cloud/spanner/README.md
  google/cloud/spanner/quickstart/README.md
  google/cloud/storage/README.md
  google/cloud/storage/quickstart/README.md
  super/CMakeLists.txt
Labels: cla: yes

#5834 doc: ARCHITECTURE.md a rough map for developers
  ARCHITECTURE.md
Labels: cla: yes

#5833 doc: refactor CONTRIBUTING.md-related documents
  CONTRIBUTING.md
  README.md
  ci/generate-markdown/generate-bigtable-readme.sh
  ci/generate-markdown/generate-packaging.sh
  ci/generate-markdown/generate-pubsub-readme.sh
  ci/generate-markdown/generate-readme.sh
  ci/generate-markdown/generate-spanner-readme.sh
  ci/generate-markdown/generate-storage-readme.sh
  doc/contributor/README.md
  doc/contributor/howto-guide-forks-and-pull-requests.md
  doc/contributor/howto-guide-running-ci-builds-locally.md
  doc/contributor/howto-guide-setup-cmake-environment.md
  doc/contributor/howto-guide-setup-development-workstation.md
  doc/contributor/working-with-bazel-and-cmake.md
  doc/packaging.md
  doc/setup-cmake-environment.md
  google/cloud/bigtable/README.md
  google/cloud/bigtable/quickstart/README.md
  google/cloud/pubsub/README.md
  google/cloud/pubsub/quickstart/README.md
  google/cloud/spanner/README.md
  google/cloud/spanner/quickstart/README.md
  google/cloud/storage/README.md
  google/cloud/storage/quickstart/README.md
Labels: cla: yes

#5837 doc: multiple fixes to ARCHITECTURE.md
  ARCHITECTURE.md
Labels: cla: yes

#5835 feat(spanner): Point-In-Time Recovery backup support
  ci/test-abi/spanner_client.expected.abi.dump.gz
  google/cloud/spanner/database_admin_client.cc
  google/cloud/spanner/database_admin_client.h
  google/cloud/spanner/database_admin_client_test.cc
  google/cloud/spanner/database_admin_connection.cc
  google/cloud/spanner/database_admin_connection.h
  google/cloud/spanner/database_admin_connection_test.cc
  google/cloud/spanner/integration_tests/backup_integration_test.cc
  google/cloud/spanner/samples/samples.cc
Labels: api: spanner, cla: yes

#5838 feat(storage): gRPC clients can have their own channel
  google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark.cc
  google/cloud/storage/benchmarks/throughput_experiment.cc
  google/cloud/storage/benchmarks/throughput_experiment.h
  google/cloud/storage/benchmarks/throughput_experiment_test.cc
  google/cloud/storage/grpc_plugin.cc
  google/cloud/storage/grpc_plugin.h
  google/cloud/storage/internal/grpc_client.cc
  google/cloud/storage/internal/grpc_client.h
  google/cloud/storage/internal/hybrid_client.cc
  google/cloud/storage/internal/hybrid_client.h
Labels: api: storage, cla: yes

#5839 doc(bigtable): add configure_connection_pool sample
  google/cloud/bigtable/examples/data_snippets.cc
Labels: api: bigtable, cla: yes, samples

#5841 ci: add Z switch so mounts work on selinux systems
  ci/kokoro/docker/build.sh
Labels: cla: yes

#5842 doc: add development setup for macOS
  doc/contributor/howto-guide-setup-development-workstation.md
Labels: cla: yes

#5840 cleanup(storage): fix "launching emulator" banner
  google/cloud/storage/tools/run_emulator_utils.sh
Labels: api: storage, cla: yes

#5845 cleanup: simplify #include for `setenv`
  google/cloud/internal/setenv.cc
Labels: cla: yes

#5847 ci: improve vcpkg download and usage
  ci/kokoro/windows/build-cmake-dependencies.ps1
  ci/kokoro/windows/build.ps1
Labels: cla: yes

#5844 refactor(spanner)!: avoid chrono::time_point for Spanner timestamps
  ci/test-abi/spanner_client.expected.abi.dump.gz
  google/cloud/spanner/database_admin_client.cc
  google/cloud/spanner/database_admin_client.h
  google/cloud/spanner/database_admin_client_test.cc
  google/cloud/spanner/database_admin_connection.cc
  google/cloud/spanner/database_admin_connection.h
  google/cloud/spanner/database_admin_connection_test.cc
  google/cloud/spanner/integration_tests/backup_integration_test.cc
  google/cloud/spanner/integration_tests/data_types_integration_test.cc
  google/cloud/spanner/integration_tests/database_admin_integration_test.cc
  google/cloud/spanner/internal/connection_impl.cc
  google/cloud/spanner/internal/transaction_impl_test.cc
  google/cloud/spanner/results.cc
  google/cloud/spanner/samples/samples.cc
  google/cloud/spanner/timestamp.cc
  google/cloud/spanner/timestamp.h
  google/cloud/spanner/timestamp_test.cc
  google/cloud/spanner/value_test.cc
Labels: cla: yes

#5853 cleanup: use CMAKE_MSVC_RUNTIME_LIBRARY when possible
  cmake/SelectMSVCRuntime.cmake
Labels: cla: yes

#5855 cleanup: fewer warnings for proto files
  cmake/CompileProtos.cmake
  cmake/EnableWerror.cmake
  external/googleapis/CMakeLists.txt
  generator/integration_tests/CMakeLists.txt
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/tests/CMakeLists.txt
Labels: cla: yes

#5856 fix: support for static builds with MSVC
  CMakeLists.txt
  cmake/SelectMSVCRuntime.cmake
Labels: cla: yes

#5843 feat: introduce a dynamic Options class that all services can use
  google/cloud/BUILD
  google/cloud/CMakeLists.txt
  google/cloud/google_cloud_cpp_common.bzl
  google/cloud/google_cloud_cpp_common_unit_tests.bzl
  google/cloud/options.h
  google/cloud/options_test.cc
Labels: cla: yes

#5858 feat: added equality to TracingOptions
  google/cloud/tracing_options.cc
  google/cloud/tracing_options.h
  google/cloud/tracing_options_test.cc
Labels: cla: yes

#5860 feat: add support for get_pointer
  google/cloud/options.h
  google/cloud/options_test.cc
Labels: cla: yes

#5863 Revert "feat: add support for get_pointer"
  google/cloud/options.h
  google/cloud/options_test.cc
Labels: cla: yes

#5851 refactor(spanner): spanner::Timestamp/protobuf::Timestamp conversions
  google/cloud/spanner/database_admin_client.cc
  google/cloud/spanner/database_admin_client_test.cc
  google/cloud/spanner/database_admin_connection.cc
  google/cloud/spanner/database_admin_connection_test.cc
  google/cloud/spanner/integration_tests/backup_integration_test.cc
  google/cloud/spanner/integration_tests/database_admin_integration_test.cc
  google/cloud/spanner/internal/connection_impl.cc
  google/cloud/spanner/internal/connection_impl_test.cc
  google/cloud/spanner/internal/transaction_impl_test.cc
  google/cloud/spanner/results.cc
  google/cloud/spanner/results_test.cc
  google/cloud/spanner/timestamp.cc
  google/cloud/spanner/timestamp.h
  google/cloud/spanner/timestamp_test.cc
  google/cloud/spanner/transaction.cc
Labels: api: spanner, cla: yes

#5866 cleanup: move experimental `Options` to internal namespace
  google/cloud/CMakeLists.txt
  google/cloud/google_cloud_cpp_common.bzl
  google/cloud/google_cloud_cpp_common_unit_tests.bzl
  google/cloud/internal/options.h
  google/cloud/internal/options_test.cc
Labels: cla: yes

#5867 cleanup: add missing newline at end of file to new doc
  doc/contributor/howto-guide-running-ci-builds-locally.md
Labels: cla: yes

#5869 doc: workarounds for Bazel and path length problems
  google/cloud/bigtable/quickstart/README.md
  google/cloud/bigtable/quickstart/WORKSPACE
  google/cloud/pubsub/quickstart/README.md
  google/cloud/pubsub/quickstart/WORKSPACE
  google/cloud/spanner/quickstart/README.md
  google/cloud/spanner/quickstart/WORKSPACE
  google/cloud/storage/quickstart/README.md
  google/cloud/storage/quickstart/WORKSPACE
Labels: cla: yes

#5870 doc(storage): Update UBLA documentation to reflect its current status
  google/cloud/storage/bucket_metadata.h
Labels: api: storage, cla: yes

#5868 refactor(spanner): reorganize backup_integration_test
  google/cloud/spanner/integration_tests/backup_integration_test.cc
Labels: api: spanner, cla: yes

#5864 feat: ConnectionOptions<T> can convert to `internal::Options`
  google/cloud/CMakeLists.txt
  google/cloud/connection_options.h
  google/cloud/connection_options_test.cc
  google/cloud/google_cloud_cpp_common.bzl
  google/cloud/google_cloud_cpp_common_unit_tests.bzl
  google/cloud/google_cloud_cpp_grpc_utils.bzl
  google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl
  google/cloud/internal/common_options.h
  google/cloud/internal/common_options_test.cc
  google/cloud/internal/grpc_options.cc
  google/cloud/internal/grpc_options.h
  google/cloud/internal/grpc_options_test.cc
Labels: cla: yes

#5874 cleanup(spanner): tidy up spanner backup/restore samples
  google/cloud/spanner/samples/samples.cc
Labels: api: spanner, cla: yes, samples

#5873 ci: retry "vcpkg install google-cloud-cpp" once
  ci/kokoro/docker/build-in-docker-quickstart-cmake.sh
  ci/kokoro/macos/build-quickstart-cmake.sh
  ci/retry-command.sh
Labels: cla: yes

#5875 cleanup: small fixes to *_options.h
  google/cloud/internal/common_options.h
  google/cloud/internal/grpc_options.h
Labels: cla: yes

#5861 feature(generator): check for changes in golden files to indicate generator plugin behavior changes
  ci/check-golden-md5-hashes.sh
  ci/etc/generator-golden-md5-hashes.md5
  ci/kokoro/docker/build-in-docker-bazel.sh
  generator/generate-libraries.sh
  generator/integration_tests/golden/CMakeLists.txt
  generator/integration_tests/golden/google_cloud_cpp_generator_golden_files.bzl
Labels: cla: yes

#5876 refactor(spanner): spanner::Timestamp/protobuf::Timestamp conversions…
  google/cloud/spanner/database_admin_client.cc
  google/cloud/spanner/database_admin_client_test.cc
  google/cloud/spanner/database_admin_connection.cc
  google/cloud/spanner/database_admin_connection.h
  google/cloud/spanner/database_admin_connection_test.cc
  google/cloud/spanner/integration_tests/backup_integration_test.cc
  google/cloud/spanner/integration_tests/data_types_integration_test.cc
  google/cloud/spanner/internal/connection_impl.cc
  google/cloud/spanner/internal/connection_impl_test.cc
  google/cloud/spanner/internal/transaction_impl_test.cc
  google/cloud/spanner/results.cc
  google/cloud/spanner/results_test.cc
  google/cloud/spanner/samples/samples.cc
  google/cloud/spanner/timestamp.cc
  google/cloud/spanner/timestamp.h
  google/cloud/spanner/timestamp_test.cc
  google/cloud/spanner/transaction.cc
  google/cloud/spanner/transaction.h
  google/cloud/spanner/value_test.cc
Labels: api: spanner, cla: yes

#5881 feat(bigtable): limit default connection pool size
  google/cloud/bigtable/client_options.cc
  google/cloud/bigtable/client_options_test.cc
  google/cloud/bigtable/internal/client_options_defaults.h
Labels: api: bigtable, cla: yes

#5882 ci: prefer curl which is avail by default more often
  ci/install-bazel.sh
  ci/install-cloud-sdk.sh
Labels: cla: yes

#5883 ci: avoid dep on realpath(1)
  ci/lib/init.sh
Labels: cla: yes

#5880 chore(spanner): fully qualify google::protobuf::util names
  google/cloud/spanner/internal/connection_impl.cc
  google/cloud/spanner/timestamp.cc
Labels: api: spanner, cla: yes

#5884 ci: use x86_64 bazel package on macOS M1
  ci/install-bazel.sh
Labels: cla: yes

#5885 test(spanner): support filtering of `PickRandomInstance()` candidates
  google/cloud/spanner/testing/pick_random_instance.cc
  google/cloud/spanner/testing/pick_random_instance.h
Labels: api: spanner, cla: yes

#5886 doc: fix inconsistent package vs. target names
  ci/generate-markdown/generate-packaging.sh
  doc/packaging.md
Labels: cla: yes

#5887 chore: update google-cloud-sdk version
  ci/etc/install-config.sh
Labels: cla: yes

#5889 fix(generator): properly escape delimiter character
  generator/integration_tests/golden/golden_kitchen_sink_client.gcpcxx.pb.h
  generator/integration_tests/test.proto
  generator/internal/client_generator.cc
  generator/internal/descriptor_utils.cc
  generator/internal/descriptor_utils.h
  generator/internal/descriptor_utils_test.cc
Labels: cla: yes

#5890 cleanup(spanner): simplify some *AdminClient samples
  google/cloud/spanner/samples/samples.cc
Labels: api: spanner, cla: yes, samples

#5879 cleanup(spanner): stop creating an instance in BackupTest.BackupTest
  google/cloud/spanner/integration_tests/backup_integration_test.cc
Labels: api: spanner, cla: yes

#5888 feat(pubsub): add stub for the schema service
  google/cloud/pubsub/CMakeLists.txt
  google/cloud/pubsub/google_cloud_cpp_pubsub.bzl
  google/cloud/pubsub/integration_tests/CMakeLists.txt
  google/cloud/pubsub/integration_tests/pubsub_client_integration_tests.bzl
  google/cloud/pubsub/integration_tests/schema_admin_integration_test.cc
  google/cloud/pubsub/internal/schema_stub.cc
  google/cloud/pubsub/internal/schema_stub.h
  google/cloud/pubsub/testing/random_names.cc
  google/cloud/pubsub/testing/random_names.h
Labels: api: pubsub, cla: yes

#5891 cleanup: make CMake builds less verbose
  ci/check-style.sh
  ci/kokoro/docker/build-in-docker-cmake.sh
  ci/kokoro/docker/build.sh
Labels: cla: yes

#5896 fix(generator): correct exit code and update hashes
  ci/check-golden-md5-hashes.sh
  ci/etc/generator-golden-md5-hashes.md5
Labels: cla: yes

#5897 generator(feature): default to nonidempotent for rpcs missing http option
  generator/internal/descriptor_utils.cc
  generator/internal/descriptor_utils_test.cc
Labels: cla: yes

#5898 cleanup: add internal-only Contains() and ContainsIf() helpers
  google/cloud/CMakeLists.txt
  google/cloud/bigtable/app_profile_config.cc
  google/cloud/bigtable/examples/bigtable_hello_instance_admin.cc
  google/cloud/bigtable/instance_update_config.h
  google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
  google/cloud/bigtable/tests/instance_admin_integration_test.cc
  google/cloud/google_cloud_cpp_common.bzl
  google/cloud/google_cloud_cpp_common_unit_tests.bzl
  google/cloud/internal/algorithm.h
  google/cloud/internal/algorithm_test.cc
  google/cloud/storage/tests/bucket_integration_test.cc
Labels: cla: yes

#5900 cleanup: internal/*_options.h were not in the internal namespace
  google/cloud/connection_options_test.cc
  google/cloud/internal/common_options.h
  google/cloud/internal/grpc_options.h
Labels: cla: yes

#5895 cleanup(spanner): cleanup instance_admin_integration_test
  google/cloud/spanner/integration_tests/instance_admin_integration_test.cc
Labels: api: spanner, cla: yes

#5893 feat(pubsub): add a class for Schema names
  google/cloud/pubsub/CMakeLists.txt
  google/cloud/pubsub/experimental/schema.cc
  google/cloud/pubsub/experimental/schema.h
  google/cloud/pubsub/experimental/schema_test.cc
  google/cloud/pubsub/google_cloud_cpp_pubsub.bzl
  google/cloud/pubsub/integration_tests/schema_admin_integration_test.cc
  google/cloud/pubsub/pubsub_client_unit_tests.bzl
Labels: api: pubsub, cla: yes

#5902 doc: add dropdowns to packaging.md
  ci/generate-markdown/generate-packaging.sh
  doc/packaging.md
Labels: cla: yes

#5903 feat(pubsub): implement SchemaLogging
  google/cloud/pubsub/CMakeLists.txt
  google/cloud/pubsub/google_cloud_cpp_pubsub.bzl
  google/cloud/pubsub/internal/schema_logging.cc
  google/cloud/pubsub/internal/schema_logging.h
  google/cloud/pubsub/internal/schema_logging_test.cc
  google/cloud/pubsub/pubsub_client_testing.bzl
  google/cloud/pubsub/pubsub_client_unit_tests.bzl
  google/cloud/pubsub/testing/mock_schema_stub.h
Labels: api: pubsub, cla: yes

#5905 feat(pubsub): implement SchemaMetadata decorator
  google/cloud/pubsub/CMakeLists.txt
  google/cloud/pubsub/google_cloud_cpp_pubsub.bzl
  google/cloud/pubsub/internal/schema_metadata.cc
  google/cloud/pubsub/internal/schema_metadata.h
  google/cloud/pubsub/internal/schema_metadata_test.cc
  google/cloud/pubsub/pubsub_client_unit_tests.bzl
Labels: api: pubsub, cla: yes

#5904 feat(pubsub): implement SchemaAdminConnection
  google/cloud/pubsub/CMakeLists.txt
  google/cloud/pubsub/experimental/schema_admin_connection.cc
  google/cloud/pubsub/experimental/schema_admin_connection.h
  google/cloud/pubsub/google_cloud_cpp_pubsub.bzl
  google/cloud/pubsub/integration_tests/schema_admin_integration_test.cc
Labels: api: pubsub, cla: yes

#5911 cleanup: fix TODO entry
  google/cloud/storage/tests/object_integration_test.cc
Labels: cla: yes

#5909 feat(pubsub): use SchemaMetadata in SchemaAdminConnection
  google/cloud/pubsub/CMakeLists.txt
  google/cloud/pubsub/experimental/schema_admin_connection.cc
  google/cloud/pubsub/experimental/schema_admin_connection_test.cc
  google/cloud/pubsub/pubsub_client_unit_tests.bzl
Labels: api: pubsub, cla: yes

#5906 feat(spanner): Point-In-Time Recovery (PITR)
  ci/test-abi/google_cloud_cpp_spanner.expected.abi.dump.gz
  google/cloud/spanner/database_admin_client.cc
  google/cloud/spanner/database_admin_client.h
  google/cloud/spanner/database_admin_client_test.cc
  google/cloud/spanner/database_admin_connection.cc
  google/cloud/spanner/database_admin_connection.h
  google/cloud/spanner/database_admin_connection_test.cc
  google/cloud/spanner/integration_tests/backup_integration_test.cc
  google/cloud/spanner/integration_tests/client_integration_test.cc
  google/cloud/spanner/integration_tests/database_admin_integration_test.cc
  google/cloud/spanner/samples/samples.cc
  google/cloud/spanner/testing/database_integration_test.cc
Labels: api: spanner, cla: yes

#5912 feat(pubsub): implement SchemaAdminClient part 1/2
  google/cloud/pubsub/CMakeLists.txt
  google/cloud/pubsub/experimental/mock_schema_admin_connection.h
  google/cloud/pubsub/experimental/schema_admin_client.cc
  google/cloud/pubsub/experimental/schema_admin_client.h
  google/cloud/pubsub/experimental/schema_admin_client_test.cc
  google/cloud/pubsub/google_cloud_cpp_pubsub.bzl
  google/cloud/pubsub/google_cloud_cpp_pubsub_mocks.bzl
  google/cloud/pubsub/pubsub_client_unit_tests.bzl
Labels: api: pubsub, cla: yes

#5913 feat(pubsub): implement SchemaAdminClient part 2/2
  google/cloud/pubsub/experimental/schema_admin_client.cc
  google/cloud/pubsub/experimental/schema_admin_client.h
  google/cloud/pubsub/experimental/schema_admin_client_test.cc
  google/cloud/pubsub/integration_tests/schema_admin_integration_test.cc
Labels: api: pubsub, cla: yes

#5914 feat(pubsub): implement schema admin examples 1/2
  google/cloud/pubsub/experimental/schema_admin_client.h
  google/cloud/pubsub/samples/pubsub_samples_common.cc
  google/cloud/pubsub/samples/pubsub_samples_common.h
  google/cloud/pubsub/samples/pubsub_samples_common_test.cc
  google/cloud/pubsub/samples/samples.cc
Labels: api: pubsub, cla: yes

#5917 ci: pin cspell@5.2.4 to improve docker image consistency
  ci/kokoro/docker/Dockerfile.fedora-install
Labels: cla: yes

#5916 feat(pubsub): implement schema admin examples 2/2
  google/cloud/pubsub/experimental/schema_admin_client.h
  google/cloud/pubsub/samples/BUILD
  google/cloud/pubsub/samples/CMakeLists.txt
  google/cloud/pubsub/samples/samples.cc
  google/cloud/pubsub/samples/samples.proto
Labels: api: pubsub, cla: yes

#5919 chore: update googleapis version
  bazel/google_cloud_cpp_deps.bzl
  ci/etc/generator-googleapis-commit-hash.sh
  external/googleapis/CMakeLists.txt
  google/cloud/iam/iam_credentials_client.gcpcxx.pb.h
  google/cloud/logging/logging_service_v2_client.gcpcxx.pb.h
Labels: cla: yes

#5920 feat(pubsub): support schemas when creating topics
  google/cloud/pubsub/samples/samples.cc
  google/cloud/pubsub/topic_admin_client.h
  google/cloud/pubsub/topic_builder.h
  google/cloud/pubsub/topic_builder_test.cc
Labels: api: pubsub, cla: yes

#5921 feat(bigtable): add CMEK attributes to admin APIs
  google/cloud/bigtable/cluster_config.h
  google/cloud/bigtable/cluster_config_test.cc
  google/cloud/bigtable/table_admin.cc
  google/cloud/bigtable/table_admin.h
Labels: api: bigtable, cla: yes

#5926 test(spanner): extend samples and integration-test timeouts
  google/cloud/spanner/integration_tests/BUILD
  google/cloud/spanner/samples/BUILD
Labels: api: spanner, cla: yes, samples

#5924 cleanup(bigtable): deprecate admin async functions
  CHANGELOG.md
  google/cloud/CMakeLists.txt
  google/cloud/bigtable/async_list_app_profiles_test.cc
  google/cloud/bigtable/async_list_clusters_test.cc
  google/cloud/bigtable/async_list_instances_test.cc
  google/cloud/bigtable/examples/bigtable_table_admin_backup_async_snippets.cc
  google/cloud/bigtable/examples/instance_admin_async_snippets.cc
  google/cloud/bigtable/examples/table_admin_async_snippets.cc
  google/cloud/bigtable/examples/table_admin_iam_policy_snippets.cc
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/instance_admin_test.cc
  google/cloud/bigtable/table_admin.cc
  google/cloud/bigtable/table_admin.h
  google/cloud/bigtable/table_admin_test.cc
  google/cloud/bigtable/tests/admin_async_future_integration_test.cc
  google/cloud/bigtable/tests/admin_backup_async_future_integration_test.cc
  google/cloud/bigtable/tests/admin_iam_policy_integration_test.cc
  google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
  google/cloud/bigtable/version.h
  google/cloud/google_cloud_cpp_common.bzl
  google/cloud/internal/attributes.h
  google/cloud/internal/disable_deprecation_warnings.inc
Labels: api: bigtable, cla: yes

#5928 cleanup: issue deprecation warnings for some IAM functions
  CHANGELOG.md
  google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/table_admin.h
  google/cloud/bigtable/tests/instance_admin_integration_test.cc
  google/cloud/bigtable/version.h
  google/cloud/storage/bucket_test.cc
  google/cloud/storage/client.h
  google/cloud/storage/examples/storage_bucket_iam_samples.cc
  google/cloud/storage/tests/bucket_integration_test.cc
  google/cloud/storage/version.h
Labels: cla: yes

#5933 cleanup: remove openSUSE:Tumbleweed builds
  ci/generate-markdown/generate-packaging.sh
  ci/kokoro/install/Dockerfile.opensuse-tumbleweed
  ci/kokoro/install/opensuse-tumbleweed-presubmit.cfg
  ci/kokoro/install/opensuse-tumbleweed.cfg
  doc/packaging.md
Labels: cla: yes

#5936 cleanup: add testing_util::ScopedLog
  generator/integration_tests/golden/tests/golden_kitchen_sink_logging_decorator_test.cc
  generator/integration_tests/golden/tests/golden_kitchen_sink_stub_factory_test.cc
  generator/integration_tests/golden/tests/golden_thing_admin_logging_decorator_test.cc
  generator/integration_tests/golden/tests/golden_thing_admin_stub_factory_test.cc
  google/cloud/bigtable/internal/logging_admin_client_test.cc
  google/cloud/bigtable/internal/logging_data_client_test.cc
  google/cloud/bigtable/internal/logging_instance_admin_client_test.cc
  google/cloud/bigtable/row_reader_test.cc
  google/cloud/bigtable/tests/admin_integration_test.cc
  google/cloud/bigtable/tests/data_integration_test.cc
  google/cloud/bigtable/tests/instance_admin_integration_test.cc
  google/cloud/iam/integration_tests/iam_credentials_integration_test.cc
  google/cloud/internal/log_wrapper_test.cc
  google/cloud/internal/resumable_streaming_read_rpc_test.cc
  google/cloud/internal/streaming_read_rpc_logging_test.cc
  google/cloud/internal/streaming_read_rpc_test.cc
  google/cloud/logging/integration_tests/logging_integration_test.cc
  google/cloud/pubsub/experimental/schema_admin_connection_test.cc
  google/cloud/pubsub/internal/publisher_logging_test.cc
  google/cloud/pubsub/internal/schema_logging_test.cc
  google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc
  google/cloud/pubsub/internal/subscriber_logging_test.cc
  google/cloud/pubsub/publisher_connection_test.cc
  google/cloud/pubsub/subscriber_connection_test.cc
  google/cloud/pubsub/subscription_admin_connection_test.cc
  google/cloud/pubsub/topic_admin_connection_test.cc
  google/cloud/spanner/internal/database_admin_logging_test.cc
  google/cloud/spanner/internal/instance_admin_logging_test.cc
  google/cloud/spanner/internal/logging_result_set_reader_test.cc
  google/cloud/spanner/internal/logging_spanner_stub_test.cc
  google/cloud/spanner/internal/spanner_stub_test.cc
  google/cloud/storage/internal/logging_resumable_upload_session_test.cc
  google/cloud/storage/tests/curl_resumable_upload_session_integration_test.cc
  google/cloud/storage/tests/object_checksum_integration_test.cc
  google/cloud/storage/tests/object_file_integration_test.cc
  google/cloud/storage/tests/object_hash_integration_test.cc
  google/cloud/storage/tests/object_insert_integration_test.cc
  google/cloud/storage/tests/object_rewrite_integration_test.cc
  google/cloud/testing_util/CMakeLists.txt
  google/cloud/testing_util/capture_log_lines_backend.h
  google/cloud/testing_util/google_cloud_cpp_testing.bzl
  google/cloud/testing_util/scoped_log.cc
  google/cloud/testing_util/scoped_log.h
Labels: cla: yes

#5938 feat: adds internal::CheckExpectedOptions<T>(...)
  google/cloud/CMakeLists.txt
  google/cloud/google_cloud_cpp_common.bzl
  google/cloud/internal/common_options.h
  google/cloud/internal/common_options_test.cc
  google/cloud/internal/grpc_options.h
  google/cloud/internal/grpc_options_test.cc
  google/cloud/internal/options.cc
  google/cloud/internal/options.h
  google/cloud/internal/options_test.cc
Labels: cla: yes

#5939 refactor: simplify the Options API, easier to use, improved efficiency
  google/cloud/connection_options.h
  google/cloud/connection_options_test.cc
  google/cloud/internal/common_options.h
  google/cloud/internal/common_options_test.cc
  google/cloud/internal/grpc_options.cc
  google/cloud/internal/grpc_options.h
  google/cloud/internal/grpc_options_test.cc
  google/cloud/internal/options.h
  google/cloud/internal/options_test.cc
Labels: cla: yes

#5937 feat(storage): implement {Get,Set}NativeBucketIamPolicy
  google/cloud/iam_policy.h
  google/cloud/storage/emulator/emulator.py
  google/cloud/storage/emulator/gcs/bucket.py
  google/cloud/storage/emulator/grpc_server.py
  google/cloud/storage/iam_policy.h
  google/cloud/storage/internal/bucket_requests.cc
  google/cloud/storage/internal/bucket_requests.h
  google/cloud/storage/internal/bucket_requests_test.cc
  google/cloud/storage/internal/grpc_client.cc
  google/cloud/storage/internal/grpc_client.h
  google/cloud/storage/internal/grpc_client_bucket_request_test.cc
  google/cloud/storage/internal/grpc_client_failures_test.cc
  google/cloud/storage/tests/grpc_integration_test.cc
Labels: api: storage, cla: yes

#5940 cleanup: internal::MakeOptions accepts by value
  google/cloud/connection_options.h
  google/cloud/connection_options_test.cc
Labels: cla: yes
