Repository googleapis/google-cloud-cpp, pull requests merged in 2021-10, with the labels that each got.

#7383 feat(generator): add "generator" to API client header "gccl" semver
  generator/integration_tests/golden/internal/golden_kitchen_sink_metadata_decorator.cc
  generator/integration_tests/golden/internal/golden_thing_admin_metadata_decorator.cc
  generator/integration_tests/golden/tests/golden_kitchen_sink_metadata_decorator_test.cc
  generator/integration_tests/golden/tests/golden_thing_admin_metadata_decorator_test.cc
  generator/internal/metadata_decorator_generator.cc
  google/cloud/bigquery/internal/bigquery_read_metadata_decorator.cc
  google/cloud/iam/internal/iam_credentials_metadata_decorator.cc
  google/cloud/iam/internal/iam_metadata_decorator.cc
  google/cloud/internal/api_client_header.cc
  google/cloud/internal/api_client_header.h
  google/cloud/internal/api_client_header_test.cc
  google/cloud/logging/internal/logging_service_v2_metadata_decorator.cc
  google/cloud/spanner/admin/internal/database_admin_metadata_decorator.cc
  google/cloud/spanner/admin/internal/instance_admin_metadata_decorator.cc
Labels: cla: yes

#7386 chore(release): update changelog for 2021-10 release
  CHANGELOG.md
  ci/abi-dumps/google_cloud_cpp_bigquery.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_bigtable.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_common.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_grpc_utils.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_iam.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_pubsub.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_spanner.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_storage.expected.abi.dump.gz
Labels: cla: yes

#7388 chore: bump version numbers after v1.32.0 release
  CMakeLists.txt
  google/cloud/bigquery/quickstart/WORKSPACE
  google/cloud/bigtable/quickstart/WORKSPACE
  google/cloud/iam/quickstart/WORKSPACE
  google/cloud/internal/version_info.h
  google/cloud/pubsub/quickstart/WORKSPACE
  google/cloud/spanner/quickstart/WORKSPACE
  google/cloud/storage/quickstart/WORKSPACE
Labels: cla: yes

#7377 doc(storage): 'unspecified' value for PAP is deprecated
  ci/cloudbuild/builds/lib/integration.sh
  google/cloud/storage/bucket_metadata.cc
  google/cloud/storage/bucket_metadata.h
  google/cloud/storage/bucket_metadata_test.cc
  google/cloud/storage/examples/storage_bucket_samples.cc
Labels: cla: yes, api: storage

#7390 fix(storage): prevent crashes on double Close()
  google/cloud/storage/internal/object_write_streambuf.cc
  google/cloud/storage/tests/object_write_stream_integration_test.cc
Labels: cla: yes, api: storage

#7391 cleanup: tweak some items in the release process
  release/README.md
  release/changes.sh
Labels: cla: yes

#7393 cleanup: remove unused import
  google/cloud/bigtable/tools/generate_rpc_policy_parameters.py
Labels: cla: yes

#7398 ci: use CodeQL for security scans
  .github/workflows/codeql-analysis.yml
Labels: cla: yes

#7397 cleanup(bigtable): make default clients conform
  google/cloud/bigtable/admin_client.cc
  google/cloud/bigtable/client_options.h
  google/cloud/bigtable/data_client.cc
  google/cloud/bigtable/data_client.h
  google/cloud/bigtable/instance_admin_client.cc
Labels: cla: yes, api: bigtable

#7401 test(storage): ignore RPO on insert
  google/cloud/storage/tests/bucket_integration_test.cc
Labels: cla: yes, api: storage

#7400 cleanup(storage): fix example bucket leaks
  google/cloud/storage/examples/storage_bucket_samples.cc
Labels: cla: yes, api: storage

#7399 test(storage): special cleanup for requester pay
  google/cloud/storage/testing/remove_stale_buckets.cc
  google/cloud/storage/testing/remove_stale_buckets.h
  google/cloud/storage/testing/remove_stale_buckets_test.cc
  google/cloud/storage/testing/storage_integration_test.cc
Labels: cla: yes, api: storage

#7406 fix(pubsub): do not overwrite ConnectionOptions
  google/cloud/pubsub/internal/defaults.cc
  google/cloud/pubsub/internal/defaults.h
  google/cloud/pubsub/internal/defaults_test.cc
  google/cloud/pubsub/publisher_options.cc
  google/cloud/pubsub/publisher_options_test.cc
  google/cloud/pubsub/subscriber_options.cc
  google/cloud/pubsub/subscriber_options_test.cc
Labels: cla: yes, api: pubsub

#7408 fix(pubsub): do not overwrite ConnectionOptions
  google/cloud/pubsub/internal/defaults.cc
  google/cloud/pubsub/internal/defaults.h
  google/cloud/pubsub/internal/defaults_test.cc
  google/cloud/pubsub/publisher_options.cc
  google/cloud/pubsub/publisher_options_test.cc
  google/cloud/pubsub/subscriber_options.cc
  google/cloud/pubsub/subscriber_options_test.cc
Labels: cla: yes, api: pubsub

#7409 doc: update CHANGELOG and version numbers for v1.32.1
  CHANGELOG.md
  CMakeLists.txt
  google/cloud/internal/version_info.h
Labels: cla: yes

#7414 chore(deps): update google/crc32c to 1.1.2
  bazel/crc32c.BUILD
  bazel/google_cloud_cpp_deps.bzl
  ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile
  ci/cloudbuild/dockerfiles/demo-debian-bullseye.Dockerfile
  ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile
  ci/cloudbuild/dockerfiles/demo-debian-stretch.Dockerfile
  ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile
  ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile
  ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile
  ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile
  ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile
  ci/cloudbuild/dockerfiles/demo-ubuntu-xenial.Dockerfile
  ci/cloudbuild/dockerfiles/fedora-34.Dockerfile
  ci/cloudbuild/dockerfiles/ubuntu-bionic-install.Dockerfile
  ci/cloudbuild/dockerfiles/ubuntu-xenial.Dockerfile
  doc/packaging.md
Labels: cla: yes

#7536 test(spanner): bump create-database timeout from ~120s to ~300s
  google/cloud/spanner/integration_tests/rpc_failure_threshold_integration_test.cc
Labels: cla: yes, api: spanner

#7537 cleanup(generator): use printer mocks
  generator/internal/descriptor_utils_test.cc
  generator/internal/printer_test.cc
  generator/internal/service_code_generator_test.cc
  generator/testing/printer_mocks.h
Labels: cla: yes

#7543 cleanup(generator): new line in auth cc
  generator/internal/auth_decorator_generator.cc
  google/cloud/bigquery/internal/bigquery_read_auth_decorator.cc
  google/cloud/iam/internal/iam_auth_decorator.cc
  google/cloud/iam/internal/iam_credentials_auth_decorator.cc
  google/cloud/logging/internal/logging_service_v2_auth_decorator.cc
Labels: cla: yes
