Repository googleapis/google-cloud-cpp, pull requests merged in 2021-04, with the labels that each got.

#6162 cleanup: do not duplicate the Status code within its message
  google/cloud/internal/retry_loop_helpers.cc
  google/cloud/storage/internal/retry_client.cc
  google/cloud/storage/internal/retry_object_read_source.cc
  google/cloud/storage/internal/retry_resumable_upload_session.cc
Labels: cla: yes

#6158 chore(bigquery): add windows quickstart env var
  ci/etc/integration-tests-config.ps1
  ci/etc/integration-tests-config.sh
Labels: api: bigquery, cla: yes

#6169 feat(storage): reduce overhead in pooled handle factory
  google/cloud/storage/internal/curl_handle_factory.cc
  google/cloud/storage/internal/curl_handle_factory.h
Labels: api: storage, cla: yes

#6172 chore: April 2021 release notes and ABI update
  CHANGELOG.md
  ci/test-abi/google_cloud_cpp_bigtable.expected.abi.dump.gz
  ci/test-abi/google_cloud_cpp_common.expected.abi.dump.gz
  ci/test-abi/google_cloud_cpp_grpc_utils.expected.abi.dump.gz
  ci/test-abi/google_cloud_cpp_spanner.expected.abi.dump.gz
  ci/test-abi/google_cloud_cpp_storage.expected.abi.dump.gz
Labels: cla: yes

#6175 cleanup(bigtable): remove DirectPath specific endpoint
  google/cloud/bigtable/client_options.cc
  google/cloud/bigtable/client_options_test.cc
Labels: api: bigtable, cla: yes

#6173 chore: bump version numbers after v1.26 release
  CMakeLists.txt
  google/cloud/bigquery/quickstart/WORKSPACE
  google/cloud/bigtable/quickstart/WORKSPACE
  google/cloud/internal/version_info.h
  google/cloud/pubsub/quickstart/WORKSPACE
  google/cloud/spanner/quickstart/WORKSPACE
  google/cloud/storage/quickstart/WORKSPACE
Labels: cla: yes

#6183 refactor(storage): use g::c::Options in ClientOptions
  google/cloud/storage/client_options.cc
  google/cloud/storage/client_options.h
  google/cloud/storage/client_options_test.cc
Labels: api: storage, cla: yes

#6186 ci(gcb): add elapsed time to Ninja builds
  ci/cloudbuild/builds/lib/cmake.sh
Labels: cla: yes

#6188 feat(iam): an example for GenerateAccessToken
  ci/cloudbuild/builds/integration.sh
  google/cloud/iam/CMakeLists.txt
  google/cloud/iam/samples/BUILD
  google/cloud/iam/samples/CMakeLists.txt
  google/cloud/iam/samples/grpc_credential_types.cc
  google/cloud/iam/samples/iam_client_integration_samples.bzl
Labels: api: iam, cla: yes

#6190 cleanup: require CMake >= 3.15 with MSVC
  CMakeLists.txt
  cmake/SelectMSVCRuntime.cmake
Labels: cla: yes

#6191 cleanup: prefer vcpkg to manage dependencies
  doc/contributor/howto-guide-setup-cmake-environment.md
  super/ExternalProjectHelper.cmake
  vcpkg.json
Labels: cla: yes

#6193 ci: improve Windows+CMake logs
  ci/kokoro/windows/build-cmake.ps1
Labels: cla: yes

#6194 ci: windows update vcpkg version
  ci/kokoro/windows/build-cmake-dependencies.ps1
Labels: cla: yes

#6197 ci: fix quickstart+CMake builds on macOS
  ci/kokoro/lib/cache.sh
  ci/kokoro/macos/build-quickstart-cmake.sh
  ci/kokoro/macos/build.sh
Labels: cla: yes

#6199 ci: adapt build scripts for catalina pool
  ci/kokoro/macos/build-bazel.sh
  ci/kokoro/macos/build-cmake.sh
  ci/kokoro/macos/build-quickstart-bazel.sh
Labels: cla: yes

#6200 refactor(storage): compute default options in a single function
  google/cloud/storage/client_options.cc
  google/cloud/storage/client_options.h
Labels: api: storage, cla: yes

#6203 refactor(storage): use g::c::Options in CurlClient
  google/cloud/storage/client_options.cc
  google/cloud/storage/client_options.h
  google/cloud/storage/client_options_test.cc
  google/cloud/storage/internal/curl_client.cc
  google/cloud/storage/internal/curl_client.h
  google/cloud/storage/internal/curl_handle_factory.cc
  google/cloud/storage/internal/curl_handle_factory.h
  google/cloud/storage/internal/curl_handle_factory_test.cc
  google/cloud/storage/internal/curl_request_builder.cc
  google/cloud/storage/internal/curl_request_builder.h
  google/cloud/storage/internal/curl_resumable_upload_session_test.cc
  google/cloud/storage/internal/curl_wrappers.cc
  google/cloud/storage/internal/curl_wrappers.h
  google/cloud/storage/internal/curl_wrappers_disable_sigpipe_handler_test.cc
  google/cloud/storage/internal/curl_wrappers_enable_sigpipe_handler_test.cc
  google/cloud/storage/internal/curl_wrappers_locking_already_present_test.cc
  google/cloud/storage/internal/curl_wrappers_locking_disabled_test.cc
  google/cloud/storage/internal/curl_wrappers_locking_enabled_test.cc
  google/cloud/storage/oauth2/authorized_user_credentials.h
  google/cloud/storage/oauth2/service_account_credentials.h
  google/cloud/storage/tests/curl_request_integration_test.cc
Labels: api: storage, cla: yes

#6209 refactor(storage): use g::c::Options for GrpcClient
  google/cloud/storage/benchmarks/throughput_experiment.cc
  google/cloud/storage/client_options.cc
  google/cloud/storage/client_options.h
  google/cloud/storage/client_options_test.cc
  google/cloud/storage/grpc_plugin.cc
  google/cloud/storage/internal/curl_client.h
  google/cloud/storage/internal/curl_resumable_upload_session_test.cc
  google/cloud/storage/internal/grpc_client.cc
  google/cloud/storage/internal/grpc_client.h
  google/cloud/storage/internal/grpc_client_failures_test.cc
  google/cloud/storage/internal/grpc_client_object_request_test.cc
  google/cloud/storage/internal/grpc_resumable_upload_session_test.cc
  google/cloud/storage/internal/hybrid_client.cc
  google/cloud/storage/internal/hybrid_client.h
  google/cloud/storage/testing/storage_integration_test.cc
  google/cloud/storage/tests/grpc_integration_test.cc
Labels: api: storage, cla: yes

#6211 ci(gcb): add bigquery notifier
  ci/cloudbuild/notifiers/bigquery/README.md
  ci/cloudbuild/notifiers/bigquery/bigquery.yaml
  ci/cloudbuild/notifiers/bigquery/deploy.sh
Labels: cla: yes

#6215 ci(gcb): tag builds as ci or pr
  ci/cloudbuild/build.sh
  ci/cloudbuild/trigger.sh
  ci/cloudbuild/triggers/asan-ci.yaml
  ci/cloudbuild/triggers/asan-pr.yaml
  ci/cloudbuild/triggers/checkers-ci.yaml
  ci/cloudbuild/triggers/checkers-pr.yaml
  ci/cloudbuild/triggers/clang-38-ci.yaml
  ci/cloudbuild/triggers/clang-38-pr.yaml
  ci/cloudbuild/triggers/clang-tidy-ci.yaml
  ci/cloudbuild/triggers/clang-tidy-pr.yaml
  ci/cloudbuild/triggers/cmake-clang-ci.yaml
  ci/cloudbuild/triggers/cmake-clang-pr.yaml
  ci/cloudbuild/triggers/cmake-gcc-ci.yaml
  ci/cloudbuild/triggers/cmake-gcc-pr.yaml
  ci/cloudbuild/triggers/cmake-install-ci.yaml
  ci/cloudbuild/triggers/cmake-install-pr.yaml
  ci/cloudbuild/triggers/cmake-super-ci.yaml
  ci/cloudbuild/triggers/cmake-super-pr.yaml
  ci/cloudbuild/triggers/gcc-54-ci.yaml
  ci/cloudbuild/triggers/gcc-54-pr.yaml
  ci/cloudbuild/triggers/integration-ci.yaml
  ci/cloudbuild/triggers/integration-pr.yaml
  ci/cloudbuild/triggers/quickstart-bazel-ci.yaml
  ci/cloudbuild/triggers/quickstart-bazel-pr.yaml
  ci/cloudbuild/triggers/quickstart-cmake-ci.yaml
  ci/cloudbuild/triggers/quickstart-cmake-pr.yaml
  ci/cloudbuild/triggers/tsan-ci.yaml
  ci/cloudbuild/triggers/tsan-pr.yaml
  ci/cloudbuild/triggers/ubsan-ci.yaml
  ci/cloudbuild/triggers/ubsan-pr.yaml
  ci/cloudbuild/triggers/xsan-ci.yaml
  ci/cloudbuild/triggers/xsan-pr.yaml
Labels: cla: yes

#6217 ci(gcb): run clang-38 and gcc-54 builds on xenial
  ci/cloudbuild/triggers/clang-38-ci.yaml
  ci/cloudbuild/triggers/clang-38-pr.yaml
  ci/cloudbuild/triggers/gcc-54-ci.yaml
  ci/cloudbuild/triggers/gcc-54-pr.yaml
Labels: cla: yes

#6218 doc: clarify warnings about disabling exceptions
  cmake/EnableCxxExceptions.cmake
Labels: cla: yes

#6219 ci(gcb): set CLOUD_SDK_LOCATION in Dockerfile
  ci/cloudbuild/builds/integration.sh
  ci/cloudbuild/fedora.Dockerfile
  ci/cloudbuild/ubuntu-bionic.Dockerfile
Labels: cla: yes

#6222 ci(gcb): pass PROJECT_ID and BUILD_ID to build scripts
  ci/cloudbuild/build.sh
  ci/cloudbuild/cloudbuild.yaml
Labels: cla: yes

#6223 fix(ci): gitignore pattern that was too broad
  .gitignore
  ci/cloudbuild/triggers/bazel-clang-ci.yaml
  ci/cloudbuild/triggers/bazel-clang.yaml
  ci/cloudbuild/triggers/bazel-gcc-ci.yaml
  ci/cloudbuild/triggers/bazel-gcc.yaml
Labels: cla: yes

#6216 docs: fix typos
  doc/contributor/howto-guide-setup-cmake-environment.md
  doc/contributor/howto-guide-setup-development-workstation.md
Labels: cla: yes

#6225 ci(gcb): add missing bazel trigger files
  ci/cloudbuild/triggers/bazel-clang-pr.yaml
  ci/cloudbuild/triggers/bazel-gcc-pr.yaml
Labels: cla: yes

#6227 ci(gcb): run integration tests from sanitizer builds
  ci/cloudbuild/builds/asan.sh
  ci/cloudbuild/builds/integration.sh
  ci/cloudbuild/builds/lib/integration.sh
  ci/cloudbuild/builds/tsan.sh
  ci/cloudbuild/builds/ubsan.sh
  ci/cloudbuild/builds/xsan.sh
Labels: cla: yes

#6228 ci(gcb): use ctcache to speed up clang-tidy builds
  ci/cloudbuild/builds/clang-tidy.sh
  ci/cloudbuild/cloudbuild.yaml
  ci/cloudbuild/fedora.Dockerfile
  ci/cloudbuild/triggers/clang-tidy-pr.yaml
Labels: cla: yes

#6229 ci(gcb): add useful tags to all builds
  ci/cloudbuild/cloudbuild.yaml
  ci/cloudbuild/triggers/asan-ci.yaml
  ci/cloudbuild/triggers/asan-pr.yaml
  ci/cloudbuild/triggers/bazel-clang-ci.yaml
  ci/cloudbuild/triggers/bazel-clang-pr.yaml
  ci/cloudbuild/triggers/bazel-gcc-ci.yaml
  ci/cloudbuild/triggers/bazel-gcc-pr.yaml
  ci/cloudbuild/triggers/checkers-ci.yaml
  ci/cloudbuild/triggers/checkers-pr.yaml
  ci/cloudbuild/triggers/clang-38-ci.yaml
  ci/cloudbuild/triggers/clang-38-pr.yaml
  ci/cloudbuild/triggers/clang-tidy-ci.yaml
  ci/cloudbuild/triggers/clang-tidy-pr.yaml
  ci/cloudbuild/triggers/cmake-clang-ci.yaml
  ci/cloudbuild/triggers/cmake-clang-pr.yaml
  ci/cloudbuild/triggers/cmake-gcc-ci.yaml
  ci/cloudbuild/triggers/cmake-gcc-pr.yaml
  ci/cloudbuild/triggers/cmake-install-ci.yaml
  ci/cloudbuild/triggers/cmake-install-pr.yaml
  ci/cloudbuild/triggers/cmake-super-ci.yaml
  ci/cloudbuild/triggers/cmake-super-pr.yaml
  ci/cloudbuild/triggers/gcc-54-ci.yaml
  ci/cloudbuild/triggers/gcc-54-pr.yaml
  ci/cloudbuild/triggers/integration-ci.yaml
  ci/cloudbuild/triggers/integration-pr.yaml
  ci/cloudbuild/triggers/quickstart-bazel-ci.yaml
  ci/cloudbuild/triggers/quickstart-bazel-pr.yaml
  ci/cloudbuild/triggers/quickstart-cmake-ci.yaml
  ci/cloudbuild/triggers/quickstart-cmake-pr.yaml
  ci/cloudbuild/triggers/tsan-ci.yaml
  ci/cloudbuild/triggers/tsan-pr.yaml
  ci/cloudbuild/triggers/ubsan-ci.yaml
  ci/cloudbuild/triggers/ubsan-pr.yaml
  ci/cloudbuild/triggers/xsan-ci.yaml
  ci/cloudbuild/triggers/xsan-pr.yaml
Labels: cla: yes

#6233 ci(gcb): build quickstarts during install test
  ci/cloudbuild/builds/cmake-install.sh
  ci/cloudbuild/fedora.Dockerfile
Labels: cla: yes

#6230 fix(storage): disable self-signed JWT authentication
  google/cloud/storage/examples/CMakeLists.txt
  google/cloud/storage/examples/storage_auth_samples.cc
  google/cloud/storage/examples/storage_examples.bzl
  google/cloud/storage/oauth2/google_credentials.cc
Labels: api: storage, cla: yes

#6234 fix(storage): deflake IAM integration test
  google/cloud/storage/tests/bucket_integration_test.cc
Labels: api: storage, cla: yes

#6237 cleanup: tweak dockerignore to rebuild images less often
  .dockerignore
  ci/.dockerignore
Labels: cla: yes

#6239 ci(gcb): add demo-centos-7 install build
  ci/cloudbuild/builds/demo-install.sh
  ci/cloudbuild/demo-centos-7.Dockerfile
  ci/cloudbuild/triggers/demo-centos-7-ci.yaml
  ci/cloudbuild/triggers/demo-centos-7-pr.yaml
Labels: cla: yes

#6242 ci(gcb): build.sh now has a --trigger flag
  ci/cloudbuild/build.sh
Labels: cla: yes

#6236 feature(generator): support omitting rpcs from code generation
  ci/etc/generator-golden-md5-hashes.md5
  generator/CMakeLists.txt
  generator/google_cloud_cpp_generator_unit_tests.bzl
  generator/integration_tests/generator_integration_test.cc
  generator/integration_tests/golden/golden_kitchen_sink_client.gcpcxx.pb.h
  generator/integration_tests/golden/tests/golden_kitchen_sink_stub_test.cc
  generator/integration_tests/test.proto
  generator/internal/codegen_utils.cc
  generator/internal/connection_generator.cc
  generator/internal/option_defaults_generator.cc
  generator/internal/options_generator.cc
  generator/internal/predicate_utils.cc
  generator/internal/predicate_utils.h
  generator/internal/predicate_utils_test.cc
  generator/internal/service_code_generator.cc
  generator/internal/service_code_generator.h
  generator/internal/service_code_generator_test.cc
Labels: cla: yes

#6245 ci(gcb): add all remaining demo builds
  ci/cloudbuild/builds/demo-install.sh
  ci/cloudbuild/demo-centos-8.Dockerfile
  ci/cloudbuild/demo-debian-buster.Dockerfile
  ci/cloudbuild/demo-debian-stretch.Dockerfile
  ci/cloudbuild/demo-fedora.Dockerfile
  ci/cloudbuild/demo-opensuse-leap.Dockerfile
  ci/cloudbuild/demo-ubuntu-bionic.Dockerfile
  ci/cloudbuild/demo-ubuntu-focal.Dockerfile
  ci/cloudbuild/demo-ubuntu-xenial.Dockerfile
  ci/cloudbuild/triggers/demo-centos-8-ci.yaml
  ci/cloudbuild/triggers/demo-centos-8-pr.yaml
  ci/cloudbuild/triggers/demo-debian-buster-ci.yaml
  ci/cloudbuild/triggers/demo-debian-buster-pr.yaml
  ci/cloudbuild/triggers/demo-debian-stretch-ci.yaml
  ci/cloudbuild/triggers/demo-debian-stretch-pr.yaml
  ci/cloudbuild/triggers/demo-fedora-ci.yaml
  ci/cloudbuild/triggers/demo-fedora-pr.yaml
  ci/cloudbuild/triggers/demo-opensuse-leap-ci.yaml
  ci/cloudbuild/triggers/demo-opensuse-leap-pr.yaml
  ci/cloudbuild/triggers/demo-ubuntu-bionic-ci.yaml
  ci/cloudbuild/triggers/demo-ubuntu-bionic-pr.yaml
  ci/cloudbuild/triggers/demo-ubuntu-focal-ci.yaml
  ci/cloudbuild/triggers/demo-ubuntu-focal-pr.yaml
  ci/cloudbuild/triggers/demo-ubuntu-xenial-ci.yaml
  ci/cloudbuild/triggers/demo-ubuntu-xenial-pr.yaml
Labels: cla: yes

#6243 ci!: generator/ is no longer built by default in CMake
  CHANGELOG.md
  CMakeLists.txt
  ci/cloudbuild/builds/clang-tidy.sh
  ci/kokoro/docker/build-in-docker-cmake.sh
  ci/kokoro/install/Dockerfile.debian-buster
  doc/packaging.md
Labels: cla: yes

#6246 cleanup(gcb): move 12 Dockerfiles to a dockerfiles/ dir
  ci/cloudbuild/build.sh
  ci/cloudbuild/cloudbuild.yaml
  ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile
  ci/cloudbuild/dockerfiles/demo-centos-8.Dockerfile
  ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile
  ci/cloudbuild/dockerfiles/demo-debian-stretch.Dockerfile
  ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile
  ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile
  ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile
  ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile
  ci/cloudbuild/dockerfiles/demo-ubuntu-xenial.Dockerfile
  ci/cloudbuild/dockerfiles/fedora.Dockerfile
  ci/cloudbuild/dockerfiles/ubuntu-bionic.Dockerfile
  ci/cloudbuild/dockerfiles/ubuntu-xenial.Dockerfile
Labels: cla: yes

#6248 fix(gcb): ldconfig /usr/local/lib after installing stuff
  ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile
  ci/cloudbuild/dockerfiles/demo-centos-8.Dockerfile
  ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile
  ci/cloudbuild/dockerfiles/demo-debian-stretch.Dockerfile
  ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile
  ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile
  ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile
  ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile
  ci/cloudbuild/dockerfiles/demo-ubuntu-xenial.Dockerfile
Labels: cla: yes

#6249 doc(storage): wrong arguments for quickstart program
  google/cloud/storage/quickstart/README.md
Labels: api: storage, cla: yes

#6238 fix(storage): disable self-signed JWT authentication
  google/cloud/storage/examples/CMakeLists.txt
  google/cloud/storage/examples/storage_auth_samples.cc
  google/cloud/storage/examples/storage_examples.bzl
  google/cloud/storage/oauth2/google_credentials.cc
Labels: api: storage, cla: yes

#6250 ci(gcb): enable noex build
  ci/cloudbuild/builds/noex.sh
  ci/cloudbuild/triggers/noex-ci.yaml
  ci/cloudbuild/triggers/noex-pr.yaml
Labels: cla: yes

#6252 ci(gcb): add cxx17 build
  ci/cloudbuild/builds/cxx17.sh
  ci/cloudbuild/triggers/cxx17-ci.yaml
  ci/cloudbuild/triggers/cxx17-pr.yaml
Labels: cla: yes

#6253 ci(gcb): add libcxx build
  ci/cloudbuild/builds/libcxx.sh
  ci/cloudbuild/triggers/libcxx-ci.yaml
  ci/cloudbuild/triggers/libcxx-pr.yaml
Labels: cla: yes

#6251 chore: update version and release notes
  CHANGELOG.md
  CMakeLists.txt
  google/cloud/internal/version_info.h
Labels: cla: yes

#6255 ci(gcb): triggers will work on all branches we care about
  ci/cloudbuild/trigger.sh
  ci/cloudbuild/triggers/asan-ci.yaml
  ci/cloudbuild/triggers/asan-pr.yaml
  ci/cloudbuild/triggers/bazel-clang-ci.yaml
  ci/cloudbuild/triggers/bazel-clang-pr.yaml
  ci/cloudbuild/triggers/bazel-gcc-ci.yaml
  ci/cloudbuild/triggers/bazel-gcc-pr.yaml
  ci/cloudbuild/triggers/checkers-ci.yaml
  ci/cloudbuild/triggers/checkers-pr.yaml
  ci/cloudbuild/triggers/clang-38-ci.yaml
  ci/cloudbuild/triggers/clang-38-pr.yaml
  ci/cloudbuild/triggers/clang-tidy-ci.yaml
  ci/cloudbuild/triggers/clang-tidy-pr.yaml
  ci/cloudbuild/triggers/cmake-clang-ci.yaml
  ci/cloudbuild/triggers/cmake-clang-pr.yaml
  ci/cloudbuild/triggers/cmake-gcc-ci.yaml
  ci/cloudbuild/triggers/cmake-gcc-pr.yaml
  ci/cloudbuild/triggers/cmake-install-ci.yaml
  ci/cloudbuild/triggers/cmake-install-pr.yaml
  ci/cloudbuild/triggers/cmake-super-ci.yaml
  ci/cloudbuild/triggers/cmake-super-pr.yaml
  ci/cloudbuild/triggers/cxx17-ci.yaml
  ci/cloudbuild/triggers/cxx17-pr.yaml
  ci/cloudbuild/triggers/demo-centos-7-ci.yaml
  ci/cloudbuild/triggers/demo-centos-7-pr.yaml
  ci/cloudbuild/triggers/demo-centos-8-ci.yaml
  ci/cloudbuild/triggers/demo-centos-8-pr.yaml
  ci/cloudbuild/triggers/demo-debian-buster-ci.yaml
  ci/cloudbuild/triggers/demo-debian-buster-pr.yaml
  ci/cloudbuild/triggers/demo-debian-stretch-ci.yaml
  ci/cloudbuild/triggers/demo-debian-stretch-pr.yaml
  ci/cloudbuild/triggers/demo-fedora-ci.yaml
  ci/cloudbuild/triggers/demo-fedora-pr.yaml
  ci/cloudbuild/triggers/demo-opensuse-leap-ci.yaml
  ci/cloudbuild/triggers/demo-opensuse-leap-pr.yaml
  ci/cloudbuild/triggers/demo-ubuntu-bionic-ci.yaml
  ci/cloudbuild/triggers/demo-ubuntu-bionic-pr.yaml
  ci/cloudbuild/triggers/demo-ubuntu-focal-ci.yaml
  ci/cloudbuild/triggers/demo-ubuntu-focal-pr.yaml
  ci/cloudbuild/triggers/demo-ubuntu-xenial-ci.yaml
  ci/cloudbuild/triggers/demo-ubuntu-xenial-pr.yaml
  ci/cloudbuild/triggers/gcc-54-ci.yaml
  ci/cloudbuild/triggers/gcc-54-pr.yaml
  ci/cloudbuild/triggers/integration-ci.yaml
  ci/cloudbuild/triggers/integration-pr.yaml
  ci/cloudbuild/triggers/libcxx-ci.yaml
  ci/cloudbuild/triggers/libcxx-pr.yaml
  ci/cloudbuild/triggers/noex-ci.yaml
  ci/cloudbuild/triggers/noex-pr.yaml
  ci/cloudbuild/triggers/quickstart-bazel-ci.yaml
  ci/cloudbuild/triggers/quickstart-bazel-pr.yaml
  ci/cloudbuild/triggers/quickstart-cmake-ci.yaml
  ci/cloudbuild/triggers/quickstart-cmake-pr.yaml
  ci/cloudbuild/triggers/tsan-ci.yaml
  ci/cloudbuild/triggers/tsan-pr.yaml
  ci/cloudbuild/triggers/ubsan-ci.yaml
  ci/cloudbuild/triggers/ubsan-pr.yaml
  ci/cloudbuild/triggers/xsan-ci.yaml
  ci/cloudbuild/triggers/xsan-pr.yaml
Labels: cla: yes

#6256 refactor(storage): common code for client unit tests
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/bucket_test.cc
  google/cloud/storage/client_bucket_acl_test.cc
  google/cloud/storage/client_default_object_acl_test.cc
  google/cloud/storage/client_notifications_test.cc
  google/cloud/storage/client_object_acl_test.cc
  google/cloud/storage/client_object_copy_test.cc
  google/cloud/storage/client_service_account_test.cc
  google/cloud/storage/client_sign_policy_document_test.cc
  google/cloud/storage/client_sign_url_test.cc
  google/cloud/storage/client_write_object_test.cc
  google/cloud/storage/object_test.cc
  google/cloud/storage/parallel_uploads_test.cc
  google/cloud/storage/storage_client_testing.bzl
  google/cloud/storage/testing/client_unit_test.cc
  google/cloud/storage/testing/client_unit_test.h
  google/cloud/storage/testing/mock_client.h
Labels: api: storage, cla: yes

#6259 ci(gcb): add msan build
  ci/cloudbuild/builds/msan.sh
  ci/cloudbuild/dockerfiles/fedora-msan.Dockerfile
  ci/cloudbuild/triggers/msan-ci.yaml
  ci/cloudbuild/triggers/msan-pr.yaml
Labels: cla: yes

#6261 chore(spanner): quash warning about a leaked mocked object
  google/cloud/spanner/database_admin_connection_test.cc
Labels: api: spanner, cla: yes

#6258 cleanup(storage): deprecate overly permissive functions
  google/cloud/storage/benchmarks/throughput_experiment_test.cc
  google/cloud/storage/client.cc
  google/cloud/storage/client.h
  google/cloud/storage/client_test.cc
  google/cloud/storage/client_write_object_test.cc
  google/cloud/storage/examples/storage_client_mock_samples.cc
  google/cloud/storage/grpc_plugin.cc
  google/cloud/storage/object_test.cc
  google/cloud/storage/parallel_upload.h
  google/cloud/storage/testing/mock_client.h
  google/cloud/storage/testing/remove_stale_buckets_test.cc
  google/cloud/storage/testing/retry_tests.h
  google/cloud/storage/testing/storage_integration_test.cc
  google/cloud/storage/tests/curl_resumable_upload_session_integration_test.cc
  google/cloud/storage/tests/curl_sign_blob_integration_test.cc
  google/cloud/storage/tests/object_resumable_write_integration_test.cc
  google/cloud/storage/tests/object_write_streambuf_integration_test.cc
Labels: api: storage, cla: yes

#6265 cleanup: avoid CMake warning-message markup
  super/ExternalProjectHelper.cmake
Labels: cla: yes

#6264 ci: introduce io::log_cmdline
  ci/kokoro/docker/build-in-docker-bazel.sh
  ci/kokoro/docker/build-in-docker-cmake.sh
  ci/kokoro/docker/build.sh
  ci/lib/io.sh
  google/cloud/storage/tools/run_emulator_utils.sh
Labels: cla: yes

#6267 ci(gcb): add gcs-grpc build
  ci/cloudbuild/builds/gcs-grpc.sh
  ci/cloudbuild/triggers/gcs-grpc-ci.yaml
  ci/cloudbuild/triggers/gcs-grpc-pr.yaml
Labels: cla: yes

#6269 cleanup: use wildcard matcher (_) even more sparingly
  generator/integration_tests/golden/tests/golden_kitchen_sink_logging_decorator_test.cc
  generator/integration_tests/golden/tests/golden_thing_admin_logging_decorator_test.cc
  google/cloud/bigtable/testing/mock_async_failing_rpc_factory.h
  google/cloud/spanner/samples/mock_execute_query.cc
  google/cloud/storage/examples/storage_client_mock_samples.cc
Labels: cla: yes

#6270 ci(gcb): enable coverage build
  ci/cloudbuild/build.sh
  ci/cloudbuild/builds/coverage.sh
  ci/cloudbuild/cloudbuild.yaml
  ci/cloudbuild/triggers/coverage-ci.yaml
  ci/cloudbuild/triggers/coverage-pr.yaml
Labels: cla: yes

#6273 ci(gcb): fix coverage build (hopefully)
  ci/cloudbuild/builds/coverage.sh
Labels: cla: yes

#6262 feature(generator): add standalone executable with config file support
  generator/BUILD
  generator/CMakeLists.txt
  generator/generator_config.proto
  generator/generator_config.textproto
  generator/plugin_main.cc
  generator/standalone_main.cc
Labels: cla: yes

#6277 ci(gcb): run slow spanner instance tests during coverage build
  ci/cloudbuild/builds/coverage.sh
  ci/cloudbuild/builds/lib/integration.sh
Labels: cla: yes

#6275 ci(gcb): fix missing trigger type in some builds
  ci/cloudbuild/trigger.sh
  ci/cloudbuild/triggers/coverage-ci.yaml
  ci/cloudbuild/triggers/coverage-pr.yaml
  ci/cloudbuild/triggers/cxx17-ci.yaml
  ci/cloudbuild/triggers/cxx17-pr.yaml
  ci/cloudbuild/triggers/gcs-grpc-ci.yaml
  ci/cloudbuild/triggers/gcs-grpc-pr.yaml
  ci/cloudbuild/triggers/libcxx-ci.yaml
  ci/cloudbuild/triggers/libcxx-pr.yaml
  ci/cloudbuild/triggers/msan-ci.yaml
  ci/cloudbuild/triggers/msan-pr.yaml
  ci/cloudbuild/triggers/noex-ci.yaml
  ci/cloudbuild/triggers/noex-pr.yaml
  ci/cloudbuild/triggers/shared-ci.yaml
  ci/cloudbuild/triggers/shared-pr.yaml
Labels: cla: yes

#6280 ci(gcb): set LD_LIBRARY_PATH when running `quickstart`
  ci/cloudbuild/builds/lib/quickstart.sh
Labels: cla: yes

#6281 ci(gcb): misc cleanups
  ci/cloudbuild/README.md
  ci/cloudbuild/build.sh
  ci/cloudbuild/builds/README.md
Labels: cla: yes

#6282 refactor(storage): use g::c::Options in RawClients
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/benchmarks/throughput_experiment.cc
  google/cloud/storage/client.cc
  google/cloud/storage/client.h
  google/cloud/storage/client_options.cc
  google/cloud/storage/client_options.h
  google/cloud/storage/client_options_test.cc
  google/cloud/storage/examples/storage_grpc_samples.cc
  google/cloud/storage/google_cloud_cpp_storage.bzl
  google/cloud/storage/grpc_plugin.cc
  google/cloud/storage/grpc_plugin.h
  google/cloud/storage/idempotency_policy.h
  google/cloud/storage/internal/curl_client.h
  google/cloud/storage/internal/curl_client_test.cc
  google/cloud/storage/internal/grpc_client.cc
  google/cloud/storage/internal/grpc_client.h
  google/cloud/storage/internal/grpc_client_failures_test.cc
  google/cloud/storage/internal/hybrid_client.cc
  google/cloud/storage/internal/hybrid_client.h
  google/cloud/storage/internal/retry_client.cc
  google/cloud/storage/internal/retry_client.h
  google/cloud/storage/internal/retry_client_test.cc
  google/cloud/storage/internal/retry_object_read_source_test.cc
  google/cloud/storage/options.h
  google/cloud/storage/testing/storage_integration_test.cc
Labels: api: storage, cla: yes

#6284 ci(gcb): write logs to our own bucket
  ci/cloudbuild/build.sh
  ci/cloudbuild/cloudbuild.yaml
Labels: cla: yes

#6285 ci(gcb): rename _CACHE_TYPE -> _TRIGGER_SOURCE
  ci/cloudbuild/build.sh
  ci/cloudbuild/cloudbuild.yaml
Labels: cla: yes

#6287 ci(gcb): include PR number as a build tag
  ci/cloudbuild/cloudbuild.yaml
Labels: cla: yes

#6288 fix(generator): missing tests
  generator/integration_tests/golden/CMakeLists.txt
  generator/integration_tests/golden/google_cloud_cpp_generator_golden_tests.bzl
  generator/integration_tests/golden/tests/golden_thing_admin_option_defaults_test.cc
Labels: cla: yes

#6296 test(storage): fix emulator offset handling
  google/cloud/storage/emulator/database.py
Labels: api: storage, cla: yes

#6290 refactor(generator): generate libraries using generator config file
  generator/generate-libraries.sh
Labels: cla: yes

#6292 ci(gcb): add the log-linker script
  ci/cloudbuild/builds/log-linker.sh
  ci/cloudbuild/cloudbuild.yaml
  ci/cloudbuild/dockerfiles/debian-github.Dockerfile
  ci/cloudbuild/triggers/log-linker-pr.yaml
Labels: cla: yes

#6297 cleanup(storage): simplify RawGrpc initialization
  google/cloud/storage/benchmarks/throughput_experiment.cc
Labels: api: storage, cla: yes

#6298 ci(gcb): write build logs to `cloud-cpp-community-publiclogs` bucket
  ci/cloudbuild/build.sh
  ci/cloudbuild/builds/log-linker.sh
  ci/cloudbuild/cloudbuild.yaml
Labels: cla: yes

#6299 feat(common): bootstrap Unified Authentication Client
  google/cloud/CMakeLists.txt
  google/cloud/google_cloud_cpp_common.bzl
  google/cloud/google_cloud_cpp_common_unit_tests.bzl
  google/cloud/internal/credentials.cc
  google/cloud/internal/credentials.h
  google/cloud/internal/credentials_test.cc
Labels: cla: yes

#6301 feat(storage): map unified to REST credentials
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/google_cloud_cpp_storage.bzl
  google/cloud/storage/internal/access_token_credentials.cc
  google/cloud/storage/internal/access_token_credentials.h
  google/cloud/storage/internal/access_token_credentials_test.cc
  google/cloud/storage/internal/error_credentials.cc
  google/cloud/storage/internal/error_credentials.h
  google/cloud/storage/internal/unified_rest_credentials.cc
  google/cloud/storage/internal/unified_rest_credentials.h
  google/cloud/storage/internal/unified_rest_credentials_test.cc
  google/cloud/storage/storage_client_unit_tests.bzl
Labels: api: storage, cla: yes

#6305 feature(generator): handle enum types in method signature
  ci/etc/generator-golden-md5-hashes.md5
  generator/integration_tests/golden/golden_kitchen_sink_client.cc
  generator/integration_tests/golden/golden_kitchen_sink_client.h
  generator/integration_tests/golden/golden_kitchen_sink_connection.cc
  generator/integration_tests/golden/golden_kitchen_sink_connection.h
  generator/integration_tests/golden/golden_kitchen_sink_connection_idempotency_policy.cc
  generator/integration_tests/golden/golden_kitchen_sink_connection_idempotency_policy.h
  generator/integration_tests/golden/internal/golden_kitchen_sink_logging_decorator.cc
  generator/integration_tests/golden/internal/golden_kitchen_sink_logging_decorator.h
  generator/integration_tests/golden/internal/golden_kitchen_sink_metadata_decorator.cc
  generator/integration_tests/golden/internal/golden_kitchen_sink_metadata_decorator.h
  generator/integration_tests/golden/internal/golden_kitchen_sink_stub.cc
  generator/integration_tests/golden/internal/golden_kitchen_sink_stub.h
  generator/integration_tests/golden/mocks/mock_golden_kitchen_sink_connection.h
  generator/integration_tests/golden/tests/golden_kitchen_sink_client_test.cc
  generator/integration_tests/golden/tests/golden_kitchen_sink_connection_test.cc
  generator/integration_tests/golden/tests/golden_kitchen_sink_idempotency_policy_test.cc
  generator/integration_tests/golden/tests/golden_kitchen_sink_logging_decorator_test.cc
  generator/integration_tests/golden/tests/golden_kitchen_sink_metadata_decorator_test.cc
  generator/integration_tests/golden/tests/golden_kitchen_sink_stub_test.cc
  generator/integration_tests/test.proto
  generator/internal/descriptor_utils.cc
  generator/internal/descriptor_utils_test.cc
Labels: cla: yes

#6312 feature(generator): ensure method signature parameters passed by const-ref where appropriate
  ci/etc/generator-golden-md5-hashes.md5
  generator/integration_tests/golden/golden_kitchen_sink_client.cc
  generator/integration_tests/golden/golden_kitchen_sink_client.h
  generator/internal/descriptor_utils.cc
  generator/internal/descriptor_utils_test.cc
Labels: cla: yes

#6314 ci(gcb): add check-abi build
  ci/cloudbuild/builds/check-abi.sh
  ci/cloudbuild/dockerfiles/fedora.Dockerfile
  ci/cloudbuild/triggers/check-abi-ci.yaml
  ci/cloudbuild/triggers/check-abi-pr.yaml
Labels: cla: yes

#6315 ci(gcb): fix bug in check-abi
  ci/cloudbuild/builds/check-abi.sh
Labels: cla: yes

#6304 feat(common): support unified credentials in gRPC
  google/cloud/CMakeLists.txt
  google/cloud/google_cloud_cpp_grpc_utils.bzl
  google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl
  google/cloud/internal/grpc_access_token_authentication.cc
  google/cloud/internal/grpc_access_token_authentication.h
  google/cloud/internal/grpc_access_token_authentication_test.cc
  google/cloud/internal/grpc_channel_credentials_authentication.cc
  google/cloud/internal/grpc_channel_credentials_authentication.h
  google/cloud/internal/grpc_channel_credentials_authentication_test.cc
  google/cloud/internal/unified_grpc_credentials.cc
  google/cloud/internal/unified_grpc_credentials.h
  google/cloud/internal/unified_grpc_credentials_test.cc
Labels: cla: yes

#6316 ci(gcb): create secrets if necessary
  ci/cloudbuild/build.sh
Labels: cla: yes

#6320 cleanup(storage): remove redundant integration test
  google/cloud/storage/tests/grpc_integration_test.cc
Labels: api: storage, cla: yes

#6321 ci(gcb): add 'update abi' behavior to 'check-abi'
  ci/cloudbuild/builds/check-abi.sh
Labels: cla: yes

#6322 ci(gcb): add generator hash checks to checkers build
  ci/cloudbuild/builds/checkers.sh
Labels: cla: yes

#6324 ci: clang-tidy the GCS+gRPC plugin code
  ci/cloudbuild/builds/clang-tidy.sh
Labels: cla: yes

#6318 ci: some further tweaking of build.sh logging
  ci/kokoro/docker/build-in-docker-bazel.sh
  ci/kokoro/docker/build-in-docker-cmake.sh
  ci/kokoro/docker/build.sh
Labels: cla: yes

#6317 cleanup(spanner): quash some doxygen warnings
  google/cloud/spanner/database_admin_connection.h
  google/cloud/spanner/instance_admin_connection.h
Labels: api: spanner, cla: yes

#6323 feat(storage): use the unified authentication client
  google/cloud/internal/grpc_access_token_authentication_test.cc
  google/cloud/internal/grpc_channel_credentials_authentication_test.cc
  google/cloud/internal/unified_grpc_credentials_test.cc
  google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh
  google/cloud/storage/internal/grpc_client.cc
  google/cloud/storage/internal/grpc_client.h
  google/cloud/storage/internal/grpc_object_read_source.cc
  google/cloud/storage/internal/grpc_object_read_source.h
  google/cloud/storage/internal/grpc_object_read_source_test.cc
  google/cloud/storage/tests/CMakeLists.txt
  google/cloud/storage/tests/storage_client_integration_tests.bzl
  google/cloud/storage/tests/unified_credentials_integration_test.cc
Labels: api: storage, cla: yes

#6326 cleanup(spanner): adjust naming of RequestOptions.Priority values
  google/cloud/spanner/internal/connection_impl.cc
  google/cloud/spanner/internal/connection_impl_test.cc
  google/cloud/spanner/read_partition.cc
Labels: api: spanner, cla: yes

#6325 feat: support errors in DynamicAccessTokenCredentials
  google/cloud/internal/credentials.h
  google/cloud/internal/credentials_test.cc
  google/cloud/internal/grpc_access_token_authentication.cc
  google/cloud/internal/grpc_access_token_authentication.h
  google/cloud/internal/grpc_access_token_authentication_test.cc
  google/cloud/storage/internal/access_token_credentials.cc
  google/cloud/storage/internal/access_token_credentials.h
  google/cloud/storage/internal/access_token_credentials_test.cc
Labels: cla: yes

#6329 ci(gcb): run integration tests with cmake builds
  ci/cloudbuild/builds/asan.sh
  ci/cloudbuild/builds/clang-tidy.sh
  ci/cloudbuild/builds/cmake-clang.sh
  ci/cloudbuild/builds/cmake-gcc.sh
  ci/cloudbuild/builds/coverage.sh
  ci/cloudbuild/builds/cxx17.sh
  ci/cloudbuild/builds/gcs-grpc.sh
  ci/cloudbuild/builds/integration.sh
  ci/cloudbuild/builds/lib/integration.sh
  ci/cloudbuild/builds/libcxx.sh
  ci/cloudbuild/builds/msan.sh
  ci/cloudbuild/builds/noex.sh
  ci/cloudbuild/builds/tsan.sh
  ci/cloudbuild/builds/ubsan.sh
  ci/cloudbuild/builds/xsan.sh
Labels: cla: yes

#6331 ci(gcb): add rotate-keys *manual* build
  ci/cloudbuild/builds/rotate-keys.sh
Labels: cla: yes

#6334 ci: parallelize unit and integration test with CTest
  ci/cloudbuild/builds/clang-tidy.sh
  ci/cloudbuild/builds/cmake-clang.sh
  ci/cloudbuild/builds/cmake-gcc.sh
  ci/cloudbuild/builds/cxx17.sh
  ci/cloudbuild/builds/lib/integration.sh
  ci/cloudbuild/builds/noex.sh
  ci/cloudbuild/builds/shared.sh
Labels: cla: yes

#6335 ci: remove docker pull noise from main step
  ci/cloudbuild/cloudbuild.yaml
Labels: cla: yes

#6338 ci(gcb): make GCB logs link directly to PR
  ci/cloudbuild/builds/log-linker.sh
Labels: cla: yes

#6339 ci: enable dependabot
  .github/DEPENDENCIES.md
  .github/dependabot.yml
  .github/workflows/dependencies.yaml
Labels: cla: yes

#6340 ci(gcb): add publish-docs build
  ci/cloudbuild/build.sh
  ci/cloudbuild/builds/publish-docs.sh
  ci/cloudbuild/cloudbuild.yaml
  ci/cloudbuild/triggers/publish-docs-ci.yaml
  ci/cloudbuild/triggers/publish-docs-pr.yaml
Labels: cla: yes

#6341 doc(release): update our release instructions for GCB changes
  release/README.md
Labels: cla: yes

#6344 ci(gcb): add generate-libraries
  ci/cloudbuild/builds/checkers.sh
  ci/cloudbuild/builds/generate-libraries.sh
  ci/cloudbuild/builds/lib/git.sh
  ci/cloudbuild/builds/lib/integration.sh
  ci/cloudbuild/triggers/generate-libraries-ci.yaml
  ci/cloudbuild/triggers/generate-libraries-pr.yaml
Labels: cla: yes

#6347 ci: disable dependabot
  .github/dependabot.yml
Labels: cla: yes

#6348 feat: minimal stub for service account impersonation
  google/cloud/BUILD
  google/cloud/CMakeLists.txt
  google/cloud/google_cloud_cpp_grpc_utils.bzl
  google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl
  google/cloud/internal/minimal_iam_credentials_stub.cc
  google/cloud/internal/minimal_iam_credentials_stub.h
  google/cloud/internal/minimal_iam_credentials_stub_test.cc
Labels: cla: yes

#6355 fix(gcb): set env vars so --local builds work
  ci/cloudbuild/build.sh
  ci/cloudbuild/builds/publish-docs.sh
Labels: cla: yes

#6356 ci(gcb): add scan-build but no trigger
  ci/cloudbuild/builds/scan-build.sh
Labels: cla: yes

#6359 ci: tell Renovate to ignore googleapis/googleapis
  .github/renovate.json
  renovate.json
Labels: cla: yes

#6362 doc: add link and heading to gcb readme
  ci/cloudbuild/README.md
Labels: cla: yes

#6369 ci(gcb): checkers build generates markdown
  ci/cloudbuild/builds/checkers.sh
Labels: cla: yes

#6363 ci(gcb): test component installs
  ci/cloudbuild/builds/cmake-install.sh
  ci/cloudbuild/builds/demo-install.sh
  ci/cloudbuild/builds/lib/quickstart.sh
  ci/cloudbuild/builds/shared.sh
Labels: cla: yes

#6364 ci: automatically update Dockerfiles with Renovate
  .github/renovate.json
Labels: cla: yes

#6373 test(spanner): isolate unit test from prevailing environment
  google/cloud/spanner/internal/defaults_test.cc
Labels: api: spanner, cla: yes

#6376 ci: make Dockerfiles easier to update
  ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile
  ci/cloudbuild/dockerfiles/demo-centos-8.Dockerfile
  ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile
  ci/cloudbuild/dockerfiles/demo-debian-stretch.Dockerfile
  ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile
  ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile
  ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile
  ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile
  ci/cloudbuild/dockerfiles/demo-ubuntu-xenial.Dockerfile
Labels: cla: yes

#6379 ci: make install Dockerfiles easier to update
  ci/generate-markdown/dockerfile2markdown.sh
  ci/kokoro/install/Dockerfile.centos-7
  ci/kokoro/install/Dockerfile.centos-8
  ci/kokoro/install/Dockerfile.debian-buster
  ci/kokoro/install/Dockerfile.debian-stretch
  ci/kokoro/install/Dockerfile.fedora
  ci/kokoro/install/Dockerfile.fedora-components
  ci/kokoro/install/Dockerfile.opensuse-leap
  ci/kokoro/install/Dockerfile.ubuntu-bionic
  ci/kokoro/install/Dockerfile.ubuntu-focal
  ci/kokoro/install/Dockerfile.ubuntu-xenial
  doc/packaging.md
Labels: cla: yes

#6380 cleanup: remove dependabot remnants
  .github/DEPENDENCIES.md
  .github/workflows/dependencies.yaml
Labels: cla: yes

#6381 feat: a cache for access tokens retrieved using gRPC
  google/cloud/CMakeLists.txt
  google/cloud/google_cloud_cpp_grpc_utils.bzl
  google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl
  google/cloud/internal/grpc_async_access_token_cache.cc
  google/cloud/internal/grpc_async_access_token_cache.h
  google/cloud/internal/grpc_async_access_token_cache_test.cc
Labels: cla: yes

#6382 ci(gcb): add builds to verify current/deprecated targets
  ci/cloudbuild/builds/bazel-targets.sh
  ci/cloudbuild/builds/cmake-install.sh
  ci/cloudbuild/triggers/bazel-targets-ci.yaml
  ci/cloudbuild/triggers/bazel-targets-pr.yaml
Labels: cla: yes

#6383 doc: update dev docs to use cloudbuild tools
  ci/cloudbuild/builds/publish-docs.sh
  doc/contributor/README.md
  doc/contributor/howto-guide-forks-and-pull-requests.md
  doc/contributor/howto-guide-running-ci-builds-locally.md
  doc/contributor/howto-guide-setup-development-workstation.md
Labels: cla: yes

#6332 fix: support resumable uploads for nodejs-storage
  google/cloud/storage/emulator/emulator.py
  google/cloud/storage/emulator/gcs/holder.py
  google/cloud/storage/emulator/utils/common.py
Labels: cla: yes

#6386 ci(gcb): add integration-daily build to GCB
  ci/cloudbuild/builds/integration-daily.sh
  ci/cloudbuild/builds/lib/integration.sh
Labels: cla: yes

#6385 doc(gcb): update the markdown generators to use gcb files
  ci/cloudbuild/builds/demo-install.sh
  ci/cloudbuild/dockerfiles/demo-ubuntu-xenial.Dockerfile
  ci/generate-markdown/README.md
  ci/generate-markdown/extract-install.sh
  ci/generate-markdown/generate-packaging.sh
  doc/packaging.md
Labels: cla: yes

#6387 cleanup: remove support for dynamic access token
  google/cloud/internal/credentials.cc
  google/cloud/internal/credentials.h
  google/cloud/internal/credentials_test.cc
  google/cloud/internal/grpc_access_token_authentication.cc
  google/cloud/internal/grpc_access_token_authentication.h
  google/cloud/internal/grpc_access_token_authentication_test.cc
  google/cloud/internal/unified_grpc_credentials.cc
  google/cloud/storage/internal/access_token_credentials.cc
  google/cloud/storage/internal/access_token_credentials.h
  google/cloud/storage/internal/access_token_credentials_test.cc
  google/cloud/storage/internal/unified_rest_credentials.cc
  google/cloud/storage/internal/unified_rest_credentials_test.cc
  google/cloud/storage/tests/unified_credentials_integration_test.cc
Labels: cla: yes

#6390 ci: create an index.html file with the logs for each PR
  ci/cloudbuild/builds/log-linker.sh
  ci/cloudbuild/notifiers/logs/README.md
  ci/cloudbuild/notifiers/logs/function/CMakeLists.txt
  ci/cloudbuild/notifiers/logs/function/function.cc
  ci/cloudbuild/notifiers/logs/function/vcpkg.json
Labels: cla: yes

#6392 chore(generator): formatting
  generator/internal/descriptor_utils_test.cc
Labels: cla: yes

#6389 ci(gcb): include log links in log output
  ci/cloudbuild/build.sh
  ci/cloudbuild/cloudbuild.yaml
Labels: cla: yes

#6393 ci: build with older versions of each dep
  ci/cloudbuild/builds/cmake-oldest-deps.sh
  ci/cloudbuild/dockerfiles/fedora.Dockerfile
  ci/cloudbuild/triggers/cmake-oldest-deps-ci.yaml
  ci/cloudbuild/triggers/cmake-oldest-deps-pr.yaml
  ci/etc/oldest-deps/vcpkg.json
Labels: cla: yes

#6397 ci(gcb): ui tweaks to the public logs index.html page
  ci/cloudbuild/builds/log-linker.sh
  ci/cloudbuild/notifiers/logs/README.md
  ci/cloudbuild/notifiers/logs/function/function.cc
Labels: cla: yes

#6396 cleanup: remove remnants of AccessTokenSource
  google/cloud/storage/internal/access_token_credentials.h
  google/cloud/storage/tests/unified_credentials_integration_test.cc
Labels: cla: yes

#6391 feat(common): support asynchronous RPCs in GrpcAuthenticationStrategy
  google/cloud/internal/grpc_access_token_authentication.cc
  google/cloud/internal/grpc_access_token_authentication.h
  google/cloud/internal/grpc_channel_credentials_authentication.cc
  google/cloud/internal/grpc_channel_credentials_authentication.h
  google/cloud/internal/unified_grpc_credentials.h
Labels: cla: yes

#6400 cleanup(bigtable): remove duplicate test
  google/cloud/bigtable/table_sample_row_keys_test.cc
Labels: cla: yes

#6403 test: avoid overwhelming the emulator
  google/cloud/storage/tests/object_file_multi_threaded_test.cc
  google/cloud/storage/tools/run_emulator_utils.sh
Labels: cla: yes

#6405 ci(gcb): add title for public logs index.html page
  ci/cloudbuild/notifiers/logs/function/function.cc
Labels: cla: yes

#6401 feat(common): gRPC support for service account impersonation
  ci/cloudbuild/builds/lib/integration.sh
  google/cloud/BUILD
  google/cloud/CMakeLists.txt
  google/cloud/google_cloud_cpp_grpc_utils.bzl
  google/cloud/google_cloud_cpp_grpc_utils_integration_tests.bzl
  google/cloud/internal/grpc_impersonate_service_account.cc
  google/cloud/internal/grpc_impersonate_service_account.h
  google/cloud/internal/grpc_impersonate_service_account_integration_test.cc
  google/cloud/internal/minimal_iam_credentials_stub.cc
Labels: cla: yes

#6407 ci(gcb): add patch to cloudbuild docker images
  ci/cloudbuild/dockerfiles/fedora.Dockerfile
  ci/cloudbuild/dockerfiles/ubuntu-bionic.Dockerfile
  ci/cloudbuild/dockerfiles/ubuntu-xenial.Dockerfile
  external/googleapis/CMakeLists.txt
Labels: cla: yes

#6404 ci: support testing for the logs notifier
  ci/cloudbuild/notifiers/logs/README.md
  ci/cloudbuild/notifiers/logs/function/function.cc
Labels: cla: yes

#6409 doc: remove Linux Kokoro badges
  README.md
  ci/generate-markdown/generate-readme.sh
Labels: cla: yes

#6406 refactor: make logs notifier easier to explain
  ci/cloudbuild/notifiers/logs/function/CMakeLists.txt
  ci/cloudbuild/notifiers/logs/function/function.cc
Labels: cla: yes

#6408 ci: improve build logs summary
  ci/cloudbuild/notifiers/logs/README.md
  ci/cloudbuild/notifiers/logs/function/CMakeLists.txt
  ci/cloudbuild/notifiers/logs/function/function.cc
  ci/cloudbuild/notifiers/logs/function/vcpkg.json
Labels: cla: yes

#6411 ci: fix mistake in test instructions
  ci/cloudbuild/notifiers/logs/README.md
Labels: cla: yes

#6412 ci: enable integration tests from local docker
  ci/cloudbuild/build.sh
  ci/cloudbuild/builds/lib/integration.sh
  ci/cloudbuild/builds/lib/quickstart.sh
Labels: cla: yes

#6413 ci: fix mount point for gcloud config
  ci/cloudbuild/build.sh
Labels: cla: yes

#6414 ci: fix abi compat_report to be written in cmake-out
  ci/cloudbuild/builds/check-abi.sh
Labels: cla: yes

#6415 chore: configure trusted-contribution bot
  .github/trusted-contribution.yml
Labels: cla: yes

#6416 ci: avoid root-owned /h/.config/gcloud dir
  ci/cloudbuild/build.sh
Labels: cla: yes

#6419 chore: configure renovate to run weekly
  .github/renovate.json
Labels: cla: yes

#6420 ci: remove dupe builds
  ci/cloudbuild/builds/bazel-clang.sh
  ci/cloudbuild/builds/bazel-gcc.sh
  ci/cloudbuild/builds/cmake-clang.sh
  ci/cloudbuild/builds/cmake-gcc.sh
  ci/cloudbuild/triggers/bazel-clang-ci.yaml
  ci/cloudbuild/triggers/bazel-clang-pr.yaml
  ci/cloudbuild/triggers/bazel-gcc-ci.yaml
  ci/cloudbuild/triggers/bazel-gcc-pr.yaml
  ci/cloudbuild/triggers/cmake-clang-ci.yaml
  ci/cloudbuild/triggers/cmake-clang-pr.yaml
  ci/cloudbuild/triggers/cmake-gcc-ci.yaml
  ci/cloudbuild/triggers/cmake-gcc-pr.yaml
Labels: cla: yes

#6421 ci: remove separate integration build
  ci/cloudbuild/build.sh
  ci/cloudbuild/builds/integration.sh
  ci/cloudbuild/triggers/integration-ci.yaml
  ci/cloudbuild/triggers/integration-pr.yaml
Labels: cla: yes

#6422 ci: rename check-abi -> check-api
  ci/cloudbuild/builds/check-api.sh
  ci/cloudbuild/triggers/check-api-ci.yaml
  ci/cloudbuild/triggers/check-api-pr.yaml
  release/README.md
Labels: cla: yes

#6423 ci: use tags that don't conflict w/ snippet-bot
  ci/cloudbuild/builds/demo-install.sh
  ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile
  ci/cloudbuild/dockerfiles/demo-centos-8.Dockerfile
  ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile
  ci/cloudbuild/dockerfiles/demo-debian-stretch.Dockerfile
  ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile
  ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile
  ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile
  ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile
  ci/cloudbuild/dockerfiles/demo-ubuntu-xenial.Dockerfile
  ci/generate-markdown/dockerfile2markdown.sh
  ci/generate-markdown/generate-packaging.sh
Labels: cla: yes

#6425 feat(storage): minimal stub for IAM credentials service
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh
  google/cloud/storage/google_cloud_cpp_storage.bzl
  google/cloud/storage/internal/minimal_iam_credentials_rest.cc
  google/cloud/storage/internal/minimal_iam_credentials_rest.h
  google/cloud/storage/tests/CMakeLists.txt
  google/cloud/storage/tests/minimal_iam_credentials_rest_integration_test.cc
  google/cloud/storage/tests/storage_client_integration_tests.bzl
Labels: api: storage, cla: yes

#6428 ci: quickstart Makefile doesn't leave binary in repo
  ci/cloudbuild/builds/lib/quickstart.sh
  google/cloud/bigquery/quickstart/Makefile
  google/cloud/bigtable/quickstart/Makefile
  google/cloud/pubsub/quickstart/Makefile
  google/cloud/spanner/quickstart/Makefile
  google/cloud/storage/quickstart/Makefile
Labels: cla: yes

#6431 ci: forward GOOGLE_CLOUD_* env to docker
  ci/cloudbuild/build.sh
  ci/cloudbuild/builds/lib/integration.sh
  google/cloud/spanner/internal/defaults.cc
Labels: cla: yes
