Repository googleapis/google-cloud-cpp, pull requests merged in 2021-11, with the labels that each got.

#7540 feat(generator): selectively generate async methods for certain RPCs
  generator/generator_config.proto
  generator/integration_tests/generator_integration_test.cc
  generator/integration_tests/golden/golden_thing_admin_client.cc
  generator/integration_tests/golden/golden_thing_admin_client.h
  generator/integration_tests/golden/golden_thing_admin_connection.cc
  generator/integration_tests/golden/golden_thing_admin_connection.h
  generator/integration_tests/golden/internal/golden_kitchen_sink_auth_decorator.cc
  generator/integration_tests/golden/internal/golden_kitchen_sink_auth_decorator.h
  generator/integration_tests/golden/internal/golden_thing_admin_auth_decorator.cc
  generator/integration_tests/golden/internal/golden_thing_admin_auth_decorator.h
  generator/integration_tests/golden/internal/golden_thing_admin_logging_decorator.cc
  generator/integration_tests/golden/internal/golden_thing_admin_logging_decorator.h
  generator/integration_tests/golden/internal/golden_thing_admin_metadata_decorator.cc
  generator/integration_tests/golden/internal/golden_thing_admin_metadata_decorator.h
  generator/integration_tests/golden/internal/golden_thing_admin_stub.cc
  generator/integration_tests/golden/internal/golden_thing_admin_stub.h
  generator/integration_tests/golden/mocks/mock_golden_thing_admin_connection.h
  generator/integration_tests/golden/mocks/mock_golden_thing_admin_stub.h
  generator/integration_tests/golden/tests/golden_thing_admin_auth_decorator_test.cc
  generator/integration_tests/golden/tests/golden_thing_admin_client_test.cc
  generator/integration_tests/golden/tests/golden_thing_admin_connection_test.cc
  generator/integration_tests/golden/tests/golden_thing_admin_logging_decorator_test.cc
  generator/integration_tests/golden/tests/golden_thing_admin_metadata_decorator_test.cc
  generator/integration_tests/golden/tests/golden_thing_admin_stub_test.cc
  generator/internal/auth_decorator_generator.cc
  generator/internal/client_generator.cc
  generator/internal/codegen_utils.cc
  generator/internal/codegen_utils_test.cc
  generator/internal/connection_generator.cc
  generator/internal/logging_decorator_generator.cc
  generator/internal/metadata_decorator_generator.cc
  generator/internal/mock_connection_generator.cc
  generator/internal/service_code_generator.cc
  generator/internal/service_code_generator.h
  generator/internal/stub_generator.cc
  generator/standalone_main.cc
Labels: cla: yes

#7518 test(bigtable): clarify which admin integration tests run, and when
  ci/kokoro/macos/builds/bazel.sh
  ci/kokoro/windows/build-bazel.ps1
  google/cloud/bigtable/ci/run_integration_tests_emulator_cmake.sh
  google/cloud/bigtable/testing/table_integration_test.cc
  google/cloud/bigtable/testing/table_integration_test.h
  google/cloud/bigtable/tests/admin_backup_integration_test.cc
  google/cloud/bigtable/tests/admin_iam_policy_integration_test.cc
  google/cloud/bigtable/tests/admin_integration_test.cc
  google/cloud/bigtable/tests/instance_admin_integration_test.cc
Labels: cla: yes, api: bigtable

#7546 doc: update CHANGELOG for v1.33.0 release
  CHANGELOG.md
Labels: cla: yes

#7548 chore: bump version and abi dumps
  CMakeLists.txt
  ci/abi-dumps/google_cloud_cpp_bigquery.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_bigtable.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_common.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_grpc_utils.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_iam.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_pubsub.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_spanner.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_storage.expected.abi.dump.gz
  google/cloud/internal/version_info.h
Labels: cla: yes

#7551 ci: fix testbench install on linux
  ci/cloudbuild/builds/lib/integration.sh
Labels: cla: yes

#7549 test(spanner): bump create-database timeout from ~300s to ~600s
  google/cloud/spanner/integration_tests/rpc_failure_threshold_integration_test.cc
  google/cloud/spanner/testing/database_integration_test.cc
Labels: cla: yes, api: spanner

#7550 feat(bigtable): add generated admin APIs
  ci/cloudbuild/builds/generate-libraries.sh
  generator/generator_config.textproto
  google/cloud/bigtable/admin/bigtable_instance_admin_client.cc
  google/cloud/bigtable/admin/bigtable_instance_admin_client.h
  google/cloud/bigtable/admin/bigtable_instance_admin_connection.cc
  google/cloud/bigtable/admin/bigtable_instance_admin_connection.h
  google/cloud/bigtable/admin/bigtable_instance_admin_connection_idempotency_policy.cc
  google/cloud/bigtable/admin/bigtable_instance_admin_connection_idempotency_policy.h
  google/cloud/bigtable/admin/bigtable_instance_admin_options.h
  google/cloud/bigtable/admin/bigtable_table_admin_client.cc
  google/cloud/bigtable/admin/bigtable_table_admin_client.h
  google/cloud/bigtable/admin/bigtable_table_admin_connection.cc
  google/cloud/bigtable/admin/bigtable_table_admin_connection.h
  google/cloud/bigtable/admin/bigtable_table_admin_connection_idempotency_policy.cc
  google/cloud/bigtable/admin/bigtable_table_admin_connection_idempotency_policy.h
  google/cloud/bigtable/admin/bigtable_table_admin_options.h
  google/cloud/bigtable/admin/internal/bigtable_instance_admin_auth_decorator.cc
  google/cloud/bigtable/admin/internal/bigtable_instance_admin_auth_decorator.h
  google/cloud/bigtable/admin/internal/bigtable_instance_admin_logging_decorator.cc
  google/cloud/bigtable/admin/internal/bigtable_instance_admin_logging_decorator.h
  google/cloud/bigtable/admin/internal/bigtable_instance_admin_metadata_decorator.cc
  google/cloud/bigtable/admin/internal/bigtable_instance_admin_metadata_decorator.h
  google/cloud/bigtable/admin/internal/bigtable_instance_admin_option_defaults.cc
  google/cloud/bigtable/admin/internal/bigtable_instance_admin_option_defaults.h
  google/cloud/bigtable/admin/internal/bigtable_instance_admin_stub.cc
  google/cloud/bigtable/admin/internal/bigtable_instance_admin_stub.h
  google/cloud/bigtable/admin/internal/bigtable_instance_admin_stub_factory.cc
  google/cloud/bigtable/admin/internal/bigtable_instance_admin_stub_factory.h
  google/cloud/bigtable/admin/internal/bigtable_table_admin_auth_decorator.cc
  google/cloud/bigtable/admin/internal/bigtable_table_admin_auth_decorator.h
  google/cloud/bigtable/admin/internal/bigtable_table_admin_logging_decorator.cc
  google/cloud/bigtable/admin/internal/bigtable_table_admin_logging_decorator.h
  google/cloud/bigtable/admin/internal/bigtable_table_admin_metadata_decorator.cc
  google/cloud/bigtable/admin/internal/bigtable_table_admin_metadata_decorator.h
  google/cloud/bigtable/admin/internal/bigtable_table_admin_option_defaults.cc
  google/cloud/bigtable/admin/internal/bigtable_table_admin_option_defaults.h
  google/cloud/bigtable/admin/internal/bigtable_table_admin_stub.cc
  google/cloud/bigtable/admin/internal/bigtable_table_admin_stub.h
  google/cloud/bigtable/admin/internal/bigtable_table_admin_stub_factory.cc
  google/cloud/bigtable/admin/internal/bigtable_table_admin_stub_factory.h
  google/cloud/bigtable/admin/mocks/mock_bigtable_instance_admin_connection.h
  google/cloud/bigtable/admin/mocks/mock_bigtable_table_admin_connection.h
  google/cloud/bigtable/admin/retry_traits.h
Labels: cla: yes, api: bigtable

#7553 test(storage): restore GCS+gRPC integration tests
  ci/cloudbuild/builds/gcs-grpc.sh
Labels: cla: yes, api: storage

#7554 ci: build generated bigtable admin APIs
  .codecov.yml
  ci/cloudbuild/builds/cmake-install.sh
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/google_cloud_cpp_bigtable.bzl
Labels: cla: yes

#7557 ci: vcpkg now requires $VCPKG_ROOT
  .github/workflows/codeql-analysis.yml
  README.md
  ci/cloudbuild/builds/lib/vcpkg.sh
  ci/generate-markdown/generate-readme.sh
  ci/kokoro/macos/builds/cmake-vcpkg.sh
  ci/kokoro/macos/builds/quickstart-cmake.sh
  doc/contributor/howto-guide-setup-cmake-environment.md
  doc/contributor/howto-guide-setup-development-workstation.md
Labels: cla: yes

#7558 test(GCS+gRPC): missed restoring some integration tests
  google/cloud/storage/tests/grpc_integration_test.cc
Labels: cla: yes

#7560 cleanup: codeql yaml
  .github/workflows/codeql-analysis.yml
Labels: cla: yes

#7559 fix(GCS+gRPC): correct format Object ids
  google/cloud/storage/internal/grpc_client.cc
  google/cloud/storage/internal/grpc_client_test.cc
  google/cloud/storage/tests/object_basic_crud_integration_test.cc
Labels: cla: yes

#7564 test(storage): reduce iterations in integration test
  google/cloud/storage/tests/thread_integration_test.cc
Labels: cla: yes, api: storage

#7563 feat(GCS+gRPC): synthetic object metadata links
  google/cloud/storage/internal/grpc_client.cc
  google/cloud/storage/internal/grpc_client.h
  google/cloud/storage/internal/grpc_client_test.cc
  google/cloud/storage/internal/grpc_resumable_upload_session.cc
  google/cloud/storage/object_metadata.cc
  google/cloud/storage/tests/object_basic_crud_integration_test.cc
Labels: cla: yes

#7566 test(bigtable): create table once
  google/cloud/bigtable/tests/admin_backup_integration_test.cc
  google/cloud/bigtable/tests/admin_iam_policy_integration_test.cc
Labels: cla: yes, api: bigtable

#7568 cleanup(bigtable): slightly better logging tests
  google/cloud/bigtable/tests/admin_integration_test.cc
  google/cloud/bigtable/tests/data_integration_test.cc
  google/cloud/bigtable/tests/instance_admin_integration_test.cc
Labels: cla: yes, api: bigtable

#7569 cleanup(bigtable): cleanup admin integration tests
  google/cloud/bigtable/tests/admin_backup_integration_test.cc
  google/cloud/bigtable/tests/admin_iam_policy_integration_test.cc
  google/cloud/bigtable/tests/admin_integration_test.cc
  google/cloud/bigtable/tests/instance_admin_integration_test.cc
Labels: cla: yes, api: bigtable

#7570 test(bigtable): duplicate admin integration tests
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/admin/integration_tests/BUILD
  google/cloud/bigtable/admin/integration_tests/CMakeLists.txt
  google/cloud/bigtable/admin/integration_tests/admin_backup_integration_test.cc
  google/cloud/bigtable/admin/integration_tests/admin_iam_policy_integration_test.cc
  google/cloud/bigtable/admin/integration_tests/bigtable_admin_integration_tests.bzl
  google/cloud/bigtable/admin/integration_tests/instance_admin_integration_test.cc
  google/cloud/bigtable/admin/integration_tests/table_admin_integration_test.cc
  google/cloud/bigtable/ci/run_integration_tests_emulator_bazel.sh
Labels: cla: yes, api: bigtable

#7571 test(bigtable): convert admin integration tests to use generated code
  google/cloud/bigtable/admin/integration_tests/admin_backup_integration_test.cc
  google/cloud/bigtable/admin/integration_tests/admin_iam_policy_integration_test.cc
  google/cloud/bigtable/admin/integration_tests/instance_admin_integration_test.cc
  google/cloud/bigtable/admin/integration_tests/table_admin_integration_test.cc
Labels: cla: yes, api: bigtable

#7572 feat(GCS+gRPC): endpoint overrides with secure credentials
  google/cloud/storage/internal/grpc_client.cc
Labels: cla: yes

#7573 chore: pin copyright year in generated code
  google/cloud/CMakeLists.txt
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/admin/integration_tests/CMakeLists.txt
  google/cloud/bigtable/benchmarks/CMakeLists.txt
  google/cloud/bigtable/examples/CMakeLists.txt
  google/cloud/bigtable/tests/CMakeLists.txt
  google/cloud/pubsub/samples/CMakeLists.txt
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/benchmarks/CMakeLists.txt
  google/cloud/storage/examples/CMakeLists.txt
  google/cloud/storage/tests/CMakeLists.txt
  google/cloud/testing_util/CMakeLists.txt
Labels: cla: yes

#7574 cleanup(bigtable): implement `TableIntegrationTest` using preferred API
  google/cloud/bigtable/admin/integration_tests/admin_backup_integration_test.cc
  google/cloud/bigtable/admin/integration_tests/admin_iam_policy_integration_test.cc
  google/cloud/bigtable/admin/integration_tests/table_admin_integration_test.cc
  google/cloud/bigtable/testing/table_integration_test.cc
  google/cloud/bigtable/testing/table_integration_test.h
Labels: cla: yes, api: bigtable

#7576 test(storage): speed up thread_integration_test
  google/cloud/storage/tests/thread_integration_test.cc
Labels: cla: yes, api: storage

#7577 chore(deps): update Abseil to latest release
  bazel/google_cloud_cpp_deps.bzl
  ci/abi-dumps/google_cloud_cpp_bigquery.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_bigtable.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_common.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_grpc_utils.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_iam.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_pubsub.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_spanner.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_storage.expected.abi.dump.gz
  ci/cloudbuild/dockerfiles/debian-stretch.Dockerfile
  ci/cloudbuild/dockerfiles/demo-centos-7.Dockerfile
  ci/cloudbuild/dockerfiles/demo-debian-bullseye.Dockerfile
  ci/cloudbuild/dockerfiles/demo-debian-buster.Dockerfile
  ci/cloudbuild/dockerfiles/demo-debian-stretch.Dockerfile
  ci/cloudbuild/dockerfiles/demo-fedora.Dockerfile
  ci/cloudbuild/dockerfiles/demo-opensuse-leap.Dockerfile
  ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile
  ci/cloudbuild/dockerfiles/demo-ubuntu-bionic.Dockerfile
  ci/cloudbuild/dockerfiles/demo-ubuntu-focal.Dockerfile
  ci/cloudbuild/dockerfiles/fedora-34-cxx11.Dockerfile
  ci/cloudbuild/dockerfiles/fedora-34-cxx20.Dockerfile
  ci/cloudbuild/dockerfiles/fedora-34.Dockerfile
  ci/cloudbuild/dockerfiles/ubuntu-bionic-install.Dockerfile
  doc/packaging.md
Labels: cla: yes

#7578 cleanup(bigtable): remove dead code
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/bigtable_client_unit_tests.bzl
  google/cloud/bigtable/google_cloud_cpp_bigtable.bzl
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/internal/async_retry_multi_page.h
  google/cloud/bigtable/internal/async_retry_multi_page_test.cc
  google/cloud/bigtable/table_admin.cc
Labels: cla: yes, api: bigtable

#7580 chore: add more aggressive idempotency policy to reduce IAM test flakes
  google/cloud/iam/integration_tests/iam_integration_test.cc
Labels: cla: yes

#7581 test(GCS+gRPC): disable production integration tests
  ci/cloudbuild/builds/gcs-grpc.sh
  google/cloud/storage/tests/grpc_integration_test.cc
Labels: cla: yes

#7583 feature(generator): add support for "omitted_services"
  generator/generator.cc
  generator/generator_config.proto
  generator/generator_config.textproto
  generator/internal/codegen_utils.cc
  generator/internal/codegen_utils_test.cc
  generator/standalone_main.cc
Labels: cla: yes

#7582 chore: increase retry time for GetSeviceAccountKey in sample
  google/cloud/iam/samples/iam_samples.cc
Labels: cla: yes, samples

#7585 ci: ignore generated code in coverage build
  .codecov.yml
Labels: cla: yes

#7588 fix(spanner): avoid use-after-move bugs
  google/cloud/spanner/row.cc
  google/cloud/spanner/row.h
  google/cloud/spanner/row_test.cc
Labels: cla: yes, api: spanner

#7589 fix(spanner): GetSingularRow accepts by value
  google/cloud/spanner/row.h
Labels: cla: yes, api: spanner

#7586 feat(generator): support service-qualified names in RPC lists
  generator/integration_tests/generator_integration_test.cc
  generator/internal/service_code_generator.cc
Labels: cla: yes

#7587 feat: scaffold for the Pub/Sub Lite library
  CMakeLists.txt
  ci/cloudbuild/builds/cmake-install.sh
  cmake/CompileProtos.cmake
  doc/adding_new_libraries.md
  external/googleapis/CMakeLists.txt
  external/googleapis/protodeps/pubsublite.deps
  external/googleapis/protolists/pubsublite.list
  generator/scaffold/CMakeLists.txt.in
  generator/scaffold/README.md.in
  generator/scaffold/config.cmake.in
  generator/scaffold/config.pc.in
  generator/scaffold/create_scaffold.cmake
  generator/scaffold/placeholder.cc.in
  google/cloud/pubsublite/CMakeLists.txt
  google/cloud/pubsublite/README.md
  google/cloud/pubsublite/config.cmake.in
  google/cloud/pubsublite/config.pc.in
  google/cloud/pubsublite/google_cloud_cpp_pubsublite.bzl
  google/cloud/pubsublite/google_cloud_cpp_pubsublite_mocks.bzl
  google/cloud/pubsublite/internal/placeholder.cc
Labels: cla: yes

#7590 cleanup(generator): rename tests
  generator/integration_tests/golden/tests/golden_thing_admin_connection_test.cc
Labels: cla: yes

#7591 cleanup(generator): log unexpected options
  generator/integration_tests/golden/golden_kitchen_sink_connection.cc
  generator/integration_tests/golden/golden_thing_admin_connection.cc
  generator/integration_tests/golden/tests/golden_kitchen_sink_connection_test.cc
  generator/integration_tests/golden/tests/golden_thing_admin_connection_test.cc
  generator/internal/connection_generator.cc
  google/cloud/bigquery/bigquery_read_connection.cc
  google/cloud/bigtable/admin/bigtable_instance_admin_connection.cc
  google/cloud/bigtable/admin/bigtable_table_admin_connection.cc
  google/cloud/iam/iam_connection.cc
  google/cloud/iam/iam_credentials_connection.cc
  google/cloud/logging/logging_service_v2_connection.cc
  google/cloud/spanner/admin/database_admin_connection.cc
  google/cloud/spanner/admin/instance_admin_connection.cc
Labels: cla: yes

#7599 feat: automatically update feature list
  ci/cloudbuild/builds/cmake-install.sh
  ci/etc/full_feature_list
  generator/standalone_main.cc
Labels: cla: yes

#7598 chore(deps): update googleapis circa 2021-11-12
  bazel/google_cloud_cpp_deps.bzl
  external/googleapis/CMakeLists.txt
  google/cloud/bigquery/bigquery_read_client.h
  google/cloud/bigtable/admin/bigtable_instance_admin_client.h
  google/cloud/bigtable/admin/bigtable_table_admin_client.h
  google/cloud/iam/iam_client.h
  google/cloud/iam/iam_credentials_client.h
  google/cloud/logging/logging_service_v2_client.h
  google/cloud/spanner/admin/database_admin_client.h
  google/cloud/spanner/admin/instance_admin_client.h
Labels: cla: yes

#7596 cleanup: explicitly list Doxygen sources
  cmake/GoogleCloudCppCommon.cmake
  generator/scaffold/CMakeLists.txt.in
  google/cloud/CMakeLists.txt
  google/cloud/bigquery/CMakeLists.txt
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/iam/CMakeLists.txt
  google/cloud/logging/CMakeLists.txt
  google/cloud/pubsub/CMakeLists.txt
  google/cloud/pubsublite/CMakeLists.txt
  google/cloud/spanner/CMakeLists.txt
  google/cloud/storage/CMakeLists.txt
Labels: cla: yes

#7601 chore(pubsublite): commit generated files
  google/cloud/pubsublite/admin_client.cc
  google/cloud/pubsublite/admin_client.h
  google/cloud/pubsublite/admin_connection.cc
  google/cloud/pubsublite/admin_connection.h
  google/cloud/pubsublite/admin_connection_idempotency_policy.cc
  google/cloud/pubsublite/admin_connection_idempotency_policy.h
  google/cloud/pubsublite/admin_options.h
  google/cloud/pubsublite/internal/admin_auth_decorator.cc
  google/cloud/pubsublite/internal/admin_auth_decorator.h
  google/cloud/pubsublite/internal/admin_logging_decorator.cc
  google/cloud/pubsublite/internal/admin_logging_decorator.h
  google/cloud/pubsublite/internal/admin_metadata_decorator.cc
  google/cloud/pubsublite/internal/admin_metadata_decorator.h
  google/cloud/pubsublite/internal/admin_option_defaults.cc
  google/cloud/pubsublite/internal/admin_option_defaults.h
  google/cloud/pubsublite/internal/admin_stub.cc
  google/cloud/pubsublite/internal/admin_stub.h
  google/cloud/pubsublite/internal/admin_stub_factory.cc
  google/cloud/pubsublite/internal/admin_stub_factory.h
  google/cloud/pubsublite/mocks/mock_admin_connection.h
Labels: cla: yes, api: pubsublite

#7604 feat(generator): create scaffold if requested
  doc/adding_new_libraries.md
  generator/BUILD
  generator/CMakeLists.txt
  generator/google_cloud_cpp_generator.bzl
  generator/google_cloud_cpp_generator_unit_tests.bzl
  generator/internal/scaffold_generator.cc
  generator/internal/scaffold_generator.h
  generator/internal/scaffold_generator_test.cc
  generator/scaffold/CMakeLists.txt.in
  generator/scaffold/README.md.in
  generator/scaffold/config.cmake.in
  generator/scaffold/config.pc.in
  generator/scaffold/create_scaffold.cmake
  generator/scaffold/placeholder.cc.in
  generator/standalone_main.cc
Labels: cla: yes, cpp: generator

#7603 feat(common): add internal-only payload support to Status
  google/cloud/status.cc
  google/cloud/status.h
  google/cloud/status_test.cc
Labels: cla: yes

#7606 feat(generator): more stable googleapis proto links
  ci/cloudbuild/builds/generate-libraries.sh
  cmake/GoogleapisConfig.cmake
  external/googleapis/CMakeLists.txt
  generator/generator_test.cc
  generator/integration_tests/generator_integration_test.cc
  generator/integration_tests/golden/golden_kitchen_sink_client.h
  generator/integration_tests/golden/golden_thing_admin_client.h
  generator/integration_tests/golden/internal/golden_thing_admin_auth_decorator.cc
  generator/integration_tests/golden/internal/golden_thing_admin_auth_decorator.h
  generator/internal/codegen_utils.cc
  generator/internal/codegen_utils_test.cc
  generator/internal/descriptor_utils.cc
  generator/internal/descriptor_utils_test.cc
  generator/internal/scaffold_generator.cc
  generator/standalone_main.cc
  google/cloud/bigquery/CMakeLists.txt
  google/cloud/bigquery/bigquery_read_client.h
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/admin/bigtable_instance_admin_client.h
  google/cloud/bigtable/admin/bigtable_table_admin_client.h
  google/cloud/iam/CMakeLists.txt
  google/cloud/iam/iam_client.h
  google/cloud/iam/iam_credentials_client.h
  google/cloud/logging/CMakeLists.txt
  google/cloud/logging/logging_service_v2_client.h
  google/cloud/pubsub/CMakeLists.txt
  google/cloud/pubsublite/CMakeLists.txt
  google/cloud/pubsublite/admin_client.h
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/admin/database_admin_client.h
  google/cloud/spanner/admin/instance_admin_client.h
  google/cloud/storage/CMakeLists.txt
Labels: cla: yes

#7608 fix(generator): add missing dependency for library
  generator/BUILD
  generator/CMakeLists.txt
  generator/internal/auth_decorator_generator.cc
  generator/internal/connection_generator.cc
  generator/internal/descriptor_utils.cc
  generator/internal/descriptor_utils_test.cc
  generator/internal/idempotency_policy_generator.cc
  generator/internal/logging_decorator_generator.cc
  generator/internal/metadata_decorator_generator.cc
  generator/internal/mock_connection_generator.cc
  generator/internal/option_defaults_generator.cc
  generator/internal/options_generator.cc
  generator/internal/predicate_utils.cc
  generator/internal/stub_factory_generator.cc
  generator/internal/stub_generator.cc
Labels: cla: yes

#7602 feat: enable the Pub/Sub Lite library
  BUILD
  ci/cloudbuild/builds/cmake-install.sh
  ci/etc/expected_install_directories
  ci/etc/full_feature_list
  doc/adding_new_libraries.md
  generator/generator_config.textproto
  google/cloud/pubsublite/BUILD
  google/cloud/pubsublite/CMakeLists.txt
  google/cloud/pubsublite/README.md
  google/cloud/pubsublite/config.cmake.in
  google/cloud/pubsublite/google_cloud_cpp_pubsublite.bzl
  google/cloud/pubsublite/google_cloud_cpp_pubsublite_mocks.bzl
  google/cloud/pubsublite/retry_traits.h
Labels: cla: yes

#7609 fix(pubsublite): regenerate the code with new links
  google/cloud/pubsublite/admin_client.h
Labels: cla: yes, api: pubsublite

#7611 fix(generator): more precise matching of directories
  generator/internal/scaffold_generator.cc
Labels: cla: yes

#7607 ci: automatically publish docs for new libraries
  ci/cloudbuild/builds/cmake-install.sh
  ci/cloudbuild/builds/lib/features.sh
  ci/cloudbuild/builds/publish-docs.sh
  cmake/GoogleCloudCppCommon.cmake
Labels: cla: yes

#7614 chore(deps): update googleapis circa 2021-11-16
  bazel/google_cloud_cpp_deps.bzl
  cmake/GoogleapisConfig.cmake
  google/cloud/bigtable/admin/bigtable_instance_admin_client.cc
  google/cloud/bigtable/admin/bigtable_instance_admin_client.h
  google/cloud/bigtable/admin/bigtable_instance_admin_connection.cc
  google/cloud/bigtable/admin/bigtable_instance_admin_connection.h
  google/cloud/bigtable/admin/bigtable_instance_admin_connection_idempotency_policy.cc
  google/cloud/bigtable/admin/bigtable_instance_admin_connection_idempotency_policy.h
  google/cloud/bigtable/admin/internal/bigtable_instance_admin_auth_decorator.cc
  google/cloud/bigtable/admin/internal/bigtable_instance_admin_auth_decorator.h
  google/cloud/bigtable/admin/internal/bigtable_instance_admin_logging_decorator.cc
  google/cloud/bigtable/admin/internal/bigtable_instance_admin_logging_decorator.h
  google/cloud/bigtable/admin/internal/bigtable_instance_admin_metadata_decorator.cc
  google/cloud/bigtable/admin/internal/bigtable_instance_admin_metadata_decorator.h
  google/cloud/bigtable/admin/internal/bigtable_instance_admin_stub.cc
  google/cloud/bigtable/admin/internal/bigtable_instance_admin_stub.h
  google/cloud/bigtable/admin/mocks/mock_bigtable_instance_admin_connection.h
Labels: cla: yes

#7612 doc: improve instructions for new libraries
  doc/adding_new_libraries.md
Labels: cla: yes

#7615 feat(common): add tracing for the LRO polling loop
  google/cloud/internal/async_polling_loop.cc
  google/cloud/spanner/samples/samples.cc
Labels: cla: yes

#7621 doc: update https://github.com/google/googletest links
  google/cloud/bigquery/doc/bigquery-read-mock.dox
  google/cloud/iam/doc/iam-credentials-mock.dox
  google/cloud/iam/doc/iam-mock.dox
  google/cloud/log_test.cc
  google/cloud/pubsub/doc/publisher-mock.dox
  google/cloud/pubsub/doc/subscriber-mock.dox
Labels: cla: yes

#7617 feat(tasks): generate Cloud Tasks library
  BUILD
  ci/etc/expected_install_directories
  ci/etc/full_feature_list
  external/googleapis/protodeps/tasks.deps
  external/googleapis/protolists/tasks.list
  generator/generator_config.textproto
  google/cloud/tasks/BUILD
  google/cloud/tasks/CMakeLists.txt
  google/cloud/tasks/README.md
  google/cloud/tasks/cloud_tasks_client.cc
  google/cloud/tasks/cloud_tasks_client.h
  google/cloud/tasks/cloud_tasks_connection.cc
  google/cloud/tasks/cloud_tasks_connection.h
  google/cloud/tasks/cloud_tasks_connection_idempotency_policy.cc
  google/cloud/tasks/cloud_tasks_connection_idempotency_policy.h
  google/cloud/tasks/cloud_tasks_options.h
  google/cloud/tasks/config.cmake.in
  google/cloud/tasks/config.pc.in
  google/cloud/tasks/google_cloud_cpp_tasks.bzl
  google/cloud/tasks/google_cloud_cpp_tasks_mocks.bzl
  google/cloud/tasks/internal/cloud_tasks_auth_decorator.cc
  google/cloud/tasks/internal/cloud_tasks_auth_decorator.h
  google/cloud/tasks/internal/cloud_tasks_logging_decorator.cc
  google/cloud/tasks/internal/cloud_tasks_logging_decorator.h
  google/cloud/tasks/internal/cloud_tasks_metadata_decorator.cc
  google/cloud/tasks/internal/cloud_tasks_metadata_decorator.h
  google/cloud/tasks/internal/cloud_tasks_option_defaults.cc
  google/cloud/tasks/internal/cloud_tasks_option_defaults.h
  google/cloud/tasks/internal/cloud_tasks_stub.cc
  google/cloud/tasks/internal/cloud_tasks_stub.h
  google/cloud/tasks/internal/cloud_tasks_stub_factory.cc
  google/cloud/tasks/internal/cloud_tasks_stub_factory.h
  google/cloud/tasks/mocks/mock_cloud_tasks_connection.h
  google/cloud/tasks/retry_traits.h
Labels: cla: yes, api: cloudtasks

#7622 refactor(common): Status ignores message if code==OK
  google/cloud/status.h
  google/cloud/status_test.cc
Labels: cla: yes

#7620 refactor(common): attach Status proto as g::c::Status payload when available
  google/cloud/CMakeLists.txt
  google/cloud/google_cloud_cpp_common.bzl
  google/cloud/google_cloud_cpp_common_unit_tests.bzl
  google/cloud/grpc_error_delegate.cc
  google/cloud/grpc_error_delegate.h
  google/cloud/grpc_error_delegate_test.cc
  google/cloud/internal/status_payload_keys.cc
  google/cloud/internal/status_payload_keys.h
  google/cloud/internal/status_payload_keys_test.cc
Labels: cla: yes

#7623 cleanup(generator): retry traits header is internal
  cmake/GoogleCloudCppCommon.cmake
  generator/integration_tests/golden/BUILD
  generator/integration_tests/golden/CMakeLists.txt
  generator/integration_tests/golden/golden_kitchen_sink_connection.h
  generator/integration_tests/golden/golden_thing_admin_connection.h
  generator/integration_tests/golden/google_cloud_cpp_generator_golden_files.bzl
  generator/integration_tests/golden/internal/retry_traits.h
  generator/internal/descriptor_utils.cc
  generator/internal/descriptor_utils_test.cc
  google/cloud/bigquery/CMakeLists.txt
  google/cloud/bigquery/bigquery_read_connection.h
  google/cloud/bigquery/google_cloud_cpp_bigquery.bzl
  google/cloud/bigquery/internal/retry_traits.h
  google/cloud/bigquery/retry_traits.h
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/admin/bigtable_instance_admin_connection.h
  google/cloud/bigtable/admin/bigtable_table_admin_connection.h
  google/cloud/bigtable/admin/internal/retry_traits.h
  google/cloud/bigtable/google_cloud_cpp_bigtable.bzl
  google/cloud/iam/CMakeLists.txt
  google/cloud/iam/google_cloud_cpp_iam.bzl
  google/cloud/iam/iam_connection.h
  google/cloud/iam/iam_credentials_connection.h
  google/cloud/iam/internal/retry_traits.h
  google/cloud/iam/retry_traits.h
  google/cloud/logging/CMakeLists.txt
  google/cloud/logging/google_cloud_cpp_logging.bzl
  google/cloud/logging/internal/retry_traits.h
  google/cloud/logging/logging_service_v2_connection.h
  google/cloud/pubsublite/CMakeLists.txt
  google/cloud/pubsublite/admin_connection.h
  google/cloud/pubsublite/google_cloud_cpp_pubsublite.bzl
  google/cloud/pubsublite/internal/retry_traits.h
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/admin/database_admin_connection.h
  google/cloud/spanner/admin/instance_admin_connection.h
  google/cloud/spanner/admin/internal/retry_traits.h
  google/cloud/spanner/admin/retry_traits.h
  google/cloud/spanner/google_cloud_cpp_spanner.bzl
  google/cloud/tasks/CMakeLists.txt
  google/cloud/tasks/cloud_tasks_connection.h
  google/cloud/tasks/google_cloud_cpp_tasks.bzl
  google/cloud/tasks/internal/retry_traits.h
Labels: cla: yes

#7625 ci: do not fall through from cloud mode to docker mode
  ci/cloudbuild/build.sh
Labels: cla: yes

#7626 test(spanner): expand use of test instance labelling
  google/cloud/spanner/admin/integration_tests/backup_extra_integration_test.cc
  google/cloud/spanner/admin/integration_tests/backup_integration_test.cc
  google/cloud/spanner/integration_tests/backup_extra_integration_test.cc
  google/cloud/spanner/integration_tests/backup_integration_test.cc
  google/cloud/spanner/samples/samples.cc
Labels: cla: yes, api: spanner

#7627 ci: hint for using the Spanner staging service for integration tests
  ci/etc/integration-tests-config.ps1
  ci/etc/integration-tests-config.sh
Labels: cla: yes

#7629 cleanup(common): delete unused synchronous PollingLoop
  google/cloud/CMakeLists.txt
  google/cloud/google_cloud_cpp_grpc_utils.bzl
  google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl
  google/cloud/internal/polling_loop.h
  google/cloud/internal/polling_loop_test.cc
Labels: cla: yes

#7630 doc: another pass on the instructions for new libs
  doc/adding_new_libraries.md
Labels: cla: yes

#7631 cleanup(generator): remove unused generator
  generator/CMakeLists.txt
  generator/google_cloud_cpp_generator.bzl
  generator/internal/retry_policy_generator.cc
  generator/internal/retry_policy_generator.h
Labels: cla: yes

#7628 refactor: g::c::Status now logs code first then message
  google/cloud/internal/throw_delegate_test.cc
  google/cloud/status.h
  google/cloud/status_or_test.cc
  google/cloud/status_test.cc
  google/cloud/storage/benchmarks/throughput_result_test.cc
  google/cloud/storage/internal/logging_resumable_upload_session_test.cc
  google/cloud/testing_util/status_matchers_test.cc
Labels: cla: yes

#7633 feat(storage): default payload format for CreateNotification
  google/cloud/storage/client.h
  google/cloud/storage/client_notifications_test.cc
  google/cloud/storage/examples/storage_notification_samples.cc
Labels: cla: yes, api: storage

#7634 feat(storage): `storage::Client` is a value type
  google/cloud/storage/client.h
  google/cloud/storage/client_test.cc
Labels: cla: yes, api: storage

#7635 fix: avoid use-after-move StatusOr
  google/cloud/stream_range.h
Labels: cla: yes

#7636 feat(bigtable): add multi-cluster routing for specific clusters
  google/cloud/bigtable/app_profile_config.cc
  google/cloud/bigtable/app_profile_config.h
  google/cloud/bigtable/app_profile_config_test.cc
Labels: cla: yes, api: bigtable

#7632 feat(generator): generate retry traits from config
  doc/adding_new_libraries.md
  generator/CMakeLists.txt
  generator/generator_config.proto
  generator/generator_config.textproto
  generator/google_cloud_cpp_generator.bzl
  generator/integration_tests/generator_integration_test.cc
  generator/integration_tests/golden/CMakeLists.txt
  generator/integration_tests/golden/golden_kitchen_sink_connection.h
  generator/integration_tests/golden/golden_thing_admin_connection.h
  generator/integration_tests/golden/google_cloud_cpp_generator_golden_files.bzl
  generator/integration_tests/golden/internal/golden_kitchen_sink_retry_traits.h
  generator/integration_tests/golden/internal/golden_thing_admin_retry_traits.h
  generator/integration_tests/golden/tests/golden_thing_admin_connection_test.cc
  generator/internal/codegen_utils.cc
  generator/internal/descriptor_utils.cc
  generator/internal/descriptor_utils_test.cc
  generator/internal/retry_traits_generator.cc
  generator/internal/retry_traits_generator.h
  generator/standalone_main.cc
  google/cloud/bigquery/CMakeLists.txt
  google/cloud/bigquery/bigquery_read_connection.h
  google/cloud/bigquery/google_cloud_cpp_bigquery.bzl
  google/cloud/bigquery/internal/bigquery_read_retry_traits.h
  google/cloud/bigquery/retry_traits.h
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/admin/bigtable_instance_admin_connection.h
  google/cloud/bigtable/admin/bigtable_table_admin_connection.h
  google/cloud/bigtable/admin/internal/bigtable_instance_admin_retry_traits.h
  google/cloud/bigtable/admin/internal/bigtable_table_admin_retry_traits.h
  google/cloud/bigtable/google_cloud_cpp_bigtable.bzl
  google/cloud/iam/CMakeLists.txt
  google/cloud/iam/google_cloud_cpp_iam.bzl
  google/cloud/iam/iam_connection.h
  google/cloud/iam/iam_credentials_connection.h
  google/cloud/iam/internal/iam_credentials_retry_traits.h
  google/cloud/iam/internal/iam_retry_traits.h
  google/cloud/iam/retry_traits.h
  google/cloud/logging/CMakeLists.txt
  google/cloud/logging/google_cloud_cpp_logging.bzl
  google/cloud/logging/internal/logging_service_v2_retry_traits.h
  google/cloud/logging/logging_service_v2_connection.h
  google/cloud/pubsublite/CMakeLists.txt
  google/cloud/pubsublite/admin_connection.h
  google/cloud/pubsublite/google_cloud_cpp_pubsublite.bzl
  google/cloud/pubsublite/internal/admin_retry_traits.h
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/admin/database_admin_connection.h
  google/cloud/spanner/admin/instance_admin_connection.h
  google/cloud/spanner/admin/internal/database_admin_retry_traits.h
  google/cloud/spanner/admin/internal/instance_admin_retry_traits.h
  google/cloud/spanner/admin/retry_traits.h
  google/cloud/spanner/google_cloud_cpp_spanner.bzl
  google/cloud/tasks/CMakeLists.txt
  google/cloud/tasks/cloud_tasks_connection.h
  google/cloud/tasks/google_cloud_cpp_tasks.bzl
  google/cloud/tasks/internal/cloud_tasks_retry_traits.h
Labels: cla: yes

#7639 refactor: optimize Status moving error data to heap-allocated Impl
  google/cloud/status.cc
  google/cloud/status.h
  google/cloud/status_or.h
  google/cloud/status_or_test.cc
  google/cloud/status_test.cc
Labels: cla: yes

#7637 doc(storage): describe connection pool
  google/cloud/storage/client.h
Labels: cla: yes, api: storage

#7638 feat(generator): improve initial README files
  generator/internal/scaffold_generator.cc
  generator/internal/scaffold_generator_test.cc
  google/cloud/pubsublite/README.md
  google/cloud/tasks/README.md
Labels: cla: yes

#7641 feat(generator): reduce required editing on scaffold
  doc/adding_new_libraries.md
  generator/internal/scaffold_generator.cc
  generator/internal/scaffold_generator_test.cc
  google/cloud/pubsublite/CMakeLists.txt
  google/cloud/tasks/CMakeLists.txt
Labels: cla: yes

#7643 fix: update texttospeech proto library deps
  external/googleapis/CMakeLists.txt
  external/googleapis/protodeps/texttospeech.deps
  external/googleapis/protolists/texttospeech.list
  external/googleapis/update_libraries.sh
Labels: cla: yes

#7640 feat: expose and log ErrorInfo if present
  google/cloud/BUILD
  google/cloud/CMakeLists.txt
  google/cloud/grpc_error_delegate.cc
  google/cloud/grpc_error_delegate_test.cc
  google/cloud/status.cc
  google/cloud/status.h
  google/cloud/status_test.cc
Labels: cla: yes

#7645 test(spanner): parenthesize the user-supplied instance filter
  google/cloud/spanner/testing/pick_random_instance.cc
Labels: cla: yes, api: spanner

#7646 test(spanner): use the last instance config as the PickConfig() default
  google/cloud/spanner/samples/samples.cc
Labels: cla: yes, api: spanner

#7647 ci: update quickstart build image
  ci/cloudbuild/dockerfiles/ubuntu-focal.Dockerfile
  ci/cloudbuild/triggers/quickstart-bazel-ci.yaml
  ci/cloudbuild/triggers/quickstart-bazel-pr.yaml
  ci/cloudbuild/triggers/quickstart-cmake-ci.yaml
  ci/cloudbuild/triggers/quickstart-cmake-pr.yaml
Labels: cla: yes

#7648 ci: parallelize CMake quickstart builds
  .cmake-format.py
  ci/cloudbuild/builds/cmake-install.sh
  ci/cloudbuild/builds/lib/quickstart.sh
  ci/cloudbuild/builds/quickstart-cmake.sh
  ci/verify_quickstart/CMakeLists.txt
Labels: cla: yes

#7651 ci: speedup Rocky Linux build
  ci/cloudbuild/dockerfiles/demo-rockylinux-8.Dockerfile
  doc/packaging.md
Labels: cla: yes

#7653 chore(deps): update googleapis/googleapis circa 2021-11-22
  bazel/google_cloud_cpp_deps.bzl
  cmake/GoogleapisConfig.cmake
Labels: cla: yes

#7654 feat: GCS parse "error info" from JSON when available
  google/cloud/storage/internal/http_response.cc
  google/cloud/storage/internal/http_response_test.cc
Labels: cla: yes

#7652 chore(generator): change doxygen commnent character sequence
  generator/integration_tests/golden/golden_kitchen_sink_client.h
  generator/integration_tests/golden/golden_thing_admin_client.h
  generator/internal/descriptor_utils.cc
  generator/internal/descriptor_utils_test.cc
  google/cloud/bigquery/bigquery_read_client.h
  google/cloud/bigtable/admin/bigtable_instance_admin_client.h
  google/cloud/bigtable/admin/bigtable_table_admin_client.h
  google/cloud/iam/iam_client.h
  google/cloud/iam/iam_credentials_client.h
  google/cloud/logging/logging_service_v2_client.h
  google/cloud/pubsublite/admin_client.h
  google/cloud/spanner/admin/database_admin_client.h
  google/cloud/spanner/admin/instance_admin_client.h
  google/cloud/tasks/cloud_tasks_client.h
Labels: cla: yes

#7655 feat(storage): separate option for download timeouts
  google/cloud/storage/client_options.cc
  google/cloud/storage/client_options.h
  google/cloud/storage/client_options_test.cc
  google/cloud/storage/internal/curl_download_request.cc
  google/cloud/storage/internal/curl_download_request.h
  google/cloud/storage/internal/curl_request_builder.cc
  google/cloud/storage/internal/curl_request_builder.h
  google/cloud/storage/internal/grpc_client.cc
  google/cloud/storage/options.h
Labels: cla: yes, api: storage

#7656 feat: add secret manager library
  BUILD
  ci/cloudbuild/builds/cmake-install.sh
  ci/etc/expected_install_directories
  ci/etc/full_feature_list
  doc/adding_new_libraries.md
  external/googleapis/protodeps/secretmanager.deps
  external/googleapis/protolists/secretmanager.list
  external/googleapis/update_libraries.sh
  generator/generator_config.textproto
  google/cloud/secretmanager/BUILD
  google/cloud/secretmanager/CMakeLists.txt
  google/cloud/secretmanager/README.md
  google/cloud/secretmanager/config.cmake.in
  google/cloud/secretmanager/config.pc.in
  google/cloud/secretmanager/google_cloud_cpp_secretmanager.bzl
  google/cloud/secretmanager/google_cloud_cpp_secretmanager_mocks.bzl
  google/cloud/secretmanager/internal/secret_manager_auth_decorator.cc
  google/cloud/secretmanager/internal/secret_manager_auth_decorator.h
  google/cloud/secretmanager/internal/secret_manager_logging_decorator.cc
  google/cloud/secretmanager/internal/secret_manager_logging_decorator.h
  google/cloud/secretmanager/internal/secret_manager_metadata_decorator.cc
  google/cloud/secretmanager/internal/secret_manager_metadata_decorator.h
  google/cloud/secretmanager/internal/secret_manager_option_defaults.cc
  google/cloud/secretmanager/internal/secret_manager_option_defaults.h
  google/cloud/secretmanager/internal/secret_manager_retry_traits.h
  google/cloud/secretmanager/internal/secret_manager_stub.cc
  google/cloud/secretmanager/internal/secret_manager_stub.h
  google/cloud/secretmanager/internal/secret_manager_stub_factory.cc
  google/cloud/secretmanager/internal/secret_manager_stub_factory.h
  google/cloud/secretmanager/mocks/mock_secret_manager_connection.h
  google/cloud/secretmanager/secret_manager_client.cc
  google/cloud/secretmanager/secret_manager_client.h
  google/cloud/secretmanager/secret_manager_connection.cc
  google/cloud/secretmanager/secret_manager_connection.h
  google/cloud/secretmanager/secret_manager_connection_idempotency_policy.cc
  google/cloud/secretmanager/secret_manager_connection_idempotency_policy.h
  google/cloud/secretmanager/secret_manager_options.h
Labels: cla: yes

#7657 ci: speed up publish-docs build
  cmake/GoogleCloudCppCommon.cmake
Labels: cla: yes

#7660 cleanup: missing libraries in update script
  external/googleapis/protodeps/pubsublite.deps
  external/googleapis/protodeps/tasks.deps
  external/googleapis/protolists/pubsublite.list
  external/googleapis/protolists/tasks.list
  external/googleapis/update_libraries.sh
Labels: cla: yes

#7663 ci: upload docs
  ci/cloudbuild/builds/publish-docs.sh
Labels: cla: yes

#7662 feat(storage): better debugging for session rewinds
  google/cloud/storage/client_write_object_test.cc
  google/cloud/storage/internal/resumable_upload_session.cc
  google/cloud/storage/internal/resumable_upload_session_test.cc
  google/cloud/storage/internal/retry_resumable_upload_session.cc
  google/cloud/storage/internal/retry_resumable_upload_session.h
  google/cloud/storage/internal/retry_resumable_upload_session_test.cc
Labels: cla: yes, api: storage

#7665 feat(generator): link each method input and output types
  cmake/GoogleapisConfig.cmake
  generator/integration_tests/golden/golden_kitchen_sink_client.h
  generator/integration_tests/golden/golden_thing_admin_client.h
  generator/internal/descriptor_utils.cc
  generator/internal/descriptor_utils_test.cc
  google/cloud/bigquery/bigquery_read_client.h
  google/cloud/bigtable/admin/bigtable_instance_admin_client.h
  google/cloud/bigtable/admin/bigtable_table_admin_client.h
  google/cloud/iam/iam_client.h
  google/cloud/iam/iam_credentials_client.h
  google/cloud/logging/logging_service_v2_client.h
  google/cloud/pubsublite/admin_client.h
  google/cloud/secretmanager/secret_manager_client.h
  google/cloud/spanner/admin/database_admin_client.h
  google/cloud/spanner/admin/instance_admin_client.h
  google/cloud/tasks/cloud_tasks_client.h
Labels: cla: yes

#7668 doc: update instructions for macOS
  doc/contributor/howto-guide-setup-development-workstation.md
Labels: cla: yes

#7673 feat(generator): document details about `*Client`
  generator/integration_tests/golden/golden_kitchen_sink_client.h
  generator/integration_tests/golden/golden_thing_admin_client.h
  generator/internal/descriptor_utils.cc
  generator/internal/descriptor_utils_test.cc
  google/cloud/bigquery/bigquery_read_client.h
  google/cloud/iam/iam_client.h
  google/cloud/iam/iam_credentials_client.h
  google/cloud/logging/logging_service_v2_client.h
  google/cloud/pubsublite/admin_client.h
  google/cloud/secretmanager/secret_manager_client.h
  google/cloud/spanner/admin/database_admin_client.h
  google/cloud/spanner/admin/instance_admin_client.h
  google/cloud/tasks/cloud_tasks_client.h
Labels: cla: yes
