Repository googleapis/google-cloud-cpp, pull requests merged in 2021-03, with the labels that each got.

#5932 doc(ADR): deprecated functions do not have examples
  doc/adr/2021-03-01-deprecated-functions-do-not-have-examples.md
Labels: cla: yes

#5942 refactor: renamed option to GrpcBackgroundThreadsFactoryOption
  google/cloud/connection_options.h
  google/cloud/internal/grpc_options.cc
  google/cloud/internal/grpc_options.h
  google/cloud/internal/grpc_options_test.cc
Labels: cla: yes

#5943 cleanup(spanner): new version time in spanner_create_backup sample
  google/cloud/spanner/samples/samples.cc
Labels: api: spanner, cla: yes, samples

#5945 doc: prepare CHANGELOG.md for v1.25.0 release
  CHANGELOG.md
Labels: cla: yes

#5946 cleanup(bigtable): remove examples for admin async operations
  google/cloud/bigtable/ci/run_integration_tests_emulator_bazel.sh
  google/cloud/bigtable/examples/CMakeLists.txt
  google/cloud/bigtable/examples/bigtable_examples.bzl
  google/cloud/bigtable/examples/bigtable_examples_common.cc
  google/cloud/bigtable/examples/bigtable_examples_common.h
  google/cloud/bigtable/examples/bigtable_examples_common_test.cc
  google/cloud/bigtable/examples/bigtable_table_admin_backup_async_snippets.cc
  google/cloud/bigtable/examples/instance_admin_async_snippets.cc
  google/cloud/bigtable/examples/table_admin_async_snippets.cc
  google/cloud/bigtable/examples/table_admin_iam_policy_snippets.cc
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/table_admin.h
Labels: api: bigtable, cla: yes

#5944 doc(pubsub): fix region tags for two examples
  google/cloud/pubsub/samples/samples.cc
Labels: api: pubsub, cla: yes

#5947 refactor: add Options::get<T>()
  google/cloud/internal/options.h
  google/cloud/internal/options_test.cc
Labels: cla: yes

#5948 chore: bump version numbers post v1.25.0 release
  CMakeLists.txt
  google/cloud/bigtable/quickstart/WORKSPACE
  google/cloud/internal/version_info.h
  google/cloud/pubsub/quickstart/WORKSPACE
  google/cloud/spanner/quickstart/WORKSPACE
  google/cloud/storage/quickstart/WORKSPACE
Labels: cla: yes

#5941 feat(storage): implement storage::GrpcClient::DeleteResumableUpload
  google/cloud/storage/internal/grpc_client.cc
  google/cloud/storage/internal/grpc_client.h
  google/cloud/storage/internal/grpc_client_failures_test.cc
  google/cloud/storage/tests/object_integration_test.cc
Labels: api: storage, cla: yes

#5949 refactor: reimplement ConnectionOptions in terms of Options more
  google/cloud/connection_options.h
  google/cloud/connection_options_test.cc
Labels: cla: yes

#5951 cleanup(spanner): prefer spanner::Timestamp streaming
  google/cloud/spanner/samples/samples.cc
Labels: api: spanner, cla: yes

#5953 refactor: rename user-agent option and change type
  google/cloud/connection_options.h
  google/cloud/connection_options_test.cc
  google/cloud/internal/common_options.h
  google/cloud/internal/common_options_test.cc
  google/cloud/internal/grpc_options.cc
Labels: cla: yes

#5955 refactor: remove Options::get_or
  google/cloud/internal/common_options_test.cc
  google/cloud/internal/grpc_options.cc
  google/cloud/internal/grpc_options_test.cc
  google/cloud/internal/options.h
  google/cloud/internal/options_test.cc
Labels: cla: yes

#5957 feat(storage): implement storage::GrpcClient::TestBucketIamPermissions
  google/cloud/storage/emulator/grpc_server.py
  google/cloud/storage/internal/grpc_client.cc
  google/cloud/storage/internal/grpc_client.h
  google/cloud/storage/internal/grpc_client_bucket_request_test.cc
  google/cloud/storage/internal/grpc_client_failures_test.cc
  google/cloud/storage/tests/grpc_integration_test.cc
Labels: api: storage, cla: yes

#5962 chore: standardize on MOCK_METHOD()
  google/cloud/bigtable/internal/async_retry_multi_page_test.cc
  google/cloud/bigtable/row_reader_test.cc
  google/cloud/bigtable/testing/mock_admin_client.h
  google/cloud/bigtable/testing/mock_data_client.h
  google/cloud/bigtable/testing/mock_instance_admin_client.h
  google/cloud/bigtable/testing/mock_response_reader.h
  google/cloud/completion_queue_test.cc
  google/cloud/internal/async_retry_loop_test.cc
  google/cloud/internal/async_retry_unary_rpc_test.cc
  google/cloud/internal/retry_loop_test.cc
  google/cloud/log_test.cc
  google/cloud/pubsub/mocks/mock_ack_handler.h
  google/cloud/pubsub/testing/mock_subscriber_stub.h
  google/cloud/pubsub/testing/mock_subscription_batch_source.h
  google/cloud/pubsub/testing/mock_subscription_message_source.h
  google/cloud/spanner/internal/connection_impl_test.cc
  google/cloud/spanner/internal/partial_result_set_resume_test.cc
  google/cloud/spanner/mocks/mock_database_admin_connection.h
  google/cloud/spanner/mocks/mock_instance_admin_connection.h
  google/cloud/spanner/mocks/mock_spanner_connection.h
  google/cloud/spanner/testing/mock_database_admin_stub.h
  google/cloud/spanner/testing/mock_instance_admin_stub.h
  google/cloud/spanner/testing/mock_partial_result_set_reader.h
  google/cloud/spanner/testing/mock_spanner_stub.h
  google/cloud/storage/client_write_object_test.cc
  google/cloud/storage/internal/curl_resumable_upload_session_test.cc
  google/cloud/storage/internal/grpc_object_read_source_test.cc
  google/cloud/storage/internal/grpc_resumable_upload_session_test.cc
  google/cloud/storage/internal/retry_object_read_source_test.cc
  google/cloud/storage/testing/mock_client.h
  google/cloud/storage/testing/mock_http_request.h
  google/cloud/testing_util/mock_async_response_reader.h
  google/cloud/testing_util/mock_completion_queue_impl.h
Labels: cla: yes

#5965 cleanup: prefer including .pb.h files over .grpc.pb.h
  google/cloud/bigtable/cluster_list_responses.h
  google/cloud/bigtable/iam_binding.h
  google/cloud/bigtable/instance_list_responses.h
  google/cloud/bigtable/mutation_batcher.h
  google/cloud/pubsub/internal/publisher_stub.cc
  google/cloud/pubsub/internal/publisher_stub.h
  google/cloud/pubsub/internal/subscriber_stub.cc
  google/cloud/pubsub/internal/subscriber_stub.h
  google/cloud/spanner/database_admin_connection.h
  google/cloud/spanner/instance_admin_connection.h
  google/cloud/spanner/internal/database_admin_stub.cc
  google/cloud/spanner/internal/database_admin_stub.h
  google/cloud/spanner/internal/instance_admin_stub.cc
  google/cloud/spanner/internal/instance_admin_stub.h
  google/cloud/spanner/internal/partial_result_set_reader.h
  google/cloud/spanner/internal/partial_result_set_source.h
Labels: cla: yes

#5968 chore: update googleapis version
  bazel/google_cloud_cpp_deps.bzl
  ci/etc/generator-googleapis-commit-hash.sh
  external/googleapis/CMakeLists.txt
  google/cloud/iam/iam_credentials_client.gcpcxx.pb.h
  google/cloud/iam/iam_credentials_connection.gcpcxx.pb.h
  google/cloud/logging/logging_service_v2_client.gcpcxx.pb.h
  google/cloud/logging/logging_service_v2_connection.gcpcxx.pb.h
  google/cloud/logging/mocks/mock_logging_service_v2_connection.gcpcxx.pb.h
Labels: cla: yes

#5969 feat(bigtable): enable keepalive pings by default
  google/cloud/bigtable/client_options.cc
  google/cloud/bigtable/client_options_test.cc
Labels: api: bigtable, cla: yes

#5972 fix(generator): remove hardcoded method and response type in streaming rpc stub
  generator/internal/stub_generator.cc
Labels: cla: yes

#5971 cleanup(storage): avoid using sscanf()
  google/cloud/storage/internal/object_requests.cc
Labels: api: storage, cla: yes

#5979 fix(storage): do not update upload session ids
  google/cloud/storage/internal/curl_resumable_upload_session.cc
  google/cloud/storage/internal/curl_resumable_upload_session_test.cc
  google/cloud/storage/object_stream.h
Labels: api: storage, cla: yes

#5980 fix(storage): correctly set customTime on inserts
  google/cloud/storage/internal/object_metadata_parser.cc
  google/cloud/storage/object_metadata_test.cc
  google/cloud/storage/tests/object_integration_test.cc
Labels: api: storage, cla: yes

#5981 test(spanner): exercise enumeration of optimizer versions
  google/cloud/spanner/integration_tests/client_integration_test.cc
Labels: api: spanner, cla: yes

#5983 doc(storage): describe how to use optional parameters
  google/cloud/storage/client.h
Labels: api: storage, cla: yes

#5982 refactor(generator): only require golden hash check on integration and CI builds
  ci/kokoro/docker/build.sh
Labels: cla: yes

#5987 cleanup: add/remove a few spanner headers
  google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
  google/cloud/spanner/connection.h
  google/cloud/spanner/database_admin_connection.cc
  google/cloud/spanner/database_admin_connection_test.cc
  google/cloud/spanner/instance_admin_connection.cc
  google/cloud/spanner/instance_admin_connection_test.cc
  google/cloud/spanner/internal/connection_impl.cc
  google/cloud/spanner/internal/connection_impl_test.cc
  google/cloud/spanner/internal/database_admin_logging.cc
  google/cloud/spanner/internal/database_admin_logging.h
  google/cloud/spanner/internal/database_admin_logging_test.cc
  google/cloud/spanner/internal/database_admin_metadata.cc
  google/cloud/spanner/internal/database_admin_metadata.h
  google/cloud/spanner/internal/database_admin_metadata_test.cc
  google/cloud/spanner/internal/database_admin_stub.cc
  google/cloud/spanner/internal/database_admin_stub.h
  google/cloud/spanner/internal/instance_admin_logging.cc
  google/cloud/spanner/internal/instance_admin_logging.h
  google/cloud/spanner/internal/instance_admin_logging_test.cc
  google/cloud/spanner/internal/instance_admin_metadata.cc
  google/cloud/spanner/internal/instance_admin_metadata.h
  google/cloud/spanner/internal/instance_admin_metadata_test.cc
  google/cloud/spanner/internal/instance_admin_stub.cc
  google/cloud/spanner/internal/instance_admin_stub.h
  google/cloud/spanner/internal/logging_spanner_stub.cc
  google/cloud/spanner/internal/logging_spanner_stub.h
  google/cloud/spanner/internal/logging_spanner_stub_test.cc
  google/cloud/spanner/internal/metadata_spanner_stub.cc
  google/cloud/spanner/internal/metadata_spanner_stub.h
  google/cloud/spanner/internal/metadata_spanner_stub_test.cc
  google/cloud/spanner/internal/partial_result_set_source_test.cc
  google/cloud/spanner/internal/session_pool.cc
  google/cloud/spanner/internal/session_pool_test.cc
  google/cloud/spanner/internal/spanner_stub.cc
  google/cloud/spanner/internal/spanner_stub_test.cc
  google/cloud/spanner/testing/mock_database_admin_stub.h
  google/cloud/spanner/testing/mock_instance_admin_stub.h
  google/cloud/spanner/testing/mock_spanner_stub.h
  google/cloud/spanner/testing/pick_instance_config.cc
Labels: cla: yes

#5985 refactor(spanner): add spanner_internal::DefaultOptions() in preparation for using `Options`
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/connection_options.cc
  google/cloud/spanner/google_cloud_cpp_spanner.bzl
  google/cloud/spanner/internal/options.cc
  google/cloud/spanner/internal/options.h
  google/cloud/spanner/internal/options_test.cc
  google/cloud/spanner/spanner_client_unit_tests.bzl
Labels: cla: yes

#5988 cleanup: avoid potentially disrespectful terms
  CHANGELOG.md
  google/cloud/bigtable/async_row_reader_test.cc
  google/cloud/bigtable/filters_test.cc
  google/cloud/bigtable/internal/async_longrunning_op_test.cc
  google/cloud/bigtable/row_reader_test.cc
  google/cloud/completion_queue_test.cc
  google/cloud/internal/async_connection_ready_test.cc
  google/cloud/spanner/client_test.cc
  google/cloud/spanner/integration_tests/client_stress_test.cc
  google/cloud/spanner/integration_tests/database_admin_integration_test.cc
  google/cloud/spanner/internal/connection_impl_test.cc
  google/cloud/spanner/results_test.cc
  google/cloud/spanner/value_test.cc
  google/cloud/storage/client_sign_url_test.cc
  google/cloud/storage/internal/complex_option_test.cc
  google/cloud/storage/internal/generic_request_test.cc
  google/cloud/storage/tests/object_hash_integration_test.cc
  google/cloud/testing_util/validate_metadata.cc
Labels: cla: yes

#5989 feature(bigquery): storage library generation
  BUILD
  CMakeLists.txt
  ci/kokoro/docker/build-in-docker-cmake.sh
  external/googleapis/CMakeLists.txt
  generator/generate-libraries.sh
  google/cloud/CMakeLists.txt
  google/cloud/bigquery/BUILD
  google/cloud/bigquery/CMakeLists.txt
  google/cloud/bigquery/README.md
  google/cloud/bigquery/big_query_read_client.gcpcxx.pb.cc
  google/cloud/bigquery/big_query_read_client.gcpcxx.pb.h
  google/cloud/bigquery/big_query_read_connection.gcpcxx.pb.cc
  google/cloud/bigquery/big_query_read_connection.gcpcxx.pb.h
  google/cloud/bigquery/big_query_read_connection_idempotency_policy.gcpcxx.pb.cc
  google/cloud/bigquery/big_query_read_connection_idempotency_policy.gcpcxx.pb.h
  google/cloud/bigquery/config.cmake.in
  google/cloud/bigquery/config.pc.in
  google/cloud/bigquery/google_cloud_cpp_bigquery.bzl
  google/cloud/bigquery/google_cloud_cpp_bigquery_mocks.bzl
  google/cloud/bigquery/integration_tests/BUILD
  google/cloud/bigquery/integration_tests/CMakeLists.txt
  google/cloud/bigquery/integration_tests/big_query_read_integration_test.cc
  google/cloud/bigquery/integration_tests/bigquery_client_integration_tests.bzl
  google/cloud/bigquery/internal/big_query_read_logging_decorator.gcpcxx.pb.cc
  google/cloud/bigquery/internal/big_query_read_logging_decorator.gcpcxx.pb.h
  google/cloud/bigquery/internal/big_query_read_metadata_decorator.gcpcxx.pb.cc
  google/cloud/bigquery/internal/big_query_read_metadata_decorator.gcpcxx.pb.h
  google/cloud/bigquery/internal/big_query_read_stub.gcpcxx.pb.cc
  google/cloud/bigquery/internal/big_query_read_stub.gcpcxx.pb.h
  google/cloud/bigquery/internal/big_query_read_stub_factory.gcpcxx.pb.cc
  google/cloud/bigquery/internal/big_query_read_stub_factory.gcpcxx.pb.h
  google/cloud/bigquery/mocks/mock_big_query_read_connection.gcpcxx.pb.h
  google/cloud/bigquery/retry_traits.h
  google/cloud/bigquery/streaming.cc
Labels: api: bigquery, cla: yes

#5991 feat(internal): add internal::MergeOptions()
  google/cloud/internal/options.cc
  google/cloud/internal/options.h
  google/cloud/internal/options_test.cc
Labels: cla: yes

#5992 refactor(spanner): implement SessionPoolOptions in terms of Options
  google/cloud/spanner/internal/options.cc
  google/cloud/spanner/internal/options_test.cc
  google/cloud/spanner/session_pool_options.h
  google/cloud/spanner/session_pool_options_test.cc
Labels: api: spanner, cla: yes

#5967 feat: bind `CompletionQueue` with InstanceAdmin
  google/cloud/bigtable/client_options.cc
  google/cloud/bigtable/client_options.h
  google/cloud/bigtable/instance_admin.cc
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/instance_admin_client.cc
  google/cloud/bigtable/instance_admin_client.h
  google/cloud/bigtable/internal/common_client.h
  google/cloud/bigtable/internal/logging_instance_admin_client.h
  google/cloud/bigtable/testing/mock_instance_admin_client.h
  google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
Labels: cla: yes

#5995 refactor(spanner): remove unnecessary MakeConnection factory
  google/cloud/spanner/client.cc
  google/cloud/spanner/internal/connection_impl.cc
  google/cloud/spanner/internal/connection_impl.h
  google/cloud/spanner/internal/connection_impl_test.cc
Labels: api: spanner, cla: yes

#5994 refactor(spanner): adds internal-only spanner-specific Retry and Backoff options
  google/cloud/spanner/internal/connection_impl.cc
  google/cloud/spanner/internal/options.cc
  google/cloud/spanner/internal/options.h
  google/cloud/spanner/internal/options_test.cc
Labels: api: spanner, cla: yes

#5996 refactor(generator): streaming reads to accept proto by const-ref
  ci/etc/generator-golden-md5-hashes.md5
  generator/integration_tests/golden/golden_kitchen_sink_client.gcpcxx.pb.cc
  generator/integration_tests/golden/golden_kitchen_sink_client.gcpcxx.pb.h
  generator/integration_tests/golden/golden_kitchen_sink_connection.gcpcxx.pb.cc
  generator/integration_tests/golden/golden_kitchen_sink_connection.gcpcxx.pb.h
  generator/integration_tests/golden/mocks/mock_golden_kitchen_sink_connection.gcpcxx.pb.h
  generator/internal/client_generator.cc
  generator/internal/connection_generator.cc
  generator/internal/mock_connection_generator.cc
  google/cloud/bigquery/big_query_read_client.gcpcxx.pb.cc
  google/cloud/bigquery/big_query_read_client.gcpcxx.pb.h
  google/cloud/bigquery/big_query_read_connection.gcpcxx.pb.cc
  google/cloud/bigquery/big_query_read_connection.gcpcxx.pb.h
  google/cloud/bigquery/mocks/mock_big_query_read_connection.gcpcxx.pb.h
Labels: cla: yes

#5999 cleanup: get roots.pem from https://pki.google.com
  ci/kokoro/macos/build-quickstart-bazel.sh
  ci/kokoro/macos/build-quickstart-cmake.sh
  ci/kokoro/macos/build.sh
  ci/kokoro/windows/build-bazel.ps1
  ci/kokoro/windows/build-cmake.ps1
  ci/kokoro/windows/build-quickstart-bazel.ps1
  ci/kokoro/windows/build-quickstart-cmake.ps1
  google/cloud/bigtable/examples/README.md
  google/cloud/bigtable/quickstart/README.md
  google/cloud/pubsub/quickstart/README.md
  google/cloud/spanner/quickstart/README.md
  google/cloud/spanner/samples/README.md
Labels: cla: yes

#6000 test: deflake bigtable integration tests
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/bigtable/bigtable_client_testing.bzl
  google/cloud/bigtable/bigtable_client_unit_tests.bzl
  google/cloud/bigtable/examples/BUILD
  google/cloud/bigtable/examples/CMakeLists.txt
  google/cloud/bigtable/examples/bigtable_examples_common.cc
  google/cloud/bigtable/examples/bigtable_examples_common.h
  google/cloud/bigtable/examples/bigtable_examples_common_test.cc
  google/cloud/bigtable/examples/bigtable_hello_app_profile.cc
  google/cloud/bigtable/examples/bigtable_hello_instance_admin.cc
  google/cloud/bigtable/examples/bigtable_hello_table_admin.cc
  google/cloud/bigtable/examples/bigtable_hello_world.cc
  google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc
  google/cloud/bigtable/examples/bigtable_table_admin_backup_snippets.cc
  google/cloud/bigtable/examples/data_async_snippets.cc
  google/cloud/bigtable/examples/data_filter_snippets.cc
  google/cloud/bigtable/examples/data_snippets.cc
  google/cloud/bigtable/examples/read_snippets.cc
  google/cloud/bigtable/examples/table_admin_iam_policy_snippets.cc
  google/cloud/bigtable/examples/table_admin_snippets.cc
  google/cloud/bigtable/testing/cleanup_stale_resources.cc
  google/cloud/bigtable/testing/cleanup_stale_resources.h
  google/cloud/bigtable/testing/cleanup_stale_resources_test.cc
  google/cloud/bigtable/testing/random_names.cc
  google/cloud/bigtable/testing/random_names.h
  google/cloud/bigtable/testing/random_names_test.cc
  google/cloud/bigtable/testing/table_integration_test.cc
  google/cloud/bigtable/testing/table_integration_test.h
Labels: cla: yes

#5998 refactor(spanner): changes the "stub" layer to use `Options`
  google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
  google/cloud/spanner/client.cc
  google/cloud/spanner/connection_options.cc
  google/cloud/spanner/connection_options.h
  google/cloud/spanner/connection_options_test.cc
  google/cloud/spanner/database_admin_connection.cc
  google/cloud/spanner/instance_admin_connection.cc
  google/cloud/spanner/integration_tests/session_pool_integration_test.cc
  google/cloud/spanner/internal/database_admin_stub.cc
  google/cloud/spanner/internal/database_admin_stub.h
  google/cloud/spanner/internal/instance_admin_stub.cc
  google/cloud/spanner/internal/instance_admin_stub.h
  google/cloud/spanner/internal/spanner_stub.cc
  google/cloud/spanner/internal/spanner_stub.h
  google/cloud/spanner/internal/spanner_stub_test.cc
Labels: api: spanner, cla: yes

#6002 cleanup(bigtable): remove ill-conceived static checks
  google/cloud/bigtable/testing/random_names.cc
  google/cloud/bigtable/testing/random_names_test.cc
Labels: api: bigtable, cla: yes

#6004 feat: bind `CompletionQueue` with `TableAdmin`
  google/cloud/bigtable/admin_client.cc
  google/cloud/bigtable/admin_client.h
  google/cloud/bigtable/internal/logging_admin_client.h
  google/cloud/bigtable/table_admin.cc
  google/cloud/bigtable/table_admin.h
  google/cloud/bigtable/testing/inprocess_admin_client.h
  google/cloud/bigtable/testing/mock_admin_client.h
Labels: cla: yes

#6003 test(bigtable): plug one table leak
  google/cloud/bigtable/tests/data_integration_test.cc
Labels: api: bigtable, cla: yes

#6011 Arch build support: ca-certificates.crt location
  bazel/curl.BUILD
Labels: cla: yes

#6010 ci: retry initial vcpkg install
  ci/kokoro/windows/build-cmake-dependencies.ps1
Labels: cla: yes

#6009 ci: perform bazel fetch for Windows build
  ci/kokoro/windows/build-bazel.ps1
  ci/kokoro/windows/build.bat
Labels: cla: yes

#6012 feat(bigtable): Bind CompletionQueue with Table
  ci/test-abi/google_cloud_cpp_bigtable.expected.abi.dump.gz
  google/cloud/bigtable/async_row_reader_test.cc
  google/cloud/bigtable/benchmarks/CMakeLists.txt
  google/cloud/bigtable/benchmarks/benchmark.h
  google/cloud/bigtable/benchmarks/read_sync_vs_async_benchmark.cc
  google/cloud/bigtable/data_client.cc
  google/cloud/bigtable/data_client.h
  google/cloud/bigtable/examples/CMakeLists.txt
  google/cloud/bigtable/examples/data_async_snippets.cc
  google/cloud/bigtable/internal/async_bulk_apply_test.cc
  google/cloud/bigtable/internal/async_longrunning_op_test.cc
  google/cloud/bigtable/internal/async_poll_op_test.cc
  google/cloud/bigtable/internal/async_retry_unary_rpc_and_poll_test.cc
  google/cloud/bigtable/internal/logging_data_client.h
  google/cloud/bigtable/mutation_batcher.cc
  google/cloud/bigtable/mutation_batcher.h
  google/cloud/bigtable/mutation_batcher_test.cc
  google/cloud/bigtable/row_reader_test.cc
  google/cloud/bigtable/table.cc
  google/cloud/bigtable/table.h
  google/cloud/bigtable/table_apply_test.cc
  google/cloud/bigtable/table_bulk_apply_test.cc
  google/cloud/bigtable/table_check_and_mutate_row_test.cc
  google/cloud/bigtable/table_readmodifywriterow_test.cc
  google/cloud/bigtable/table_readrow_test.cc
  google/cloud/bigtable/table_readrows_test.cc
  google/cloud/bigtable/table_sample_row_keys_test.cc
  google/cloud/bigtable/table_test.cc
  google/cloud/bigtable/testing/inprocess_data_client.h
  google/cloud/bigtable/testing/mock_data_client.h
  google/cloud/bigtable/testing/table_test_fixture.cc
  google/cloud/bigtable/testing/table_test_fixture.h
  google/cloud/bigtable/tests/CMakeLists.txt
  google/cloud/bigtable/tests/data_async_future_integration_test.cc
  google/cloud/bigtable/version.h
Labels: api: bigtable, cla: yes

#6014 fix(bigtable): set timeouts for asynchronous operations
  google/cloud/CMakeLists.txt
  google/cloud/google_cloud_cpp_grpc_utils.bzl
  google/cloud/internal/async_retry_loop.h
  google/cloud/internal/async_retry_loop_test.cc
  google/cloud/internal/async_retry_unary_rpc.h
  google/cloud/internal/async_retry_unary_rpc_test.cc
  google/cloud/internal/setup_context.h
Labels: api: bigtable, cla: yes

#6015 test(spanner): sometimes the credentials are null
  google/cloud/spanner/internal/options_test.cc
Labels: api: spanner, cla: yes

#6006 refactor(spanner): session_pool now uses Options
  google/cloud/spanner/client.cc
  google/cloud/spanner/integration_tests/session_pool_integration_test.cc
  google/cloud/spanner/internal/connection_impl.cc
  google/cloud/spanner/internal/options.cc
  google/cloud/spanner/internal/options_test.cc
  google/cloud/spanner/internal/session_pool.cc
  google/cloud/spanner/internal/session_pool.h
  google/cloud/spanner/internal/session_pool_test.cc
Labels: api: spanner, cla: yes

#6016 cleanup(spanner): new version time in spanner_create_backup sample
  google/cloud/spanner/samples/samples.cc
Labels: api: spanner, cla: yes, samples

#6017 refactor(spanner): connection_impl now uses new Options
  google/cloud/spanner/client.cc
  google/cloud/spanner/internal/connection_impl.cc
  google/cloud/spanner/internal/connection_impl.h
  google/cloud/spanner/internal/connection_impl_test.cc
Labels: api: spanner, cla: yes

#6018 feat(ci): remove sudo from scripts
  ci/generate-markdown/README.md
  ci/kokoro/docker/build.sh
  ci/kokoro/docker/dump-reports.sh
  ci/kokoro/docker/upload-coverage.sh
  doc/contributor/howto-guide-setup-development-workstation.md
Labels: cla: yes

#6021 test(spanner): fix driver for slow samples
  google/cloud/spanner/samples/samples.cc
Labels: api: spanner, cla: yes, samples

#6023 feat(internal): add internal-only `TypeList`
  google/cloud/CMakeLists.txt
  google/cloud/google_cloud_cpp_common.bzl
  google/cloud/google_cloud_cpp_common_unit_tests.bzl
  google/cloud/internal/type_list.h
  google/cloud/internal/type_list_test.cc
Labels: cla: yes

#6024 refactor(internal): create OptionList<...> implemented with TypeList
  google/cloud/internal/common_options.h
  google/cloud/internal/common_options_test.cc
  google/cloud/internal/grpc_options.h
  google/cloud/internal/grpc_options_test.cc
  google/cloud/internal/options.h
  google/cloud/internal/options_test.cc
  google/cloud/spanner/client.cc
  google/cloud/spanner/internal/options.h
  google/cloud/spanner/session_pool_options.h
Labels: cla: yes

#6022 refactor(spanner): add spanner_internal::MakeConnection
  google/cloud/spanner/client.cc
  google/cloud/spanner/client.h
  google/cloud/spanner/client_test.cc
Labels: api: spanner, cla: yes

#6026 refactor(spanner): db admin connection uses new Options
  google/cloud/spanner/database_admin_connection.cc
  google/cloud/spanner/database_admin_connection.h
  google/cloud/spanner/database_admin_connection_test.cc
  google/cloud/spanner/internal/options.cc
  google/cloud/spanner/internal/options.h
  google/cloud/spanner/internal/options_test.cc
Labels: api: spanner, cla: yes

#6028 refactor(spanner): use common UserAgentPrefix function
  google/cloud/spanner/internal/options.cc
Labels: api: spanner, cla: yes

#6027 refactor(spanner): instance admin uses new Options
  google/cloud/spanner/instance_admin_connection.cc
  google/cloud/spanner/instance_admin_connection.h
  google/cloud/spanner/instance_admin_connection_test.cc
Labels: api: spanner, cla: yes

#6029 doc(spanner): fix expected option lists
  google/cloud/spanner/client.h
  google/cloud/spanner/database_admin_connection.h
  google/cloud/spanner/instance_admin_connection.h
Labels: api: spanner, cla: yes

#6035 refactor(spanner): DefaultAdminOptions don't need SessionPool options
  google/cloud/spanner/internal/options.cc
  google/cloud/spanner/internal/options_test.cc
Labels: api: spanner, cla: yes

#6036 doc(ARCHITECTURE): fix typo
  ARCHITECTURE.md
Labels: cla: yes

#6030 cleanup(pubsub): cleanup Status/StatusOr<T> gmock matchers
  google/cloud/pubsub/integration_tests/subscriber_integration_test.cc
  google/cloud/pubsub/integration_tests/subscription_admin_integration_test.cc
  google/cloud/pubsub/integration_tests/topic_admin_integration_test.cc
  google/cloud/pubsub/internal/batching_publisher_connection_test.cc
  google/cloud/pubsub/internal/default_batch_sink_test.cc
  google/cloud/pubsub/internal/ordering_key_publisher_connection_test.cc
  google/cloud/pubsub/internal/publisher_logging_test.cc
  google/cloud/pubsub/internal/publisher_metadata_test.cc
  google/cloud/pubsub/internal/publisher_round_robin_test.cc
  google/cloud/pubsub/internal/rejects_with_ordering_key_test.cc
  google/cloud/pubsub/internal/schema_logging_test.cc
  google/cloud/pubsub/internal/sequential_batch_sink_test.cc
  google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc
  google/cloud/pubsub/internal/subscriber_logging_test.cc
  google/cloud/pubsub/internal/subscriber_metadata_test.cc
  google/cloud/pubsub/internal/subscriber_round_robin_test.cc
  google/cloud/pubsub/internal/subscription_concurrency_control_test.cc
  google/cloud/pubsub/internal/subscription_lease_management_test.cc
  google/cloud/pubsub/internal/subscription_session_test.cc
  google/cloud/pubsub/publisher_connection_test.cc
  google/cloud/pubsub/publisher_test.cc
  google/cloud/pubsub/subscriber_connection_test.cc
  google/cloud/pubsub/subscriber_test.cc
  google/cloud/pubsub/subscription_admin_client_test.cc
  google/cloud/pubsub/subscription_admin_connection_test.cc
  google/cloud/pubsub/topic_admin_client_test.cc
  google/cloud/pubsub/topic_admin_connection_test.cc
Labels: api: pubsub, cla: yes

#6032 cleanup(spanner): cleanup Status/StatusOr<T> gmock matchers
  google/cloud/spanner/benchmarks/benchmarks_config_test.cc
  google/cloud/spanner/bytes_test.cc
  google/cloud/spanner/client_test.cc
  google/cloud/spanner/database_admin_client_test.cc
  google/cloud/spanner/database_admin_connection_test.cc
  google/cloud/spanner/instance_admin_client_test.cc
  google/cloud/spanner/instance_admin_connection_test.cc
  google/cloud/spanner/integration_tests/backup_integration_test.cc
  google/cloud/spanner/integration_tests/client_integration_test.cc
  google/cloud/spanner/integration_tests/client_stress_test.cc
  google/cloud/spanner/integration_tests/data_types_integration_test.cc
  google/cloud/spanner/integration_tests/database_admin_integration_test.cc
  google/cloud/spanner/integration_tests/instance_admin_integration_test.cc
  google/cloud/spanner/integration_tests/rpc_failure_threshold_integration_test.cc
  google/cloud/spanner/integration_tests/session_pool_integration_test.cc
  google/cloud/spanner/internal/connection_impl_test.cc
  google/cloud/spanner/internal/database_admin_logging_test.cc
  google/cloud/spanner/internal/database_admin_metadata_test.cc
  google/cloud/spanner/internal/instance_admin_logging_test.cc
  google/cloud/spanner/internal/instance_admin_metadata_test.cc
  google/cloud/spanner/internal/logging_result_set_reader_test.cc
  google/cloud/spanner/internal/logging_spanner_stub_test.cc
  google/cloud/spanner/internal/merge_chunk_test.cc
  google/cloud/spanner/internal/metadata_spanner_stub_test.cc
  google/cloud/spanner/internal/partial_result_set_resume_test.cc
  google/cloud/spanner/internal/partial_result_set_source_test.cc
  google/cloud/spanner/internal/session_pool_test.cc
  google/cloud/spanner/query_partition_test.cc
  google/cloud/spanner/read_partition_test.cc
  google/cloud/spanner/results_test.cc
  google/cloud/spanner/row_test.cc
  google/cloud/spanner/sql_statement_test.cc
  google/cloud/spanner/testing/cleanup_stale_databases_test.cc
  google/cloud/spanner/testing/database_integration_test.cc
  google/cloud/spanner/value_test.cc
Labels: api: spanner, cla: yes

#6033 cleanup(generator): cleanup Status/StatusOr<T> gmock matchers
  generator/integration_tests/BUILD
  generator/integration_tests/generator_integration_test.cc
  generator/integration_tests/golden/tests/golden_kitchen_sink_client_test.cc
  generator/integration_tests/golden/tests/golden_kitchen_sink_connection_test.cc
  generator/integration_tests/golden/tests/golden_kitchen_sink_logging_decorator_test.cc
  generator/integration_tests/golden/tests/golden_kitchen_sink_metadata_decorator_test.cc
  generator/integration_tests/golden/tests/golden_kitchen_sink_stub_test.cc
  generator/integration_tests/golden/tests/golden_thing_admin_client_test.cc
  generator/integration_tests/golden/tests/golden_thing_admin_connection_test.cc
  generator/integration_tests/golden/tests/golden_thing_admin_logging_decorator_test.cc
  generator/integration_tests/golden/tests/golden_thing_admin_metadata_decorator_test.cc
  generator/integration_tests/golden/tests/golden_thing_admin_stub_test.cc
  generator/internal/codegen_utils_test.cc
  generator/internal/descriptor_utils_test.cc
Labels: cla: yes

#6034 cleanup(bigtable): cleanup Status/StatusOr<T> gmock matchers
  google/cloud/bigtable/async_list_app_profiles_test.cc
  google/cloud/bigtable/async_list_clusters_test.cc
  google/cloud/bigtable/async_list_instances_test.cc
  google/cloud/bigtable/async_read_stream_test.cc
  google/cloud/bigtable/async_row_reader_test.cc
  google/cloud/bigtable/benchmarks/bigtable_benchmark_test.cc
  google/cloud/bigtable/benchmarks/embedded_server_test.cc
  google/cloud/bigtable/benchmarks/setup_test.cc
  google/cloud/bigtable/cell_test.cc
  google/cloud/bigtable/client_options_test.cc
  google/cloud/bigtable/instance_admin_test.cc
  google/cloud/bigtable/internal/async_bulk_apply_test.cc
  google/cloud/bigtable/internal/async_longrunning_op_test.cc
  google/cloud/bigtable/internal/async_poll_op_test.cc
  google/cloud/bigtable/internal/async_retry_multi_page_test.cc
  google/cloud/bigtable/internal/async_retry_unary_rpc_and_poll_test.cc
  google/cloud/bigtable/internal/common_client_test.cc
  google/cloud/bigtable/internal/logging_admin_client_test.cc
  google/cloud/bigtable/internal/logging_data_client_test.cc
  google/cloud/bigtable/internal/logging_instance_admin_client_test.cc
  google/cloud/bigtable/internal/readrowsparser_test.cc
  google/cloud/bigtable/mutation_batcher_test.cc
  google/cloud/bigtable/mutations_test.cc
  google/cloud/bigtable/row_reader_test.cc
  google/cloud/bigtable/table_admin_test.cc
  google/cloud/bigtable/table_apply_test.cc
  google/cloud/bigtable/table_bulk_apply_test.cc
  google/cloud/bigtable/table_check_and_mutate_row_test.cc
  google/cloud/bigtable/table_readmodifywriterow_test.cc
  google/cloud/bigtable/table_readrow_test.cc
  google/cloud/bigtable/table_readrows_test.cc
  google/cloud/bigtable/table_sample_row_keys_test.cc
  google/cloud/bigtable/testing/mock_response_reader.h
  google/cloud/bigtable/testing/table_integration_test.cc
  google/cloud/bigtable/tests/admin_async_future_integration_test.cc
  google/cloud/bigtable/tests/admin_backup_async_future_integration_test.cc
  google/cloud/bigtable/tests/admin_backup_integration_test.cc
  google/cloud/bigtable/tests/admin_iam_policy_integration_test.cc
  google/cloud/bigtable/tests/admin_integration_test.cc
  google/cloud/bigtable/tests/data_async_future_integration_test.cc
  google/cloud/bigtable/tests/data_integration_test.cc
  google/cloud/bigtable/tests/filters_integration_test.cc
  google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
  google/cloud/bigtable/tests/instance_admin_integration_test.cc
  google/cloud/bigtable/tests/mutations_integration_test.cc
Labels: api: bigtable, cla: yes

#6038 cleanup: cleanup Status/StatusOr<T> gmock matchers
  google/cloud/bigquery/integration_tests/big_query_read_integration_test.cc
  google/cloud/completion_queue_test.cc
  google/cloud/iam/integration_tests/iam_credentials_integration_test.cc
  google/cloud/internal/async_connection_ready_test.cc
  google/cloud/internal/async_read_write_stream_impl_test.cc
  google/cloud/internal/async_retry_loop_test.cc
  google/cloud/internal/async_retry_unary_rpc_test.cc
  google/cloud/internal/big_endian_test.cc
  google/cloud/internal/polling_loop_test.cc
  google/cloud/internal/resumable_streaming_read_rpc_test.cc
  google/cloud/internal/retry_loop_test.cc
  google/cloud/internal/streaming_read_rpc_logging_test.cc
  google/cloud/internal/streaming_read_rpc_test.cc
  google/cloud/internal/time_utils_test.cc
  google/cloud/kms_key_name_test.cc
  google/cloud/logging/integration_tests/logging_integration_test.cc
  google/cloud/status_or_test.cc
Labels: cla: yes

#6039 cleanup(bigtable): cleanup Status/StatusOr<T> gmock matchers
  google/cloud/bigtable/internal/readrowsparser_acceptance_tests.inc
  google/cloud/bigtable/internal/readrowsparser_test.cc
  google/cloud/bigtable/tools/convert_acceptance_tests.py
Labels: api: bigtable, cla: yes

#6037 refactor(spanner): improve Option discoverability by having a single spanner/options.h
  ci/custom-words.txt
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
  google/cloud/spanner/client.cc
  google/cloud/spanner/connection_options.cc
  google/cloud/spanner/database_admin_connection.cc
  google/cloud/spanner/database_admin_connection_test.cc
  google/cloud/spanner/google_cloud_cpp_spanner.bzl
  google/cloud/spanner/instance_admin_connection.cc
  google/cloud/spanner/instance_admin_connection_test.cc
  google/cloud/spanner/integration_tests/session_pool_integration_test.cc
  google/cloud/spanner/internal/connection_impl.cc
  google/cloud/spanner/internal/connection_impl_test.cc
  google/cloud/spanner/internal/defaults.cc
  google/cloud/spanner/internal/defaults.h
  google/cloud/spanner/internal/defaults_test.cc
  google/cloud/spanner/internal/session_pool.cc
  google/cloud/spanner/internal/session_pool_test.cc
  google/cloud/spanner/internal/spanner_stub_test.cc
  google/cloud/spanner/options.cc
  google/cloud/spanner/options.h
  google/cloud/spanner/session_pool_options.h
  google/cloud/spanner/spanner_client_unit_tests.bzl
Labels: api: spanner, cla: yes

#6040 cleanup: cleanup Status/StatusOr<T> gmock matchers
  google/cloud/testing_util/CMakeLists.txt
  google/cloud/testing_util/assert_ok.h
  google/cloud/testing_util/assert_ok_test.cc
  google/cloud/testing_util/google_cloud_cpp_testing.bzl
  google/cloud/testing_util/google_cloud_cpp_testing_unit_tests.bzl
Labels: cla: yes

#6043 cleanup(spanner): remove some TODOs
  google/cloud/spanner/connection_options.cc
  google/cloud/spanner/internal/connection_impl.cc
  google/cloud/spanner/internal/connection_impl.h
Labels: api: spanner, cla: yes

#6042 feat(common): make Options public
  google/cloud/CMakeLists.txt
  google/cloud/common_options.h
  google/cloud/common_options_test.cc
  google/cloud/connection_options.h
  google/cloud/connection_options_test.cc
  google/cloud/google_cloud_cpp_common.bzl
  google/cloud/google_cloud_cpp_common_unit_tests.bzl
  google/cloud/google_cloud_cpp_grpc_utils.bzl
  google/cloud/google_cloud_cpp_grpc_utils_unit_tests.bzl
  google/cloud/grpc_options.cc
  google/cloud/grpc_options.h
  google/cloud/grpc_options_test.cc
  google/cloud/options.cc
  google/cloud/options.h
  google/cloud/options_test.cc
  google/cloud/spanner/benchmarks/multiple_rows_cpu_benchmark.cc
  google/cloud/spanner/client.cc
  google/cloud/spanner/client.h
  google/cloud/spanner/client_test.cc
  google/cloud/spanner/connection_options.cc
  google/cloud/spanner/database_admin_connection.cc
  google/cloud/spanner/database_admin_connection.h
  google/cloud/spanner/database_admin_connection_test.cc
  google/cloud/spanner/instance_admin_connection.cc
  google/cloud/spanner/instance_admin_connection.h
  google/cloud/spanner/instance_admin_connection_test.cc
  google/cloud/spanner/internal/connection_impl.cc
  google/cloud/spanner/internal/connection_impl.h
  google/cloud/spanner/internal/connection_impl_test.cc
  google/cloud/spanner/internal/database_admin_stub.cc
  google/cloud/spanner/internal/database_admin_stub.h
  google/cloud/spanner/internal/defaults.cc
  google/cloud/spanner/internal/defaults.h
  google/cloud/spanner/internal/defaults_test.cc
  google/cloud/spanner/internal/instance_admin_stub.cc
  google/cloud/spanner/internal/instance_admin_stub.h
  google/cloud/spanner/internal/session_pool.cc
  google/cloud/spanner/internal/session_pool.h
  google/cloud/spanner/internal/session_pool_test.cc
  google/cloud/spanner/internal/spanner_stub.cc
  google/cloud/spanner/internal/spanner_stub.h
  google/cloud/spanner/internal/spanner_stub_test.cc
  google/cloud/spanner/options.h
  google/cloud/spanner/session_pool_options.h
Labels: cla: yes

#6045 doc(ARCHITECTURE): add section about `Options`
  ARCHITECTURE.md
Labels: cla: yes

#6046 feat(spanner): connection factories now prefer `Options`
  google/cloud/spanner/client.cc
  google/cloud/spanner/client.h
  google/cloud/spanner/client_test.cc
  google/cloud/spanner/database_admin_connection.cc
  google/cloud/spanner/database_admin_connection.h
  google/cloud/spanner/database_admin_connection_test.cc
  google/cloud/spanner/instance_admin_connection.cc
  google/cloud/spanner/instance_admin_connection.h
  google/cloud/spanner/instance_admin_connection_test.cc
  google/cloud/spanner/integration_tests/session_pool_integration_test.cc
  google/cloud/spanner/internal/connection_impl.cc
  google/cloud/spanner/internal/connection_impl_test.cc
  google/cloud/spanner/internal/defaults.cc
  google/cloud/spanner/internal/defaults_test.cc
  google/cloud/spanner/internal/session_pool.cc
  google/cloud/spanner/internal/session_pool_test.cc
  google/cloud/spanner/options.h
  google/cloud/spanner/session_pool_options.h
  google/cloud/spanner/session_pool_options_test.cc
Labels: api: spanner, cla: yes

#6044 common: fix ambiguous match bazel error on macos 11 intel
  google/cloud/testing_util/BUILD
Labels: cla: yes

#6048 feat(common): log the last N entries
  google/cloud/CMakeLists.txt
  google/cloud/google_cloud_cpp_common.bzl
  google/cloud/google_cloud_cpp_common_unit_tests.bzl
  google/cloud/internal/log_impl.cc
  google/cloud/internal/log_impl.h
  google/cloud/internal/log_impl_test.cc
  google/cloud/log.cc
  google/cloud/log.h
  google/cloud/log_test.cc
  google/cloud/testing_util/scoped_log.h
Labels: cla: yes

#6049 feat(common): experimental logging configuration
  google/cloud/bigtable/doc/bigtable-main.dox
  google/cloud/internal/log_impl.h
  google/cloud/internal/log_impl_test.cc
  google/cloud/log.cc
  google/cloud/log.h
  google/cloud/pubsub/doc/pubsub-main.dox
  google/cloud/spanner/doc/spanner-main.dox
  google/cloud/storage/doc/storage-main.dox
Labels: cla: yes

#6050 test: log the last few RPCs on sample failures
  ci/kokoro/docker/build-in-docker-bazel.sh
  ci/kokoro/docker/build-in-docker-cmake.sh
  ci/kokoro/macos/build-bazel.sh
  ci/kokoro/macos/build-cmake.sh
  ci/kokoro/windows/build-bazel.ps1
  google/cloud/bigtable/ci/run_integration_tests_emulator_bazel.sh
  google/cloud/bigtable/ci/run_integration_tests_emulator_cmake.sh
  google/cloud/bigtable/tests/data_integration_test.cc
  google/cloud/internal/log_impl_test.cc
  google/cloud/log_test.cc
  google/cloud/pubsub/ci/run_integration_tests_emulator_bazel.sh
  google/cloud/pubsub/ci/run_integration_tests_emulator_cmake.sh
  google/cloud/spanner/ci/run_integration_tests_emulator_cmake.sh
  google/cloud/spanner/samples/samples.cc
  google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh
  google/cloud/storage/ci/run_integration_tests_emulator_cmake.sh
  google/cloud/testing_util/example_driver.cc
Labels: cla: yes, samples

#6051 fix(bigtable): multiple region tags on same line
  google/cloud/bigtable/examples/table_admin_snippets.cc
Labels: api: bigtable, cla: yes

#6047 cleanup(bigtable)!: make *Client::BackgroundThreadsFactory() pure
  CHANGELOG.md
  ci/test-abi/google_cloud_cpp_bigtable.expected.abi.dump.gz
  google/cloud/bigtable/admin_client.h
  google/cloud/bigtable/data_client.h
  google/cloud/bigtable/instance_admin_client.h
Labels: api: bigtable, cla: yes

#6052 test: log last RPCs on integration test failures
  google/cloud/bigquery/integration_tests/big_query_read_integration_test.cc
  google/cloud/bigtable/testing/table_integration_test.h
  google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc
  google/cloud/bigtable/tests/instance_admin_integration_test.cc
  google/cloud/iam/integration_tests/iam_credentials_integration_test.cc
  google/cloud/logging/integration_tests/logging_integration_test.cc
  google/cloud/pubsub/integration_tests/schema_admin_integration_test.cc
  google/cloud/pubsub/integration_tests/subscriber_integration_test.cc
  google/cloud/pubsub/integration_tests/subscription_admin_integration_test.cc
  google/cloud/pubsub/integration_tests/topic_admin_integration_test.cc
  google/cloud/spanner/integration_tests/backup_integration_test.cc
  google/cloud/spanner/integration_tests/database_admin_integration_test.cc
  google/cloud/spanner/integration_tests/rpc_failure_threshold_integration_test.cc
  google/cloud/spanner/testing/database_integration_test.h
  google/cloud/storage/BUILD
  google/cloud/storage/testing/storage_integration_test.h
  google/cloud/testing_util/CMakeLists.txt
  google/cloud/testing_util/google_cloud_cpp_testing.bzl
  google/cloud/testing_util/integration_test.cc
  google/cloud/testing_util/integration_test.h
Labels: cla: yes

#6054 ci: require sourced modules to specify full path
  ci/check-generated-code-hash.sh
  ci/check-golden-md5-hashes.sh
  ci/check-style.sh
  ci/kokoro/docker/build-in-docker-bazel.sh
  ci/kokoro/docker/build-in-docker-cmake.sh
  ci/kokoro/docker/build-in-docker-quickstart-bazel.sh
  ci/kokoro/docker/build-in-docker-quickstart-cmake.sh
  ci/kokoro/docker/build.sh
  ci/kokoro/docker/check-abi.sh
  ci/kokoro/docker/download-cache.sh
  ci/kokoro/docker/upload-cache.sh
  ci/kokoro/docker/upload-docs.sh
  ci/kokoro/install/build.sh
  ci/kokoro/install/run-installed-programs.sh
  ci/kokoro/macos/build-bazel.sh
  ci/kokoro/macos/build-cmake.sh
  ci/kokoro/macos/build-quickstart-bazel.sh
  ci/kokoro/macos/build-quickstart-cmake.sh
  ci/kokoro/macos/build.sh
  ci/kokoro/macos/download-cache.sh
  ci/kokoro/macos/upload-cache.sh
  ci/lib/init.sh
  ci/lib/io.sh
  generator/ci/run_integration_tests_emulator_bazel.sh
  generator/ci/run_integration_tests_emulator_cmake.sh
  generator/generate-libraries.sh
  google/cloud/bigtable/ci/run_integration_tests_emulator_bazel.sh
  google/cloud/bigtable/ci/run_integration_tests_emulator_cmake.sh
  google/cloud/pubsub/ci/lib/pubsub_emulator.sh
  google/cloud/pubsub/ci/run_integration_tests_emulator_bazel.sh
  google/cloud/pubsub/ci/run_integration_tests_emulator_cmake.sh
  google/cloud/spanner/ci/lib/spanner_emulator.sh
  google/cloud/spanner/ci/run_integration_tests_emulator_cmake.sh
  google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh
  google/cloud/storage/ci/run_integration_tests_emulator_cmake.sh
  google/cloud/storage/tools/run_emulator_utils.sh
Labels: cla: yes

#6056 ci: change sourced shell scripts to "modules" in /ci/kokoro/lib
  ci/kokoro/docker/build-in-docker-bazel.sh
  ci/kokoro/docker/build-in-docker-cmake.sh
  ci/kokoro/docker/build.sh
  ci/kokoro/docker/download-cache.sh
  ci/kokoro/docker/dump-logs.sh
  ci/kokoro/docker/dump-reports.sh
  ci/kokoro/docker/publish-refdocs.sh
  ci/kokoro/docker/upload-cache.sh
  ci/kokoro/docker/upload-coverage.sh
  ci/kokoro/install/build.sh
  ci/kokoro/lib/cache.sh
  ci/kokoro/lib/docker-variables.sh
  ci/kokoro/lib/dump-log.sh
  ci/kokoro/lib/gcloud.sh
  ci/kokoro/macos/download-cache.sh
  ci/kokoro/macos/upload-cache.sh
Labels: cla: yes

#6055 fix(pubsub): deadlocks for cancel during session startup
  google/cloud/pubsub/internal/streaming_subscription_batch_source.cc
  google/cloud/pubsub/internal/streaming_subscription_batch_source_test.cc
  google/cloud/pubsub/samples/samples.cc
Labels: api: pubsub, cla: yes

#6058 ci: all shell 'libraries' converted to 'source module'
  ci/kokoro/install/build.sh
  ci/kokoro/install/lib/run-installed-programs.sh
  google/cloud/bigtable/ci/run_integration_tests_emulator_bazel.sh
  google/cloud/bigtable/ci/run_integration_tests_emulator_cmake.sh
  google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh
  google/cloud/storage/ci/run_integration_tests_emulator_cmake.sh
Labels: cla: yes

#6057 refactor(generator): move default policy creation inside options default function
  ci/etc/generator-golden-md5-hashes.md5
  generator/integration_tests/generator_integration_test.cc
  generator/integration_tests/golden/golden_kitchen_sink_connection.gcpcxx.pb.cc
  generator/integration_tests/golden/golden_kitchen_sink_connection.gcpcxx.pb.h
  generator/integration_tests/golden/golden_kitchen_sink_options.gcpcxx.pb.h
  generator/integration_tests/golden/golden_thing_admin_connection.gcpcxx.pb.cc
  generator/integration_tests/golden/golden_thing_admin_connection.gcpcxx.pb.h
  generator/integration_tests/golden/golden_thing_admin_options.gcpcxx.pb.h
  generator/integration_tests/golden/internal/golden_kitchen_sink_option_defaults.gcpcxx.pb.cc
  generator/integration_tests/golden/internal/golden_thing_admin_option_defaults.gcpcxx.pb.cc
  generator/internal/connection_generator.cc
  generator/internal/option_defaults_generator.cc
  generator/internal/options_generator.cc
  google/cloud/bigquery/big_query_read_connection.gcpcxx.pb.cc
  google/cloud/bigquery/big_query_read_connection.gcpcxx.pb.h
  google/cloud/bigquery/big_query_read_options.gcpcxx.pb.h
  google/cloud/bigquery/internal/big_query_read_option_defaults.gcpcxx.pb.cc
  google/cloud/iam/iam_credentials_connection.gcpcxx.pb.cc
  google/cloud/iam/iam_credentials_connection.gcpcxx.pb.h
  google/cloud/iam/iam_credentials_options.gcpcxx.pb.h
  google/cloud/iam/internal/iam_credentials_option_defaults.gcpcxx.pb.cc
  google/cloud/logging/internal/logging_service_v2_option_defaults.gcpcxx.pb.cc
  google/cloud/logging/logging_service_v2_connection.gcpcxx.pb.cc
  google/cloud/logging/logging_service_v2_connection.gcpcxx.pb.h
  google/cloud/logging/logging_service_v2_options.gcpcxx.pb.h
Labels: cla: yes

#6061 cleanup(pubsub): make some examples more readable
  google/cloud/pubsub/samples/samples.cc
Labels: api: pubsub, cla: yes

#6067 cleanup(bigtable): cleanup static analyzer nit
  google/cloud/bigtable/instance_admin_test.cc
Labels: api: bigtable, cla: yes

#6065 ci: support manually running clang's static analyzer
  ci/kokoro/docker/Dockerfile.fedora-install
  ci/kokoro/docker/build-in-docker-cmake.sh
  ci/kokoro/docker/build.sh
Labels: cla: yes

#6066 fix(storage): use after move problems
  google/cloud/storage/internal/grpc_client.cc
  google/cloud/storage/lifecycle_rule.cc
Labels: api: storage, cla: yes

#6064 fix(storage): move disabling consts
  google/cloud/storage/parallel_upload.cc
  google/cloud/storage/parallel_upload.h
  google/cloud/storage/parallel_uploads_test.cc
Labels: api: storage, cla: yes

#6068 fix(common): move disabling consts
  google/cloud/iam_bindings.h
Labels: cla: yes

#6069 cleanup: deprecate some IAM types
  google/cloud/iam_binding.h
  google/cloud/iam_bindings.cc
  google/cloud/iam_bindings.h
  google/cloud/iam_bindings_test.cc
  google/cloud/iam_policy.h
  google/cloud/storage/internal/bucket_requests.cc
  google/cloud/storage/internal/bucket_requests_test.cc
  google/cloud/version.h
Labels: cla: yes

#6070 refactor: add snake case exception list for bigquery
  generator/internal/codegen_utils.cc
  generator/internal/codegen_utils_test.cc
  google/cloud/bigquery/CMakeLists.txt
  google/cloud/bigquery/bigquery_read_client.gcpcxx.pb.cc
  google/cloud/bigquery/bigquery_read_client.gcpcxx.pb.h
  google/cloud/bigquery/bigquery_read_connection.gcpcxx.pb.cc
  google/cloud/bigquery/bigquery_read_connection.gcpcxx.pb.h
  google/cloud/bigquery/bigquery_read_connection_idempotency_policy.gcpcxx.pb.cc
  google/cloud/bigquery/bigquery_read_connection_idempotency_policy.gcpcxx.pb.h
  google/cloud/bigquery/bigquery_read_options.gcpcxx.pb.h
  google/cloud/bigquery/google_cloud_cpp_bigquery.bzl
  google/cloud/bigquery/google_cloud_cpp_bigquery_mocks.bzl
  google/cloud/bigquery/integration_tests/CMakeLists.txt
  google/cloud/bigquery/integration_tests/bigquery_client_integration_tests.bzl
  google/cloud/bigquery/integration_tests/bigquery_read_integration_test.cc
  google/cloud/bigquery/internal/bigquery_read_logging_decorator.gcpcxx.pb.cc
  google/cloud/bigquery/internal/bigquery_read_logging_decorator.gcpcxx.pb.h
  google/cloud/bigquery/internal/bigquery_read_metadata_decorator.gcpcxx.pb.cc
  google/cloud/bigquery/internal/bigquery_read_metadata_decorator.gcpcxx.pb.h
  google/cloud/bigquery/internal/bigquery_read_option_defaults.gcpcxx.pb.cc
  google/cloud/bigquery/internal/bigquery_read_option_defaults.gcpcxx.pb.h
  google/cloud/bigquery/internal/bigquery_read_stub.gcpcxx.pb.cc
  google/cloud/bigquery/internal/bigquery_read_stub.gcpcxx.pb.h
  google/cloud/bigquery/internal/bigquery_read_stub_factory.gcpcxx.pb.cc
  google/cloud/bigquery/internal/bigquery_read_stub_factory.gcpcxx.pb.h
  google/cloud/bigquery/mocks/mock_bigquery_read_connection.gcpcxx.pb.h
  google/cloud/bigquery/streaming.cc
Labels: cla: yes

#6072 cleanup: fix #warning message for unsupported "diagnostic push"
  google/cloud/internal/diagnostics_push.inc
Labels: cla: yes

#6075 doc(storage): better description for ObjectWriteStream
  google/cloud/storage/client.h
  google/cloud/storage/object_stream.h
Labels: api: storage, cla: yes

#6076 cleanup: remove workarounds for absl package
  generator/CMakeLists.txt
  google/cloud/CMakeLists.txt
  google/cloud/bigquery/CMakeLists.txt
  google/cloud/bigtable/CMakeLists.txt
  google/cloud/iam/CMakeLists.txt
  google/cloud/logging/CMakeLists.txt
  google/cloud/pubsub/CMakeLists.txt
  google/cloud/pubsub/benchmarks/CMakeLists.txt
  google/cloud/spanner/CMakeLists.txt
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/benchmarks/CMakeLists.txt
Labels: cla: yes

#6077 test(bigtable): fix ports for emulators with Bazel
  google/cloud/bigtable/ci/run_integration_tests_emulator_bazel.sh
  google/cloud/bigtable/tools/run_emulator_utils.sh
Labels: api: bigtable, cla: yes

#6079 fix(ci): check for tty before calling tput
  ci/lib/io.sh
Labels: cla: yes

#6080 ci: add basic Cloud Build files
  ci/cloudbuild/README.md
  ci/cloudbuild/build.sh
  ci/cloudbuild/builds/README.md
  ci/cloudbuild/builds/asan.sh
  ci/cloudbuild/builds/bazel+clang.sh
  ci/cloudbuild/builds/bazel+gcc.sh
  ci/cloudbuild/builds/clang-tidy.sh
  ci/cloudbuild/builds/cmake+clang.sh
  ci/cloudbuild/builds/cmake+gcc.sh
  ci/cloudbuild/builds/ubsan.sh
  ci/cloudbuild/cloudbuild.yaml
  ci/cloudbuild/fedora.Dockerfile
Labels: cla: yes

#6084 feat(ci): add caching to GCB builds
  ci/cloudbuild/build.sh
  ci/cloudbuild/cache.sh
  ci/cloudbuild/cloudbuild.yaml
Labels: cla: yes

#6086 ci: add bazel remote caching to GCB builds
  ci/cloudbuild/builds/asan.sh
  ci/cloudbuild/builds/bazel+clang.sh
  ci/cloudbuild/builds/bazel+gcc.sh
  ci/cloudbuild/builds/lib/bazel.sh
  ci/cloudbuild/builds/ubsan.sh
  ci/cloudbuild/cloudbuild.yaml
Labels: cla: yes

#6088 ci: print ccache stats at the end of cmake builds
  ci/cloudbuild/builds/clang-tidy.sh
  ci/cloudbuild/builds/cmake+clang.sh
  ci/cloudbuild/builds/cmake+gcc.sh
  ci/cloudbuild/builds/lib/cmake.sh
Labels: cla: yes

#6090 ci: add an xsan GCB build
  .bazelrc
  ci/cloudbuild/builds/xsan.sh
Labels: cla: yes

#6089 chore: update googleapis version
  bazel/google_cloud_cpp_deps.bzl
  ci/etc/generator-googleapis-commit-hash.sh
  external/googleapis/CMakeLists.txt
  google/cloud/bigquery/bigquery_read_client.gcpcxx.pb.h
  google/cloud/iam/iam_credentials_client.gcpcxx.pb.h
  google/cloud/logging/logging_service_v2_client.gcpcxx.pb.h
Labels: cla: yes

#6092 ci: add yaml files for current triggers
  ci/cloudbuild/trigger.sh
  ci/cloudbuild/triggers/asan-ci.yaml
  ci/cloudbuild/triggers/asan.yaml
  ci/cloudbuild/triggers/clang-tidy-ci.yaml
  ci/cloudbuild/triggers/clang-tidy.yaml
  ci/cloudbuild/triggers/cmake-clang-ci.yaml
  ci/cloudbuild/triggers/cmake-clang.yaml
  ci/cloudbuild/triggers/cmake-gcc-ci.yaml
  ci/cloudbuild/triggers/cmake-gcc.yaml
  ci/cloudbuild/triggers/ubsan.yaml
  ci/cloudbuild/triggers/xsan-ci.yaml
Labels: cla: yes

#6093 refactor(storage): move MakeJWTAssertionNoThrow
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/google_cloud_cpp_storage.bzl
  google/cloud/storage/internal/make_jwt_assertion.cc
  google/cloud/storage/internal/make_jwt_assertion.h
  google/cloud/storage/internal/make_jwt_assertion_test.cc
  google/cloud/storage/oauth2/google_credentials.cc
  google/cloud/storage/oauth2/service_account_credentials.cc
  google/cloud/storage/oauth2/service_account_credentials.h
  google/cloud/storage/storage_client_unit_tests.bzl
Labels: api: storage, cla: yes

#6095 fix: pkg-config requires typo
  external/googleapis/CMakeLists.txt
Labels: cla: yes

#6097 fix: two more pkg-config requires typos
  external/googleapis/CMakeLists.txt
Labels: cla: yes

#6098 fix(bigquery): pkg-config dep for protos
  google/cloud/bigquery/CMakeLists.txt
Labels: api: bigquery, cla: yes

#6096 feat(storage): self-signed JWTs for service accounts
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/google_cloud_cpp_storage.bzl
  google/cloud/storage/internal/make_jwt_assertion_test.cc
  google/cloud/storage/internal/self_signing_service_account_credentials.cc
  google/cloud/storage/internal/self_signing_service_account_credentials.h
  google/cloud/storage/internal/self_signing_service_account_credentials_test.cc
  google/cloud/storage/oauth2/google_credentials.cc
  google/cloud/storage/storage_client_unit_tests.bzl
  google/cloud/storage/testing/constants.h
Labels: api: storage, cla: yes

#6099 ci: add cmake-install GCB build
  ci/cloudbuild/builds/cmake-install.sh
Labels: cla: yes

#6087 feature(spanner): customer-managed encryption
  ci/test-abi/google_cloud_cpp_spanner.expected.abi.dump.gz
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/database_admin_client.cc
  google/cloud/spanner/database_admin_client.h
  google/cloud/spanner/database_admin_connection.cc
  google/cloud/spanner/database_admin_connection.h
  google/cloud/spanner/database_admin_connection_test.cc
  google/cloud/spanner/encryption_config.h
  google/cloud/spanner/google_cloud_cpp_spanner.bzl
  google/cloud/spanner/integration_tests/backup_integration_test.cc
  google/cloud/spanner/integration_tests/database_admin_integration_test.cc
  google/cloud/spanner/samples/samples.cc
Labels: api: spanner, cla: yes

#6101 fix(generator): ClientContext metadata and lifetime issues for streaming rpcs
  ci/etc/generator-golden-md5-hashes.md5
  generator/integration_tests/golden/golden_kitchen_sink_connection.gcpcxx.pb.cc
  generator/integration_tests/golden/internal/golden_kitchen_sink_logging_decorator.gcpcxx.pb.cc
  generator/integration_tests/golden/internal/golden_kitchen_sink_logging_decorator.gcpcxx.pb.h
  generator/integration_tests/golden/internal/golden_kitchen_sink_metadata_decorator.gcpcxx.pb.cc
  generator/integration_tests/golden/internal/golden_kitchen_sink_metadata_decorator.gcpcxx.pb.h
  generator/integration_tests/golden/internal/golden_kitchen_sink_stub.gcpcxx.pb.cc
  generator/integration_tests/golden/internal/golden_kitchen_sink_stub.gcpcxx.pb.h
  generator/integration_tests/golden/tests/golden_kitchen_sink_connection_test.cc
  generator/integration_tests/golden/tests/golden_kitchen_sink_logging_decorator_test.cc
  generator/integration_tests/golden/tests/golden_kitchen_sink_metadata_decorator_test.cc
  generator/integration_tests/golden/tests/golden_kitchen_sink_stub_test.cc
  generator/internal/connection_generator.cc
  generator/internal/logging_decorator_generator.cc
  generator/internal/metadata_decorator_generator.cc
  generator/internal/stub_generator.cc
  google/cloud/bigquery/bigquery_read_connection.gcpcxx.pb.cc
  google/cloud/bigquery/internal/bigquery_read_logging_decorator.gcpcxx.pb.cc
  google/cloud/bigquery/internal/bigquery_read_logging_decorator.gcpcxx.pb.h
  google/cloud/bigquery/internal/bigquery_read_metadata_decorator.gcpcxx.pb.cc
  google/cloud/bigquery/internal/bigquery_read_metadata_decorator.gcpcxx.pb.h
  google/cloud/bigquery/internal/bigquery_read_stub.gcpcxx.pb.cc
  google/cloud/bigquery/internal/bigquery_read_stub.gcpcxx.pb.h
  google/cloud/internal/log_wrapper.h
Labels: cla: yes

#6100 ci: add yaml configs for cmake-install build
  ci/cloudbuild/triggers/cmake-install-ci.yaml
  ci/cloudbuild/triggers/cmake-install.yaml
Labels: cla: yes

#6102 feature(bigquery): add success case integration tests
  google/cloud/bigquery/integration_tests/bigquery_read_integration_test.cc
Labels: api: bigquery, cla: yes

#6106 ci(generator): pass GOOGLE_CLOUD_CPP_GENERATOR_CODE_PATH env var to t…
  generator/ci/run_integration_tests_emulator_bazel.sh
Labels: cla: yes

#6104 chore: building blocks for patching googleapis after download
  bazel/google_cloud_cpp_deps.bzl
  ci/kokoro/docker/Dockerfile.fedora
  ci/kokoro/docker/Dockerfile.fedora-install
  external/googleapis/CMakeLists.txt
Labels: cla: yes

#6108 refactor(ci): simplified gcb build.sh to accept --project
  ci/cloudbuild/build.sh
  ci/cloudbuild/cloudbuild.yaml
Labels: cla: yes

#6109 ci: use Cloud ID rather than unix ID
  ci/cloudbuild/build.sh
Labels: cla: yes

#6110 ci: fix typo
  ci/cloudbuild/build.sh
Labels: cla: yes

#6107 chore: add patch to Dockerfile.fedora-libcxx-msan
  ci/kokoro/docker/Dockerfile.fedora-libcxx-msan
Labels: cla: yes

#6112 ci: add integration tests to GCB
  ci/cloudbuild/builds/integration.sh
Labels: cla: yes

#6114 ci: add h1 and h2 heads to ci/lib/io.sh
  ci/cloudbuild/build.sh
  ci/cloudbuild/builds/cmake-install.sh
  ci/lib/io.sh
Labels: cla: yes

#6111 ci: garbage collect docker images in GCB
  ci/cloudbuild/cloudbuild.yaml
Labels: cla: yes

#6117 ci: use io::log_h2 in GCB integration build
  ci/cloudbuild/builds/integration.sh
Labels: cla: yes

#6118 ci: rename builds to match trigger names
  ci/cloudbuild/builds/bazel-clang.sh
  ci/cloudbuild/builds/bazel-gcc.sh
  ci/cloudbuild/builds/cmake-clang.sh
  ci/cloudbuild/builds/cmake-gcc.sh
  ci/cloudbuild/triggers/cmake-clang-ci.yaml
  ci/cloudbuild/triggers/cmake-clang.yaml
  ci/cloudbuild/triggers/cmake-gcc-ci.yaml
  ci/cloudbuild/triggers/cmake-gcc.yaml
Labels: cla: yes

#6115 feat(pubsub): schemas are no longer experimental
  ci/cloudbuild/builds/cmake-install.sh
  ci/test-abi/google_cloud_cpp_pubsub.expected.abi.dump.gz
  google/cloud/pubsub/CMakeLists.txt
  google/cloud/pubsub/google_cloud_cpp_pubsub.bzl
  google/cloud/pubsub/google_cloud_cpp_pubsub_mocks.bzl
  google/cloud/pubsub/integration_tests/schema_admin_integration_test.cc
  google/cloud/pubsub/internal/schema_metadata_test.cc
  google/cloud/pubsub/mocks/mock_schema_admin_connection.h
  google/cloud/pubsub/pubsub_client_unit_tests.bzl
  google/cloud/pubsub/samples/pubsub_samples_common.cc
  google/cloud/pubsub/samples/pubsub_samples_common.h
  google/cloud/pubsub/samples/pubsub_samples_common_test.cc
  google/cloud/pubsub/samples/samples.cc
  google/cloud/pubsub/schema.cc
  google/cloud/pubsub/schema.h
  google/cloud/pubsub/schema_admin_client.cc
  google/cloud/pubsub/schema_admin_client.h
  google/cloud/pubsub/schema_admin_client_test.cc
  google/cloud/pubsub/schema_admin_connection.cc
  google/cloud/pubsub/schema_admin_connection.h
  google/cloud/pubsub/schema_admin_connection_test.cc
  google/cloud/pubsub/schema_test.cc
  google/cloud/pubsub/topic_builder.h
  google/cloud/pubsub/topic_builder_test.cc
Labels: api: pubsub, cla: yes

#6119 ci: add --local flag to GCB build.sh
  ci/cloudbuild/build.sh
  ci/cloudbuild/cloudbuild.yaml
Labels: cla: yes

#6121 ci(gcb): distro can now be looked up from trigger file
  ci/cloudbuild/build.sh
Labels: cla: yes

#6120 feature(spanner): update CMEK samples
  google/cloud/spanner/integration_tests/backup_integration_test.cc
  google/cloud/spanner/samples/samples.cc
Labels: api: spanner, cla: yes, samples

#6122 ci(gcb): add --docker flag
  .bazelignore
  .gitignore
  ci/cloudbuild/build.sh
Labels: cla: yes

#6123 ci(gcb): print info about machine doing local build
  ci/cloudbuild/build.sh
Labels: cla: yes

#6124 ci(gcb): set TZ=:UTC; log google_time
  ci/cloudbuild/build.sh
  ci/cloudbuild/cloudbuild.yaml
Labels: cla: yes

#6116 feature(bigquery): add quickstart
  .bazelignore
  ci/etc/integration-tests-config.sh
  google/cloud/bigquery/quickstart/BUILD
  google/cloud/bigquery/quickstart/CMakeLists.txt
  google/cloud/bigquery/quickstart/Makefile
  google/cloud/bigquery/quickstart/README.md
  google/cloud/bigquery/quickstart/WORKSPACE
  google/cloud/bigquery/quickstart/quickstart.cc
Labels: api: bigquery, cla: yes

#6128 ci(gcb): add cmake-super build on ubuntu-bionic
  ci/cloudbuild/builds/cmake-super.sh
  ci/cloudbuild/triggers/cmake-super-ci.yaml
  ci/cloudbuild/triggers/cmake-super.yaml
  ci/cloudbuild/ubuntu-bionic.Dockerfile
Labels: cla: yes

#6126 chore: update googleapis version
  bazel/google_cloud_cpp_deps.bzl
  ci/etc/generator-googleapis-commit-hash.sh
  external/googleapis/CMakeLists.txt
  google/cloud/bigquery/bigquery_read_client.gcpcxx.pb.h
  google/cloud/iam/iam_credentials_client.gcpcxx.pb.h
  google/cloud/logging/logging_service_v2_client.gcpcxx.pb.h
Labels: cla: yes

#6131 doc(ci): document GCB testing principles
  ci/cloudbuild/README.md
Labels: cla: yes

#6129 chore(bigquery): enable quickstart building
  ci/kokoro/install/Dockerfile.centos-7
  ci/kokoro/install/Dockerfile.centos-8
  ci/kokoro/install/Dockerfile.debian-buster
  ci/kokoro/install/Dockerfile.debian-stretch
  ci/kokoro/install/Dockerfile.fedora
  ci/kokoro/install/Dockerfile.fedora-components
  ci/kokoro/install/Dockerfile.opensuse-leap
  ci/kokoro/install/Dockerfile.ubuntu-bionic
  ci/kokoro/install/Dockerfile.ubuntu-focal
  ci/kokoro/install/Dockerfile.ubuntu-xenial
  google/cloud/bigquery/quickstart/Makefile
  google/cloud/bigquery/quickstart/quickstart.cc
Labels: api: bigquery, cla: yes

#6132 ci(gcb): add quickstart-cmake and quickstart-bazel builds
  ci/cloudbuild/builds/lib/bazel.sh
  ci/cloudbuild/builds/quickstart-bazel.sh
  ci/cloudbuild/builds/quickstart-cmake.sh
  ci/cloudbuild/cloudbuild.yaml
  ci/cloudbuild/triggers/quickstart-bazel-ci.yaml
  ci/cloudbuild/triggers/quickstart-bazel.yaml
  ci/cloudbuild/triggers/quickstart-cmake-ci.yaml
  ci/cloudbuild/triggers/quickstart-cmake.yaml
  ci/cloudbuild/ubuntu-bionic.Dockerfile
  ci/etc/quickstart-config.sh
Labels: cla: yes

#6133 ci(gcb): adds a "checkers" build
  ci/check-style.sh
  ci/cloudbuild/builds/checkers.sh
  ci/cloudbuild/cloudbuild.yaml
  ci/cloudbuild/triggers/checkers-ci.yaml
  ci/cloudbuild/triggers/checkers.yaml
Labels: cla: yes

#6134 ci(gcb): add tsan build
  ci/cloudbuild/builds/tsan.sh
  ci/cloudbuild/triggers/tsan-ci.yaml
  ci/cloudbuild/triggers/tsan.yaml
Labels: cla: yes

#6135 ci(gcb): add builds for old clang and gcc
  ci/cloudbuild/builds/clang-38.sh
  ci/cloudbuild/builds/gcc-54.sh
  ci/cloudbuild/triggers/clang-38-ci.yaml
  ci/cloudbuild/triggers/clang-38.yaml
  ci/cloudbuild/triggers/gcc-54-ci.yaml
  ci/cloudbuild/triggers/gcc-54.yaml
  ci/cloudbuild/ubuntu-xenial.Dockerfile
Labels: cla: yes

#6138 ci: prevent flakes in Bazel builds
  ci/cloudbuild/builds/lib/bazel.sh
Labels: cla: yes

#6141 ci(gcb): enable storage integration tests
  ci/cloudbuild/builds/integration.sh
  google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh
Labels: cla: yes

#6143 ci(gcb): time the bazel prefetching
  ci/cloudbuild/builds/lib/bazel.sh
Labels: cla: yes

#6144 ci: fix typos in some comments
  ci/cloudbuild/builds/integration.sh
Labels: cla: yes

#6146 ci(gcb): write newline to stderr to match time
  ci/cloudbuild/builds/lib/bazel.sh
Labels: cla: yes

#6147 ci: fix tracing configuration for storage library
  ci/cloudbuild/builds/integration.sh
  ci/kokoro/docker/build-in-docker-bazel.sh
  ci/kokoro/macos/build-bazel.sh
  ci/kokoro/windows/build-bazel.ps1
Labels: cla: yes

#6149 doc(storage): always use signing account in examples
  ci/cloudbuild/builds/integration.sh
  google/cloud/storage/examples/storage_policy_doc_samples.cc
  google/cloud/storage/examples/storage_signed_url_v2_samples.cc
  google/cloud/storage/examples/storage_signed_url_v4_samples.cc
Labels: api: storage, cla: yes

#6150 ci(gcb): enable GCS tests that require json and p12 keyfiles
  ci/cloudbuild/builds/integration.sh
  ci/cloudbuild/fedora.Dockerfile
Labels: cla: yes
