Repository googleapis/google-cloud-cpp, pull requests merged in 2021-08, with the labels that each got.

#7095 cleanup(bigtable): update MutationBatcher defaults
  google/cloud/bigtable/mutation_batcher.cc
  google/cloud/bigtable/mutation_batcher_test.cc
Labels: api: bigtable, cla: yes

#7096 test(storage): missing separators in benchmark output
  google/cloud/storage/benchmarks/aggregate_throughput_benchmark.cc
Labels: api: storage, cla: yes

#7099 ci(check-api): add IAM and BigQuery to check-api build
  ci/abi-dumps/google_cloud_cpp_bigquery.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_bigtable.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_common.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_grpc_utils.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_iam.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_pubsub.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_spanner.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_storage.expected.abi.dump.gz
  ci/cloudbuild/builds/check-api.sh
Labels: cla: yes

#7098 ci(check-api): use abi-dumper w/ integer overflow fix
  ci/abi-dumps/google_cloud_cpp_bigquery.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_bigtable.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_common.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_grpc_utils.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_iam.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_pubsub.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_spanner.expected.abi.dump.gz
  ci/abi-dumps/google_cloud_cpp_storage.expected.abi.dump.gz
  ci/cloudbuild/dockerfiles/fedora-34.Dockerfile
Labels: cla: yes

#7100 chore(release): update changelog for 2021-08 release
  CHANGELOG.md
Labels: cla: yes

#7105 chore(release): update release instructions
  release/README.md
Labels: cla: yes

#7104 chore: bump version to 1.31 following the Aug release
  CMakeLists.txt
  google/cloud/bigquery/quickstart/WORKSPACE
  google/cloud/bigtable/quickstart/WORKSPACE
  google/cloud/iam/quickstart/WORKSPACE
  google/cloud/internal/version_info.h
  google/cloud/pubsub/quickstart/WORKSPACE
  google/cloud/spanner/quickstart/WORKSPACE
  google/cloud/storage/quickstart/WORKSPACE
  google/cloud/storage/quickstart/grpc/WORKSPACE
Labels: cla: yes

#7102 chore: add release/changes.sh to help automate release CHANGELOG creation
  release/README.md
  release/changes.sh
Labels: cla: yes

#7107 chore: enable pipefail option in all bash scripts
  ci/cloudbuild/builds/asan.sh
  ci/cloudbuild/builds/bazel-targets.sh
  ci/cloudbuild/builds/check-api.sh
  ci/cloudbuild/builds/checkers.sh
  ci/cloudbuild/builds/clang-60.sh
  ci/cloudbuild/builds/clang-tidy.sh
  ci/cloudbuild/builds/cmake-install.sh
  ci/cloudbuild/builds/cmake-oldest-deps.sh
  ci/cloudbuild/builds/coverage.sh
  ci/cloudbuild/builds/cxx17.sh
  ci/cloudbuild/builds/demo-install.sh
  ci/cloudbuild/builds/gcc-54.sh
  ci/cloudbuild/builds/gcs-grpc.sh
  ci/cloudbuild/builds/generate-libraries.sh
  ci/cloudbuild/builds/install-gcs-grpc.sh
  ci/cloudbuild/builds/integration-daily.sh
  ci/cloudbuild/builds/libcxx.sh
  ci/cloudbuild/builds/log-linker.sh
  ci/cloudbuild/builds/msan.sh
  ci/cloudbuild/builds/noex.sh
  ci/cloudbuild/builds/publish-docs.sh
  ci/cloudbuild/builds/quickstart-bazel.sh
  ci/cloudbuild/builds/quickstart-cmake.sh
  ci/cloudbuild/builds/rotate-keys.sh
  ci/cloudbuild/builds/scan-build.sh
  ci/cloudbuild/builds/shared.sh
  ci/cloudbuild/builds/tsan.sh
  ci/cloudbuild/builds/ubsan.sh
  ci/cloudbuild/builds/xsan.sh
  ci/coverity-scan.sh
  ci/etc/repo-config.sh
  ci/generate-markdown/dockerfile2markdown.sh
  ci/generate-markdown/generate-bigquery-readme.sh
  ci/generate-markdown/generate-bigtable-readme.sh
  ci/generate-markdown/generate-iam-readme.sh
  ci/generate-markdown/generate-packaging.sh
  ci/generate-markdown/generate-pubsub-readme.sh
  ci/generate-markdown/generate-readme.sh
  ci/generate-markdown/generate-spanner-readme.sh
  ci/generate-markdown/generate-storage-readme.sh
  ci/install-cloud-sdk.sh
  ci/kokoro/macos/build.sh
  ci/kokoro/macos/builds/bazel.sh
  ci/kokoro/macos/builds/cmake-vcpkg.sh
  ci/kokoro/macos/builds/quickstart-bazel.sh
  ci/kokoro/macos/builds/quickstart-cmake.sh
  ci/kokoro/macos/download-cache.sh
  ci/kokoro/macos/upload-cache.sh
  ci/retry-command.sh
  google/cloud/bigtable/ci/run_integration_tests_emulator_bazel.sh
  google/cloud/bigtable/ci/run_integration_tests_emulator_cmake.sh
  google/cloud/bigtable/tools/run_emulator_utils.sh
  google/cloud/pubsub/ci/run_integration_tests_emulator_bazel.sh
  google/cloud/pubsub/ci/run_integration_tests_emulator_cmake.sh
  google/cloud/spanner/ci/run_integration_tests_emulator_bazel.sh
  google/cloud/spanner/ci/run_integration_tests_emulator_cmake.sh
  google/cloud/storage/ci/run_integration_tests_emulator_bazel.sh
  google/cloud/storage/ci/run_integration_tests_emulator_cmake.sh
  google/cloud/storage/emulator/ci/run_integration_tests_bazel.sh
  release/release.sh
Labels: cla: yes

#7110 ci: remove unneeded gfile resource
  ci/kokoro/windows/common.cfg
Labels: cla: yes

#7108 feat(GCS+gRPC): initial support for download timeouts
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/internal/grpc_client.cc
  google/cloud/storage/internal/grpc_client.h
  google/cloud/storage/internal/grpc_client_read_object_test.cc
  google/cloud/storage/storage_client_grpc_unit_tests.bzl
  google/cloud/storage/testing/mock_storage_stub.h
Labels: cla: yes

#7111 chore(docs): remove reference to GCR for kokoro
  ci/kokoro/README.md
Labels: cla: yes

#7112 feat(GCS+gRPC): timeout downloads in benchmark
  google/cloud/storage/benchmarks/aggregate_throughput_benchmark.cc
  google/cloud/storage/benchmarks/aggregate_throughput_options.cc
  google/cloud/storage/benchmarks/aggregate_throughput_options.h
  google/cloud/storage/benchmarks/aggregate_throughput_options_test.cc
Labels: cla: yes

#7113 feat(storage): make benchmark more robust on stalls
  google/cloud/storage/benchmarks/aggregate_throughput_benchmark.cc
Labels: api: storage, cla: yes

#7114 ci(kokoro): remove GCS P12 keyfile test from mac+win
  ci/kokoro/macos/builds/bazel.sh
  ci/kokoro/macos/builds/cmake-vcpkg.sh
  ci/kokoro/macos/common.cfg
  ci/kokoro/windows/build-bazel.ps1
  ci/kokoro/windows/build-cmake.ps1
  ci/kokoro/windows/build-quickstart-bazel.ps1
  ci/kokoro/windows/build-quickstart-cmake.ps1
  ci/kokoro/windows/common.cfg
  google/cloud/storage/tests/key_file_integration_test.cc
  google/cloud/storage/tests/object_insert_integration_test.cc
Labels: cla: yes

#7117 cleanup: fix too many backticks for clode block
  ci/generate-markdown/generate-spanner-readme.sh
  ci/generate-markdown/generate-storage-readme.sh
  google/cloud/spanner/README.md
  google/cloud/storage/README.md
Labels: cla: yes

#7116 ci(checkers): trim trailing blank lines from text files
  .codecov.yml
  .github/ISSUE_TEMPLATE/internal-cleanup.md
  ci/cloudbuild/builds/checkers.sh
  ci/generate-markdown/generate-bigquery-readme.sh
  ci/generate-markdown/generate-bigtable-readme.sh
  ci/generate-markdown/generate-iam-readme.sh
  ci/generate-markdown/generate-pubsub-readme.sh
  ci/generate-markdown/generate-spanner-readme.sh
  ci/generate-markdown/generate-storage-readme.sh
  doc/adr/2018-06-13-storage-always-retries.md
  doc/adr/2019-01-04-error-reporting-with-statusor.md
  doc/adr/adr-template.md
  generator/integration_tests/golden/golden_kitchen_sink_client.cc
  generator/integration_tests/golden/golden_kitchen_sink_connection.cc
  generator/integration_tests/golden/golden_kitchen_sink_connection_idempotency_policy.cc
  generator/integration_tests/golden/golden_thing_admin_client.cc
  generator/integration_tests/golden/golden_thing_admin_connection.cc
  generator/integration_tests/golden/golden_thing_admin_connection_idempotency_policy.cc
  generator/integration_tests/golden/internal/golden_kitchen_sink_auth_decorator.cc
  generator/integration_tests/golden/internal/golden_kitchen_sink_logging_decorator.cc
  generator/integration_tests/golden/internal/golden_kitchen_sink_metadata_decorator.cc
  generator/integration_tests/golden/internal/golden_kitchen_sink_option_defaults.cc
  generator/integration_tests/golden/internal/golden_kitchen_sink_stub.cc
  generator/integration_tests/golden/internal/golden_kitchen_sink_stub_factory.cc
  generator/integration_tests/golden/internal/golden_thing_admin_auth_decorator.cc
  generator/integration_tests/golden/internal/golden_thing_admin_logging_decorator.cc
  generator/integration_tests/golden/internal/golden_thing_admin_metadata_decorator.cc
  generator/integration_tests/golden/internal/golden_thing_admin_option_defaults.cc
  generator/integration_tests/golden/internal/golden_thing_admin_stub.cc
  generator/integration_tests/golden/internal/golden_thing_admin_stub_factory.cc
  generator/internal/connection_generator.cc
  generator/internal/service_code_generator.cc
  google/cloud/bigquery/README.md
  google/cloud/bigtable/README.md
  google/cloud/iam/README.md
  google/cloud/pubsub/README.md
  google/cloud/spanner/README.md
  google/cloud/storage/README.md
Labels: cla: yes

#7118 fix(spanner): fix Client::OverlayQueryOptions() to merge correctly
  google/cloud/spanner/client.cc
  google/cloud/spanner/client.h
  google/cloud/spanner/client_test.cc
  google/cloud/spanner/doc/spanner-main.dox
  google/cloud/spanner/query_options.h
Labels: cla: yes, api: spanner

#7119 feat(common): capture thread that creates log record
  google/cloud/internal/log_impl_test.cc
  google/cloud/log.cc
  google/cloud/log.h
  google/cloud/log_test.cc
Labels: cla: yes

#7121 chore: simplify release.sh version increment
  release/release.sh
Labels: cla: yes

#7120 chore: update vcpkg commit hash for version containing v1.30.0
  ci/cloudbuild/builds/lib/vcpkg.sh
Labels: cla: yes

#7123 cleanup(storage): reduce logging in normal case
  google/cloud/storage/internal/retry_object_read_source.cc
Labels: cla: yes, api: storage

#7122 test(storage): better logging in benchmark
  google/cloud/storage/benchmarks/aggregate_throughput_benchmark.cc
Labels: cla: yes, api: storage

#7125 test(spanner): generalize ConnectionImplTest.QueryOptions
  google/cloud/spanner/internal/connection_impl_test.cc
Labels: cla: yes, api: spanner

#7115 feature(generator): support adding include directives for certain well known protobuf types
  generator/integration_tests/golden/golden_kitchen_sink_client.h
  generator/internal/client_generator.cc
  generator/internal/service_code_generator.cc
  generator/internal/service_code_generator.h
  generator/internal/service_code_generator_test.cc
  google/cloud/iam/iam_credentials_client.h
Labels: cla: yes

#7131 chore(generator): use single quotes in StrSplit calls
  generator/internal/codegen_utils.cc
  generator/internal/descriptor_utils.cc
  generator/internal/service_code_generator.cc
Labels: cla: yes

#7128 fix(GCS+gRPC): return status on stream closure
  google/cloud/storage/internal/grpc_object_read_source.cc
  google/cloud/storage/internal/grpc_object_read_source_test.cc
Labels: cla: yes

#7134 refactor(stream_range): remove unnecessary noexcept spec
  google/cloud/stream_range.h
Labels: cla: yes

#7136 fix(storage): release handles for oauth2 refresh
  google/cloud/storage/oauth2/authorized_user_credentials.h
  google/cloud/storage/oauth2/authorized_user_credentials_test.cc
  google/cloud/storage/oauth2/service_account_credentials.h
  google/cloud/storage/oauth2/service_account_credentials_test.cc
Labels: cla: yes, api: storage

#7132 refactor(statusor): use absl::optional rather than union
  google/cloud/status_or.h
Labels: cla: yes

#7137 refactor(storage): isolate header parsing to REST
  google/cloud/storage/CMakeLists.txt
  google/cloud/storage/internal/curl_download_request.cc
  google/cloud/storage/internal/curl_download_request.h
  google/cloud/storage/internal/curl_download_request_test.cc
  google/cloud/storage/internal/grpc_object_read_source.cc
  google/cloud/storage/internal/grpc_object_read_source.h
  google/cloud/storage/internal/grpc_object_read_source_test.cc
  google/cloud/storage/internal/hash_validator.h
  google/cloud/storage/internal/hash_validator_impl.cc
  google/cloud/storage/internal/hash_validator_impl.h
  google/cloud/storage/internal/hash_validator_test.cc
  google/cloud/storage/internal/object_read_source.h
  google/cloud/storage/internal/object_read_streambuf.cc
  google/cloud/storage/internal/retry_object_read_source.cc
  google/cloud/storage/internal/retry_object_read_source_test.cc
  google/cloud/storage/storage_client_unit_tests.bzl
  google/cloud/storage/tests/curl_download_request_integration_test.cc
  google/cloud/storage/tests/object_read_headers_integration_test.cc
Labels: cla: yes, api: storage

#7138 cleanup(noexcept): remove noexcept from defaulted functions
  generator/integration_tests/golden/golden_kitchen_sink_client.h
  generator/integration_tests/golden/golden_thing_admin_client.h
  generator/internal/client_generator.cc
  google/cloud/bigquery/bigquery_read_client.h
  google/cloud/bigtable/column_family.h
  google/cloud/bigtable/filters.h
  google/cloud/bigtable/internal/async_longrunning_op.h
  google/cloud/bigtable/metadata_update_policy.h
  google/cloud/bigtable/read_modify_write_rule.h
  google/cloud/bigtable/row_range.h
  google/cloud/bigtable/row_reader.h
  google/cloud/bigtable/row_set.h
  google/cloud/future_generic.h
  google/cloud/future_void.h
  google/cloud/iam/iam_client.h
  google/cloud/iam/iam_credentials_client.h
  google/cloud/internal/filesystem.h
  google/cloud/internal/future_base.h
  google/cloud/logging/logging_service_v2_client.h
  google/cloud/pubsub/ack_handler.h
  google/cloud/pubsub/publisher.h
  google/cloud/storage/internal/object_read_streambuf.h
  google/cloud/storage/internal/object_write_streambuf.h
Labels: cla: yes

#7130 doc(doxygen): fix typo in storage-mocking.dox: ueeful -> useful
  google/cloud/storage/doc/storage-mocking.dox
Labels: cla: yes

#7139 refactor(build.sh): make build.sh --docker the default
  ci/cloudbuild/build.sh
  ci/cloudbuild/cloudbuild.yaml
Labels: cla: yes

#7140 feat(spanner): send session-refresh request at low priority
  google/cloud/spanner/internal/session_pool.cc
Labels: cla: yes, api: spanner

#7141 test(spanner): extend and generalize ConnectionImplTest.QueryOptions
  google/cloud/spanner/internal/connection_impl_test.cc
Labels: cla: yes, api: spanner

#7147 fix(GCS+gRPC): quickstart build with Bazel+Windows
  google/cloud/storage/BUILD
  google/cloud/storage/quickstart/grpc/BUILD
Labels: cla: yes

#7149 doc: correct minimum MSVC version
  README.md
  ci/generate-markdown/generate-bigquery-readme.sh
  ci/generate-markdown/generate-bigtable-readme.sh
  ci/generate-markdown/generate-iam-readme.sh
  ci/generate-markdown/generate-pubsub-readme.sh
  ci/generate-markdown/generate-readme.sh
  ci/generate-markdown/generate-spanner-readme.sh
  ci/generate-markdown/generate-storage-readme.sh
  google/cloud/README.md
  google/cloud/bigquery/README.md
  google/cloud/bigtable/README.md
  google/cloud/iam/README.md
  google/cloud/pubsub/README.md
  google/cloud/spanner/README.md
  google/cloud/storage/README.md
Labels: cla: yes

#7148 test(spanner): configurable leader placement support
  google/cloud/spanner/integration_tests/client_integration_test.cc
  google/cloud/spanner/samples/samples.cc
Labels: cla: yes, api: spanner

#7150 fix(statusor)!: remove status() accessor returning non-const lvalue
  CHANGELOG.md
  google/cloud/bigtable/benchmarks/read_sync_vs_async_benchmark.cc
  google/cloud/spanner/internal/connection_impl_test.cc
  google/cloud/status_or.h
Labels: cla: yes

#7135 chore: back port CI changes
  ci/kokoro/macos/builds/bazel.sh
  ci/kokoro/macos/builds/cmake-vcpkg.sh
  ci/kokoro/macos/common.cfg
  ci/kokoro/windows/build-bazel.ps1
  ci/kokoro/windows/build-cmake.ps1
  ci/kokoro/windows/build-quickstart-bazel.ps1
  ci/kokoro/windows/build-quickstart-cmake.ps1
  ci/kokoro/windows/common.cfg
  google/cloud/iam/CMakeLists.txt
  google/cloud/storage/tests/key_file_integration_test.cc
  google/cloud/storage/tests/object_insert_integration_test.cc
Labels: cla: yes

#7151 fix: experimental bigquery iam cmake target installation
  google/cloud/bigquery/CMakeLists.txt
  google/cloud/bigquery/config.cmake.in
  google/cloud/iam/CMakeLists.txt
  google/cloud/iam/config.cmake.in
Labels: cla: yes

#7152 chore: update CHANGELOG and set version for v1.30.1 release
  CHANGELOG.md
  CMakeLists.txt
  google/cloud/internal/version_info.h
Labels: cla: yes

#7143 doc: make GCS+gRPC quickstart easier to find
  ci/cloudbuild/builds/lib/quickstart.sh
  ci/kokoro/windows/build-quickstart-bazel.ps1
  google/cloud/storage/doc/storage-grpc.dox
  google/cloud/storage/doc/storage-main.dox
  google/cloud/storage/examples/storage_grpc_samples.cc
  google/cloud/storage/grpc_plugin.h
  google/cloud/storage/quickstart/.bazelignore
  google/cloud/storage/quickstart/BUILD
  google/cloud/storage/quickstart/CMakeLists.txt
  google/cloud/storage/quickstart/Makefile
  google/cloud/storage/quickstart/grpc/BUILD
  google/cloud/storage/quickstart/grpc/CMakeLists.txt
  google/cloud/storage/quickstart/grpc/Makefile
  google/cloud/storage/quickstart/grpc/WORKSPACE
  google/cloud/storage/quickstart/quickstart_grpc.cc
Labels: cla: yes

#7157 ci: compile and run BigQuery quickstart on Windows
  ci/kokoro/windows/build-quickstart-bazel.ps1
Labels: cla: yes

#7159 doc: update quickstart Makefiles
  google/cloud/bigtable/quickstart/Makefile
  google/cloud/pubsub/quickstart/Makefile
  google/cloud/spanner/quickstart/Makefile
  google/cloud/storage/quickstart/Makefile
Labels: cla: yes

#7160 chore: update main with v1.30.1 changes
  CHANGELOG.md
  google/cloud/bigquery/CMakeLists.txt
  google/cloud/bigquery/config.cmake.in
  google/cloud/iam/CMakeLists.txt
  google/cloud/iam/config.cmake.in
Labels: cla: yes

#7162 test(pubsub): deflake default batching publisher test
  google/cloud/pubsub/internal/batching_publisher_connection_test.cc
Labels: cla: yes, api: pubsub

#7164 cleanup: remove references to super builds from ci, docs
  README.md
  ci/generate-markdown/generate-readme.sh
  ci/kokoro/macos/builds/cmake-vcpkg.sh
  doc/contributor/howto-guide-setup-development-workstation.md
Labels: cla: yes

#7163 cleanup: fix west const to east const
  generator/generator_test.cc
  generator/integration_tests/golden/tests/golden_kitchen_sink_stub_test.cc
  generator/integration_tests/golden/tests/golden_thing_admin_stub_test.cc
  generator/internal/descriptor_utils.cc
  generator/internal/descriptor_utils_test.cc
  generator/internal/predicate_utils_test.cc
  generator/internal/service_code_generator.cc
  generator/internal/service_code_generator_test.cc
  google/cloud/firestore/field_path.h
  google/cloud/internal/async_rpc_details.h
  google/cloud/pubsub/internal/session_shutdown_manager.cc
  google/cloud/spanner/instance_admin_connection_test.cc
  google/cloud/spanner/internal/partial_result_set_source_test.cc
  google/cloud/spanner/row_test.cc
  google/cloud/spanner/sql_statement_test.cc
  google/cloud/spanner/value.cc
  google/cloud/storage/examples/storage_bucket_acl_samples.cc
  google/cloud/storage/examples/storage_object_acl_samples.cc
  google/cloud/storage/internal/curl_handle_factory_test.cc
  google/cloud/storage/internal/grpc_client.cc
  google/cloud/storage/internal/object_read_streambuf.cc
  google/cloud/terminate_handler.cc
  google/cloud/terminate_handler.h
  google/cloud/terminate_handler_test.cc
Labels: cla: yes

#7165 test(spanner): update spanner_set_transaction_tag sample
  google/cloud/spanner/samples/samples.cc
Labels: cla: yes, api: spanner, samples

#7169 doc: require an explicit flag to enable Doxygen
  CMakeLists.txt
  ci/cloudbuild/builds/publish-docs.sh
  cmake/GoogleCloudCppCommon.cmake
Labels: cla: yes

#7173 cleanup: remove unneeded NOLINT since clang-tidy upgrade
  google/cloud/bigtable/async_row_reader.h
  google/cloud/bigtable/cell.h
  google/cloud/bigtable/instance_admin.h
  google/cloud/bigtable/internal/async_poll_op.h
  google/cloud/bigtable/internal/async_retry_multi_page.h
  google/cloud/bigtable/internal/async_retry_unary_rpc_and_poll.h
  google/cloud/bigtable/table.h
  google/cloud/bigtable/table_admin.h
  google/cloud/connection_options.h
  google/cloud/future_generic.h
  google/cloud/internal/async_read_stream_impl.h
  google/cloud/internal/async_retry_unary_rpc.h
  google/cloud/internal/future_impl.h
  google/cloud/storage/internal/bucket_acl_requests.h
  google/cloud/storage/internal/common_metadata.h
  google/cloud/storage/internal/default_object_acl_requests.h
  google/cloud/storage/internal/generic_object_request.h
  google/cloud/storage/internal/object_acl_requests.h
  google/cloud/storage/oauth2/service_account_credentials.h
Labels: cla: yes

#7178 typo: hositng -> hosting
  CMakeLists.txt
Labels: cla: yes

#7177 ci: add Debian:11 (Bullseye) build files
  ci/cloudbuild/dockerfiles/demo-debian-bullseye.Dockerfile
  ci/cloudbuild/triggers/demo-debian-bullseye-ci.yaml
  ci/cloudbuild/triggers/demo-debian-bullseye-pr.yaml
  ci/generate-markdown/generate-packaging.sh
  doc/packaging.md
Labels: cla: yes

#7176 cleanup(GCS+gRPC): configure via GOOGLE_CLOUD_CPP_ENABLE
  CMakeLists.txt
  google/cloud/storage/CMakeLists.txt
Labels: cla: yes

#7180 test(storage): deflake integration tests
  google/cloud/storage/tests/object_plenty_clients_serially_integration_test.cc
  google/cloud/storage/tests/object_plenty_clients_simultaneously_integration_test.cc
Labels: cla: yes, api: storage

#7181 cleanup: scope GOOGLE_CLOUD_CPP_ENABLE uses
  CMakeLists.txt
Labels: cla: yes

#7174 chore: update vcpkg hash to version that includes v1.30.1
  ci/cloudbuild/builds/lib/vcpkg.sh
  ci/kokoro/macos/builds/cmake-vcpkg.sh
  ci/kokoro/windows/build-cmake-dependencies.ps1
Labels: cla: yes

#7109 chore: remove experimental bigquery and iam targets
  BUILD
  README.md
  ci/generate-markdown/generate-readme.sh
  ci/kokoro/macos/builds/quickstart-cmake.sh
  ci/verify_current_targets/CMakeLists.txt
  google/cloud/bigquery/CMakeLists.txt
  google/cloud/bigquery/config.cmake.in
  google/cloud/bigquery/quickstart/BUILD
  google/cloud/bigquery/quickstart/CMakeLists.txt
  google/cloud/iam/CMakeLists.txt
  google/cloud/iam/config.cmake.in
  google/cloud/iam/quickstart/BUILD
  google/cloud/iam/quickstart/CMakeLists.txt
Labels: cla: yes

#7182 refactor(storage): rename aggregate throughput bm
  google/cloud/storage/benchmarks/CMakeLists.txt
  google/cloud/storage/benchmarks/aggregate_download_throughput_benchmark.cc
  google/cloud/storage/benchmarks/aggregate_download_throughput_options.cc
  google/cloud/storage/benchmarks/aggregate_download_throughput_options.h
  google/cloud/storage/benchmarks/aggregate_download_throughput_options_test.cc
  google/cloud/storage/benchmarks/storage_benchmark_programs.bzl
  google/cloud/storage/benchmarks/storage_benchmarks.bzl
  google/cloud/storage/benchmarks/storage_benchmarks_unit_tests.bzl
Labels: cla: yes, api: storage

#7183 feat(spanner): add generated admin APIs
  generator/generator_config.textproto
Labels: cla: yes, api: spanner

#7184 feat(spanner): add generated admin APIs
  ci/cloudbuild/builds/generate-libraries.sh
  google/cloud/spanner/admin/database_admin_client.cc
  google/cloud/spanner/admin/database_admin_client.h
  google/cloud/spanner/admin/database_admin_connection.cc
  google/cloud/spanner/admin/database_admin_connection.h
  google/cloud/spanner/admin/database_admin_connection_idempotency_policy.cc
  google/cloud/spanner/admin/database_admin_connection_idempotency_policy.h
  google/cloud/spanner/admin/database_admin_options.h
  google/cloud/spanner/admin/instance_admin_client.cc
  google/cloud/spanner/admin/instance_admin_client.h
  google/cloud/spanner/admin/instance_admin_connection.cc
  google/cloud/spanner/admin/instance_admin_connection.h
  google/cloud/spanner/admin/instance_admin_connection_idempotency_policy.cc
  google/cloud/spanner/admin/instance_admin_connection_idempotency_policy.h
  google/cloud/spanner/admin/instance_admin_options.h
  google/cloud/spanner/admin/internal/database_admin_auth_decorator.cc
  google/cloud/spanner/admin/internal/database_admin_auth_decorator.h
  google/cloud/spanner/admin/internal/database_admin_logging_decorator.cc
  google/cloud/spanner/admin/internal/database_admin_logging_decorator.h
  google/cloud/spanner/admin/internal/database_admin_metadata_decorator.cc
  google/cloud/spanner/admin/internal/database_admin_metadata_decorator.h
  google/cloud/spanner/admin/internal/database_admin_option_defaults.cc
  google/cloud/spanner/admin/internal/database_admin_option_defaults.h
  google/cloud/spanner/admin/internal/database_admin_stub.cc
  google/cloud/spanner/admin/internal/database_admin_stub.h
  google/cloud/spanner/admin/internal/database_admin_stub_factory.cc
  google/cloud/spanner/admin/internal/database_admin_stub_factory.h
  google/cloud/spanner/admin/internal/instance_admin_auth_decorator.cc
  google/cloud/spanner/admin/internal/instance_admin_auth_decorator.h
  google/cloud/spanner/admin/internal/instance_admin_logging_decorator.cc
  google/cloud/spanner/admin/internal/instance_admin_logging_decorator.h
  google/cloud/spanner/admin/internal/instance_admin_metadata_decorator.cc
  google/cloud/spanner/admin/internal/instance_admin_metadata_decorator.h
  google/cloud/spanner/admin/internal/instance_admin_option_defaults.cc
  google/cloud/spanner/admin/internal/instance_admin_option_defaults.h
  google/cloud/spanner/admin/internal/instance_admin_stub.cc
  google/cloud/spanner/admin/internal/instance_admin_stub.h
  google/cloud/spanner/admin/internal/instance_admin_stub_factory.cc
  google/cloud/spanner/admin/internal/instance_admin_stub_factory.h
  google/cloud/spanner/admin/mocks/mock_database_admin_connection.h
  google/cloud/spanner/admin/mocks/mock_instance_admin_connection.h
  google/cloud/spanner/admin/retry_traits.h
Labels: cla: yes, api: spanner

#7189 doc: fix nits in developer guide
  doc/contributor/howto-guide-forks-and-pull-requests.md
Labels: cla: yes

#7188 feat(spanner): add generated admin APIs
  ci/cloudbuild/builds/cmake-install.sh
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/google_cloud_cpp_spanner.bzl
  google/cloud/spanner/google_cloud_cpp_spanner_mocks.bzl
Labels: cla: yes, api: spanner

#7190 feat(storage): aggregate upload benchmark
  google/cloud/storage/benchmarks/CMakeLists.txt
  google/cloud/storage/benchmarks/aggregate_download_throughput_benchmark.cc
  google/cloud/storage/benchmarks/aggregate_upload_throughput_benchmark.cc
  google/cloud/storage/benchmarks/aggregate_upload_throughput_options.cc
  google/cloud/storage/benchmarks/aggregate_upload_throughput_options.h
  google/cloud/storage/benchmarks/aggregate_upload_throughput_options_test.cc
  google/cloud/storage/benchmarks/benchmark_utils.h
  google/cloud/storage/benchmarks/storage_benchmark_programs.bzl
  google/cloud/storage/benchmarks/storage_benchmarks.bzl
  google/cloud/storage/benchmarks/storage_benchmarks_unit_tests.bzl
Labels: cla: yes, api: storage

#7193 chore: update googleapis protos to circa 2021-08-19
  bazel/google_cloud_cpp_deps.bzl
  external/googleapis/CMakeLists.txt
  google/cloud/bigquery/bigquery_read_client.h
  google/cloud/iam/iam_client.h
  google/cloud/iam/iam_credentials_client.h
  google/cloud/logging/logging_service_v2_client.h
  google/cloud/spanner/admin/database_admin_client.h
  google/cloud/spanner/admin/instance_admin_client.h
Labels: cla: yes

#7195 test(spanner): extend timeouts for "slow" database operations
  ci/cloudbuild/builds/integration-daily.sh
  google/cloud/spanner/testing/policies.h
Labels: cla: yes, api: spanner

#7194 feat(common): add GrpcChannelArgumentsNativeOption
  google/cloud/grpc_options.cc
  google/cloud/grpc_options.h
  google/cloud/grpc_options_test.cc
Labels: cla: yes

#7196 feat(pusub): support Topic retention duration
  google/cloud/internal/time_utils.h
  google/cloud/pubsub/subscription_builder.h
  google/cloud/pubsub/topic_builder.h
  google/cloud/pubsub/topic_builder_test.cc
Labels: cla: yes

#7201 cleanup: checkers
  google/cloud/storage/client.cc
  google/cloud/storage/lifecycle_rule.cc
Labels: cla: yes

#7199 refactor: move gRPC Channel Argument helpers to common
  google/cloud/bigtable/client_options_test.cc
  google/cloud/grpc_options.cc
  google/cloud/grpc_options.h
  google/cloud/grpc_options_test.cc
Labels: cla: yes

#7200 feat(generator): customization hooks for endpoint configuration
  generator/generator.h
  generator/generator_config.proto
  generator/generator_config.textproto
  generator/integration_tests/generator_integration_test.cc
  generator/integration_tests/golden/internal/golden_kitchen_sink_option_defaults.cc
  generator/integration_tests/golden/internal/golden_thing_admin_option_defaults.cc
  generator/integration_tests/golden/tests/golden_kitchen_sink_option_defaults_test.cc
  generator/integration_tests/golden/tests/golden_thing_admin_option_defaults_test.cc
  generator/internal/codegen_utils.cc
  generator/internal/codegen_utils_test.cc
  generator/internal/descriptor_utils.cc
  generator/internal/option_defaults_generator.cc
  generator/standalone_main.cc
  google/cloud/spanner/admin/internal/database_admin_option_defaults.cc
  google/cloud/spanner/admin/internal/instance_admin_option_defaults.cc
Labels: cla: yes

#7204 cleanup: define inline ns to be GOOGLE_CLOUD_CPP_NS
  google/cloud/bigtable/version.h
  google/cloud/pubsub/version.h
  google/cloud/spanner/version.h
  google/cloud/storage/version.h
Labels: cla: yes

#7205 test(bigtable): cleanup bigtable ClientOptions unit test
  google/cloud/bigtable/client_options_test.cc
Labels: cla: yes, api: bigtable

#7206 refactor(bigtable): replace grpc::ChannelArguments with Options
  google/cloud/bigtable/client_options.cc
  google/cloud/bigtable/client_options.h
  google/cloud/bigtable/client_options_test.cc
  google/cloud/bigtable/internal/defaults.cc
Labels: cla: yes, api: bigtable

#7209 refactor(bigtable): use OptionDescriptor for benchmarks
  google/cloud/bigtable/benchmarks/CMakeLists.txt
  google/cloud/bigtable/benchmarks/apply_read_latency_benchmark.cc
  google/cloud/bigtable/benchmarks/benchmark.cc
  google/cloud/bigtable/benchmarks/benchmark.h
  google/cloud/bigtable/benchmarks/benchmark_options.cc
  google/cloud/bigtable/benchmarks/benchmark_options.h
  google/cloud/bigtable/benchmarks/benchmark_options_test.cc
  google/cloud/bigtable/benchmarks/bigtable_benchmark_common.bzl
  google/cloud/bigtable/benchmarks/bigtable_benchmark_test.cc
  google/cloud/bigtable/benchmarks/bigtable_benchmarks_unit_tests.bzl
  google/cloud/bigtable/benchmarks/constants.h
  google/cloud/bigtable/benchmarks/embedded_server.cc
  google/cloud/bigtable/benchmarks/endurance_benchmark.cc
  google/cloud/bigtable/benchmarks/read_sync_vs_async_benchmark.cc
  google/cloud/bigtable/benchmarks/scan_throughput_benchmark.cc
  google/cloud/bigtable/benchmarks/setup.cc
  google/cloud/bigtable/benchmarks/setup.h
  google/cloud/bigtable/benchmarks/setup_test.cc
Labels: cla: yes

#7213 cleanup(bigtable): make filter samples consistent with Python samples
  google/cloud/bigtable/examples/data_filter_snippets.cc
Labels: cla: yes, api: bigtable, samples

#7212 feat(spanner): support for JSON as a column type
  google/cloud/spanner/CMakeLists.txt
  google/cloud/spanner/google_cloud_cpp_spanner.bzl
  google/cloud/spanner/integration_tests/data_types_integration_test.cc
  google/cloud/spanner/integration_tests/database_admin_integration_test.cc
  google/cloud/spanner/json.h
  google/cloud/spanner/json_test.cc
  google/cloud/spanner/samples/samples.cc
  google/cloud/spanner/spanner_client_unit_tests.bzl
  google/cloud/spanner/testing/database_integration_test.cc
  google/cloud/spanner/value.cc
  google/cloud/spanner/value.h
  google/cloud/spanner/value_test.cc
Labels: cla: yes, api: spanner

#7210 docs: add instructions on generating compile_commands.json
  doc/contributor/howto-guide-setup-development-workstation.md
Labels: cla: yes

#7237 fix(bigtable): ensure connection refresh period is valid
  google/cloud/bigtable/internal/defaults.cc
  google/cloud/bigtable/internal/defaults_test.cc
  google/cloud/bigtable/options.h
Labels: cla: yes, api: bigtable

#7236 doc: fix some comments that were wrong
  google/cloud/spanner/results.h
  google/cloud/stream_range.h
Labels: cla: yes

#7240 chore(ci): put vcpkg release version in own config file
  ci/cloudbuild/builds/lib/vcpkg.sh
  ci/etc/vcpkg-config.ps1
  ci/etc/vcpkg-config.sh
  ci/kokoro/macos/builds/cmake-vcpkg.sh
  ci/kokoro/macos/builds/quickstart-cmake.sh
  ci/kokoro/windows/build-cmake-dependencies.ps1
Labels: cla: yes

#7243 cleanup: remove storage/v2 generated files
  ci/cloudbuild/builds/checkers.sh
  google/cloud/storage/emulator/google/iam/v1/iam_policy_pb2.py
  google/cloud/storage/emulator/google/iam/v1/iam_policy_pb2_grpc.py
  google/cloud/storage/emulator/google/iam/v1/options_pb2.py
  google/cloud/storage/emulator/google/iam/v1/options_pb2_grpc.py
  google/cloud/storage/emulator/google/iam/v1/policy_pb2.py
  google/cloud/storage/emulator/google/iam/v1/policy_pb2_grpc.py
  google/cloud/storage/emulator/google/storage/v2/storage_pb2.py
  google/cloud/storage/emulator/google/storage/v2/storage_pb2_grpc.py
Labels: cla: yes
